### ISSUE TITLE
Revealjs center option only applies to vertical slides, not horizontal ones

### ISSUE THREAD

**Issue by Mavoort** [quarto-dev/quarto-cli#10022]
### Bug description

I want to create a presentation with both horizontal and vertical slides;
According to the [documentation](https://quarto.org/docs/presentations/revealjs/advanced.html#vertical-slides), this can be achieved by structuring the presentation using level 1 headings for horizontal slides and level 2 headings for vertical slides, and setting `navigation-mode: vertical` in the YAML-header.

The problem is that the option `center: false` now only applies to the vertical (level2) slides, and not to the normal ones. So horizontal slides are still centered (which I don't want).

I thought that this might be intended, but that can't be the case; Because the normal behaviour of RevealJS is to apply the center option to _both_ horizontal and vertical slides. You can see this by cloning the [RevealJS repo](https://github.com/hakimel/reveal.js) and setting `center: false` in [line 471](https://github.com/hakimel/reveal.js/blob/master/demo.html#L471) of the demo presentation.

### Steps to reproduce

```` quarto
---
format:
    revealjs:
        navigation-mode: vertical
        transition: slide
        center: false
---

# Horizontal Slide
This should not be centered.

## Vertical Slide
This slide is correctly aligned to the top.

# Another Horizontal Slide
````

### Expected behavior

Since we have `center: false` in the YAML-header, the slides should not be centered.

### Actual behavior

Horizontal slides are still centered.

![slide_not_centered](https://github.com/quarto-dev/quarto-cli/assets/46296384/8275ca31-0b80-4f6a-a779-95d84a06ae1a)

### Your environment

OS: Ubuntu 23.10 mantic

### Quarto check output

``` bash
Quarto 1.4.554
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.554
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /usr/bin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.6
      Path: /usr/bin/python3
      Jupyter: 5.3.1
      Kernels: julia-1.10, python3, sagemath

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /usr/lib/R
      LibPaths:
        - /home/marcel/R/x86_64-pc-linux-gnu-library/4.3
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      knitr: 1.43
      rmarkdown: 2.23

[✓] Checking Knitr engine render......OK
```

**Comment by cderv** [comment]
This is due to an opinionated choice of Quarto (and default) regarding centering slide. And I see now this is not well documented. 

Quarto added a specific option `center-title-slide` (documented here https://quarto.org/docs/reference/formats/presentations/revealjs.html#slides) that controls the centering of title slide specifically. 

So `center: false` (which is already the default in Quarto HTML presentation) only applies to content slides. 

This means

- `center` controls the alignement of slides vertically. `center: false` is the default. 
- `center-title-slide` controls the alignement of title slides when `center: false`, which default being `true` so that title slides are centered. 

So the combination are: 

- The default is title slide centered, and content slide top aligned (`center-title-slide: true` and `center: false`). 
- `center-title-slide: false` will also top align the title slides when `center: false`
-  `center: true` will make all slides centered - there is currently no way to have content slide centered and title slides top aligned. 

In your case use 

````yaml
---
format:
  revealjs:
    navigation-mode: vertical
    transition: slide
    center-title-slide: false
---
````

This should make all your slides top aligned. 

This is currently not documented correctly in our website, so I'll add a paragraph at https://quarto.org/docs/presentations/revealjs/advanced.html#center

Thanks a lot for asking the question

**Comment by Mavoort** [comment]
That solved it for me, thank you very much!
