### ISSUE TITLE
In mulitcolumn layout, figure is named Figure 1 regardless of preexisting named figures.  

### ISSUE THREAD

**Issue by rccline** [quarto-dev/quarto-cli#1017]
Using the followinging code, the figure is entitled "Figure 1..." regardless of the number of preceding figures that exist.  

Removing the captions "Famous Elephants" destroys the layout.  The layout becomes split into two rows. 

```markdown
::: {#fig-elephants layout-ncol=2}
![Surus](surus.png){#fig-surus}
![Hanno](hanno.png){#fig-hanno}
Famous Elephants
:::
```

**Comment by cscheid** [comment]
Hi - I'm having a hard time reading your example. Can you take a look at https://yihui.org/issue/#please-format-your-issue-correctly and reformat? Thank you!

**Comment by jjallaire** [comment]
I'm not able to reproduce the numbering issue that you mentioned. If you are still seeing this behavior could you create a simple git repo or gist that reproduces the problematic behavior and post the link to it here.

Note that the syntax you are using for multi-column figures isn't quite what we have in the documentation (which is why its not working as you expect). See https://quarto.org/docs/authoring/figures.html#subfigures which uses this markdown:

````markdown
::: {#fig-elephants layout-ncol=2}

![Surus](surus.png){#fig-surus}

![Hanno](hanno.png){#fig-hanno}

Famous Elephants
:::
````

Note that there needs to be blank lines between the figures and before the caption (I'll clarify that in the docs).
