### ISSUE TITLE
Quarto doesn't index content in first section of book

### ISSUE THREAD

**Issue by truecluster** [quarto-dev/quarto-cli#10285]
### Bug description

In a quarto book, I have a chapter with first level header 
```
# Callouts

::: {.callout-caution}
cautionary callout
:::

::: {.callout-tip}
tippy callout
:::

{{< lipsum 1-10 >}}
```

### Steps to reproduce

Consider a chapter like this:
```
# Callouts

::: {.callout-caution}
cautionary callout
:::

::: {.callout-tip}
tippy callout
:::

{{< lipsum 1-10 >}}

## FailureCause

{{< lipsum 11-20 >}}
```
then the texts in the callouts are missing in the html search, e.g. searching for "tippy". Remove the line `##FailureCause` (or change the header level) and searching works. See attached poject: [quartosearch.zip](https://github.com/user-attachments/files/16199093/quartosearch.zip)

### Expected behavior

searching for text in callouts should find a search result also with next-level sections in the chapter

### Actual behavior

searching for text in callouts does not find a search result with next-level sections in the chapter

### Your environment

- IDE: 2024.04.2 Build 764
- OS: Ubuntu 20.04.6 LTS

### Quarto check output

Quarto 1.5.52
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.52
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2024.07.03
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /home/jo/.TinyTeX/bin/x86_64-linux
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.8.10
      Path: /usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.4.1
      Path: /usr/lib/R
      LibPaths:
        - /home/jo/R/x86_64-pc-linux-gnu-library/4.4
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      knitr: 1.46
      rmarkdown: 2.26

[✓] Checking Knitr engine render......OK

**Comment by cscheid** [comment]
I can repro. That's a strange one!

**Comment by cderv** [comment]
It is not related to callout. It happens because for book project, Quarto is currently indexing only what is available after the first section 
https://github.com/quarto-dev/quarto-cli/blob/92cad4456c4e8b635979d6b39f45b507aba70edb/src/project/types/website/website-search.ts#L303-L314

Selector used is `main > section:first-of-type` - so anything before the first section is not considered for the search index. 
In the book example, the first section is 
````html
<section id="failurecause" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="failurecause"><span class="header-section-number">1.1</span> FailureCause</h2>
````

And it happens we don't create a `section` for the Chapter title - it a `h1` inside a special div inside a `<header>` element. 
```html
<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Callouts</span></h1>
</div>
<div class="quarto-title-meta">  
</div>
</header>
```

It has been introduced in https://github.com/quarto-dev/quarto-cli/commit/ef09563cd1a3745247fef4fbedb0be5c1294cb4e to solve 
- https://github.com/quarto-dev/quarto-cli/issues/8011

I believe this relates to initial issue with search still incomplete 
- https://github.com/quarto-dev/quarto-cli/issues/2095

It was fixed initially by https://github.com/quarto-dev/quarto-cli/commit/67a025cd632bddcdafd4c2c8f6343d4a520228c9 trying to account for book html page structure being different. 

We probably need to find the right CSS selector and rethink the search for Books accordingly to not miss some content. 

Hope it helps understand.
