### ISSUE TITLE
`ref.label` seems not to be handled quite right 

### ISSUE THREAD

**Issue by ltierney** [quarto-dev/quarto-cli#1034]
Reusing a chunk with `ref.label` seems to not be working when the chunk body is empty. It does work with a blank line for the body or when the body contains a `#|` option. This sample document illustrates the issue:

````
---
execute:
  echo: true
---

The original chunk:

```{r}
#| label: foo
1 + 2
```

Using `ref.label` does not work with an empty body:

```{r, ref.label = "foo"}
```

Using `ref.label` does work with a blank line body:

```{r, ref.label = "foo"}

```

Using `<<...>>` noweb notation does work:

```{r}
<<foo>>
```
````

**Comment by cderv** [comment]
OK it took me a while to understand the issue as initially I thought it was something related to our **knitr** hooks and other R code. But it is not. 

In short, the issue is that this chunk 
`````markdown
```{r, ref.label = "foo"}
```
`````
does not work, because it does not get passed to **knitr** for processing. The cell is removed in Quarto pre process work where we parse the `.qmd` file to a `.rmarkdown` file for processing with **knitr**. 

@cscheid does `breakQuartoMd()` supports empty code chunks  ? It does not seem so from what I understand in the code. 
https://github.com/quarto-dev/quarto-cli/blob/aa8d33fa2b873e5f8e73ecfdc1582ee3c94236d0/src/core/lib/break-quarto-md.ts#L74
The `lineBuffer` will be empty as nothing has been put into it as end of chunk is happening next line of start of code cell. 
This cause the empty cell to be ignored and not added into `nb` that will be return for processing
https://github.com/quarto-dev/quarto-cli/blob/aa8d33fa2b873e5f8e73ecfdc1582ee3c94236d0/src/core/lib/break-quarto-md.ts#L163
https://github.com/quarto-dev/quarto-cli/blob/aa8d33fa2b873e5f8e73ecfdc1582ee3c94236d0/src/core/lib/break-quarto-md.ts#L261

They are valid with **knitr** as you can see. 

I don't have yet a possible fix, I wanted to share my findings as it took me long enough to understand all this (very interesting to finally getting to learn this part of the code base). 

Maybe you'll have an obvious one or maybe this is something we are not expecting. Happy to have your thoughts.

**Comment by cderv** [comment]
Ok that is what I thought - Thanks for confirming. Now that I found the issue, I can keep on to find a solution but @cscheid you know more than me this part so probably better if you take the follow-up on this issue, right ?  (if you have time)

**Comment by cscheid** [comment]
I'll do that right away.

**Comment by cscheid** [comment]
This should be fixed as of commit https://github.com/quarto-dev/quarto-cli/commit/a120c2a2ddf17d71447315efb6694237545ccf52. Please let me know and reopen if it doesn't solve the problem!

**Comment by cderv** [comment]
This is working fine now. This was indeed the issue. Thanks @cscheid for the quick jump in!
