### ISSUE TITLE
`highlight-style` treated differently for `format: *` and `format: live-*`

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [quarto-dev/quarto-cli#10717]
I have a website project with `revealjs` slides and `html` files in it.

I set `highlight-style: a11y-dark` [at the metadata level](https://github.com/sta199-f24/sta199-f24.github.io/blob/main/slides/_metadata.yml#L16).

In both `live-revealjs` and `live-html` outputs, the non-interactive code cells use the correct highlight style:

<img width="400" alt="Screenshot 2024-09-04 at 4 54 15 PM" src="https://github.com/user-attachments/assets/29c7a510-829b-47b1-9cd2-f6b1f6cd7402">
<img width="400" alt="Screenshot 2024-09-04 at 4 54 35 PM" src="https://github.com/user-attachments/assets/d9a878eb-e1c4-434b-928e-f80ef8e730bb">

However, in the interactive (webr) code cells, a different style is applied.

<img width="400" alt="Screenshot 2024-09-04 at 4 56 17 PM" src="https://github.com/user-attachments/assets/fdae6fa7-55e4-49d5-bce9-fc7877c28911">
<img width="400" alt="Screenshot 2024-09-04 at 4 55 59 PM" src="https://github.com/user-attachments/assets/28a1e2c5-03a3-453b-8b6a-4eb6f75e17f3">

Note that this doesn't happen if `highlight-style: github`, for example.

cc @cderv

**Comment by georgestagg** [comment]
Currently, the background colour for the Quarto Live code editor is decided by the following rules in CSS:

* `--bs-body-bg` if it exists, or
* `--r-background-color` if it exists, or
* `#ffffff`, if the Quarto theme is light, or
* `#222222`, if the Quarto theme is dark.

So the issue happens when the highlighting theme requires that code is typeset on a dark background, but the Quarto theme otherwise has a light background on the web page.

This is a problem that should really be fixed in Quarto Live. The CSS for the live editor should listen to the highlighter theme in some way to provide a dark background if required.

I will need to think about this a bit, I think the assumption that a "light" highlighter theme will be used with a "light" quarto theme is pretty deep in Quarto Live's CSS rules right now.

**Comment by mine-cetinkaya-rundel** [comment]
What's unclear to me is which syntax highlighting is the light one using? It's not `a11y` (the light version of `a11y-dark`. It's very difficult to read. Otherwise, I'd be ok with even if it doesn't necessarily match the rest of the highlighting.

**Comment by cderv** [comment]
This is now to follow up on #10722. 

In next quarto 1.6, any SCSS variable will be made available as CSS root variable with namespace `--quarto-scss-export-*`

We don't have yet a full extensive list of available variable, and this is quite new, but still can be used to access value set to color like code background. 

Should help solve this issue in quarto-live.

**Comment by georgestagg** [comment]
Apologies for the delay but the latest commit of Quarto Live now makes use of the `--quarto-scss-export-code-block-color` and `--quarto-scss-export-code-block-bg` variables.

We should still deal with the gutter in the future, but for now at least the code should be readable in the main body of the Quarto Live editor and match more closely Quarto's own code blocks.

![Image](https://github.com/user-attachments/assets/dc141937-2a2f-44bc-baf7-c013f3b16b7f)

**Comment by georgestagg** [comment]
Note that there's still an issue when using `a11y-dark` with an otherwise light theme. I've written up the technical details at: https://github.com/quarto-dev/quarto-cli/pull/10722#issuecomment-2545424570
