### ISSUE TITLE
Apostrophe causes issues in listing categories 

### ISSUE THREAD

**Issue by baker-jr-john** [quarto-dev/quarto-cli#10829]
I need help figuring out why the date on my blog's home page is not generating correctly.

## Example
Today is 2024-09-17. The date for the latest entry on my blog is `September 17, 2024` {=html}.

![Screen Shot 2024-09-17 at 12 55 44 AM](https://github.com/user-attachments/assets/ac7984fd-cbcf-44cc-91c4-1ccba79fc091)

- Website: https://penngse.johnbaker.io/
- Repo: https://github.com/baker-jr-john/Website

I'm running Quarto 1.5.57.

Please let me know if you need more information.

If someone can help figure out why, I'd be very grateful!

Please let me know where I should ask for help if there is a better place for this post.

**Comment by cscheid** [comment]
@baker-jr-john It's a Quarto bug. It's (weirdly!) caused by the apostrophe in one of your category entries. We'll fix that, but a workaround for you in the mean time is to remove the apostrophe from "Cohen's Kappa Score" and rerender that file (because you have `freeze` turned on, you'll either have to remove the freeze directory or explicitly render that specific file).

**Comment by baker-jr-john** [comment]
I removed the entire word "Cohen's" from my Category entries. I would've never figured that out. Thanks, Carlos!

**Comment by cscheid** [comment]
(Please don't close issues - we'll do that ourselves when we fix the bug. Thanks.)
