### ISSUE TITLE
Using plotly as subfigure output

### ISSUE THREAD

**Issue by verbalins** [quarto-dev/quarto-cli#1087]
Hi!

I'm having issues with subfigures produced by plotly. It seems like the fig-subcap option is not recognized. Instead, the caption is placed to the top right of the figure instead of formatted correctly at the bottom.

## reprex
Here's a minimal example to see the difference.
````
```{r setup, include=FALSE}
data(mtcars)
```

```{r}
#| layout-nrow: 1
#| fig-cap: "Plotting mtcars dataset with ggplot2"
#| fig-subcap:
#|   - "wt vs mpg"
#|   - "mpg vs wt"
#| label: fig-mtcars
mtcars |> ggplot2::ggplot(ggplot2::aes(wt, mpg)) + ggplot2::geom_point()
mtcars |> ggplot2::ggplot(ggplot2::aes(mpg, wt)) + ggplot2::geom_point()
```

```{r}
#| layout-nrow: 1
#| fig-cap: "Plotting mtcars dataset with plotly"
#| fig-subcap:
#|   - "wt vs mpg"
#|   - "mpg vs wt"
#| label: fig-mtcars-plotly
mtcars |> plotly::plot_ly(x = ~wt, y = ~mpg, type = "scatter", mode = "markers")
mtcars |> plotly::plot_ly(x = ~mpg, y = ~wt, type = "scatter", mode = "markers")
```
````

## Tested with
- quarto 0.9.535
- RStudio 2022.06.0-daily+435 "Spotted Wakerobin" Daily (d0717845d82ddf7467f7061734570f6db215da72, 2022-05-22) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36
- R 4.2.0
- plotly 4.10.0

## quarto check output
````
[>] Checking Quarto installation......OK
      Version: 0.9.535
      Path: C:\Users\XYZ\AppData\Local\Programs\Quarto\bin\
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....(None)

      Unable to locate an installed version of Python 3.
      Install Python 3 from https://www.python.org/downloads/

[>] Checking R installation...........OK
      Version: 4.2.0
      Path: C:/PROGRA~1/R/R-42~1.0
      LibPaths:
        - C:/Users/XYZ/R/win-library
        - C:/Program Files/R/R-4.2.0/library
      rmarkdown: 2.14

[>] Checking Knitr engine render......OK
````

## Checklist

When filing a _bug report_, please check the boxes below to confirm that you have provided us with the information we need. Have you:

- [x] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?

- [x] included a minimal, self-contained, and reproducible example?

- [x] documented the quarto version you're running, by providing the output produced by `quarto check` in a terminal in your issue?

- [x] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?

- [x] documented which operating system you're running? If on Linux, please provide the specific distribution as well.

- [ ] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by mpaulacaldas** [comment]
Hello! I think this issue affects more broadly any graph produced with htmlwidgets.

For example, here using highcharter instead of plotly:

````
```{r setup, include=FALSE}
data(mtcars)
```

```{r}
#| layout-nrow: 1
#| fig-cap: "Plotting mtcars dataset with ggplot2"
#| fig-subcap:
#|   - "wt vs mpg"
#|   - "mpg vs wt"
#| label: fig-mtcars
mtcars |> ggplot2::ggplot(ggplot2::aes(wt, mpg)) + ggplot2::geom_point()
mtcars |> ggplot2::ggplot(ggplot2::aes(mpg, wt)) + ggplot2::geom_point()
```

```{r}
#| layout-nrow: 1
#| fig-cap: "Plotting mtcars dataset with highcharter"
#| fig-subcap:
#|   - "wt vs mpg"
#|   - "mpg vs wt"
#| label: fig-mtcars-highcharter

suppressPackageStartupMessages(library(highcharter))
hchart(mtcars, "scatter", hcaes(wt, mpg, z = drat))
hchart(mtcars, "scatter", hcaes(mpg, wt, z = drat))
```
````

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/33395215/183919011-8595b885-2dfd-4329-b741-4dc309997314.png)

</details>

If I use the fig-cap to caption both items instead (without fig-subcap), the captions also end up in the right side of the plots.

**Comment by mcanouil** [comment]
I believe the issue to be fixed.
I am going ahead and close, but feel free to comment if that is not the case.

<img width="466" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/22d73c25-b7e9-482f-bc2b-9c1c1694e1bb">
