### ISSUE TITLE
Letter page-width is 8.5 inch, not 6.5 inch

### ISSUE THREAD

**Issue by raffaem** [quarto-dev/quarto-cli#11162]
### What would you like to do?

Report an issue on quarto.org

### Description

[Here there is written](https://quarto.org/docs/reference/formats/odt.html#layout):

> Target page width for output (used to compute columns widths for layout divs). Defaults to 6.5 inches, which corresponds to default letter page settings in docx and odt.

But the  default page width for letter paper size is  [8.5 inch](https://en.wikipedia.org/wiki/Letter_(paper_size)), not 6.5 inch.

In fact if you compiled the document, in LO writer you'll see:

![Image](https://github.com/user-attachments/assets/0d1d9ab0-b347-4091-ac0b-cc3b35aa1c1e)

**Comment by cderv** [comment]
I believe this is 6.5 inches, because it takes into account the margins of 1 inche each. 

As the doc says, this value is used to compute the layout column width when passed in %. And so 100% is really the full page width less margins. 

We can improve the wording in the document to make that more clear.
