### ISSUE TITLE
Wrap text in column headings - pandas dataframe to Quarto pdf

### ISSUE THREAD

**Issue by konnerhorton** [quarto-dev/quarto-cli#1119]
### Bug description

Jupyter notebooks wrap dataframe column heading text as needed. When rendering in Quarto the wrap is not maintained so the headers (and the tables) trail off the side of the page.

Quarto version: 0.09.495
OS: Windows 11 Pro 22000.675

Input:
```
title: "Wrap Text Column Heading"
title-block-style: default
format: pdf
```

```
import pandas as pd
data = {'Long Header Text 1': [3, 2, 1, 0],
        'Long Header Text 2': ['a', 'b', 'c', 'd'],
        'Long Header Text 3': ['a', 'b', 'c', 'd'],
        'Long Header Text 4': ['a', 'b', 'c', 'd'],
        'Long Header Text 5': ['a', 'b', 'c', 'd'],
        'Long Header Text 6': ['a', 'b', 'c', 'd'],
        'Long Header Text 7': ['a', 'b', 'c', 'd'],
        'Long Header Text 8': ['a', 'b', 'c', 'd'],
        'Long Header Text 9': ['a', 'b', 'c', 'd']}
pd.DataFrame.from_dict(data)
```
Notebook output:
![image](https://user-images.githubusercontent.com/95249835/172910416-2cc91db9-0ee8-4084-9750-1db87f50d30d.png)

Quarto output:
![image](https://user-images.githubusercontent.com/95249835/172910077-5ad6fda9-7094-4db3-9896-9f24f096158f.png)

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [X] included a minimal, self-contained, and reproducible example?
- [X] documented the quarto version you're running, by providing the output produced by `quarto check` in a terminal in your issue?
- [ ] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [X] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by cscheid** [comment]
Hello - thanks for reporting! This issue is similar to that in #1118. LaTeX tables do not wrap their headings automatically, and that's not something that we can control in Quarto. The ideal solution for this would be to add line breaks (`\\`) to the column names, but that will run directly into the problem you saw in #1118.

You should be able to work around this in the same way I described there:

    from IPython.display import display, Math
    
    data = {'Add \\ a break': [3, 2, 1, 0],
            'Another \\ break': ['a', 'b', 'c', 'd']}
    
    display(Math(pd.DataFrame.from_dict(data).style.format(escape=None).to_latex()))

We are currently working on a Python of `gt` which will offer easier consistent styling across PDF, HTML and Word. Until then, this workaround is the best path to get what you want.

**Comment by konnerhorton** [comment]
Thanks!
