### ISSUE TITLE
`QUARTO_CHROMIUM` does not work inside `_environment` file

### ISSUE THREAD

**Issue by mcanouil** [quarto-dev/quarto-cli#11205]
It appears the new `QUARTO_CHROMIUM` does not work inside [`_environment` file](https://quarto.org/docs/projects/environment.html#environment-file).

_Originally posted by @mcanouil in https://github.com/quarto-dev/quarto-cli/issues/11187#issuecomment-2439629730_

**Comment by cderv** [comment]
🤔 This is interesting. I'll need to understand why because only thing we do is read the env var
https://github.com/quarto-dev/quarto-cli/blob/b7041653ddbc374d634c23bbc9b3d3d41dc0b9a4/src/core/puppeteer.ts#L205-L210

Unless somehow `safeExistsSync(envPath)` fails in your example 🤔 

Did you build an example ? What is the value your tried ?

**Comment by cderv** [comment]
With dev version you can now activate debug logging so we have more information on what is happening.

**Comment by cderv** [comment]
This does not help me know if you set things up correctly (Are you correctly in a project ?), and how you did notice it is not used (is there any error showing) ? 

I could assume you know what you are doing, but truth is I can't reproduce on my side by guessing what you have tried. What I did 
- add `_environment` file in a quarto project, 
- call `quarto render` on a file with Mermaid graph, 
- correctly see it rendering, 
- Look at debug logging showed me it got picked up. 

I mentioned just above that "With dev version you can now activate debug logging so we have more information on what is happening." so you could now use the dev version and share the chromium part of debug logging to see what is read. 

Please do apply what you usually recommend on others issues, so that we have all the information. 
- It could be OS specific
- It could be brave specific
- It could be an issue with my previous PR indeed. 

Right now, `QUARTO_CHROMIUM` is working for me and I can't reproduce. 

Thanks !

**Comment by mcanouil** [comment]
Hum, something must have gone weirdly the last time.
It works properly with a fresh `./configure.sh` on `main` (nothing changed in the project setup).
