### ISSUE TITLE
Regression in font size for inline code present in callout blocks in Revealjs format

### ISSUE THREAD

**Issue by IndrajeetPatil** [quarto-dev/quarto-cli#11215]
### Bug description

I am not sure in which version this change happened, but the font size for code in callout blocks is completely off in revealjs presentations. I say this is a regression because I noticed the changes in [my slides](https://indrajeetpatil.github.io/intro-to-snapshot-testing/#/unit-testing-with-testthat-a-recap), which used to look great but now look hideous.

---

To reproduce, run the following:

````qmd
---
title: "example"
format:
  revealjs: 
    theme: simple
---

## Tests

:::{.callout-tip}

## Example test file

- Every test is a call to `testthat::test_that()` function.

- Every expectation is represented by `testthat::expect_*()` function.

:::
````

You can notice that the font size for code is much bigger than expected

![Image](https://github.com/user-attachments/assets/a022ec71-14fb-4409-8bd6-107a0d5eaf76)

especially if you contrast it with the HTML output:

![Image](https://github.com/user-attachments/assets/8c75c30d-d27c-427b-92c7-d08698e3a6bd)

### Quarto check output

Quarto 1.6.30
[✓] Checking environment information...
      Quarto cache location: /Users/indrajeetpatil/Library/Caches/quarto
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.4.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.46.3: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.6.30
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/indrajeetpatil/Library/TinyTeX/bin/universal-darwin
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.13.0
      Path: /opt/homebrew/opt/python@3.13/bin/python3.13
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

      There is an unactivated Python environment in .venv. Did you forget to activate it?

[✓] Checking R installation...........OK
      Version: 4.4.1
      Path: /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources
      LibPaths:
        - /Users/indrajeetpatil/Library/R/arm64/4.4/library
        - /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library
      knitr: 1.48
      rmarkdown: 2.28

[✓] Checking Knitr engine render......OK

**Comment by cscheid** [comment]
Thanks for catching this!

**Comment by cderv** [comment]
This is another impact of brand feature for Reveal this time
- #11028

We need to add the rule differently so that it applies correctly at each place. What happens here is that this rule applies 
https://github.com/quarto-dev/quarto-cli/blob/cf4e95119390f6d87ce14ccea9f4877b28b106a3/src/resources/formats/revealjs/quarto.scss#L323-L328

with `code` font size being set to `$code-inline-font-size`. However, in callout context, font-size is supposed to be reduced 
https://github.com/quarto-dev/quarto-cli/blob/cf4e95119390f6d87ce14ccea9f4877b28b106a3/src/resources/formats/revealjs/quarto.scss#L459-L463

and this does not respect that here, as `code-inline-font-size` is set to presentation size
https://github.com/quarto-dev/quarto-cli/blob/cf4e95119390f6d87ce14ccea9f4877b28b106a3/src/resources/formats/revealjs/quarto.scss#L189
https://github.com/quarto-dev/quarto-cli/blob/cf4e95119390f6d87ce14ccea9f4877b28b106a3/src/resources/formats/revealjs/quarto.scss#L20
https://github.com/quarto-dev/quarto-cli/blob/cf4e95119390f6d87ce14ccea9f4877b28b106a3/src/resources/formats/revealjs/quarto.scss#L12

So we need to think this more so that we do not force code font size like this on all element. 🤔

**Comment by IndrajeetPatil** [comment]
Thanks a lot for the quick fix! 🙌 

How can I give this a try? 
AFAICT, unlike [Pandoc](https://github.com/jgm/pandoc/actions/workflows/nightly.yml), quarto doesn't ship nightly builds, and this fix is not (yet) in a pre-release.

**Comment by cscheid** [comment]
@IndrajeetPatil you can either wait for a prerelease or run a dev version of Quarto, which is [easy to do](https://github.com/quarto-dev/quarto-cli?tab=readme-ov-file#development-version).

**Comment by IndrajeetPatil** [comment]
Thanks. 

I can confirm that this mostly fixes the previous regression but introduces another (minor) regression about code included in header elements:

![Image](https://github.com/user-attachments/assets/2ac0c159-7628-46fe-a5fd-5dacd6e25cdb)

**Comment by cderv** [comment]
I opened new issue to discuss
