### ISSUE TITLE
Question: how can I keep .aux file?

### ISSUE THREAD

**Issue by mattocci27** [quarto-dev/quarto-cli#1122]
When I render PDF, I want to keep .aux files so that I can do cross referencing using external document with {xr}.   The option `keep-tex: true` only keeps .tex files.

**Comment by jjallaire** [comment]
You should be able to specify `latex-clean: false` to preserve the intermediate files: https://quarto.org/docs/reference/formats/pdf.html#latexmk

**Comment by mattocci27** [comment]
Thanks! I missed it when check the document first time. 

Searching did not work because I was using Safari or accessing from China. Thank you so much anyway.

![Screen Shot 2022-06-10 at 6 23 37 PM](https://user-images.githubusercontent.com/12104199/173046183-d0450e35-31b7-4c98-8878-efec66c0606c.png)

**Comment by jjallaire** [comment]
We actually had excluded the reference pages from the search index (because there is a lot of duplication across dozens of formats which ends up creating a lot of noise in search results). I've just added the pdf, html, and docx options pages which now gives this for the "clean" query:

<img width="898" alt="Screen Shot 2022-06-11 at 3 06 55 PM" src="https://user-images.githubusercontent.com/104391/173201628-1b10b30b-2a50-4b8d-be06-8987475e768a.png">
