### ISSUE TITLE
1.6 Tabset dashboard rendering regression

### ISSUE THREAD

**Issue by cscheid** [quarto-dev/quarto-cli#11549]
See https://github.com/quarto-dev/quarto-cli/discussions/11544

**Comment by cscheid** [comment]
By inspecting the document, we can see that the CSS selector that triggers the margin setting is `.quarto-dashboard .tabset .dashboard-card-no-title .nav-tabs`.

In 1.6, the selector `.quarto-dashboard .tabset .dashboard-card-no-title` returns `null`, for reasons I don't yet understand.

**Comment by cscheid** [comment]
Using the reprex in the linked discussion, this returns a node in 1.5, but doesn't in 1.6:

```
document.querySelectorAll(".dashboard-card-no-title")
```

**Comment by cscheid** [comment]
It appears that in 1.5, Quarto believes the card header doesn't have a title, but that in 1.6 it does.

**Comment by cscheid** [comment]
https://github.com/quarto-dev/quarto-cli/pull/11550

This fixes the positioning. I still need to figure out why the tabset border color is wrong.

**Comment by cderv** [comment]
> I still need to figure out why the tabset border color is wrong.

This has been reported in #11561 for callouts border. See my analysis there - basically brand change introduced a mix for `$border-color`
https://github.com/quarto-dev/quarto-cli/blob/37bc223282d9e239d1245575100c7dbf3de74a52/src/resources/formats/html/bootstrap/_bootstrap-variables.scss#L275-L279
which does not work as expected on default theme, because `$border-color` ends up white. 
This variable is used in many places (like callouts, h2 underline, etc...), including the tab border
https://github.com/quarto-dev/quarto-cli/blob/37bc223282d9e239d1245575100c7dbf3de74a52/src/resources/formats/html/bootstrap/dist/scss/_variables.scss#L1183
