### ISSUE TITLE
Quarto flags YAML error where none exists.

### ISSUE THREAD

**Issue by MichelNivard** [quarto-dev/quarto-cli#11565]
### Bug description

When a user tried to render:

````
---
title: Ridian2
format: pdf
date: today
author: Eric
---
# Second attempt
Simply trying to get simple R code to function

```{r}
#| label: 4e074085
hist(runif(1000))
```

The above should have produced a histogram of uniformly distributed random variates.
````

they got this error:

```
In file Untitled_3_quarto.qmd
(line 11, columns 11--19) Field "label" has value 4e074085, which must instead be a string
10: ```{r}
11: #| label: 4e074085
             ~~~~~~~~~
12: hist(runif(1000))
✖ The value 4e074085 is of type number.
ℹ The error happened in location label.

ERROR: Validation of YAML cell metadata failed.
ERROR: Render failed due to invalid YAML.
```

In this partcular case quarto is automatically generated and I generate random strings as labels, so I can patch that by ensuirng the strongs start with a letter, but perhaps the YAML check should be more explict?

### Expected behavior

render the doc

### Actual behavior

YAML error

### Your environment

IDE: RStudio
OS: Mac and Win 11

### Quarto check output

(base) michels-MacBook-Air:lab notes 2024 michelnivard$ quarto check
Quarto 1.5.45
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.45
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2023.01
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/michelnivard/Library/TinyTeX/bin/universal-darwin
      Version: 2022

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.8 (Conda)
      Path: /Users/michelnivard/miniconda3/bin/python
      Jupyter: 5.7.1
      Kernels: ir, python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.4.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library
      knitr: 1.48
      rmarkdown: 2.27

[✓] Checking Knitr engine render......OK

(base) michels-MacBook-Air:lab notes 2024 michelnivard$

**Comment by mcanouil** [comment]
Thanks for the report.
You are using a very old pre-release. We highly recommend you to upgrade to either the current stable release or a newest pre-release.

**Comment by cderv** [comment]
The problem here is that you are not using a valid YAML string label. The problem lies in the fact that `4e074085` is seen as number by YAML because it is scientific notation for floating point. See spec: https://yaml.org/spec/1.2.2/#floating-point

> Canonical Form
> Either 0, .inf, -.inf, .nan or scientific notation matching the regular expression
> -? [1-9] ( \. [0-9]* [1-9] )? ( e [-+] [1-9] [0-9]* )?.


If you would have a `a` instead of `e`, no problem `4e074085`. 

> In this partcular case quarto is automatically generated and I generate random strings as labels, so I can patch that by ensuirng the strongs start with a letter

You need to be sure to have string as label, so in your generator add quotes `''`
```yaml 
#| label: '4e074085'
```

This is what insure this will be parsed as string, and not "guessed" by the YAML parser. 

> , but perhaps the YAML check should be more explict?

What should be more explicit ? Validation says a string need to be used, and this is not the case here. 


FWIW to be complete, I can't reproduce with 1.6 nor 1.5. It does not prevent rendering for me. Probably because when using R and **knitr** the YAML validation is loosen. 

Anyhow, I still got the YAML linting flagging this in IDE.
