### ISSUE TITLE
Mouse cursor on tabs (`{.panel-tabset}`) is not a pointer

### ISSUE THREAD

**Issue by arcruz0** [quarto-dev/quarto-cli#1227]
### Bug description

Hi, thanks for the great package!

When hovering over tabs (`{.panel-tabset}`), the cursor is not a pointer. See the MRE below:

````
---
title: "Untitled"
format: html
---

::: {.panel-tabset}

## Tab1

Tab 1 text

## Tab2

Tab 2 text

:::
````

![tabs-pointer](https://user-images.githubusercontent.com/28851411/175832807-df8a975c-052e-40da-9321-4b969e27fb7a.gif)

Using a Bootstrap theme (e.g., `theme: cerulean`) doesn't change this behavior. I think that this is a bug, as the cursor is a pointer for tabs in R Markdown, the [Quarto documentation](https://quarto.org/docs/interactive/layout.html#tabset-panel), the [Tabby documentation/demo](https://codepen.io/cferdinandi/pen/rRMJwK), etc. 

I believe that this could be fixed with some simple CSS such as `.nav-item {cursor: pointer;}`, but that might break something else, I don't know.

Many thanks!

<details>
<summary>System details</summary>
Quarto 0.9.622; R 4.2.0; RStudio 2022.02.3 Build 492; Tested on Firefox and Chrome; Pop!_OS 20.04.
</details>

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [X] included a minimal, self-contained, and reproducible example?
- [X] documented the quarto version you're running, by providing the output produced by `quarto check` in a terminal in your issue?
- [X] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [X] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by cscheid** [comment]
I can reproduce this locally on OS X as well.

The reason seems to be that for the MRE, we are not emitting an empty `href` attribute. On the website, we get this element:

`<a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false" href="">Data</a>`

On the MRE, we get this element:

<a class="nav-link active" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="true">Tab2</a>

The reason this matters is that user agents have a rule that [any-links](https://developer.mozilla.org/en-US/docs/Web/CSS/:any-link) are typically set to have `cursor: pointer`. That's what giving the website tabs pointer cursors, but isn't triggering the MRE.

(I don't know why we're emitting an empty href on the website but not on this example).
