### ISSUE TITLE
Add Date Modified (optional) to Title Block

### ISSUE THREAD

**Issue by dragonstyle** [quarto-dev/quarto-cli#1241]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/1226

<div type='discussions-op-text'>

<sup>Originally posted by **sciwonder** June 26, 2022</sup>
Love the look and feel of Quatro! I was just wondering, for blogs, is it currently possible to customise the date element so that it includes date *and time* of publication? Is there a "last updated" element as well? I can imagine some circumstances where displaying the original publication date/time and the "last updated" date/time close together could be useful.</div>

**Comment by yoctobug** [comment]
Might this help? https://quarto.org/docs/reference/dates.html

**Comment by cbrnr** [comment]
@yoctobug this is about adding a new field so that a website can show both the date when it was published (mapped to the `date` field) and the date when it was last updated (a new field is needed for this purpose). This would be a really nice and important feature because I frequently update my posts, and I want to show both the date when the post was first published and when it was last updated.

**Comment by cbrnr** [comment]
For reference, the YAML header field is called `date-modified`.
