### ISSUE TITLE
Out of Memory when rendering to HTML

### ISSUE THREAD

**Issue by jjallaire** [quarto-dev/quarto-cli#1263]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/1253

<div type='discussions-op-text'>

<sup>Originally posted by **fuhrmanator** June 29, 2022</sup>
My book project hits this bug https://github.com/denoland/deno/issues/13408 when I do `quarto render --to html` -- it's happening while doing the last HTML file, which is the Bibliography. All the chapters look OK.

If I remove half of the chapters, it finishes completely. 

Any ideas about how to proceed? The github issue above went stale because people weren't able to reproduce it, but it seems with my repo it's possible 100% of the time. Right now it's a private repo, but I will soon make it public. </div>

**Comment by jjallaire** [comment]
@fuhrmanator, thanks for reporting this! In order to investigate further we need to be able to reproduce locally. Can you send us a link to the GitHub repo where there is occurring as well as what platform you are running on?

**Comment by fuhrmanator** [comment]
Here it is: https://github.com/fuhrmanator/log210-ndc-quarto/tree/clyde (it's a branch that has not been merged yet).

**Comment by fuhrmanator** [comment]
I realize the ReadMe is in French, but probably you can figure it out (to install the tools to make the build). Otherwise a global replace of the `.plantuml ` inside the code fence elements will take away the PLANTUML requirements. But those tools might be part of the memory problem? Anyway, I can try to help if you need it.

**Comment by fuhrmanator** [comment]
I installed the latest Quarto today, and I narrowed down part of the crashing problem. Previously this setting was necessary for me to generate HTML versions of the book with the `diagram-generator.lua` filter I was using for PlantUML figures inside the markdown (without it, the images were not found, but today I saw that some bugs along those lines were fixed):

```
  html:
    # needed for inline plantuml/graphviz figures
    self-contained: true
```

I tried it just now without this option, and the HTML build works just fine with images. Not only does it work, but it creates the HTML very quickly and there is no more Out of Memory error.

Of course, you're welcome to keep working on the bug (esp. since it's reproducible), but I will update the repo to deactivate the `self-contained` option as it's no longer needed, made the build slow, and was causing the crash.

It's my hunch that the last step of the build is to concatenate all the HTML files into one big one (for resolving refs?) and with inline images (`data:` URIs) this was a huge file?

**Comment by jjallaire** [comment]
Yes, that is indeed potentially the cause! We did actually make a change recently that obviated the need for self-contained for some filter scenarios so it's not surprising that this works now.

**Comment by ethantenison** [comment]
It looks like this is happening still with revealjs presentations after a certain file size. Instead of 'self-contained' it's 'embed-resources' thought. Maybe that's why it was missed?

**Comment by cderv** [comment]
@ethantenison Can you open a new issue as it is easier to track and share a reproducible example of this please ? 
We'll be able to look into it then. 

Thank you

> Instead of 'self-contained' it's 'embed-resources' thought. Maybe that's why it was missed?

`embed-resources` is the new option name to do the same as `self-contained` from Pandoc.
