### ISSUE TITLE
Captions: colon inside `paste()` leads to `bad indentation of a mapping entry` error

### ISSUE THREAD

**Issue by arnaudgallou** [quarto-dev/quarto-cli#1265]
### Bug description

I'm getting a `YAMLException: bad indentation of a mapping entry` error when using a `:` inside `paste()` or `glue()` in `fig-`/`tbl-cap`.

I'm using RStudio 4.2.0 with Quarto v. 0.9.624 on macOS 12.3.1.

I'm pretty sure it worked a few weeks ago with an older version of Quarto.

``````
---
format: pdf
---

```{r}
#| echo: false
#| fig-cap: !expr paste("foo: bar")

plot(1)
```
``````

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [X] included a minimal, self-contained, and reproducible example?
- [X] documented the quarto version you're running, by providing the output produced by `quarto check` in a terminal in your issue?
- [X] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [ ] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by cscheid** [comment]
The issue here, I believe, is that `expr` needs a _string_, and yaml rules are usually fine with strings without quotes around them. But it's not fine when there are quotes in that string, because those get confused by mappings:

When that's the case, you need to wrap the entire expression after `!expr` with quotes:

    ---
    format: pdf
    ---
    
    ```{r}
    #| echo: false
    #| fig-cap: !expr "paste(\"foo: bar\")"
    
    plot(1)
    ```

That produces this:

<img width="792" alt="image" src="https://user-images.githubusercontent.com/285675/176915957-59241db3-541a-4d10-8e98-cf38b4bc56e7.png">
