### ISSUE TITLE
how to insert pdf file  in quarto book

### ISSUE THREAD

**Issue by zawkzaw** [quarto-dev/quarto-cli#1270]
### Bug description

Hello
I am writing a quarto book and I need to integrate external pdf files into the quarto book.
How can I do this?

Best wishes

Ko Ko Zaw

**Comment by cderv** [comment]
You should be able to add any type of resources to a Quarto website so that it gets detected and moved to output directory. 
Doc is here:
https://quarto.org/docs/websites/website-tools.html#site-resources

Quarto book is a specific type of Quarto website so it should work also. 

Did you try that alread ?

**Comment by zawkzaw** [comment]
Thank you for the suggestion. I will try it.

**Comment by PublicHealthDataGeek** [comment]
Can you insert a pdf into a quarto document - for example as you can in latex? https://stackoverflow.com/questions/2739159/inserting-a-pdf-file-in-latex
