### ISSUE TITLE
Feature Request: Page Number Manipulation & Options

### ISSUE THREAD

**Issue by SEthanMilne** [quarto-dev/quarto-cli#1606]
Many journal submissions require 1-inch margins, with a set page limit. Currently, Quarto's PDF output includes a page number at the bottom of the page, and this is included within the body text. This effectively reduces the available amount of space per page to write.

I couldn't find an existing Quarto YAML option that dealt with page numbering (like e.g. "thanks:", "linestretch:", etc.)

It would be nice if Quarto had YAML options to remove, shift position, or otherwise manipulate page numbers. I was able to fix this myself with the following YAML, but I imagine others will need this solution:

```
---
title: "Temp Title"
format:
  pdf: 
    documentclass: scrartcl
    papersize: letter
    include-in-header: 
      text: |
       \pagenumbering{gobble}
       \usepackage[margin=1in]{geometry}
---
```

**Comment by mcanouil** [comment]
The part related to geometry is not needed, margins can be set as yaml option, see https://quarto.org/docs/reference/formats/pdf.html

Regarding numbering/footer of PDF, I think using the `include-in-header` is the right way to go for small custom modifications, because I do not think that implementing all LaTeX possibilities in Quarto is really useful, because they won't work for other formats.
