### ISSUE TITLE
Powerpoint asks to repair a pptx quarto

### ISSUE THREAD

**Issue by OlexiyPukhov** [quarto-dev/quarto-cli#1630]
I try to make a quarto pptx and hit render. Then PowerPoint tries to open it and says that it detected an error, and it can try to repair. Do you know what the issue is?

![image](https://user-images.githubusercontent.com/98609419/181644096-a319b25f-76ab-4581-8661-4bb74964c914.png)

**Comment by craig-shenton** [comment]
Hi, we have been having the same issue. Only fix seems to be repairing the file and making a .potx template. The issue seems to be with all powerpoint files (inc. a fresh .pptx file or the Quarto template file) for me.
Checking the file with [https://rmarkdown-office-template.herokuapp.com/?](https://rmarkdown-office-template.herokuapp.com/?) the error with a new .pptx is as follows:
```error: ppt/slideLayouts/slideLayout3.xml: does not contain //p:sp/p:nvSpPr/p:nvPr/p:ph[not(@type)]```

**Comment by cderv** [comment]
@craig-shenton Can you share a small example of this in `.qmd`?  Are you trying to use a reference document or just setting `format: pptx` ? 

Also, if possible, can you try our latest Quarto version with this ?  https://quarto.org/docs/get-started/ 
Do you have the same issue ? 

I remember such issue in the past with Pandoc, and it was because the reference doc did not contained what Pandoc is expecting. That is why we advice to create a template from the Pandoc's one itself: https://quarto.org/docs/presentations/powerpoint.html#creating-a-template

**Comment by craig-shenton** [comment]
Hi, I did originally start from a new pandoc created template, but subsequent editing may have corrupted the file. 
- A new file made just using PowerPoint also gave the same error.
- For reference the .qmd config was as follows:
```yaml
---
title: "title"
subtitle: "subtitle"
author: "name"
date: "August 2022"
format: 
   pptx:
     reference-doc: template.pptx
     slide-level: 0
---
```
I will try with a new pandoc template in our different environments. Thanks.

**Comment by cderv** [comment]
> A new file made just using PowerPoint also gave the same error.

This was known to be an issue with Pandoc which expect some specific content, but it seems know they should be compatible with any recent template made. From powerpoint part in https://pandoc.org/MANUAL.html#option--reference-doc
> Templates included with Microsoft PowerPoint 2013 (either with .pptx or .potx extension) are known to work, as are most templates derived from these.

The list of their requirement is there too. If you have the template pptx that was not working, we could look into it. 

@dragonstyle I wonder if we could come up with a way to check the reference doc before any conversion so that issue can be detected without having to wait for an error in the rendered PPTX itself. Or at least a utility function to check a template. 🤔

**Comment by hannahsheldon** [comment]
We found what was causing the issue. I created a fresh pptx file - simply opened powerpoint and saved. This will be my reference-doc. When I save this reference template to onedrive, I get the repair error. If I save the reference template locally, I don't get the error.
I can render the output to onedrive and I don't get the issue - it seems to be when your reference-doc is not locally saved. Any ideas why this is?

**Comment by cderv** [comment]
Interesting. Is the reference-doc saved to one drive and then copied locally to be used ? Or passed a url to one drive path ? 

Pandoc only conversion should be tried too to see if the issue is with Pandoc or either a Quarto / Pandoc interaction.

**Comment by craig-shenton** [comment]
The OneDrive location we are storing the template is a local folder, but any file in that folder is synced with the online SharePoint version. An additional complication is that we are working on an Azure Virtual Machine, so I'm not sure we will be able to diagnose the exact issue without looking into how OneDrive works on VMs. The issue was resolved for us by storing the template in another location locally if anyone has the same problem. Thanks.

**Comment by imadcat** [comment]
> We found what was causing the issue. I created a fresh pptx file - simply opened powerpoint and saved. This will be my reference-doc. When I save this reference template to onedrive, I get the repair error. If I save the reference template locally, I don't get the error.
> I can render the output to onedrive and I don't get the issue - it seems to be when your reference-doc is not locally saved. Any ideas why this is?

I have the same problem, even when the reference-doc file is local. 
<img width="294" alt="image" src="https://user-images.githubusercontent.com/1559729/232774732-50367f9a-d2df-492e-a195-fe18e057681a.png">
But Keynote can open the same generated file without error miraculously, and I use Keynote to save it as a new pptx file, then PowerPoint CAN open the new file without error. 
 
Mac OS 13.3
All software at the latest version.

**Comment by cderv** [comment]
@imadcat this issue can happen with Pandoc when the reference doc used is outdated compared to the Pandoc version. 
It can corrupt the output document to use an old powerpoint reference doc. [Example of issue in Pandoc](https://github.com/jgm/pandoc/issues/8068)

We mention in our document that best way to create the template is to create one based on Pandoc's output 
https://quarto.org/docs/presentations/powerpoint.html#creating-a-template

It is possible that new Pandoc version does not work well with old reference doc.  You could try without reference doc, and with a new reference doc and see if it works.

**Comment by cscheid** [comment]
I'm closing this stale issue because we don't have enough information to reproduce. Please reopen with the needed information if this is still happening for you.
