### ISSUE TITLE
output-dir: output stores files in a new script directory while rendering if .qmd file is in a script subdirectory within quarto project

### ISSUE THREAD

**Issue by Rory-OG** [quarto-dev/quarto-cli#1691]
If the .qmd file is stored in a the "script" subdirectory and the .yml file specifies `output-dir: output` the resulting files will be rendered into a new script directory nested within the output directory.

I thought specifying `execute-dir: project` would avoid this issue, but it does not. 

Please see below for a graphical demonstration: 
before rendering: 

project
|----.gitignore
|----_quarto.yml
|-------project:    
|----------title: "some-proj"
|----------output-dir: script
|----README.md
|----some-proj.Rproj
|___script
|---------|    some-proj.qmd
|___output

after rendering: 

project
|----.gitignore
|----_quarto.yml
|-------project:    
|----------title: "some-proj"
|----------output-dir: script
|----README.md
|----some-proj.Rproj
|___script
|---------|    some-proj.qmd
|___output
**|-----------|____script
|---------------------|    some-proj.html
|---------------------|    some-proj_files__**

**Comment by jjallaire** [comment]
This is the expected behavior (the paths of output files always follow the paths of input files). The `execute-dir` affects what the current working directory is set to code execution within Knitr or Jupyter

**Comment by Rory-OG** [comment]
So there's no clean way to render to an output directory if the .qmd is stored in a script subdirectory? 

What drove that design choice?

**Comment by jjallaire** [comment]
There is one hierarchy of files defined by the location of inputs. That same hierarchy is reflected in the outputs. This is the natural default behavior (reflected in early every other static site generator). 

We could certainly juxtapose the ability to re-target inputs to other locations in the output hierarchy (e.g. custom slugs) but we just haven't done that yet (note that it's not as straightforward as it might sound because it affects the resolution of links and assets pervasively so needs to be coded carefully to make sure it works w/o fail). 

Other systems that support custom slugs (like Hugo) end up with very complicated rules about asset resolution (often requiring root level as opposed to relative references since they aren't reliable in the face of custom slugs). Again, we can do it but at a cost of complexity that I'm not sure its worth.
