### ISSUE TITLE
Use first-level heading for default references div

### ISSUE THREAD

**Issue by jooyoungseo** [quarto-dev/quarto-cli#1811]
Quarto automatically puts `## References` section at the end of document when no references section is specified by users. I've found that the auto-generated references section heading is marked with `h2` (`##`).

However, it would make more sense to use the first-level heading (`h1`: `#`). Otherwise, references section is treated as a sub heading under other first-level heading sections. This may confuse screen reader users as a side effect.

**Comment by cscheid** [comment]
We use `h2` because it's the same heading level as the recommended heading for other sections in an article. I _think_ these are Pandoc conventions that we are following here. Concretely speaking, the structure is expected to be

```
---
title: Hello
---

## Introduction

Introduction text.

## Methods

More text.
```

And then `## References` is the right level of heading to be inserted.

**Comment by jjallaire** [comment]
Yes by convention Quarto uses H2 for sections and H1 for the document title. We've found that H1 for section headers ends up with awkwardly large text is most formats. While we can control HTML we can't control docx, odt, gfm, etc.

**Comment by jooyoungseo** [comment]
@cscheid  -- Thanks for your kind explanation! Would you mind giving me the pointer to the Panodc's heading-level recommendation? I thought starting with `h1` would make more sense for each section title when there is no parent section. Most of the article templates included in {rticles} also start with `h1: #` level.

**Comment by jjallaire** [comment]
It's not strictly a pandoc recommendation just something we've observed in practice (that most formats make H1 extremely large, awkwardly so in most cases). PDFs are an exception (where H1 looks just fine) so we actually automatically upshift the heading level when rendering to PDF and there are no H1s in the doc: https://github.com/quarto-dev/quarto-cli/blob/main/src/format/pdf/format-pdf.ts#L225-L238

We do this so that users can use common conventions for authoring multi-format docs (i.e. we could say "use H1 for PDF, use H2 for docx, use H1 with custom styles to reduce size for HTML). We'd rather just have people learn that H2 is for intra-document and H1 is for chapters/parts/sections (i.e. slide decks need a way to delineate sections and we use H1 for that)

**Comment by cscheid** [comment]
> We'd rather just have people learn that H2 is for intra-document and H1 is for chapters/parts/sections (i.e. slide decks need a way to delineate sections and we use H1 for that)

This is useful information for our AST documentation/cleanup project as well. (I don't think I saw it articulated explicitly anywhere, but it's possible I missed it.)

**Comment by jooyoungseo** [comment]
@jjallaire  -- I see. I've just found that document title is marked up with `h1`. What if users do not provide title? Do we still start with `h2` in that case as well? In terms of `docx`, could we implement reference_docx and define heading styles in the template? If we ask users to start with `h2` for article sections, wouldn't there be a side effect when they apply reference_docx templates? Sometimes journals provide their Word templates defining all the heading visual styles (starting from h1).

**Comment by jjallaire** [comment]
If users don't provide a title we still start with h2.

Redefining reference_docx is tricky because users will have assumed that they can customize based on Pandoc's built in reference template not ours.

In terms of journals, if they need h1 for sections then the journal docx format can just do `shift-heading-level-by: -1` 

In terms of semantics of H2 for references, given that the title is H1 I do think that it is subsidiary to the document title and a peer of other chapters. If the user has gone "offroad" and decided to use H1 for sections (w/ requisite CSS and/or custom formats to make it look good) that will still work, but I don't think we should change the default to H1 as many users might find it quite strange that the heading size has suddenly grown at the end of the document.

**Comment by jjallaire** [comment]
To sum up here, the entire Quarto system has a strong expectation that H2 will be used for document sections and H1 for the document title (this was also the expectation for R Markdown). Whatever the merits of this position I don't think we can walk it back now and it does seem that there is room for workarounds as required by custom formats.
