### ISSUE TITLE
add basic print styling for html / websites / books

### ISSUE THREAD

**Issue by jjallaire** [quarto-dev/quarto-cli#1824]
At a minimum simply do what @hadley did for R4DS:  https://github.com/hadley/r4ds/blob/main/r4ds.scss#L59-L75

**Comment by hadley** [comment]
Note that it needs something extra for chrome — when I preview it splits lines across pages:
<img width="342" alt="Screen Shot 2022-08-11 at 11 06 08" src="https://user-images.githubusercontent.com/4196/184178852-f4a956b4-12d8-4bdc-8217-2747236535ac.png">

Not sure if this is a chrome bug or could be fixed with some extra margins somewhere.

**Comment by jjallaire** [comment]
I think this just requires that we include some default print CSS here (https://github.com/quarto-dev/quarto-cli/blob/main/src/resources/formats/html/_quarto-rules.scss). Note that we should ensure that the margins are not visible and that any use of margins via `.column-*` end up fitting to the body (as we do on mobile).
