### ISSUE TITLE
On controlling code folding's initial state

### ISSUE THREAD

**Issue by atusy** [quarto-dev/quarto-cli#19]
The Wiki introduces how to control the caption of code fodling with the `fold` chunk option.
However, I think the caption should be tweaked by different chunk option, and the `fold` chunk option rather control if fold is initially open or closed (e.g., `fold="open"`, `fold="closed"`).

Of course we can keep the current implementation and have another chunk option to specify the initial state.

https://github.com/quarto-dev/quarto-cli/wiki/Rendering-Rmds#code-folding

**Comment by apreshill** [comment]
Adding a twitter thread with a similar idea: https://twitter.com/CedScherer/status/1358071832289685505?s=20

https://twitter.com/Sciencificity/status/1358082892283445248?s=20

**Comment by jjallaire** [comment]
We'd just need to add an additional attribute to control this, perhaps:

````r
```{r fold=TRUE, fold.open=FALSE}

```
````

**Comment by jjallaire** [comment]
`fold` actually needs to also accept a state for no folding at all. So we could use something like:

```
fold = "none" | "open" | "closed"
```

and then:

```
fold.summary = "Show code"
```

We could also call it `fold.cap` (for consistency with `fig.cap`) but the actual HTML `<details>` tag has a `<summary>` tag. Not exactly sure which way to go here.

**Comment by atusy** [comment]
I think `fold.cap` is fine because we are already substitute `details` by `fold`.
In other words, `fold.cap` sounds more intuitive and is shorter than `details.summary`.

**Comment by jjallaire** [comment]
Since we need 2 attributes anyway, I think I'll keep the current option as-is and add a `fold.open` attribute (which matches w/ the `open` attribute on the `<details>` tag)

**Comment by jjallaire** [comment]
Scratch that last comment, still thinking it over....

**Comment by atusy** [comment]
> add a fold.open attribute 

If this is likely, I suggest `fold.open=NULL | NA` as a way to opt-out code folding.

BTW, my **minidown** package does not only support folding sources but also outputs, messages, warnings, and errors (https://minidown.atusy.net/#code-folding).
If this is likely to happen sometime in the future, I suggest chunk options something like `fold.source` and so on like `class.source`.

**Comment by jjallaire** [comment]
In this particular case we're not trying build out a fully comprehensive HTML document format, but rather a minimal core format. This is a difference in philosophy w/ R Markdown, which tried to throw the kitchen sink into `html_document` but then ended up never quite having enough features and being stuck on Bootstrap 3. The idea w/ Quarto will be that all the "interesting" HTML document formats will be extensions, which should allow for a more dynamic ecosystem.

So I won't try to define the entire schema here, but rather provide a simple base capability that all HTML formats get for free. More comprehensive schemes like the one you have in minidown can create their own more elaborate constructs. 

So I'd like to keep this expression very simple and straightforward (not too many nested dots, etc.) but still leave the door open for custom formats to do something more elaborate. Since I think the dominant case is folding the code itself, we could use these very straightforward attributes by default:

```
fold = "none" | "show" | "hide"
summary = "My code summary"
```

This leaves the namespace open for a custom format to define e.g.

```
source.fold
message.fold
results.fold
source.summary
message.summary
results.summary
```

There is one other unfortunate constraint I am managing against here: To be consistent with pandoc we are using `kebab-case` for Quarto YAML options (e.g. `keep-md`, `keep-yaml`, etc.). However, for consistency with knitr and due to constraints in Jupyter Markdown parsing we are using `dot.case` for chunk options. This creates an inconsistency, and therefore a bias towards chunk option names that use a single word to dodge this inconsistency (thus `fold` and `summary` above).

**Comment by atusy** [comment]
Thank you for the thoughtful explanation! I love the idea!!
I also agree `fold` and `summary` are simple and useful enough!!

**Comment by jjallaire** [comment]
Great, I will implement it that way and post back here when it's done.

**Comment by jjallaire** [comment]
This has now been implemented, updated docs are here: https://github.com/quarto-dev/quarto-cli/wiki/Rendering-Rmds#code-folding

**Comment by jjallaire** [comment]
Note that this isn't yet in our public builds. @dragonstyle Could you do a release for this one so people can try it out?

**Comment by dragonstyle** [comment]
Latest release is built - enjoy!

[https://github.com/quarto-dev/quarto-cli/releases/latest](https://github.com/quarto-dev/quarto-cli/releases/latest)
