### ISSUE TITLE
Column issue

### ISSUE THREAD

**Issue by garthtarr** [quarto-dev/quarto-cli#1940]
### Bug description

The column width parameter seems to have stopped working.

It's not working with the current [5ca1740](https://github.com/quarto-dev/quarto-cli/commit/5ca1740bc5bb503a5e8c0f375889744aabde0864)... checking back in time... it also doesn't work here de145553da303d126fcf58294e2e2c968189be11 (pandoc 2.19) but it was working in the commit before that which used pandoc 2.18 5abea1a0387e282467ae96829725ddf84a23779e

```
---
title: "Untitled"
format: revealjs
---


:::: {.columns}

::: {.column width="20%"}
Left column (20%)
:::

::: {.column width="80%"}
Right column (80%)
:::

::::
```

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [X] included a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] documented the quarto version you're running, by pasting the output from running `quarto check` in the "Quarto Check Output" text area?
- [X] documented the version of the quarto tools you're running, by providing the output from running `quarto tools check` in the "Quarto Tools Check Output" text area?
- [X] documented the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.
- [X] upgraded to the latest version, including your versions of R, the RStudio IDE, and relevant R packages?

**Comment by jjallaire** [comment]
Reported this issue to Pandoc here: https://github.com/jgm/pandoc/issues/8232

**Comment by jjallaire** [comment]
It has been fixed upstream however there is not yet a release with the fix. In the meantime we have a local fix to make it work as expected: https://github.com/quarto-dev/quarto-cli/commit/a43090353c454860dca50164f06896dec5a48968

**Comment by garthtarr** [comment]
Thanks for adding a local fix (and so quickly!).

Possibly related, code blocks used to scroll horizontally (which I found great, especially given there's the copy option in the top right), but now the column width grows to accomodate the code block. Example:

```
---
title: "Column width"
format: revealjs
---


:::: {.columns}

::: {.column width="20%"}

```{r}
ten = 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1
```

:::

::: {.column width="80%"}

```{r}
five = 1 + 1 + 1 + 1 + 1
```

:::

::::
```

**Comment by jjallaire** [comment]
@tarleb Is this intended new behavior? (columns in slide will actually grow and shrink w/ the content rather than strictly adhere to the width percentages). It seems like this is indeed the default behavior for flexbox (there may be some additional flex attributes you can specify to force the size but at that point I wonder if that's just equivalent to using %)

**Comment by tarleb** [comment]
Neither of these was intentional. The fix has been released as part of pandoc 2.19.1, restoring the effect of setting a `width`. Sorry for the trouble.

We *could* change the default to make columns being adjusted automatically, but I'd like to be sure that the change is desirable. The (old and current) default is to assume equally sized columns if no width it set. Automatic sizing would probably work well for most people, and would also allow to set the width only on a single column.

Here's a snippet that could be included anywhere in the .qmd file to test this change:

``` html
<style>
.columns > div.column{flex: auto;} /* pandoc's default is flex:1, i.e., equally sized columns */
</style>
```

I'd be happy to make `flex:auto` the new default.

**Comment by tarleb** [comment]
For completeness, this is the PR that introduced the bug: https://github.com/jgm/pandoc/pull/8208
The motivation for the change was to allow multiple columns without having to set an explicit `width`. We (I) forgot to update the HTML writer after merging this, thereby causing the issue.

**Comment by jjallaire** [comment]
@tarleb I don't think the fix is quite complete here -- if you consider the following slide:

```markdown
## Columns

::: columns
::: {.column width="20%"}
::: cell
```default
ten = 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1
```
:::
:::

::: {.column width="80%"}
::: cell
```default
five = 1 + 1 + 1 + 1 + 1
```
:::
:::
:::
```

You get this (which doesn't respect the widths because flex is allowing the first column to push out):

![Screen Shot 2022-08-20 at 9 03 33 PM](https://user-images.githubusercontent.com/104391/185771127-c005b847-9202-4243-be9d-e7593bea46c0.png)

**Comment by jjallaire** [comment]
@tarleb I'm wondering if it might be better to revert to the previous behavior (as there is tons of existing content out there relying on it) and experimenting a bit more w/ a way to overlay the new behavior more gracefullly (e.g. some version of flex that doesn't allow stretching, some conditionality on the CSS based on whether explicit widths are specified, etc.)

**Comment by tarleb** [comment]
I see what you mean now. I'm ok with reverting to non-flex behavior, although I'd prefer to keep the new style if possible.

This restored the correct column widths in my tests:

``` html
<style>
div.column { overflow-x: scroll }
</style>
```

Maybe we should add both the `flex:20%` and `width:20%` style to `.column` divs; that'd allow us to override the use of flex boxes via CSS. I'll open a pandoc PR for that.

**Comment by tarleb** [comment]
I found that the `overflow-x: scroll` solution doesn't work well in Chromium, so it's not an option.

**Comment by jjallaire** [comment]
@dragonstyle This is a reminder to update to Pandoc 2.19.2 and to check the behavior of columns once we do that.

**Comment by dragonstyle** [comment]
We are updated to 2.19.2
