### ISSUE TITLE
Deployment with Github Pages 

### ISSUE THREAD

**Issue by msh855** [quarto-dev/quarto-cli#2055]
I have created a Blog and I use Github Pages to deploy it. 

However, my blog struggles to get updated on the web when I have modified something in an old post. 

What I do, is that I push the changes to the main repo and then I go to the terminal and just type the usual command: `quarto publish `

I have tried to delete my cache in the browser, but the blog fails to update. 

I honestly cannot understand what is the process to update a blog manually, i.e. without GithubActions, when one is using Github Pages for deployment.

**Comment by cscheid** [comment]
Thanks for the report. Can you follow our github issue template so we have a reproducible example to work with? We could use the output of the terminal as you run `quarto publish`, and ideally a public github repository.

Instead of checking your cache or your local rendering, you can also navigate to the `gh-pages` branch of your repository to see the changes.

**Comment by cscheid** [comment]
Can you share the terminal output of `quarto publish`?

**Comment by cscheid** [comment]
> FYI, to make things work, I deleted manually the _site folder before I publish

Do I understand it right that the problem is solved for you? Looking at 
https://github.com/msh855/TheQuantEconomist/commits/gh-pages, I can see a transient error on github, specifically: https://github.com/msh855/TheQuantEconomist/runs/7958775180?check_suite_focus=true. Could that have been the issue?

**Comment by cscheid** [comment]
Can you share the terminal output of `quarto publish` when you _don't_ delete the `_site` folder?

If you can also share it in a markdown code block rather than screenshots, that will help making your issue searchable in the future. Thank you!

**Comment by cscheid** [comment]
I really do suspect this was some transient issue with GitHub Pages. For your own future debugging, here's a nifty GitHub trick. If you refer to this part of the log:

```
[gh-pages ed5b0e2] Built site for gh-pages
 4 files changed, 8 insertions(+), 8 deletions(-)
origin	https://github.com/msh855/TheQuantEconomist.git (fetch)
origin	https://github.com/msh855/TheQuantEconomist.git (push)
To https://github.com/msh855/TheQuantEconomist.git
   13c1179..ed5b0e2  HEAD -> gh-pages
```

you'll see `13c1179..ed5b0e2`. This indicates the old and new commits. You can just append that to `
https://github.com/msh855/TheQuantEconomist/compare/`, which is the URL for comparing commits from your repo. That yields [this link](https://github.com/msh855/TheQuantEconomist/compare/13c1179..ed5b0e2) where you can see the changes.
