### ISSUE TITLE
Problem when connecting to MySQL using environmental variables

### ISSUE THREAD

**Issue by jospueyo** [quarto-dev/quarto-cli#2145]
I set up a connection to a database but Quarto throws an error when rendering (not if I execute the chunk). The same code in Rmarkdown works smoothly.

```
library(dbplyr)

conn <- DBI::dbConnect(RMySQL::MySQL(),
                 host = "my_hostname",
                 user = "my_user",
                 password = Sys.getenv("PASSWORD_DB"),
                 dbname = "my_db",
                 port=3306)

my_table <- tbl(conn, "my_table")
```
This is the error:
```
#> Quitting from lines 11-28 (ECS_data_mining.qmd) 
#> Error in .local(drv, ...) : 
#>  Failed to connect to database: Error: Access denied for user 
#> my_user'@'2a01:57a0:1608:6300:8818:75ea:8b53:6933' (using password: NO)
#> Calls: .main ... eval -> <Anonymous> -> <Anonymous> -> .local -> .Call

#> Execution halted
```

**Comment by cderv** [comment]
This seems like a R error to me, and I am not sure Quarto is involved. 

* Does this work in the R console ? 
* Can you try out quickly in a R Markdown document ? 

This will allow us to rule out Quarto or not, and look into this in the proper place. 

Thank you

**Comment by cscheid** [comment]
> The same code in Rmarkdown works smoothly.

@cderv - they did try it in Markdown, just FYI

**Comment by jospueyo** [comment]
I wrote manually the environment variable in my .Renviron file and now it works because using `Sys.setenv()` only stored my variable while the session was active (weird, isn`t it?). So, I don't know, maybe I had a problem with `Sys.setenv()` that Rmarkdown could overpass and Quarto didn't. Does it make sense?

**Comment by cderv** [comment]
Oh @cscheid thank you. I read too fast and missed that. 🤦 

> So, I don't know, maybe I had a problem with Sys.setenv() that Rmarkdown could overpass and Quarto didn't. Does it make sense?

@jospueyo where did you put the `Sys.setenv()` ? In the same Quarto document as the ` DBI::dbConnect(RMySQL::MySQL(),` ? 
I am just curious to understand the difference between R Markdown and Quarto on this. 

Also more generic on good practice, putting such environment variable in .Renviron seems a good solution. Using tools like the **config** R 📦 is also an alternative. And there are others considered safer too
See more on how to work with DB and R in https://db.rstudio.com/best-practices/managing-credentials

**Comment by jospueyo** [comment]
I used `Sys.setenv()` from the console since the goal is not to have the passwords written in the code.

Thank you for the recommendations! I'll take a look,

**Comment by cderv** [comment]
> I used Sys.setenv() from the console since the goal is not to have the passwords written in the code.

So that explains the difference, mainly because R Markdown is built on R and Quarto is only using R as a computation engine. 
Let me explain more

* `rmarkdown::render()` when run in the R console will execute in the same environment and session as your existing interactive console. So setting the environment variable will work because it is still set to your value when rendering from R console. 
* It will also work when clicking the Knit button in RStudio IDE despite the fact it is in another session because the IDE will run a clean background process for you **but** will copy the environment variables. 

* Quarto is its own executable, that will run in its own process completely independent of your R session. R is not needed to run `quarto`. R will only be run as part of the rendering to execute in background process any computational chunks. 
This means that, when using Quarto from RStudio, anything that you define in your current R session won't apply to the R sessions that Quarto will run. 

By defining only the credentials in your R environment before rendering with Quarto, it won't get picked up. You need to use a way that allows the R code run in Quarto to get the information. `.Renviron` is one of them. 

Hope it helps understand.

**Comment by jospueyo** [comment]
Thank you!
