### ISSUE TITLE
[Bug] some `crossref` options do not work for pdf format 

### ISSUE THREAD

**Issue by juliantao** [quarto-dev/quarto-cli#215]
It seems that some of the `crossref` options do not work for `pdf` formats.

I included the following in the YAML header:
```{yaml}
crossref:
  fig-title: "**Figure**"
  tbl-title: "**Table**"
  title-delim: "."
  fig-prefix: Fig.
  tbl-prefix: Table
```
When rendered to `html`, all the options work properly.

For `pdf` output, the `fig-prefix` and `tbl-prefix` were rendered as expected, but the `fig-title`, `tbl-title`, and `title-delim` were still rendered with default formats.

**Comment by jjallaire** [comment]
Since LaTeX takes care of formatting the table and figure captions directly, we need to communicate these settings to LaTeX as follows:

```tex
\AtBeginDocument{%
\renewcommand*\figurename{Figure}
\renewcommand*\tablename{Table}
}
```

We can't readily pass formatting directives to these macros (see https://tex.stackexchange.com/questions/82993/how-to-change-the-name-of-document-elements-like-figure-contents-bibliogr)

We also don't currently attempt to forward delimiters to LaTeX although I just noted here (http://www.peteryu.ca/tutorials/publishing/latex_captions) that this is indeed possible.

These limitations were unfortunately not documented --- I've just remedies this. Will also keep this issue open as I think there is definitely more we should be doing here.

**Comment by mcanouil** [comment]
FYI, it's still happening in current 1.3 pre-release, at least for `title-delim`.
I think it would be good to put this for 1.4 milestone.
