### ISSUE TITLE
`code-tools` options mapping buggy in v1.1?

### ISSUE THREAD

**Issue by pat-s** [quarto-dev/quarto-cli#2161]
### Bug description

With the new quarto 1.1.147 release we see the following error when rendering a book

(https://github.com/mlr-org/mlr3book/runs/8047883939?check_suite_focus=true#step:13:16)

```bash
In file book/_quarto.yml
(line 67, column 7 through line 68, column 23) Key code-tools has value toggle: true
      code-fold: false, which must be `true` or `false`
66:     code-tools:
67:       toggle: true
          ~~~~~~~~~~~~
68:       code-fold: false
    ~~~~~~~~~~~~~~~~~~~~~~
69:     highlight-style: printing
✖ The value toggle: true
      code-fold: false is object.
ℹ The error happened in location format:html:code-tools.
```

AFAICS our source specification https://github.com/mlr-org/mlr3book/blob/main/book/_quarto.yml#L66-L68 looks still valid when compared to the [quarto documentation source](https://quarto.org/docs/output-formats/html-code.html#code-tools) - is this a bug in the new release?

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] Please [format your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by dragonstyle** [comment]
It looks like the `code-fold` option is indented under `code-tools`, which isn't correct (it should be a peer to `code-tools` since it isn't one of the options for `code-tools`). In 1.1 we are tightening up the schema to avoid 'open' unvalidated schema where possible, so a mistake like this might have been slipping through (without causing any issue since `code-fold` is false by default) in previous versions and we will now catch it starting in 1.1.
