### ISSUE TITLE
unexpected behavior in callouts using `#xxx-` label as header

### ISSUE THREAD

**Issue by HelenaLC** [quarto-dev/quarto-cli#2241]
In order to have numbered callouts (e.g., for cross-referenceable exercises and solutions), I have attempted to

- set callout captions to be empty via the *_quarto.yml* file
- use "#exr-" (or similar) as headers in the callouts

with the somewhat unexpected result that

- printed names (here, "Exercise") are rendered twice
- the corresponding counted is incremented twice

I am not sure whether this is a bug per se, but any suggestions how to achieve/fix this would be greatly appreciated!

**_quarto.yml:**

```
format: html
language:
  callout-note-caption: ""
```

**.qmd:**

```
::: {.callout-note #exr-one}

text

:::
See @exr-one.
```

**output:**

![image](https://user-images.githubusercontent.com/14542264/187746749-6d313de4-52d0-4592-a2fd-0e99bc2fd187.png)

- This works, but isn't ideal:

```
::: {.callout-note}
::: {#exr-two}

text

:::
:::

See @exr-two.
```

![image](https://user-images.githubusercontent.com/14542264/187746696-1a1779f1-f271-4085-b84a-22108875836d.png)

**Comment by mcanouil** [comment]
Indeed, I noticed/reported recently in #1928.

**Comment by cscheid** [comment]
Callouts are now cross-referenceable, but do note that for the time being, that means that you can't use "exr-" for a callout, since that's an _exercise_. We'll improve the situation in the next few weeks. The prefixes are:

- Note: `nte-`
- Warning: `wrn-`
- Caution: `cau-`
- Tip: `tip-`
- Important: `imp-` (We're aware that this causes weird phrasing in the resulting text, but we're doing it anyway for consistency with the original callout types)
