### ISSUE TITLE
Jupiter notebook to html render problems

### ISSUE THREAD

**Issue by ea42gh** [quarto-dev/quarto-cli#2243]
### Bug description

Admittedly complicated notebooks not rendering correctly.
The image below shows part of the render of
https://gitlab.com/ea42gh/elementary-linear-algebra/-/blob/master/notebooks/04_MatrixAlgebra.ipynb

The directory contains a number of notebooks that all fail...
![foo](https://user-images.githubusercontent.com/13033479/187792437-1a3a2ea2-7275-497b-b2df-b2b421484302.jpg)

os: windows 11
quarto 1.1.113

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] Please [format your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
Thanks for the report! Unfortunately, I think you're seeing this issue because you're using HTML blocks that are very heavily styled, and those will generally play badly with our markup.

I would recommend that you use (for example) our markup for callouts, etc, and don't use HTML styling unless you absolutely need to.
