### ISSUE TITLE
Issue rendering multiple DT tables in multiple `panel-tabset` (all appear reliably after refresh)

### ISSUE THREAD

**Issue by rich-iannone** [quarto-dev/quarto-cli#2271]
### Bug description

Issue taken from [Stack Overflow](https://stackoverflow.com/questions/73548259/tabsets-not-rendering-datatables-properly-for-quarto-revealjs-presentation) and is reproducible on my system (macOS, latest) with Quarto `1.1.179`. Problem is that in later slides some of the DT tables aren't rendered (usually in tabs 2 and 3). Refreshing causes them to appear. Might be a variation of https://github.com/quarto-dev/quarto-cli/issues/1076.

````
---
title: "test"
format: revealjs
editor: visual
---

---
format: 
  revealjs

execute:
    echo: false
    message: false
---

```{r}
#| label: load-packages
#| include: false

library(tidyverse)
library(DT)

options(dplyr.summarise.inform = FALSE)
```

# Data prep

```{r echo=TRUE}
dat1 <- diamonds %>%
  group_by(cut) %>%
  summarize(n = n(), price = round(mean(price), 2))
dat2 <- diamonds %>%
  group_by(carat) %>%
  summarize(n = n(), price = round(mean(price), 2))
dat3 <- diamonds %>%
  group_by(clarity) %>%
  summarize(n = n(), price = round(mean(price), 2))
```

## Page 1

::: panel-tabset
### Tab 1

```{r}
#| label: tab-1-1
datatable(dat1)
```

### Tab 2

```{r}
#| label: tab-1-2
datatable(dat2)
```

### Tab 3

```{r}
#| label: tab-1-3
datatable(dat3)
```
:::

## Page 2

::: panel-tabset
### Tab 1

```{r}
#| label: tab-2-1
datatable(dat3)
```

### Tab 2

```{r}
#| label: tab-2-2
datatable(dat1)
```

### Tab 3

```{r}
#| label: tab-2-3
datatable(dat2)
```
:::

## Page 3

::: panel-tabset
### Tab 1

```{r}
#| label: tab-3-1
datatable(dat3)
```

### Tab 2

```{r}
#| label: tab-3-2
datatable(dat1)
```

### Tab 3

```{r}
#| label: tab-3-3
datatable(dat2)
```
:::
````

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by allenmanning** [comment]
Are we feeling comfortable adding a milestone to this?  @cscheid

**Comment by cscheid** [comment]
It turns out that this is a gt bug, so our milestones don't apply

**Comment by rich-iannone** [comment]
Panicked for a moment, but really a DT bug. @allenmanning should this issue be moved over to `rstudio/DT`?

**Comment by cscheid** [comment]
DT, sorry! :)

**Comment by cderv** [comment]
I don't think this is only a DT issue, and maybe a DT behavior that we can work around it on our side. 

First of all, user has answered on Stackoverflow (https://stackoverflow.com/a/73692462/3436535) and this tells us that this behavior has been discussed in 2016 by @yihui https://groups.google.com/g/shiny-discuss/c/4E61F-tvGR4

In short: **DT** seems to hold off rendering of the data until this content is made visible. (So yes @rich-iannone related to #1016 I believe. 

Yihui answer at the time: 

> I think that was due to https://github.com/rstudio/DT/blob/aad518c5b/inst/htmlwidgets/datatables.js#L73
The intention here was to hold rendering until the table becomes visible: https://github.com/rstudio/DT/blob/aad518c5b/inst/htmlwidgets/datatables.js#L864
Well, other than "becoming visible", one of these events has to be triggered: https://github.com/ramnathv/htmlwidgets/blob/7454758379/inst/www/htmlwidgets.js#L582-L600

If this is something related to events, I believe we could add a RevealJS hook to handle that at slide change. I am willing to try it @cscheid unless you wanted to do something else (it is assigned to you so asking)

**Comment by cscheid** [comment]
@cderv It's assigned to me just so that there's someone responsible for it. Please go ahead and give it a shot!

**Comment by cderv** [comment]
Thanks @cscheid ! 

I got to the bottom of this now. What happens is that, htmlwidgets needs to be resized when render in static document. There are specific function in htmlwidget.js for that with specific event ([source](https://github.com/ramnathv/htmlwidgets/blob/7454758379/inst/www/htmlwidgets.js#L569-L615))

htmlwidgets R packages already handles some events  like `resize` event of `window`, or triggered in specific cases like  bootstrap tab, or bootstrap collapse. 

In Quarto, we do already the same thing - we trigger the event that will trigger the resize of htmlwidgets. We do that for Boostrap tabs 
https://github.com/quarto-dev/quarto-cli/blob/e448ec2118f0d0317f535b786a7bc0e8b7add3fc/src/resources/formats/html/quarto.js#L25-L34

and also for slides specifically 
https://github.com/quarto-dev/quarto-cli/blob/72d212c88147ab7e187093536d5047fef718023d/src/resources/rmd/execute.R#L305-L344

This handles DT and other HTML widgets. 

The issue we have here is that Tabsets are used. And in format like reveal.js this is using tabby.js and not bootstrap tabs. 
We need to specifically trigger the same event when tabs change in Tabby. Doing this in Console in the document opened in browser works 
````js
document.addEventListener('tabby', function (e) {
	// dispatch for htmlwidgets
    const event = window.document.createEvent("Event");
    event.initEvent("slideenter", true, true);
    window.document.dispatchEvent(event);
}, false);
````

I believe this is the issue and so that it is not related to **DT**. This will happen in **revealjs** with any widgets in slides. 

I see two solutions: 

1. Make **htmlwidgets** package aware of _tabby.js_ and support also this events. However, tabby.js seems quite specific to Quarto... 
2. so I think we should handles this ourselves by adding the event trigger - I am just no sure where. 

Probably in the same place as other in execute.R would be fine. I'll open a PR for this, unless one of things it should be elsewhere. 
(I was puzzled by the `quarto.js` solution added as a dependency, for one case, and the inline solution in an R script, for the other. I wasn't sure if it needs refactoring).

> Problem is that in later slides some of the DT tables aren't rendered

Note about that, this is revealJS specific because to the `viewDistance` feature (as revealjs will make several slides visible in addition to one on screen). So I think it triggers correctly the htmlwidget rendering.
