### ISSUE TITLE
Include file contents in code block is not working

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#2314]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/2312

<div type='discussions-op-text'>

<sup>Originally posted by **plessl** September  6, 2022</sup>
Hi Quarto community.

I recently discovered Quarto and I'm very impressed by this wonderful software.

I'm currently preparing a companion site to a lecture using Quarto where it would be helpful to keep code examples in files and include the contents in an HTML code cell in order to avoid code duplication (and to work around some limitations in Quarto, Juypter and Julia).

I would like to write code like this:

````
```julia
{{< include example.jl >}}
```
````

Unfortunately, this doesn't work. Instead of the contents of `example.jl` Quarto treats `{{< include example.jl >}}` like a line of Julia code and prints it. Is this a bug? Or does the include need to be escaped somehow?

Thanks,
 Christian
</div>

**Comment by cderv** [comment]
it seems broken again. I can reproduce on 1.1 and 1.2 and we are supposed to look into Code blocks: 
https://github.com/quarto-dev/quarto-cli/blob/0facbe6664e77be39b9a900cf9df29c8ffcb8b2a/src/resources/filters/quarto-pre/shortcodes.lua#L14

**Comment by cscheid** [comment]
This is a consistently unfortunate bit of semantics of the `include` shortcode. It cannot be implemented in Lua because that's too late (eg if includes have computational content, they need to execute before knitr).

Regardless of that detail, it's still the case that we're not resolving includes inside code blocks, while we _do_ resolve other shortcodes in code blocks inside Lua filters. I was under the impression that we didn't want shortcodes to be resolved in code blocks, but the Lua code clearly suggests otherwise.

I think the proper resolution of this is to allow pre-engine filters through two passes of Pandoc like we've been discussing. 

@jjallaire @dragonstyle let's discuss this on our next weekly to see how we want to resolve the problem?

**Comment by cscheid** [comment]
(Really unfortunate typo in my commit, sorry.)

**Comment by vsheg** [comment]
I hope including of ipynbs will be supported: `{{< include demo.ipynb >}}`

**Comment by cscheid** [comment]
@vsheg We are not planning on that; it crosses abstraction layers in our implementation that would be tricky to make work robustly.

**Comment by cderv** [comment]
Just an update on this : Quarto now has an extension for that: https://github.com/quarto-ext/include-code-files

Syntax is different by purpose is the same: Add a code block with a language and use content from a file.

**Comment by cscheid** [comment]
Given the [include-code-files extension](https://github.com/quarto-ext/include-code-files) and the [`{{< embed >}}` shortcode](https://quarto.org/docs/prerelease/1.3/embed.html) functionality in 1.3, I think that covers the requests in this issue. I'm going to go ahead and close it.
