### ISSUE TITLE
revealjs `fig-align` and caption

### ISSUE THREAD

**Issue by JulianTao** [quarto-dev/quarto-cli#233]
Follow up on the [comment](https://github.com/quarto-dev/quarto-cli/pull/231#issuecomment-998496713) I made on #231, potentially related to #224, #231, and #232.

Hopefully, the following example can be reproduced on your side @cderv 

<details>
<summary>revealjs_figalign.qmd</summary>

```markdown
---
format: revealjs
---

## No `fig-align` nor caption 

![](https://placekitten.com/300/300)

## No `fig-align` but caption 

![caption](https://placekitten.com/300/300)

## With `fig-align="center"` 

![](https://placekitten.com/300/300){fig-align="center"}

## Caption and `fig-align="center"`

![caption](https://placekitten.com/300/300){fig-align="center"}

## With `fig-align="right"`

![](https://placekitten.com/300/300){fig-align="right"}

## Caption and `fig-align="right"`

![caption](https://placekitten.com/300/300){fig-align="right"}

```
</details>

**Findings:**

1.  If there is a single figure on a slide without caption nor a `fig-align` attribute, the figure is aligned to the left, which is contradictory to the default [as described in the documentation](https://quarto.org/docs/authoring/figures-and-layout.html#figure-alignment). 
2. Interestingly, if a caption is given, the figure will be centered, but the caption is aligned to the left.
3. To center a single figure without caption, one need to manually add the `fig-align="center"` attribute
4. Captions are always aligned to the left no matter where the figure is placed.

**Desired outcome:**

1. If a figure is included without caption, it should be placed at the center
2. If a figure is included with a caption, the caption should be placed right below the figure.

**Comment by cderv** [comment]
Thanks for the feedback. I don't see any issue with reveal `auto-stretch` now following #232. 

Here is what I understand of the current behavior. 

> If there is a single figure on a slide without caption nor a fig-align attribute, the figure is aligned to the left, which is contradictory to the default as described in the documentation.

and 

> To center a single figure without caption, one need to manually add the fig-align="center" attribute

In Quarto (and Pandoc), a figure (https://quarto.org/docs/authoring/figures-and-layout.html) is an image with a caption
_"In Pandoc markdown, a figure is created whenever a captioned image appears by-itself in a paragraph."_

So what is described in https://quarto.org/docs/authoring/figures-and-layout.html#figure-alignment applies on figure. 
You won't get a center align image in `html` format either if no caption. `revealjs` format respects that. 

````
---
format: html
---

## No caption

Image is not centered

![](https://placekitten.com/300/300)
````

But maybe they should be ? Is this a choice @jjallaire ? 

> Interestingly, if a caption is given, the figure will be centered, but the caption is aligned to the left.
and 
> Captions are always aligned to the left no matter where is the figure placed.

We had a discussion with @jjallaire about that and this is currently by design: caption are left align all the time and not respecting `fig-align`. Did I understand correctly @jjallaire ? 

It seems you pointed us were an outdated documentation on this as https://quarto.org/docs/authoring/figures-and-layout.html#figure-alignment says 
_"Figures **and their captions** are center aligned by default."_


>  If a figure is included without caption, it should be placed at the center
>  If a figure is included with a caption, the caption should be placed right below the figure.

Thanks for your feedback on this - that is helpul ! 
I share the same feedback and caption alignment feels a bit off. Even if left align caption if a choice, it would perhaps feel better left align relatively to the image. 

I let @jjallaire comment as I think some of this is by choice and don't know what could be reconsidered.

**Comment by JulianTao** [comment]
Thanks for the reply!

> In Quarto (and Pandoc), a figure (https://quarto.org/docs/authoring/figures-and-layout.html) is an image with a caption
> _"In Pandoc markdown, a figure is created whenever a captioned image appears by-itself in a paragraph."_

Good to know! I guess all the *figure*s I used in my posts should have been *image*s.  If I can be over picky, we still need to use `fig-align` to align an ***image***  :joy: 

> it would perhaps feel better left align relatively to the image.

I agree with you on that!

**Comment by jjallaire** [comment]
Yes, figure captions are always aligned to the left. This is because very often figures will be narrow and captions will contain long explanations. If the caption was bounded into the figure box it could create captions that are many, many (even more than a dozen) lines long. Really, so long as the caption occupies ~ 80% + of the line the left aligned caption will look fine. Short captions I agree don't fare well esp. w/ narrow figures. I believe that the LaTeX typesetting algorithms might handle this automatically (left aligned by default but centered for some shorter captions). HTML doesn't currently have this level of smarts so we have chosen what we think is the most practical default.

**Comment by JulianTao** [comment]
Thank you for the detailed explanation @jjallaire !
This default now works for my use case where I have a single big figure on a slide, and the left-aligned caption will in fact look nice.  More often on a slide, I'll have two columns: one with a figure and the other with a bullet list. A layout div is perfect for that.
