### ISSUE TITLE
gt::as_raw_html, purrr::walk and quarto interaction error

### ISSUE THREAD

**Issue by boshek** [quarto-dev/quarto-cli#2370]
### Bug description

👋  thank you _so_ much for this project. I am so grateful to be using it. 

Something that is very handy is to iterate through a variable and then dynamically create tabs based on values of that variable (here `sex`). There is some strange interaction with the {gt} package whereby I can only make gt work with `purrr::walk` if I use gt::as_raw_html. However if I just produce a single table outside of `purrr::walk `I don't need `gt::as_raw_html`. Here is the error message I get {gt} does not work:

> Error running filter /Applications/quarto/share/filters/quarto-pre/quarto-pre.lua: ...lications/quarto/share/filters/quarto-pre/quarto-pre.lua:2410: attempt to concatenate a nil value (local 'v') stack traceback: ...lications/quarto/share/filters/quarto-pre/quarto-pre.lua:2417: in function <...lications/quarto/share/filters/quarto-pre/quarto-pre.lua:2415>

## editor info
I can reproduce this with RStudio (2022.07.1) and vscode 

## quarto versions tried:
- version 1.1.175
- nightly version
- **This does work on quarto version 1.0.38**

Here is the quarto code to reproduce:

````md
---
title: "Untitled"
format: html
execute:
  warning: false
---

```{r r-pkgs}
library(dplyr)
library(glue)
library(gt)
library(purrr)

## just to simplify
starwars <- starwars %>% 
  filter(!is.na(sex))
```

# Does work

::: {.panel-tabset}

```{r}
#| results: asis

walk(
  unique(starwars$sex), \(hw) {
    cat(glue("## {hw} \n\n"))
    
    starwars %>% 
      filter(sex == hw) %>% 
      count(homeworld) %>% 
      head() %>% 
      gt() %>% 
      as_raw_html() %>% 
      print()
    
    cat("\n\n")
  }
)
```
:::


# Does not work

::: {.panel-tabset}

```{r}
#| results: asis

walk(
  unique(starwars$sex), \(hw) {
    cat(glue("## {hw} \n\n"))
    
    starwars %>% 
      filter(sex == hw) %>% 
      count(homeworld) %>% 
      head() %>% 
      gt() %>% 
      print()
    
    cat("\n\n")
  }
)
```
:::

## single does work
```{r}
#| results: asis
starwars %>% 
  count(homeworld) %>% 
  head() %>% 
  gt()
```
````

```md
─ Session info ───────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.2.1 (2022-06-23)
 os       macOS Monterey 12.5
 system   aarch64, darwin20
 ui       RStudio
 ```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cderv** [comment]
This is a bug in Quarto in the sense that the error is cryptic, and should be improved. but I also believe this has to do with the `print` method used, and the iteration with `walk()`

When you use `print()` after `g()` or after `gt() %>% as_raw_html()` I believe it will not have the same effect, as the `print` method used will not be the same. In the context of **knitr**, this matters. 

Does `as_raw_html()` creates an undesired results ? It makes sense to me to include table as raw HTML in such document, and it probably will have the same result as when **gt** object are printing in knitting to HTML table (though the use of **htmltools**).
When you use `gt() %>% print()`, it will not use the correct printing method that is used when just `gt()` is in a chunk (the `knit_print()` method [more on that here](https://cran.r-project.org/web/packages/knitr/vignettes/knit_print.html) for advanced understanding.

@rich-iannone it would be interesting to know you recommandation of how to "print explicitly" a gt table in a R Markdown document

Let me add some context about **knitr** and dynamically created content. 

Iterating to dynamically create content in **knitr** require to use the correct print method (usually `knit_print()`), and it is better to iterate on child content with `knitr::knit_child()` function that will correctly handle the printed output specific to sewing result in the document. We have some resource about that in R Markdown Cookbook that would apply to Quarto as well. 

* About `knit_child()` : https://bookdown.org/yihui/rmarkdown-cookbook/child-document.html
* About `knit_expand()` also : https://bookdown.org/yihui/rmarkdown-cookbook/knit-expand.html

Let me build an example using this programmatic way. I'll update below

**Comment by boshek** [comment]
👋 @cderv 

I can't even begin to express how amazing this answer is. Thank you thank you!

**Comment by cderv** [comment]
You're welcome. Glad it helps!  

I believe on our side, we could do two things: 

* Documents this as an example. @cscheid would it be a good fit for https://github.com/quarto-dev/quarto-examples ? Not sure about the scope there yet... I could make a blog post otherwise maybe. 

* Improve the error message somehow when the content is not what we expect; 
> Error running filter /Applications/quarto/share/filters/quarto-pre/quarto-pre.lua: ...lications/quarto/share/filters/quarto-pre/quarto-pre.lua:2410: attempt to concatenate a nil value (local 'v') stack traceback: ...lications/quarto/share/filters/quarto-pre/quarto-pre.lua:2417: in function <...lications/quarto/share/filters/quarto-pre/quarto-pre.lua:2415>

This is really not helpful at all !

**Comment by cscheid** [comment]
@cderv yes wrt examples, please start adding them! :)

wrt error messages: I agree, but this is much harder because it's coming from Lua, and not Typescript. We don't have the same infrastructure to generate good error messages there.

**Comment by cderv** [comment]
> We don't have the same infrastructure to generate good error messages there.

Oh I see. i believe we could still do some checks and throw error if we don't get what we expect in the AST. But maybe that is not as easy. I'll leave this open and have a look

**Comment by cderv** [comment]
Yes it seems like a good way if you want to split in several files. We'll add such cases in the examples. (Or do send PR in the example repo if you wish). Thank you !

**Comment by cscheid** [comment]
I'm pushing this back to 1.3 because it's a Lua filter issue, and I think we'll be spending much of our 1.3 on filters. I'm reluctant to make a change right now ahead of our upcoming 1.2 release.

**Comment by akaviaLab** [comment]
This a request on the future examples work, I'd like someone to explain how to show graphs (created via map).
I create a list of plots this way
`exploratory_plots_run <- map2(run_variables$sample_vars, 
                              run_variables$qc_vars, 
                              ~ run_qc_data_thresholded %>%
                                exploratory_density_2_groups(.x, .y))`

When I'm editing the Quarto document, I do
`map(exploratory_plots_run, pluck)` to show them, but that's not in tabs

Not posting the actual data since it is proprietary.

How do I show them in tabs? 
(I tried adapting the example, and it didn't work).
If I show them in tabs, is there a way for Rstudio to show them when I'm working on my code, or do I need to have a version for editing (with/without tabs) and a version for publishing?

**Comment by cscheid** [comment]
I did just find a bug in how quarto handles some styles of gt tables, and @rich-iannone found a _separate_ bug in how some gt tables are emitted. The quarto change will be available in the 1.3 prereleases coming in, and the gt change will be here soon as well.

Rich, I'm keeping this one open until we have a version of both quarto and gt that works well in this context.

**Comment by waldemarvogt** [comment]
I tried to reproductive the code but unfortunately without success. It is not generating tabsets, all tables are in one 'line'. 
Could you please advise me, what could be wrong here? Thanks in advance 

## Tables

::: {.panel-tabset}

```{r,results='asis',echo=FALSE,fig.height=5,fig.width=10}
# https://github.com/quarto-dev/quarto-cli/issues/2370
#| output: asis

res <- purrr::map_chr(unique(infra_top10_categories), \(hw){
  knitr::knit_child(text=c(
    "### `r hw`",
    "",
    "```{r}",
    "#| echo: false",
    "belfius %>%",
      "  filter(category == hw) %>%",
      "  filter_3_month() %>% ",
      "  create_dt()",
      "```",
      "",
      ""
    
  ),envir=environment(),quiet=TRUE)
})

cat(res,sep = '\n')
```
:::

**Comment by waldemarvogt** [comment]
@cderv Thank you for your answer. I figured out what caused a problem. I had "fig.align = 'center" in opts_chunk$set.

**Comment by cderv** [comment]
Ok interesting - thank you for the update

**Comment by cscheid** [comment]
No, this is great! Thank you!

**Comment by SimonCoulombe** [comment]
hey all, just wanted to leave this here as I find this approach cleaner than going the knit_child route.
I ended up creating a [blog post](https://www.simoncoulombe.com/posts/2024-05-11-how-to-loop-stuff-in-tabset--quarto-edition/) showing how to programatically create tabsets and print different type of outputs   (kable, gt, datatable, ggplot, plotly, leaflet, mapview) because I always had to dig up old code.  


````
---
title: "Untitled"
format: html
execute:
  warning: false
keep-md: true
---

```{r r-pkgs}
library(dplyr)
library(glue)
library(gt)
library(htmltools)
library(purrr)

## just to simplify
starwars <- starwars %>% 
  filter(!is.na(sex))
```

# Tables


::: {.panel-tabset}
```{r gt }
#| results: asis
for(i in unique(starwars$sex)) {
  cat(  glue::glue("### gt {i}   \n\n"))
  cat("\n \n")
  
  print(
    tagList(
        starwars %>%
        filter(sex == i) %>%
        count(homeworld) %>%
        head() %>%
        gt()
    )
  )
  cat(' \n \n')
}
```
:::

````

![image](https://github.com/quarto-dev/quarto-cli/assets/23444900/1bc64f90-9850-4eb0-9b41-d5200b153dff)

**Comment by cderv** [comment]
Thanks for sharing this example. 

Some feedback though: It works because here output is HTML only, and not specific HTML dependencies are included by GT. 

So using `print()` method only will work as **gt** is writing the HTML directly with everything included. 

However, for more complex example, `knit_print()` method will be needed, and so `knit_child()` context. For example for using `format: docx`  so that **gt** correctly output openxml, or using another package like **reactable** that would add some JS / CSS dependency to be included into the document. 

So this above works in the limited context of **gt** and HTML output while using a for-loop with print. This is indeed a bit simpler that `knit_child()` - though the latter will always work (as it will call the right printing method required in knitting context). 

Hope it helps clarify. Thanks again !

**Comment by cderv** [comment]
> I have found that using the package once in a non-included chunk above the 'asis' chunk worked for me :

Yes because this first step will run the right `knit_print` and adds the dependencies. If all other calls are loading the same exact deps (JS and CSS), then they will be already available and added correctly in the output. 

This is a trick that brings side effect, but could not be as realiable depending on the variation of the following calls (some leaflet steps for example could add others deps not included in the default first call)
