### ISSUE TITLE
Quarto Preview Fails when run from `subprocess.run` in python on Apple Silicon / M1

### ISSUE THREAD

**Issue by hamelsmu** [quarto-dev/quarto-cli#2420]
### Step 1: Clone the minimal example

```bash
git clone https://github.com/hamelsmu/tquarto.git && cd tquarto
```

### Step 2: Run quarto through a subprocess

(You should look at the contents of this file, it is just two lines of code)

```bash
python run_quarto.py
```

### Step 3: Navigate to the /test.html page (which is also on the navbar)

The Error we get:

```
assertion failed [block != nullptr]: BasicBlock requested for unrecognized address
(BuilderBase.h:550 block_for_offset)
/usr/local/bin/quarto: line 145:  9849 Trace/BPT trap: 5       "${QUARTO_DENO}" ${QUARTO_ACTION} ${QUARTO_DENO_OPTIONS} ${QUARTO_DENO_EXTRA_OPTIONS} "${QUARTO_IMPORT_ARGMAP}" "${QUARTO_TARGET}" "$@"
```

If you don't get an error the first time, you can try this multiple times and eventually get an error.  I've also reproduced this on other machines.

## Info about my system:

- OS: MacOS Monterey 12.5.1, Apple M1 Pro
- Quarto Version `1.2.92`
- Python 3.9.12

##  Observations

- Running `quarto docs` or `quarto preview` does **not** produce the error
- The error only occurs when I run quarto through a subprocess by running `python run_quarto.py`
- The error mostly occurs when I navigate to the page generated by the notebook (i.e. `test.html`), but sometimes also occurs on server start as I think sometimes it tries to open that page directly
- I was able to repro this issue on a M1 Mac server which is a fresh/brand new environment, and other people have been able [to repro as well](https://github.com/fastai/nbdev/issues/1040). 

Could this be related to https://github.com/quarto-dev/quarto-cli/issues/2296 ? 

cc: @jjallaire 

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by jjallaire** [comment]
This error is known to occur if you run the x86_64 version of Deno on M1. My suspicion is therefore that our wrapper script is mis-identifying the platform and running the x86_64 Deno. What happens if you modify the code here to always choose the aarch64 version:

https://github.com/quarto-dev/quarto-cli/blob/main/package/scripts/common/quarto#L126-L135

@cscheid I think we need a more reliable way to detect M1 (e.g. something that inspects the filesystem rather than calling `uname -sm`).

**Comment by cscheid** [comment]
Thanks for the report! How often are you seeing this error on your end? I've done

```
$ python run_quarto.py
Preparing to preview

Watching files for changes
Browse at http://localhost:6882/
GET: /
GET: /test.html
GET: /test.html
GET: /test.html
GET: /test.html
GET: /test.html
GET: /test.html
```

about 10 times on an M1 and couldn't reproduce the issue. I'm on arm64 Python 3.10.6:

```
$ file /opt/homebrew/Cellar/python@3.10/3.10.6_2/bin/python3.10
/opt/homebrew/Cellar/python@3.10/3.10.6_2/bin/python3.10: Mach-O 64-bit executable arm64
```

Can you send us the output of 

```
$ file `which python`
```

or something equivalent to that? (eg I had to go digging a little because I run python through pyenv, and then `which python` is a wrapper script)

**Comment by jjallaire** [comment]
I think the problem is likely to come from running an x86_64 version of Python that launches Quarto (@cscheid I'm assuming that your example is running aarch64 Python?)

**Comment by hamelsmu** [comment]
@jjallaire thanks let me get the info you asked for.  In the meantime, incase it is helpful I [recorded this video](https://www.loom.com/share/f591eb6972be45cbbfbb5e326a7a5f88) with additional commentary if you want to see it live

**Comment by hamelsmu** [comment]
here is the output of which python you requested.  Perhaps this is related somehow?  (I installed python on a fresh machine with Anaconda)

```
%file `which python`                                                                                                              
/Users/hamel/opt/anaconda3/bin/python: Mach-O 64-bit executable x86_64
```

**Comment by cscheid** [comment]
@hamelsmu yes, this is the issue. Note specifically `x86_64` in your python string. You're running the Intel version of Python, which is triggering our process to try to match the architecture. Unfortunately, there appears to be an issue with Intel deno running on aarch64.

Actionable things you can do right now:

- You can ensure you're running an `aarch64` version of Python.
- You can force an `aarch64` version of deno by using the changed script you have.

Things _we_ could do:

1) Have an env var that force-sets the deno architecture.
2) Detect the architecture of the _OS_, rather than that of the parent process. This is a little obnoxious, though, because I think we _should_ be trying to match the architecture of the parent process.

We've had problems in the past where creating subprocesses with files in different architectures caused issues, so I'm not a huge fan of solution 2).

**Comment by jjallaire** [comment]
Yes, @cscheid We saw the same problem when running from our x86_64 Rust binary (which is why we reverted to the script).

@cscheid I think given that we _know_ that Deno crashes when running its x86_64 version on M1 for the time being at least we don't want to match the architecture of the parent process. For the time being at least I think we need to modify our script to detect the OS architecture not the parent process architecture.

**Comment by cscheid** [comment]
> @cscheid I think we need a more reliable way to detect M1 (e.g. something that inspects the filesystem rather than calling uname -sm).

I think it's the other way around. Inspecting the filesystem will require us to find a _file_ that is different between installations of macOS in Intel and Arm. The standard files I'm seeing are all built as universal:

```
$ file /bin/bash
/bin/bash: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64
- Mach-O 64-bit executable x86_64] [arm64e:Mach-O 64-bit executable arm64e
- Mach-O 64-bit executable arm64e]
/bin/bash (for architecture x86_64):	Mach-O 64-bit executable x86_64
/bin/bash (for architecture arm64e):	Mach-O 64-bit executable arm64e
```

This means we won't be able to tell the difference. I thought `$OSTYPE` meant the "os type", but apparently it's determined at compilation time (?!) https://ss64.com/osx/syntax-env_vars.html

So it seems to me that the solution has to be to peek at the output of `uname -sm`

**Comment by hamelsmu** [comment]
@cscheid apologies for the noob question.  Do you know a good way to install an `aarch64` version of python?  IIRC the installers I know about recommend Rosetta, which is some kind of emulator that allows most python dependencies to work under M1, which might be somehow complicating the issue?  I am not sure I can move off of the Rosetta setup or not just yet

**Comment by jjallaire** [comment]
@hamelsmu I wouldn't bother with that -- we need to fix the issue of crashing on M1 and will do so ASAP.

**Comment by hamelsmu** [comment]
🙇🏽 no problem.  Thank you so much for the delightful experience and for fixing things so fast!

**Comment by cscheid** [comment]
Just adding some additional information. The fundamental bug we have is that `uname`, despite what the documentation says, is not about the _system_, but rather about the architecture of the process calling it:

```
$ ../package/dist/bin/tools/deno-aarch64-apple-darwin/deno
Deno 1.25.1
exit using ctrl+d or close()
> Deno.run({cmd: ["uname", "-sm"]})
Darwin arm64
Process { rid: 3, pid: 8466 }
>
$ ../package/dist/bin/tools/deno-x86_64-apple-darwin/deno
Deno 1.25.1
exit using ctrl+d or close()
> Deno.run({cmd: ["uname", "-sm"]})
Darwin x86_64
Process { rid: 3, pid: 8493 }
>
```

**Comment by hamelsmu** [comment]
Awesome, I learned a bunch from this issue too.  Thanks for sharing!

**Comment by jjallaire** [comment]
Thanks @cscheid!  

@hamelsmu, v1.2.101 has the fix: https://quarto.org/docs/download/prerelease.html

**Comment by jph00** [comment]
@hamelsmu and anyone reading this in the future - for installing python, I recommend mambaforge or miniforge, both of which provide the option to install an ARM64 version:

https://github.com/conda-forge/miniforge

BTW here's a little script you can run to auto-install the latest and most appropriate version:

https://github.com/fastai/fastsetup/blob/master/setup-conda.sh
