### ISSUE TITLE
[feature request] Allow `r` like inline code for jupyter/python

### ISSUE THREAD

**Issue by amichuda** [quarto-dev/quarto-cli#244]
Currently, it seems like the only way to do inline code within a jupyter notebook is through the use of `IPython.display`. This can be, at times, cumbersome and would hinder readability of a document. Is there a way to have a similar syntax to R, where you can do ``` `r var` ```?

So something like ``` `py var` ```, for instance?

**Comment by jjallaire** [comment]
Yes, we would definitely like to do this. We are tracking this discussion in the Jupyter community (https://discourse.jupyter.org/t/inline-variable-insertion-in-markdown/10525) which appears to be close to a consensus on how to do this and make it work in JupyterLab, nbconvert, etc. Ideally we'd like to implement a standard rather than doing something ad-hoc --- this means it may take a bit more time but I think it will be worth it to have everyone speaking the dialect of inline expressions.

**Comment by amichuda** [comment]
Oh wow that makes a lot of sense! I'm happy to hear that there's a discussion about this. Thanks for the info!

**Comment by amichuda** [comment]
So it looks like that forum discourse kind of went nowhere unfortunately. Do you think there's a way forward from the quarto side?

**Comment by jjallaire** [comment]
Yes I think we will need to do _something_ later on this year (although I'm still hoping the community coalesces around at least a spec prior to then)
