### ISSUE TITLE
Hybrid sidebar not working?

### ISSUE THREAD

**Issue by giabaio** [quarto-dev/quarto-cli#2536]
### Bug description

This **may be** related to #2466, or may be not... I can't seem to make the hybrid sidebar work. The site [here](https://github.com/giabaio/reprex-site) contains a few pages/folders. I have (successfully) setup a navigation bar and would like to add a sidebar for two of the other folders (`research` and `book`). I can't seem to make it appear on the research page/folder --- while it does work on the book page/folder.

Am I missing something obvious here? 
Thanks!
Gianluca

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by dragonstyle** [comment]
The hybrid sidebar approach uses the navigation items to determine which pages show which sidebar. Since only two of the research items appear in the research sidebar, the sidebar only appears on those pages. You can explicitly show a sidebar for a page that doesn't appear on that sidebar by including the following (for example on your `research/index.qmd` page):

```yaml
sidebar: <sidebar-name>
```

more specifically:


```yaml
sidebar: research
```

**Comment by giabaio** [comment]
Ha --- perfect. Thank you -- I understand better the philosophy under the hybrid sidebar, now!
