### ISSUE TITLE
include-in-header / header-includes confusion

### ISSUE THREAD

**Issue by knuesel** [quarto-dev/quarto-cli#2547]
### Bug description

`header-includes` is not explicitely documented, although it is used on https://quarto.org/docs/reference/formats/pdf.html . It is also wrongly mentioned on https://quarto.org/docs/output-formats/pdf-basics.html (the actual code uses `include-in-header`).

Maybe `header-includes` is deprecated in favor of the `text:` subkey of `include-in-header`? Then is it possible to specifiy both include files and literal text?

My use case is that I specify a `preamble.tex` file with `include-in-header`, but I also need to add an extra header line that doesn't belong in the preamble file (the preamble is generic while the one-line fix is specific to this project). It's possible but a bit messy to make another `.tex` file just for the one-line fix, and if I already give a `preamble.tex` file to `include-in-header` then I don't think I can use the `text:` subkey.

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cderv** [comment]
> It is also wrongly mentioned on [quarto.org/docs/output-formats/pdf-basics.html](https://quarto.org/docs/output-formats/pdf-basics.html) (the actual code uses include-in-header).

Thanks for reporting this. I fixed this in the doc, it should redeploy shortly. 

> header-includes is not explicitely documented, although it is used on [quarto.org/docs/reference/formats/pdf.html](https://quarto.org/docs/reference/formats/pdf.html)

We document every Pandoc option as they are all valid, and this is one of them. For some options, we added more clever feature, and this is the case of [LaTeX includes](https://quarto.org/docs/output-formats/pdf-basics.html#latex-includes)

> It's possible but a bit messy to make another .tex file just for the one-line fix

Using everything inside files should be the recommended way IMO, as you can control the order

````yaml
format:
  pdf:
    keep-tex: true
    include-in-header: 
		- generic-preamble.tex
		- preamble-tweak.tex
````

> Then is it possible to specifiy both include files and literal text?

I don't think you can indeed do both.  You can add several files, but not mix text and files. 


This would look like this 
````yaml
format:
  pdf:
    keep-tex: true
    include-in-header: 
      file: preamble.tex
      text: |
        % I am text content
````

but does not work. (It does not pass YAML validation also). 

Trying a few things, I am seeing that this works though (because we merged the includes)

```yaml
format:
  pdf:
    keep-tex: true
    include-in-header: 
      file: preamble.tex
    header-includes: |
      % I am text content
````

Thought the order of which this is included cannot be really controlled. 

@dragonstyle @cscheid do you think we should improve this ? 

I don't know all the history behind `include-in-header` and `header-includes`, with the `text:` option addition. 

More complex includes mixing file and text, all merge by Quarto could have 

````
include-in-header: 
   - preamble1.tex
   - text: |
       % I am text preamble
   - preamble2.tex
````

FWIW in **rmarkdown** ecosystem we have `includes` argument in format for files, and pandoc `header-includes` variable for text.

**Comment by cscheid** [comment]
Yes, `include-in-header` is what we are advertising and documenting more broadly, but you'll find stray uses of the old forms in our documentation.

@cderv The issue with rmarkdown's nomenclature is that `includes` and `header-includes` are different words but whose difference has nothing to do with the difference in the semantics.

@knuesel we can't disable `header-includes` because it's ultimately a pandoc option, and we honor those by default. So although "deprecated" is too a strong a word, the sentiment is correct, we are trying to teach people about `include-in-header`, which allows us to be specific wrt to `text:` vs `file:`

**Comment by cscheid** [comment]
> With Quarto, you can't do that only using `include-in-header` it seems. Maybe that would be useful to support if not too complex.
> I don't think you can indeed do both. You can add several files, but not mix text and files.

This is a quarto bug, if that's the case. It should be possible to do it, I agree!

**Comment by cderv** [comment]
ok good. So let me add some precision to help fix this: 

First, Validation does not allow it
![image](https://user-images.githubusercontent.com/6791940/191793835-6a0831a6-cf1c-4235-9fbc-66e930e329ba.png)

````
ERROR: Validation of YAML front matter failed.
ERROR: In file test2.qmd
(line 7, columns 7--11) property name file is invalid
6:     include-in-header: 
7:       file: preamble.tex
         ~~~~
8:       text: |
i The error happened in location format:pdf:include-in-header:file.

ERROR: Render failed due to invalid YAML.
````

Then even with 
```markdown
---
title: "Test"
format:
  pdf:
    keep-tex: true
    include-in-header: 
      file: preamble.tex
      text: |
        % I am text content
validate-yaml: false
---

# test
```

Content of the file is 
````powershell
> cat .\preamble.tex
% I am the preamble
````

But in the tex file we only have the text version

````powershell
> cat .\test2.tex | grep 'preamble'
> cat .\test2.tex | grep 'text content'
% I am text content
````

So I believe this is not working and not just a validation issue.

**Comment by cscheid** [comment]
I would like our error messages to pick up on this and improve the suggestion...

**Comment by knuesel** [comment]
Thanks @cscheid and @cderv , it works indeed for my use case with something like this:

```yaml
include-in-header:
    - preamble.tex
    - text: \some_tex_command
```

Maybe adding an example along these lines in https://quarto.org/docs/output-formats/pdf-basics.html#latex-includes would be good?

And maybe also mention that `header-includes` is provided by pandoc but not recommended, since otherwise it's confusing to see documents using `header-includes` without error while the documentation only mentions `include-in-header`.

**Comment by cscheid** [comment]
We made documentation changes about `include-in-header`. We're still figuring out the best way to handle deprecation or recommendation tips in the docs, so we'll leave that for later.
