### ISSUE TITLE
Crossrefs: support uncaptioned floats

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#2551]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/2546

<div type='discussions-op-text'>

<sup>Originally posted by **werkstattcodes** September 22, 2022</sup>
I would like to number my figures without any additional caption text, just Figure 1, Figure 2...
When I use e.g.

```
#| fig-cap: ""
#| label: fig-chapter_d
```

I obtain e.g. `Figure 1: ?(caption)` as a result. I get the same result also when skipping the fig-cap row entirely from the chunk options. Is there any way to get the desired result?

Many thanks.

</div>

**Comment by cscheid** [comment]
This is looking like a 1.3 feature now that the AST rework has grown in scope. But I'm feeling good about getting a handle on this the moment we have custom nodes and can deal with figures more conveniently in our filters.

**Comment by cscheid** [comment]
This works now:

This is now possible with the following syntax:

<table>
<tr><td>

````
---
title: "missing caption causes crash"
format: html
---

```{r}
#| label: load_data
data(cars)

library(flextable)
```

Now lets try a table in our word 
document. This should be X.

```{r}
#| label: tbl-cars
#| tbl-cap: ""
cars |>
  dplyr::slice_head(n = 5) |>
  flextable() |>
  autofit()
```
````

</td><td>
<img width="788" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/ca8e6ddc-36f2-4b12-bfc7-ac06af1e8a4c">

</td></tr></table>

it's not perfect because of the required `tbl-cap: ""`, but that's going to be harder to fix on our side, because the absence of the field indicates something else for part of the code.

**Comment by cderv** [comment]
FWIW this works ok now 
````markdown
---
title: "test"
format: 
  html: default
  pdf: default
---

```{r}
#| label: fig-chapter
plot(cars)
```

See @fig-chapter

````

No error and no caption but still numbering. 

**flextable** example is quite specific because `tbl-cap` is its own specific options (no support for other table framework - at least no **knitr** native option)
