### ISSUE TITLE
can't control column width in 2-column Powerpoint slide

### ISSUE THREAD

**Issue by rgayler** [quarto-dev/quarto-cli#2635]
### Bug description

I am trying to create a Quarto PowerPoint presentation with a 2-column slide where the columns are not equal width.

I create a source document like below, but the columns are equal width in the rendered PowerPoint document.
The column width settings are respected in `revealjs` and `beamer` format documents.

```
---
title: "Untitled"
format: pptx
editor: visual
---

## Slide title

::: columns
::: {.column width="20%"}
Col 1
x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x
:::

::: {.column width="80%"}
Col 2
x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x
:::
:::
```
![Screenshot from 2022-09-28 09-53-31](https://user-images.githubusercontent.com/5409051/192657465-770a8837-f552-4bce-82d5-ab11c9054429.png)

I am using:
Quarto 1.2.160
RStudio 2022.07.2 build 576
Ubuntu 22.04.1
LibreOffice Impress 7.3.6.2 (I don't have PowerPoint on the Ubuntu PC)
PowerPoint 2007 12.0.6776.500 (issue confirmed displaying rendered PowerPoint file on a Windows PC)

**Comment by bpffjl** [comment]
I'm having a similar issue where the column width is not recognized in pptx. 

```
---
title: "Untitled"
format: pptx
editor: visual
---

## Slide title

| fruit  | price  |
|--------|--------|
| apple  | 2.05   |
| pear   | 1.37   |
| orange | 3.09   |

: Fruit prices {tbl-colwidths="[75,25]"}
```

![Screenshot 2024-03-20 144812](https://github.com/quarto-dev/quarto-cli/assets/48254282/7eee34bb-a2cc-4043-8693-9ea7f6a49b09)

**Comment by Canadauni** [comment]
I'm also seeing this issue in quarto version 1.4.553 on Windows 11 and using the Microsoft 365 Version of Powerpoint (Version 2405, Build 17628.20144).

Simple Quarto Test file is as follows:
````
---
title: "test"
format: pptx
---

:::: {.columns}

::: {.column width="70%"}
```{r}
library(ggplot2)
ggplot(mpg, aes(displ, hwy, colour = class)) +
  geom_point()
```
:::

::: {.column width="30%"}
This is some text text just to see what happens when we generate a slide.
:::

::::

````

And this outputs the following slide:
![image](https://github.com/quarto-dev/quarto-cli/assets/19292113/27246309-cc53-4168-bd63-79253c9c50e0)

Seeing as this issue has been moved to the "Future" milestone would it make sense to remove the multicolumn layout section from the powerpoint documentation? Or perhaps rejig it to remove the instructions around setting the width?

**Comment by mcanouil** [comment]
We need to look at it again, but here the syntax seems to be only Pandoc, so the issue might actually comes from it.

**Comment by cscheid** [comment]
> Seeing as this issue has been moved to the "Future" milestone

I just want to caution against overinterpreting this kind of organizational move.

**Comment by Canadauni** [comment]
> > Seeing as this issue has been moved to the "Future" milestone
> 
> I just want to caution against overinterpreting this kind of organizational move.

Fair enough, for me I was just thinking it would make sense for the documentation to match the current functionality since it didn't look like this would be in an upcoming release and this issue being open for some made me think this wasn't as much of a priority (which is totally fine btw).

When I was testing this issue out I tried to put an empty column between the two columns with content to see if that would help with proportions but the third column just got completely left out of the output file. Not sure if that would be related to the issue here but just wanted to flag that as well.

**Comment by yonisidi** [comment]
> Fair enough, for me I was just thinking it would make sense for the documentation to match the current functionality

Agree, This is confusing in current documentation

**Comment by cscheid** [comment]
I agree with the sentiments - just that the move to `Future` probably means less than what you are reading into it.

**Comment by mcanouil** [comment]
Note that the documentation "discrepancy" actually comes from Pandoc: https://pandoc.org/MANUAL.html#columns

<table>
<tr><th>Quarto document</th><th>HTML</th></tr>
<tr><td>

```sh
quarto pandoc --from markdown --to pptx -o index.pptx index.qmd
```

````qmd
---
title: "Untitled"
format: pptx
---

## Slide title

::: columns
::: {.column width="20%"}
Col 1
x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x
:::

::: {.column width="80%"}
Col 2
x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x
:::
:::

````

</td><td>

<img width="1078" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/f95e67f7-876a-4895-b994-73da725bf38a">

</td></tr>
</table>

The two columns layout is hard coded in PowerPoint template.
Since you cannot tweak any of the layout, I don't think setting width is actually supported.

**Comment by yonisidi** [comment]
from what i can see. it just uses the layout. if i change the widths in the master slides then it will conform to it.

**Comment by mcanouil** [comment]
I am re qualifying this as a documentation.
See Pandoc's discussion.

**Comment by cscheid** [comment]
Thanks, @mcanouil!!

**Comment by mcanouil** [comment]
I made a PR to add a note in the `pptx` format page.

**Comment by bennotkin** [comment]
Pardon if I'm missing it, but it looks like this note about `width` not being supported has fallen out of the documentation – and not, I believe, because pandoc now supports width for powerpoint. Neither https://quarto.org/docs/presentations/ nor https://quarto.org/docs/presentations/powerpoint.html make mention of this limitation.

**Comment by mcanouil** [comment]
@bennotkin This is a 2 years old closed issue. Please use Q&A Discussions in which you can reference this issue instead.
The documentation does not show the option at all so making this implicit.
You can see the attribute only in supported format.

FWIW: https://pandoc.org/demo/example33/10.6-columns.html
