### ISSUE TITLE
reveajs: quarto preview server does not reload automatically

### ISSUE THREAD

**Issue by JulianTao** [quarto-dev/quarto-cli#266]
The live-reloading function of the `quarto preview` command is probably affected by recent commits. 

If a source qmd file is saved with changes, the page in the browser is not reloading. The changed file is in fact re-rendered as confirmed by manually refreshing the page in the browser.  

This seems to only affect the revealjs format. I tried to render a file to html format and the preview command works as usual.

**Comment by jjallaire** [comment]
@JulianTao I am not able to reproduce this locally (although there could be OS/system differences that explain the issue). I am running Mac OS, let me know what your system is as well as if you have a MRE you can share.

One important thing to note is that if you happen to be running `quarto preview` from inside an RStudio terminal it has slightly different default behavior (it does not `--watch-inputs` by default in this case since RStudio has a **Render** button for driving updates). This might be too cute by half though as users running from the Terminal should probably get the same default behavior whether they are within RStudio or not. LMK if this might be the source of the issue you are seeing.

**Comment by jjallaire** [comment]
Wow! Fantastic sleuthing :-)  With your repro I was able to find and fix the problem: https://github.com/quarto-dev/quarto-cli/commit/7792228a199650dfdcf508b42e00f50541cd792f

**Comment by JulianTao** [comment]
I confirm that it works. Thank you as always for the fantastic work!
