### ISSUE TITLE
Asides shifts math

### ISSUE THREAD

**Issue by lcnhb** [quarto-dev/quarto-cli#2701]
It seems that any aside block will shift any math content to below it: ![image](https://user-images.githubusercontent.com/23530896/193462851-01f423ad-7964-4486-beed-cda65a50c4ca.jpeg)

This seems like some bad overlap between math ax divs and aside ones

**Comment by dragonstyle** [comment]
Can you share the portion of the `qmd` that we can use to reproduce this and confirm hat this is PDF output? TY!

**Comment by lcnhb** [comment]
It is not in the pdf it is in the HTML output!  [Here](https://github.com/lcnhb/GWAmplitudes/blob/5a2dc9c2e5a7bead08f8e41009639422a07d30ff/scattering.qmd#L243-L260) is the offending snippet in context

**Comment by dragonstyle** [comment]
Ok, I understand what is happening- the issue is basically that the aside is being placed in a grid next to it's parent element (they share a row in the grid). The size of the row is driven by whichever is larger. In your example, the aside is longer / vertically taller than the parent content, so the 'row' grows to accommodate it.

We had this issue with other margin content and resolved it, but apparently have missed asides. I will take a look soon!

**Comment by dragonstyle** [comment]
This is fixed here 7a1b9c51dd2cd2004f5087f05e872cb2e07aadfa and will be available in our next pre-release build

https://quarto.org/docs/download/prerelease.html

**Comment by lcnhb** [comment]
Wow great thanks!!
