### ISSUE TITLE
changing language of a book does work with `language` key

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#2707]
I followed instructions from documentation, but it didn't work:
```_quarto.yml
project:
  type: book

book:
  title: "My book title"
  language: "pt-BR"
  chapters:
    - index.qmd
format:
  html:
    theme: cosmo
````

_Originally posted by @fredguth in https://github.com/quarto-dev/quarto-cli/discussions/2453#discussioncomment-3779914_

**Comment by cderv** [comment]
Our documentation for language document the `lang` key for changing translation, and `language` for custom fields or custom translation files: https://quarto.org/docs/authoring/language.html

However, our reference shows in `book` that `language` can be used but it does not seem to work. See [reference for book](https://quarto.org/docs/reference/projects/books.html#meta-project-type-upper)

This is what our autocompletion suggest
![image](https://user-images.githubusercontent.com/6791940/193533770-d9f9b492-38ab-4f6f-8362-5ed1b28d2ccf.png)


Documentation issue or something else ?

**Comment by dragonstyle** [comment]
This is definitely a doc issue - the `language` attribute that is listed in book is actually from book's conformance to CSL, which allows specification of language for citation purposes (not for customizing the language of the document or project in Quarto). We should minimally clarify that this is what this would mean - I'm not sure we should go as far as connecting this to the global language since I'm not sure that the citation language should be required to match the language of the Quarto rendered output.

**Comment by fredguth** [comment]
In a latex document is very common to specify the language of the document with babel. The document class will change accordingly.  In Quarto, what is the right way of changing the language of the document (change all the assumed names like "Chapter", " Summary"  " References, etc.

**Comment by Nowosad** [comment]
@cderv, you can find a minimal example of `lang:` and `language:` keys not working as expected for quarto books at https://github.com/Nowosad/min-quarto-lang. (I just used `quarto create-project mybook --type book` to create the projects, and then added `lang` and `language` keys).

HTML output (there should be "Spis treści" instead of "Table of contents", "Autor" instead of "Author", "Rozdział" instead of "Chapter", etc.):

![2022-10-17_14-59_1](https://user-images.githubusercontent.com/3457131/196184355-d751bfa1-dd9f-410b-9854-5665c6497255.png)


PDF output (there should be "Spis treści" instead of "Table of contents"):
![2022-10-17_14-59](https://user-images.githubusercontent.com/3457131/196184209-1734ccf2-d334-4f39-a6e5-809844822d02.png)


Please let me know if this should go to a new issue. Thanks!

**Comment by dragonstyle** [comment]
I updated the docs to clarify this

**Comment by cderv** [comment]
For reference, done in https://github.com/quarto-dev/quarto-cli/commit/47d7ba29ac8e47aad3d2e618fc2813b7a594cfcf
