### ISSUE TITLE
`fig-align` and `results: asis` break tabsets

### ISSUE THREAD

**Issue by jmbarbone** [quarto-dev/quarto-cli#2784]
### Bug description

Using `fig-align` within a chunk breaks dynamically generated tabsets (`results: asis`).
I left the `knitr: opts_chunk: fig.align:center` in the example because that's what I was originally using which generated this issue.

This might be the same issue with #1456 where the `html` has the `data-layout="center"` divs, but I don't see alignment being set.

````qmd
---
format: html
# knitr:
#   opts_chunk:
#     fig.align: center
---


## tabset (ok)

::: {.panel-tabset}

### a

```{r}
plot(1:10)
```

### b

```{r}
plot(10:1)
```

:::

## tabset fig-align (ok)

::: {.panel-tabset}

### a

```{r}
#| fig-align: center
plot(1:10)
```

### b

```{r}
#| fig-align: center
plot(10:1)
```

:::


## tabset asis (ok)

::: {.panel-tabset}

```{r}
#| results: asis

writeLines("### a")
plot(1:10)
writeLines("\n")

writeLines("### b")
plot(10:1)
writeLines("\n")
```

:::

## tabset asis fig-align (not ok)

::: {.panel-tabset}

```{r}
#| results: asis
#| fig-align: center

writeLines("### a")
plot(1:10)
writeLines("\n")

writeLines("### b")
plot(10:1)
writeLines("\n")
```

:::

````

<details>
<summary>Image</summary>

![image](https://user-images.githubusercontent.com/38573843/194909701-b3cc1c20-bb18-4c8b-b103-bf9007d2f5cb.png)

</details>

<details>
<summary>Session information</summary>

``` r
quarto::quarto_version()
#> [1] '1.1.251'
devtools::session_info(info = "platform")
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.2.1 (2022-06-23 ucrt)
#>  os       Windows 10 x64 (build 19044)
#>  system   x86_64, mingw32
#>  ui       RTerm
#>  language (EN)
#>  collate  English_United States.utf8
#>  ctype    English_United States.utf8
#>  tz       America/New_York
#>  date     2022-10-10
#>  pandoc   2.19.2 @ C:/Program Files/RStudio/bin/quarto/bin/tools/ (via rmarkdown)
#> 
#> ──────────────────────────────────────────────────────────────────────────────
rstudioapi::versionInfo()
#> $citation
#> 
#> To cite RStudio in publications use:
#>   
#>   RStudio Team (2022). RStudio: Integrated Development Environment for R. RStudio, PBC, Boston, MA URL http://www.rstudio.com/.
#> 
#> A BibTeX entry for LaTeX users is
#> 
#> @Manual{,
#>   title = {RStudio: Integrated Development Environment for R},
#>   author = {{RStudio Team}},
#>   organization = {RStudio, PBC},
#>   address = {Boston, MA},
#>   year = {2022},
#>   url = {http://www.rstudio.com/},
#> }
#> 
#> 
#> $mode
#> [1] "desktop"
#> 
#> $version
#> [1] ‘2022.7.2.576’
#> 
#> $long_version
#> [1] "2022.07.2+576"
#> 
#> $release_name
#> [1] "Spotted Wakerobin"
```

</details>

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
(Apologies for the delayed response)  Unfortunately, the interaction between `results: asis` and other options puts you in deep waters. You can more or less see what's happening by inspecting the intermediate markdown with `keep-md: true`

The issue is that `results: asis` behaves differently depending on whether you add any other options to the cell. Without any other options, you get no "scaffolding at all":

````
## tabset asis (ok)

::: {.panel-tabset}



```{.r .cell-code}
writeLines("### a")
```

### a

```{.r .cell-code}
plot(1:10)
```

::: {.cell-output-display}
![](2784_files/figure-html/unnamed-chunk-5-1.png){width=672}
:::

```{.r .cell-code}
writeLines("\n")
```

```{.r .cell-code}
writeLines("### b")
```

### b

```{.r .cell-code}
plot(10:1)
```

::: {.cell-output-display}
![](2784_files/figure-html/unnamed-chunk-5-2.png){width=672}
:::

```{.r .cell-code}
writeLines("\n")
```


:::
````

This (more or less) works because the structure necessary for tabsets to be picked up correctly is that the headings should appear at the "top level" of the tab set div. But when you use `fig-align: center` _with_ `results: asis`, you get the following output:

````
## tabset asis (ok)

::: {.panel-tabset}



```{.r .cell-code}
writeLines("### a")
```

### a

```{.r .cell-code}
plot(1:10)
```

::: {.cell-output-display}
![](2784_files/figure-html/unnamed-chunk-5-1.png){width=672}
:::

```{.r .cell-code}
writeLines("\n")
```

```{.r .cell-code}
writeLines("### b")
```

### b

```{.r .cell-code}
plot(10:1)
```

::: {.cell-output-display}
![](2784_files/figure-html/unnamed-chunk-5-2.png){width=672}
:::

```{.r .cell-code}
writeLines("\n")
```


:::
````

Unfortunately, it's in general hard for us to support `results: asis` on all cases, because the markdown being emitted is (quite literally) arbitrary. So your best bet is to imitate the "good" output you're seeking. Something like this (though, do read the whole thing through, because this doesn't quite work):

````
## tabset asis fig.align workaround

::: {.panel-tabset}

```{r}
#| results: asis

writeLines("### a\n")
writeLines("::: {.cell layout-align=\"center\"}\n")
plot(1:10)
writeLines("\n")
writeLines(":::\n")

writeLines("### b")
writeLines("::: {.cell layout-align=\"center\"}\n")
plot(10:1)
writeLines("\n")
writeLines(":::\n")
```

:::
````

this generates the following MD:

````
## tabset asis fig.align workaround

::: {.panel-tabset}



```{.r .cell-code}
writeLines("### a\n")
```

### a

```{.r .cell-code}
writeLines("::: {.cell layout-align=\"center\"}\n")
```

::: {.cell layout-align="center"}

```{.r .cell-code}
plot(1:10)
```

::: {.cell-output-display}
![](2784_files/figure-html/unnamed-chunk-7-1.png){width=672}
:::

```{.r .cell-code}
writeLines("\n")
```

```{.r .cell-code}
writeLines(":::\n")
```

:::

```{.r .cell-code}
writeLines("### b")
```

### b

```{.r .cell-code}
writeLines("::: {.cell layout-align=\"center\"}\n")
```

::: {.cell layout-align="center"}

```{.r .cell-code}
plot(10:1)
```

::: {.cell-output-display}
![](2784_files/figure-html/unnamed-chunk-7-2.png){width=672}
:::

```{.r .cell-code}
writeLines("\n")
```

```{.r .cell-code}
writeLines(":::\n")
```

:::


:::
````

Notice that the issue here is that the image element (`![](...){...})`) doesn't have the required attribute `fig-align='center'` which is needed. I'm unfortunately not a knitr expert to figure out a way around this, but it would probably involve creating an object with a custom knit_print method that always emits that attribute. Notably, trying to do this with `knit_meta` won't work because that will cause the outer div to be emitted again.

Another way you could work around this is with a Lua filter that identifies the missing attributes on those image elements and adds it back.
