### ISSUE TITLE
[Question]: Does quarto support YAML params parameter? 

### ISSUE THREAD

**Issue by gjirokastrelbasanit34** [quarto-dev/quarto-cli#296]
Is there a possibility to use `params` parameter of YAML params in chunks, like in R Markdown, in Quarto? 

The naïve approach to use the `params$<param-name>` value in chunk options, e. g. like this, fails: 

```
---
title: "MWE"
author: LaTeX
date: "11.01"
fontenc: T1
mainfont: "Times New Roman"
format:
    pdf: 
        pdf-engine: lualatex
        keep-tex: true
params:
    show_code: false
---

```{python, fig.caption = "Caption", echo = params$show_code}
#| label: fig-polar
#| fig-cap: "A line plot on a polar axis"
import matplotlib.pyplot as plt

r = np.arange(0, 2, 0.01)
theta = 2 * np.pi * r
fig, ax = plt.subplots(subplot_kw={'projection': 'polar'})
ax.plot(theta, r)
ax.set_rticks([0.5, 1, 1.5, 2])
ax.grid(True)
plt.show()
```

Thanks in advance for any response.

**Comment by jjallaire** [comment]
`params` are supported, however the syntax you are using will only work for the Knitr engine (Jupyter uses a different method of parameterization, see https://quarto.org/docs/computations/parameters.html.

Since there is a single Python chunk in the source file Quarto is auto-detecting the engine as `jupyter`. If you add the `engine: knitr` option to force Quarto to use Knitr then this should work as expected.

**Comment by jjallaire** [comment]
You can also pass any metadata on the command line, so you could do this with the `jupyter` engine:

```bash
pandoc render document.qmd -M echo:false
```
