### ISSUE TITLE
Remove quarto css in minimal html option

### ISSUE THREAD

**Issue by drrajeshtalluri** [quarto-dev/quarto-cli#300]
When using `html: minimal: true` option, the following css styles are automatically included in the html output. These are not defined in the pandoc HTML template specification and cannot be controlled from the template.

```
<link href="test_template_files/libs/quarto-html/quarto-html.min.css" rel="stylesheet">
<link href="test_template_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet">
```

I wanted to have a clean slate of css for designing a custom html template. Is there a way to remove this from the output for the minimal option or is there any command-line option to remove it?

**Comment by jjallaire** [comment]
This CSS is conceptually similar to the CSS included by Pandoc (which covers CSS for features e.g .footnotes and syntax highlighting). The Quarto CSS covers features like figure layout, table caption positioning, etc. and without it those features won't work (just like footnotes won't work in Pandoc w/o the extra CSS). 

So `minimal` really means don't change the look of my document in any way, rather than "do absolutely nothing, potentially breaking features".  If you know for sure you don't need this CSS then I'd say just purge those `<link>` tags and also purge the CSS that Pandoc injects inline. 

We could redefine `minimal` to mean "do nothing" but then we really need a way opt back in to all of the features and behavior that get broken by it. This isn't a bad idea but not one we have time to work on right now.

**Comment by drrajeshtalluri** [comment]
Thank you! I understand the issues with breaking other features. I can purge the pandoc css by removing styles.html from the template.

```
  <style>
    $styles.html()$
  </style>
```

How would I go about removing quarto css from the output? I tried to remove all css files in the template but that did not work.

One possible way is to define a function that adds post processing to the render function to find and delete these two lines from the HTML.

Please let me know if you have a more efficient way.

Thanks for the help!

**Comment by jjallaire** [comment]
We are currently using `header-includes` to inject this code so If you remove these lines (https://github.com/jgm/pandoc-templates/blob/master/default.html5#L26-L28) I think that would work.

If that doesn't work then for Quarto projects you can define post-render step that does the stripping as defined here: https://quarto.org/docs/projects/quarto-projects.html#project-scripts

**Comment by jinlin82** [comment]
> We are currently using header-includes to inject this code so If you remove these lines (https://github.com/jgm/pandoc-templates/blob/master/default.html5#L26-L28) I think that would work.

can you point out where is the source line in quarto about "We are currently using header-includes to inject this code"

**Comment by jjallaire** [comment]
Header includes are used all over the place in Quarto (for both styles as well as other behaviors). So there isn't a "single" place -- its more like a service that is utilized in many places. If you want a single point of disablement then removing the lines from the template as described above it the way to go (but note some features will break, including any filters/extension that need to inject dependencies) so you should be absolutely certain you want to rip this code out before proceeding.
