### ISSUE TITLE
`ipyleaflet` not showing map on rendered quarto slides VScode + Jupyter + Python + Revealjs

### ISSUE THREAD

**Issue by rleyvasal** [quarto-dev/quarto-cli#3019]
### Bug description

Map with `ipyleaflet` shows in Jupyter notebook, but not showing on the final rendered slides.

Os: Ubuntu 22.04
VScode: 1.72.2
Quarto: 1.1.251
Quarto VScode extension: v1.51.0

[leaflet_map.zip](https://github.com/quarto-dev/quarto-cli/files/9856773/leaflet_map.zip)

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
I see this on `jupyter notebook`:

<img width="1128" alt="image" src="https://user-images.githubusercontent.com/285675/197821860-84f572df-3df7-47c9-ad11-5092b822e9f9.png">

When I run that notebook cell on `jupyter notebook` myself, I get this instead:

<img width="1103" alt="image" src="https://user-images.githubusercontent.com/285675/197822276-7bc4ba86-36ed-4c7f-9fc8-5898bb566d41.png">

That looks to be correct, but if I save the .ipynb file and then reload it _on jupyter notebook_, I get an error message as well:

<img width="1114" alt="image" src="https://user-images.githubusercontent.com/285675/197823921-c6a3689a-f0f0-44dd-9169-5166e433f208.png">

This indicates to me that there's something about ipyleaflet that makes it so that it doesn't successfully save execution state.

Like my previous suggestions, I think you need to have quarto execute the notebook, with `quarto render file.ipynb --execute`. In that case, the revealjs presentation works for me. I don't think this is a quarto bug.
