### ISSUE TITLE
Search blocked for Quarto website not on webserver

### ISSUE THREAD

**Issue by GthSd** [quarto-dev/quarto-cli#3028]
### Bug description

Opening a Quarto website (or book) from a local drive in a browser (file:///) blocks search from working due to CORS policies in modern browsers (tested on Firefox 105 & Edge 106).

Error message from Firefox:
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at file:///../search.json (Reason: CORS request not http)

Error message from Edge:
Access to fetch at 'file:///.../search.json' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, isolated-app, chrome-extension, chrome-untrusted, https, edge.

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by GthSd** [comment]
Shame it’s not considered for the future. I checked the docs, it might be good to add that search won’t work unless deployed to a webserver or in quarto preview.

**Comment by cscheid** [comment]
Thank you for the feedback.

This is unfortunately not a practical feature for us to build. To be clear: a large number of modern web features don't work on the file:/// scheme. It's not just search: it's any javascript code that makes a request outside of the current page. That means, for quarto: most jupyter html widgets; all of observableJS, any javascript that imports additional files.

It is unfortunate that quarto builds on some technologies that require a bit of knowledge about them. But we make a conscious effort not to dilute quarto documentation with general information about these technologies, since it is available elsewhere.

**Comment by GthSd** [comment]
I appreciate the effort and further explanations.
