### ISSUE TITLE
More Julia examples

### ISSUE THREAD

**Issue by gitboy16** [quarto-dev/quarto-cli#308]
Hi,
Thank you for this project.
I was wondering if there are more examples with Julia. I just started using quarto and the only example I found was the following one: https://github.com/quarto-dev/quarto-cli/issues/35
But the plot did not display.
I was windering if it would be possible to add Julia examples along yhe R and Python examples on https://quarto.org
Thank you

**Comment by jjallaire** [comment]
Yes, this is definitely on our list. There are a few subtleties of interaction w/ Jupyter that we want to iron out (see https://github.com/quarto-dev/quarto-cli/tree/main/src/resources/jupyter/lang/julia) and we'd also like to do more internal testing before we actively promote that Julia works seamlessly w/ Quarto. At that point we'll add examples, etc.

**Comment by gitboy16** [comment]
Thank you @jjallaire. By the way https://github.com/quarto-dev/quarto-cli/issues/170 would be awesome. I already use your rticles package. I love what you do.

**Comment by jjallaire** [comment]
Yes, #170 is next up on our list!

**Comment by jjallaire** [comment]
We've updated and expanded our documentation on using Julia with Quarto here: https://quarto.org/docs/computations/julia.html

**Comment by jjallaire** [comment]
Hi there @gitboy16, posting back here because I'm giving a talk on Quarto at JuliaCon next month and was hoping to find some good examples of using Julia w/ Quarto. If you are able to share any of your own (or are aware of others) please LMK over on this discussion thread: https://github.com/quarto-dev/quarto-cli/discussions/1261. Thanks!
