### ISSUE TITLE
NameError when mixing R and Python cells

### ISSUE THREAD

**Issue by katossky** [quarto-dev/quarto-cli#3083]
### Bug description

I can render the following script on its own just fine:

````
```{python}
from bokeh.io import output_notebook, show
from bokeh.layouts import gridplot
from bokeh.plotting import figure

output_notebook()

x = list(range(11))
y0 = x
y1 = [10-xx for xx in x]
y2 = [abs(xx-5) for xx in x]

# create a new plot
s1 = figure(width=250, height=250, title=None)
s1.circle(x, y0, size=10, color="navy", alpha=0.5)

# create a new plot and share both ranges
s2 = figure(width=250, height=250, x_range=s1.x_range, y_range=s1.y_range, title=None)
s2.triangle(x, y1, size=10, color="firebrick", alpha=0.5)

# create a new plot and share only one range
s3 = figure(width=250, height=250, x_range=s1.x_range, title=None)
s3.square(x, y2, size=10, color="olive", alpha=0.5)

p = gridplot([[s1, s2, s3]], toolbar_location=None)

# show the results
show(p)
```
````

However, adding an empty R cell in front rises a NameError:

````
```{r}
```
````

Gives :
```
Erreur dans py_call_impl(callable, dots$args, dots$keywords) : 
  NameError: name 'figure' is not defined
Appels : .main ... py_capture_output -> force -> <Anonymous> -> py_call_impl
```

---

RStudio 2022.07.2+576 "Spotted Wakerobin" Release (e7373ef832b49b2a9b88162cfe7eac5f22c40b34, 2022-09-06) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 12_4_0) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.10 Chrome/69.0.3497.128 Safari/537.36

---

ProductName:	macOS
ProductVersion:	12.4
BuildVersion:	21F79

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by katossky** [comment]
I forgot to mention that when running the cell independently, the first attempt fails, but the second attempt succeeds.

**Comment by katossky** [comment]
In case useful:

```
> reticulate::py_config()
python:         /opt/homebrew/bin/python3
libpython:      /opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/config-3.9-darwin/libpython3.9.dylib
pythonhome:     /opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9:/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9
version:        3.9.13 (main, May 24 2022, 21:13:51)  [Clang 13.1.6 (clang-1316.0.21.2)]
numpy:          /opt/homebrew/lib/python3.9/site-packages/numpy
numpy_version:  1.23.0
```

RStudio is set up using the same `/opt/homebrew/bin/python3` Python distribution.

**Comment by eitsupi** [comment]
Are you explicitly specifying the knitr engine?
If the first executable code block is not `{r}`, the knitr engine is not selected by default.
https://quarto.org/docs/computations/execution-options.html#engine-binding

**Comment by cscheid** [comment]
To expand on what @eitsupi said:

When a .qmd file has `r` _and_ `python` cells, the behavior is that the cells are all executed through knitr, and `python` cells are run through knitr's reticulate engine.

When a .qmd file only has `python` cells, the behavior is that cells are executed through the jupyter engine. We convert the .qmd into a .ipynb file, execute it through jupyter, then get the results back.


My first theory was that that somehow your Python settings are not the same between the jupyter and the knitr engine. Eitsupi's suggestion of explicitly setting the engine to be knitr will force the python blocks in an "all-python .qmd" to go through knitr.

However, that doesn't match the error message you're getting, which is about `reticulate` failing to find a `figure` import. That's strange, since you have a line

```python
from bokeh.plotting import figure
```

which presumably ran fine. I wonder if the lookup of `figure` is somehow different in the reticulate environment. Can you try

```python
from bokeh import plotting
...

plotting.figure # instead of "figure"
```

And see if you get better luck there?

**Comment by katossky** [comment]
> Are you explicitly specifying the knitr engine? If the first executable code block is not `{r}`, the knitr engine is not selected by default. https://quarto.org/docs/computations/execution-options.html#engine-binding

It does not work either when I force the engine to be knitr.

**Comment by katossky** [comment]
@cscheid I tried every import combination. None works.

Other weird behaviour is that :
> when running the cell independently, the first attempt fails, but the second attempt succeeds.

**Comment by cscheid** [comment]
What do you mean by "independently"? Do you mean by clicking the "Run Cell" button in RStudio?

**Comment by katossky** [comment]
Yes

**Comment by katossky** [comment]
(The environment tab only shows the objects after the imports, starting with `x`, `y0`, etc. I very briefly see a `r` object being created, which then disappears.)

**Comment by katossky** [comment]
OK the issue comes from the `output_notebook()` command.

**Comment by katossky** [comment]
(But without it, the interactive graphic is not shown.)

**Comment by cscheid** [comment]
So do I understand correctly that the issue here is running bokeh's `output_notebook()` in reticulate specifically?

**Comment by katossky** [comment]
Yes. Now it sounds reaaaaaaaally specific. 😬

**Comment by katossky** [comment]
And it is probably a joint problem of `reticulate` and `bokeh`, not yours.

**Comment by katossky** [comment]
With `output_notebook()` before the other imports, the script runs. **BUT** the graphic is not displayed.

```
from bokeh.io import output_notebook

output_notebook()

from bokeh.io import show
from bokeh.layouts import gridplot
from bokeh import plotting

x = list(range(11))
y0 = x
y1 = [10-xx for xx in x]
y2 = [abs(xx-5) for xx in x]

# create a new plot
s1 = plotting.figure(width=250, height=250, title=None)
s1.circle(x, y0, size=10, color="navy", alpha=0.5)

# create a new plot and share both ranges
s2 = plotting.figure(width=250, height=250, x_range=s1.x_range, y_range=s1.y_range, title=None)
s2.triangle(x, y1, size=10, color="firebrick", alpha=0.5)

# create a new plot and share only one range
s3 = plotting.figure(width=250, height=250, x_range=s1.x_range, title=None)
s3.square(x, y2, size=10, color="olive", alpha=0.5)

p = gridplot([[s1, s2, s3]], toolbar_location=None)

# show the results
show(p)
```

**Comment by kevinushey** [comment]
Somehow running the `output_notebook()` function through `reticulate` removes some of the existing imports?

`````
from bokeh.io import output_notebook, show
from bokeh.layouts import gridplot
from bokeh.plotting import figure
print(figure)
output_notebook()
print(figure)
`````

I see:

```
>>> print(figure)
<function figure at 0x160aeb4c0>
>>> 
>>> output_notebook()
/Users/kevin/.virtualenvs/r-reticulate/lib/python3.9/site-packages/IPython/core/interactiveshell.py:856: UserWarning: Attempting to work in a virtualenv. If you encounter problems, please install IPython inside the virtualenv.
  warn(
>>> 
>>> print(figure)
NameError: name 'figure' is not defined
```

**Comment by cscheid** [comment]
Huh, I see that in `python` too! This seems like a bokeh jupyter-only feature, then:"

```python
Python 3.10.6 (main, Aug 30 2022, 04:58:14) [Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from bokeh.io import output_notebook, show
>>> from bokeh.layouts import gridplot
>>> from bokeh.plotting import figure
>>> print(figure)
<function figure at 0x13a868280>
>>> output_notebook()
In : print(figure)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'figure' is not defined
In :
```

**Comment by cscheid** [comment]
@katossky I don't think this is a quarto _or_ reticulate bug; `output_notebook` appears to be a feature that's only supported in the jupyter engine.

**Comment by katossky** [comment]
Found a discussion at Bokeh ([link](https://discourse.bokeh.org/t/bokeh-graphics-embedded-in-quarto-files/9445/6)) that suggests that support may be quite simple but require work on Quarto's side :

> A quick look at [quarto-cli/widgets.ts at main · quarto-dev/quarto-cli · GitHub 1](https://github.com/quarto-dev/quarto-cli/blob/main/src/core/jupyter/widgets.ts) shows that, in principle, you should be able to use BokehJS with quarto. The code shows how they are requesting Plotly from deno.land and scanning the cells to see if there are any Plotly objects in the notebook for rendering. You may want to create a ticket at quarto to see if the devs can implement BokehJS rendering.
>
> Try injecting the Bokeh JavaScript in every cell that outputs a figure by adding output_notebook(hide_banner=True) before you show the figure in the notebook, to see if quarto will keep the JS around in its output. You’ll be keeping a lot of redundant code in your notebook if you have more than one figure, but it can’t hurt to try it out.

So maybe we could reopen this issue, or just create a new issue that is more of a feature request ?

**Comment by bryevdv** [comment]
The default built-in `output_notebook` hooks call Jupyter/ipython output cell publish APIs, so it is 100% that case that the default usage can only possibly function in a Jupyter/ipython environment. Anything else definitely falls under "undefined behavior" for sure. [1]

However, `output_notebook` can be configured with new/different hooks for alternative notebooks. In the past this was added so that someone could support a third-party hook for Zeppelin notebooks. So if someone was interested, they could potentially add hooks for Quarto. Or someone could just develop an entirely different `output_quarto` API  that Quarto users can use inside Quarto instead of `output_notebook`. Or Quarto could auto-magic or monkeypatch something on its end. There are several potential avenues. 

However, I have to be up-front about how likely I think anyone on the Bokeh side will take this up directly:

* no one on the core team has any experience with Quarto whatsoever
* we are all currently very over-subscribed already
* notebook integration work is generally very tedious and unpleasant  
* two people have asked about Quarto in the last ten years

So, I am happy to provide guidance, pointers to code, answer questions, etc. but realistically I think the best chance for movement would be if someone with a direct vested interest in having it work takes the lead. [2]

[1] I'd love for this to be better but Jupyter has ossified an ideological stance regarding complete front-end / back-end separation, and generally just will not let any python code know what (or even if there is) a front-end is. So here we are. 

[2] But I could also be wrong, and maybe there is someone willing and able to take an active role on this. Certainly feel free to make a GH issue on the Bokeh tracker to see if that is the case.

**Comment by katossky** [comment]
@bryevdv You say "in the last ten years" but Quarto v1 only dates back from July. Twice since then, that's not bad :)

**Comment by bryevdv** [comment]
Fair enough, I have only my on POV as a long-term maintainer to rely on.

**Comment by katossky** [comment]
Thank you for sharing ! In my view that definitely falls into the "feature request" on both sides, and we may wait for additional users to weigh in. @cscheid should I create a new issue for the request or just rename this conversation? @bryevdv, I have created a feature request on the Bokeh side: https://github.com/bokeh/bokeh/issues/12521

**Comment by katossky** [comment]
(And unfortunately I have no experience whatsoever with notebook development, I am just an end-user here. I would have loved to help at my level but you with your experience saying that "notebook integration work is generally very tedious and unpleasant" slightly frightens me, I must say.)

**Comment by cscheid** [comment]
@bryevdv Thanks for weighing in, I super appreciate your perspective. I hope I didn't sound like I expected this to be something that Bokeh developers should take on. I _certainly_ don't mean in that way (I wasn't even aware of that discourse post.). We all have our plates super full! 

Your understanding of jupyter's stance on front-end/back-end separation is very helpful, and I completely understand their position as well.

@katossky I think this work will have to be done by someone with a lot of experience in _both_ quarto and bokeh. I would love for the feature to exist on our side, but, just like Bryan, we are working on full plates.

Finally, I will note that, from my understanding, bokeh _does_ work with quarto when we render via jupyter. IIUC, where it doesn't work is through knitr/reticulate. So this work is not critically high-priority for us, since it would only be a blocker for people who need to run R, Python, _and_ bokeh in a single page.

**Comment by bryevdv** [comment]
>  I hope I didn't sound like I expected this to be something that Bokeh developers should take on.

Definitely not, I've just gotten into the habit of being as up front as possible in these kinds of discussions :) Hopefully I didn't come off too brash.

> IIUC, where it doesn't work is through knitr/reticulate. So this work is not critically high-priority for us, since it would only be a blocker for people who need to run R, Python, and bokeh in a single page.

I agree that seems like a subset of a subset of a subset of users. FWIW is there is ever anyone who would be interested in pursuing this with some funding, I am happy to help with submitting a NumFOCUS small development grant (no guarantees they would bite, of course)
