### ISSUE TITLE
TOC ignoring subsections from child document

### ISSUE THREAD

**Issue by nclJoshCowley** [quarto-dev/quarto-cli#3178]
### Bug description

**Context,** my current workflow is to have a QMD that analyses a model fit using only the fit object.
This is then pulled into a application specific report using `knitr::knit_child`.

**Issue** is that the table of contents (TOC) is missing subsections if the child report has n > 1 subsections.

See the TOC in the following reproducible example.

````
---
format: html
keep-md: true
toc: true
toc-depth: 3
number-sections: true
---

```{r setup}
#| include: false
include_child <- function(n) {
  txt <- paste(
    sprintf("### H3 (Child) - %s\nSome content\n", seq(n), seq(n)),
    collapse = "\n"
  )
    
  res <- knitr::knit_child(text = txt, quiet = TRUE)
  return(res)
}
```

## Good

Section appears in TOC.

```{r}
#| echo: false
#| results: asis
cat(include_child(n = 1))
```

## Bad

No sections appears in TOC.

```{r}
#| echo: false
#| results: asis
cat(include_child(n = 2))
```
````

I'm using Windows 10 and the following version of RStudio:
> RStudio 2022.07.2+576 "Spotted Wakerobin" Release (e7373ef832b49b2a9b88162cfe7eac5f22c40b34, 2022-09-06) for Windows
> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
(@cderv, just FYI I assigned you because you understand knit_child better than I do. We can eventually work on this together.)

**Comment by cderv** [comment]
First let just fix the R code above, and remove the second `seq(n)` unneeded because only one `%s` in sprintf. 

The .qmd will produce this intermediate .md

<details>
<summary>Details</summary>

````markdown
---
format: html
keep-md: true
toc: true
toc-depth: 3
number-sections: true
---






## Good

Section appears in TOC.




### H3 (Child) - 1
Some content



## Bad

No sections appears in TOC.




### H3 (Child) - 1
Some content

### H3 (Child) - 2
Some content

````

</details>

There are lots of spaces introduced by our intermediate processing but basically, it shows that `knit_child` works ok. 

The issue can be reproduced using this file. 
````markdown
---
format: html
keep-md: true
toc: true
toc-depth: 3
number-sections: true
---

## Good

Section appears in TOC.

### H3 (Child) - 1

Some content

## Bad

No sections appears in TOC.

### H3 (Child) - 1

Some content

### H3 (Child) - 2

Some content
````

![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/74314eec-9cce-4594-9e03-c8c832ba4328)


So nothing to do with **knitr** engine. Something is not right in our TOC processing somehow.

**Comment by cderv** [comment]
Looking in the HTML source, the headers are there  but `class = "collapse"` has been added 
````html
<li><a href="#bad" id="toc-bad" class="nav-link" data-scroll-target="#bad"><span class="header-section-number">2</span> Bad</a>
  <ul class="collapse">
  <li><a href="#h3-child---1-1" id="toc-h3-child---1-1" class="nav-link" data-scroll-target="#h3-child---1-1"><span class="header-section-number">2.1</span> H3 (Child) - 1</a></li>
  <li><a href="#h3-child---2" id="toc-h3-child---2" class="nav-link active" data-scroll-target="#h3-child---2"><span class="header-section-number">2.2</span> H3 (Child) - 2</a></li>
  </ul></li>
````

So probably a problem at 
https://github.com/quarto-dev/quarto-cli/blob/ec4a95f0787bfc0f9ce1e925930fc7b3e4d35224/src/format/html/format-html-bootstrap.ts#L396-L409

**Comment by cderv** [comment]
In fact it could be in our client processing for this feature 
https://github.com/quarto-dev/quarto-cli/blob/ec4a95f0787bfc0f9ce1e925930fc7b3e4d35224/src/resources/formats/html/quarto.js#L739-L755

**Comment by mcanouil** [comment]
Hum, what's the issue? TOC expand is set to 2 by default, so as long as you are not in the other section, you don't see the subsections which is as expected.

| Original | Simplified |
|--------|--------|
| [Cell](https://github.com/quarto-dev/quarto-cli/assets/8896044/aac3430e-4112-47b7-aeb6-1444e73e2d6e) | [Cell](https://github.com/quarto-dev/quarto-cli/assets/8896044/ed09dd86-4b0f-492e-95a2-d745572bc770) | 

The same behaviour can be observed wit the original example.

Switching from 2 to 3 via `toc-expand: 3` will display all.

<img width="1624" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/be88b5c5-21f7-4159-baa0-f3c9b48533af">


Source: https://quarto.org/docs/output-formats/html-basics.html#table-of-contents

**Comment by cderv** [comment]
> Hum, what's the issue? TOC expand is set to 2 by default, so as long as you are not in the other section, you don't see the subsections which is as expected.

Thanks for the reminder about `toc-expand`, and its default with auto-expansion behavior. From doc 
> Use the toc-expand option to specify how much of the table of contents to show initially (defaults to 1 with auto-expansion as the user scrolls). Use true to expand all or false to collapse all.

So default is 1 for first section expanded. `toc-expand: 2` would expand by default 2 sections, and `toc-expand: true` would expand all.  So a good workaround for this is to set `toc-expand: true` so that all TOC show, or another number depending on the page content. `toc-expand: 2` would work here for the specific example. 

Regarding the issue, or unfriendly behavior I would say, if there is no scrolling offered on the screen (because all content fit on page for example), then you don't get the TOC showing for the second section, and there is no way to expand it as no scrolling possible. See this 

https://github.com/quarto-dev/quarto-cli/assets/6791940/0e6be2ca-d9f8-46b1-a0bb-05220a4fd3c5

No vertical scroll back so no way to make the second section active. You are stuck with an unexpanded toc, and no auto expansion possible. 

It does not seem ideal to me, and maybe we can do something about it.

**Comment by mcanouil** [comment]
Modifying the JavaScript to force expansion when there is no vertical scrollbar on the viewport should not be hard to implement, I believe.

**Comment by cderv** [comment]
I believe it is there already. This below makes active links based 
https://github.com/quarto-dev/quarto-cli/blob/99fad064789715bf2eb11dc9ee3adc59b7c15b8f/src/resources/formats/html/quarto.js#L130-L159
and active links are supposed to be what defines the toc expansion 
https://github.com/quarto-dev/quarto-cli/blob/99fad064789715bf2eb11dc9ee3adc59b7c15b8f/src/resources/formats/html/quarto.js#L716-L764
So we call the expansion before updating active link initially, and I don't find how a new expansion is trigger. 

The current logic is not that simple and probleme is not solve this specific behavior, but be sure we don't break any others by solving this one. 

But there is definitely an issue to me as it does not seem to work as it should or we would want it to work.

**Comment by cderv** [comment]
Once initialized we only update active link on scrolling
https://github.com/quarto-dev/quarto-cli/blob/99fad064789715bf2eb11dc9ee3adc59b7c15b8f/src/resources/formats/html/quarto.js#L766-L778

which does not happen in the issue here. So that is the problem I believe
