### ISSUE TITLE
Running bash chunks using wsl

### ISSUE THREAD

**Issue by elgabbas** [quarto-dev/quarto-cli#3302]
### Bug description

Hello,

I am trying to run a bash code chunk using Quarto (`v1.2.269`).  The following works nicely
````
---
format:
  html:
    kernel: knitr
---
```{r}
```
```{bash}
echo "AA"
```
````

However, it uses the default git bash software, which does not support all bash/shell commands. I would like to use Ubuntu [Windows Subsystem for Linux (WSL)] installation instead [on windows 11 pro 22H2].

I was able to change the terminal in Rstudio [`v2022.07.2+576.`] as shown in the next screenshot. It works but only while using the terminal tab.
![image](https://user-images.githubusercontent.com/7375051/201476873-5780c2c7-78cf-4c8e-80fd-e5d85e2bddcd.png)

However, this does not apply to code chunks. I tried to change (force) Quarto to use a specific version of bash using the `engine.path` and `engine.opts` arguments without success [the same also occurred in VS code].
````
```{bash engine.path="C:/WINDOWS/system32/wsl.exe", engine.opts="-d Ubuntu-20.04"}
echo "Some text"
```
````
I receive the following error:
> running: C:/WINDOWS/system32/wsl.exe -d Ubuntu-20.04 -c "echo \"Some text\""
Quitting from lines 20-21 (211.qmd) 
>Error in engine(options) : I
> Calls: .main ... call_block -> block_exec -> in_input_dir -> in_dir -> engine
In addition: Warning message:
In system2(cmd, code, stdout = TRUE, stderr = TRUE, env = options$engine.env) :
> running command '"C:/WINDOWS/system32/wsl.exe" -d Ubuntu-20.04 -c "echo \"Some text\""' had status 65535
Execution halted

Note that running the following command in the command prompt `"C:/WINDOWS/system32/wsl.exe" -d Ubuntu-20.04 echo "Some text"` works with printing the 'some text' string. I am not an expert in this, but I think there may be a problem with additional quotations and the `-c` argument.

Could you please help me with using the wsl installation of Ubunto in Quarto?

> This may be related to this issue posted on [RStudio](https://github.com/rstudio/rstudio/issues/7493).

Thanks, Ahmed

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cderv** [comment]
@elgabbas  I believe this could be a configuration matter on your side. 

**knitr** `bash` engine will simply make R call `bash` using `system2()`. So whatever `bash` is found on PATH will be used. 
What do you get from `Sys.which("bash")` in R.  I got the WSL one on my side
````r
> Sys.which("bash")
                             bash 
"C:\\WINDOWS\\SYSTEM32\\bash.exe" 
````

And a quick tests shows that it is found correctly 
````markdown
---
title: "Test"
format: html
knitr: true
---

```{bash}
echo $WSL_DISTRO_NAME
```
````
![image](https://user-images.githubusercontent.com/6791940/201654933-efe4f89b-a7d0-4719-971b-5e98212c70a7.png)

If your Windows is configured like mine, which I believe is default, calling `bash` in Windows Terminal would run WSL. 

> However, it uses the default git bash software

In your example, what makes you think the wrong bash is used ? 

So I would check that `Sys.which("bash")` correctly returns the `bash` command for WSL. Possibly you have in your PATH the Git bash that override maybe the one from Windows WSL. 

Please do check and gave us feedback thanks ! 

> Note that running the following command in the command prompt "C:/WINDOWS/system32/wsl.exe" -d Ubuntu-20.04 echo "Some text" works with printing the 'some text' string. I am not an expert in this, but I think there may be a problem with additional quotations and the -c argument.

The `-c` is here, because `bash` takes it as argument, but here you are not passing `bash.exe` but `wsl.exe` which does not take this argument.  `bash` engine in **knitr** will path code content after `-c` as `bash` expect that. 

We don't have a `wsl` engine yet in **knitr**. `wsl.exe` seems to me as the tools to configure the Linux distribution ( you can't really pass script to it), and `bash.exe` the way to execute code. 
One could try [use new `exec` engine](https://github.com/yihui/knitr-examples/blob/master/124-exec-engine.Rmd), but it requires the command line to accept a script to run code, which `wsl.exe` does not. 

Hope it helps

**Comment by elgabbas** [comment]
Thanks Christophe @cderv,

Actually, using `Sys.which("bash")` returns **"D:\\Program Files\\rtools42\\usr\\bin\\bash.exe"**, not git bash or wsl! I was not aware of this command, thanks. I checked the `$PATH` in the terminal and in environmental variables under windows settings and did not find any link to the **rtools** subfolder. Further, I can not find the **"C:\\WINDOWS\\SYSTEM32\\bash.exe"** file on my machine.

I think I was able to find a solution by linking to the correct ubuntu installation. I used this bash command `where ubuntu2004.exe` to locate the location of the wsl ubuntu installation. The command returns **"C:\Users\Ahmed\AppData\Local\Microsoft\WindowsApps\ubuntu2004.exe"** not **"C:/WINDOWS/system32/wsl.exe"**!

I used the correct path as the `engine.path` argument of shell chunks or to global knitr options and it seems to work now! I may need still to make some tests on that!

Thanks. Ahmed.

**Comment by cderv** [comment]
Oh yes Rtools has a bash emulation like Git Bash. Forgot that. 

I don't have RTools in PATH myself though it seems, I set it up following default installer in https://cran.r-project.org/bin/windows/Rtools/rtools42/rtools.html and it is in c://rtools42

> I checked the $PATH in the terminal and in environmental variables under windows settings and did not find any link to the rtools subfolder

Check PATH in R: `Sys.getenv("PATH")`, you'll probably have it there - maybe set in you `.Renviron` somehow ? 

> Further, I can not find the "C:\WINDOWS\SYSTEM32\bash.exe" file on my machine

I use WSL since a long time, and maybe it was something install in earlier version and no more available. (guessing from https://github.com/MicrosoftDocs/WSL/issues/1242) . `wsl.exe` should be fine, but it does not take the `-c` argument, which makes it uncompatible with **knitr** `bash` chunk.  Argument is `--` it seems. Too bad it does not take a file as argument to use the new exec engine. We would need a specific new chunk engine (you can open a FR in **knitr** and I'll take a look at it) 

> I used the correct path as the engine.path argument of shell chunks or to global knitr options and it seems to work now! I may need still to make some tests on that!

I am not sure this will work considering the other `exe` does not behave like `bash.exe` but please do share feedback. 

I'll close here as this is not related to Quarto. Please open again in **knitr** if you want to share improvement ideas for that. 

Thank you
