### ISSUE TITLE
Tiny font for side-by-side plot

### ISSUE THREAD

**Issue by plessl** [quarto-dev/quarto-cli#3361]
### Bug description

When rendering two figures created with Julia Plots (GR backend) side-by-side, the font of the plots is tiny. Is there a way to adjust this or is this a bug?

MWE Quarto document is shown below and screenshot demonstrating the problem is attached.

Versions:
Quarto:  1.2.269
OS: macOS 13.0.1
Julia: 1.8.2

Any help is greatly appreciated.

````
---
format:
  html:
    code-fold: true
    output: false
    theme: cosmo
jupyter: julia-1.8
---

# Test to demonstrate tiny font for side by side plots

```{julia}
#| output: true
#| fig-cap: Caption
#| fig-subcap:
#|   - "Subcaption 1"
#|   - "Subcaption 2"
#| layout-ncol: 2

using Plots

p1 = plot(rand(4,2))
p2 = plot(rand(6,2))
display(p1)
display(p2)
```
````

![Screenshot](https://user-images.githubusercontent.com/25529/202357138-d2b6f566-f6b2-4966-adee-eb90e4b9c939.png)

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by dragonstyle** [comment]
I'm not that familiar with Julia, but typically if you control the size of the generated plot with the code itself (e.g. there is likely a `size()` function for plots which will actually emit the plot at a target size), you get much better results since the plot generation can maintain a reasonable font size while producing the plot. If you don't specify a size and allow the browser the scale the plot, the entire image is scaled (including text).
