### ISSUE TITLE
Website hybrid nav - pages referenced by a sidebar will have that sidebar applied to it.

### ISSUE THREAD

**Issue by kmasiello** [quarto-dev/quarto-cli#3389]
### Bug description

Issue: Any page that is referenced by a sidebar will have that sidebar applied to it, even if a separate definition for that page's sidebar exists in _quarto.yml

Related to https://github.com/quarto-dev/quarto-cli/issues/1853

Observed Behavior: In this repo, observe that the "Get Started" page has a sidebar defined in _quarto.yml and that the "Other" page has zero definition for a sidebar. However, because both are referenced in the sidebar: id: gallery, both of these pages have the sidebar for the Gallery applied.

Expected Behavior: A page will only have the sidebar defined by its sidebar: id.

In this example, I would expect that "Get Started" and "Gallery" would have the sidebars defined by their respective ids and called out by the _metadata.yml file in their directories. I also would expect that "Other" would not have a sidebar.

### Reprex
https://github.com/kmasiello/sidebar-reprex

**Comment by dragonstyle** [comment]
I think this is by design - pages generally will display sidebars that they appear within (which prevents users from having explicitly decorate pages or folders with sidebar parents - the definition in `_quarto.yml` is enough for simple cases). For cases where the sidebar is ambiguous or you'd like the sidebar to not appear, you can use `sidebar` in the document or folder metadata to control the sidebar. In the case of the `other.qmd` file, you should place `sidebar: false` in the document or folder metadata to prevent the sidebar from being shown, even though this document appears in a sidebar.

Let me know if I'm misunderstanding and I'll take a another look!

**Comment by kmasiello** [comment]
Thanks @dragonstyle. `sidebar: false` solves one of my issues. I wasn't aware of that one - perfect!  

I'm still confused by this case though - I defined a sidebar in `_quarto.yml` as `id: get-started` and then apply that sidebar in `get-started/_metadata.yml` using `sidebar: get-started`. However, on the Get Started index page, the gallery sidebar is still being applied.  There happens to be a subfolder titled `get-started/untitled` and when I pull that page up, it DOES have the `get-started` sidebar applied.  So the discontinuity is why the index page for Get Started, where the `_metadata.yml` file lives, does not correctly apply the sidebar I want.

**Comment by dragonstyle** [comment]
Great news - I can definitely reproduce just what you're seeing and that is definitely confusing. When I move the `sidebar: get-started` into the getting started `index.qmd` itself, everything works as expected, so I'm thinking it is related to the use of `_metadata.yml` file. But in any event this seems like a legit bug that I will take a look at!
