### ISSUE TITLE
embed-resources returns a libs folder

### ISSUE THREAD

**Issue by cscheid** [quarto-dev/quarto-cli#3445]
I think we're forwarding self-contained: true to pandoc's embed-resources: true but we're not passing embed-resources directly. This is a bug, right?

### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/3436

<div type='discussions-op-text'>

<sup>Originally posted by **dmacoritto** November 23, 2022</sup>
Hello everyone,

I am trying to switch from RMarkdown to Quarto and I have run into a challenge with the embed-resources YAML option. I would like to output an HTML document which is a standalone document with no dependencies.

Below is a screenshot of the YAML options for my document.

![image](https://user-images.githubusercontent.com/64702803/203508396-69b6caad-5c76-4fcc-be75-35f636169b31.png)

My issue is that, despite having included the "embed-resources: true" in the YAML, I get an external *_files folder that includes the required libraries to run the document (see below).  My charts are indeed embedded in my HTML document but not my libraries. Is there a way to get a complete self-contained document with no dependencies to a *_files folder ?

![image](https://user-images.githubusercontent.com/64702803/203509169-6714d2a8-77aa-420f-93bc-7936b9df5bcd.png)

Thank you very much for your help.

Darko</div>

**Comment by cscheid** [comment]
> I think we're forwarding self-contained: true to pandoc's embed-resources: true but we're not passing embed-resources directly. This is a bug, right?

This is incorrect. That MWE shows a `_files` folder with either option set. So it's something else going on.

**Comment by cscheid** [comment]
Oh, that makes sense. _Should_ be cleaned when `embed-resources: true`? It's not referred to anywhere in the .html file...

**Comment by cderv** [comment]
My understanding is that we clean always when `embed-resources: true` unless `keep-md: true` is asked. 
https://github.com/quarto-dev/quarto-cli/blob/6917a2d09036a3ece33f261c349d26fffc7841a0/src/command/render/cleanup.ts#L48-L55

When `embed-resources: false` we never clean. 

If we do clean always when `embed-resources: true`, then I don't think there is a case where `keep-md` matters. 

I believe this is important with plots rather than libs, because HTML dependencies don't end up in the markdown file. But if you do 


````markdown
---
title: "Test"
format:
  html:
    keep-md: true
    embed-resources: true
---

```{r}
plot(cars)
```

````

no sign of `*_files` in the HTML file because it is embeded, however, in the md you get 
````
::: {.cell-output-display}
![](index_files/figure-html/unnamed-chunk-1-1.png){width=672}
:::
````

And so you may not want the `*_files` folder with the plot being deleted when `keep-md: true` is set, because the file will be missing. 

I believe this is why it makes sense to have the cleaning depends on `keep-md`  and not just `embed-resources`

**Comment by cscheid** [comment]
Ah yes, the intermediate files make total sense, of course. Closing this one as notabug!
