### ISSUE TITLE
Is there a build script for pre-existing Deno installation?

### ISSUE THREAD

**Issue by yurivict** [quarto-dev/quarto-cli#353]
```configure-linux.sh``` downloads deno. Is there a way to use pre-installed deno?

For packaging it is preferable to use pre-installed dependencies.

**Comment by jjallaire** [comment]
One problem is that since Deno is a very fast-moving project Quarto often requires a very specific version of Deno. There have been times where we've been stuck on a several months old version and times where we need a recent unreleased commit. i.e. Deno isn't really a stable dependency that we need any old version of, we often need specifically the version listed in our configuration (or things won't compile or run correctly). 

If you need Quarto to run with an external Deno you can certainly make a small patch to configure-linux.sh and package/scripts/common/quarto to make this happen. I would just say that if its not the version in our current configuration there is some chance that things won't work.
