### ISSUE TITLE
Is there an install script?

### ISSUE THREAD

**Issue by yurivict** [quarto-dev/quarto-cli#354]
The README says "To install the development version of the Quarto CLI" ... run configure-linux.sh

But is there an install script? It should copy files into ```$DESTDIR$PREFIX```.

**Comment by dragonstyle** [comment]
Configuring will just build build the files into `<repo>/dist/bin` and attempt to configure a symlink to `quarto` in that directory (we try to create the symlink at either `/usr/local/bin/quarto` or `~/bin/quarto` (expanded)). We don't currently have a script that will install it to another directory other than the packaged installers under releases. (For a developer installation we currently rely upon the binary path being relative to the source directory in order to detect that it is not a packaged installation / to discover other resources that we need.)

If you'd like to run locally using a developer configuration, I'd recommend that you run configure and setup a symlink to provide the behavior you're looking for, it possible.

**Comment by yurivict** [comment]
For packaging it's better to install files into standard locations, otherwise nobody would know how to do this.

It should copy the tree into ```$DISTDIR$PREFIX/share/quarto``` and create a symlink ```$DISTDIR$PREFIX/bin/quarto```.

**Comment by dragonstyle** [comment]
Perhaps we should correct the README language to be more clear (if I'm understanding you correctly). The `configure-` scripts are intended to configure the user's local machine for usage of the development version, which isn't packaged and will run using any source code live from the source directory. It is not intended as packaging or installation of the development version.

We produce releases frequently which should have the desired behavior (installation of the packaged version to `share`/`bin`).

**Comment by yurivict** [comment]
Releases don't work for packaging because they bundle all dependencies: https://github.com/quarto-dev/quarto-cli/issues/357
