### ISSUE TITLE
Help R code discover Pandoc

### ISSUE THREAD

**Issue by aronatkins** [quarto-dev/quarto-cli#3688]
### Bug description

Given the following Quarto document:

````markdown
---
title: "test"
---

```{r}
w <- reactable::reactable(iris)

htmlwidgets::saveWidget(
  widget = w, 
  file = "test.html",
  selfcontained = TRUE
)

htmltools::includeHTML("test.html")
```
````

When this document is rendered from a terminal (outside RStudio), the R code fails to find Pandoc, producing the error:

```
Quitting from lines 8-18 (index.qmd)
Error in htmlwidgets::saveWidget(widget = w, file = "test.html", selfcontained = TRUE) :
  Saving a widget with selfcontained = TRUE requires pandoc. For details see:
https://github.com/rstudio/rmarkdown/blob/master/PANDOC.md
Calls: .main ... eval_with_user_handlers -> eval -> eval -> <Anonymous>

Execution halted
```

This problem can be avoided by setting `RSTUDIO_PANDOC` to the path to the Pandoc executable included with Quarto:

```bash
RSTUDIO_PANDOC=$QUARTO_ROOT/bin/tools quarto render index.qmd
```

Quarto should set `RSTUDIO_PANDOC` and possibly add its managed Quarto to the PATH.

Using Quarto 1.2.269 on macOS Monterey (12.6.1) and Linux (various versions).

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [x] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cderv** [comment]
Quarto should indeed configure behavior so that all tools relying on `rmarkdown::find_pandoc()` should use its bundled Pandoc 
 
 Some context information about how **rmarkdown** finds which Pandoc to use 

Currently **rmarkdown** do the following: 
* Use explicitly specified version if any set with `rmarkdown::find_pandoc(dir=)` in the current R session
* Look in `RSTUDIO_PANDOC` value, in `PATH` and in `~/opt/pandoc` and use the pandoc with the highest version

So for Quarto, I see two options : 
* Overriding `RSTUDIO_PANDOC` so that `rmarkdown::find_pandoc()` searches in Quarto folder location. One limit: If a newer Pandoc is available in PATH, it will be used though, and not the one from Quarto. 
* Calling `rmarkdown::find_pandoc(dir = <quarto pandoc folder>)` so that we force rmarkdown to use this one and not search only.  (or introduce a new env var for that in **rmarkdown**)

This will apply to R only though. I don't know if Python also have tools that are supposed to use Pandoc or not. If so, maybe a third option is to add Quarto pandoc to PATH. Contract regarding Quarto and other tool would be: When using Quarto, the bundled `pandoc` is set in PATH so that same pandoc version is used by Quarto itself and any other tools (R, Python, ...) using `pandoc`.

**Comment by cscheid** [comment]
> If so, maybe a third option is to add Quarto pandoc to PATH.

This might confuse users who would prefer to use a custom version of pandoc, so if we do it, we should respect `QUARTO_PANDOC` in case that exists. (for example, this issue recently came up on a linux arm64 build)

I think that setting `RSTUDIO_PANDOC` is cleaner and safer.

**Comment by cderv** [comment]
> This might confuse users who would prefer to use a custom version of pandoc

Yes I agree - Let's go with a R only solution as this is the issue here. 

> we should respect QUARTO_PANDOC in case that exists

Is this an existing variable we should use in **rmarkdown** ? 

> I think that setting RSTUDIO_PANDOC is cleaner and safer.

I agree this is simpler, if we accept the edge case I shared. 

On side notes, we are more and more using this variable for other purpose than its name really. It feels always a bit wrong to me to keep using something not correctly name. I feel we should have a `RMARKDOWN_PANDOC` variable for this kind of usage in the **rmarkdown** package, instead of using `RSTUDIO_PANDOC` initially used by the IDE. 

Anyway, I think we agree on the solution. I'll submit a PR.

**Comment by cscheid** [comment]
> > we should respect QUARTO_PANDOC in case that exists

> Is this an existing variable we should use in rmarkdown ?

`QUARTO_PANDOC` is used as an env var to override the `pandoc` version used by quarto, ultimately through `toolsPath` in `src/core/resources.ts`. I don't think it's necessary for `rmarkdown` to reflect that behavior, but I don't know enough about rmarkdown to judge :)
