### ISSUE TITLE
Chapter numbers are not assigned correctly to files in subdirectories on windows (HTML book)

### ISSUE THREAD

**Issue by eitsupi** [quarto-dev/quarto-cli#372]
When I rendered a quarto book (html) on Windows (quarto cli v0.9.51), I noticed some differences in the files generated compared to rendering on Linux.

1. ~~`number-sections: true` is set, but no number are assigned to the headers.~~ No numbers are assigned to headers for files in sub directories.
2. `search.json`'s path separator is a backslash `\\`.
3. The newline code of the files in `site_libs` dir is CRLF.

Sorry if I missed any options, but it would be great if it could output the exact same file as when run under Linux.

**Comment by jjallaire** [comment]
Thanks for reporting all of these, definitely not the intended behavior!

The search.json issue is fixed here: https://github.com/quarto-dev/quarto-cli/commit/4a83cb1185dab63c9da0811fcb371a6f3d348cd4

For newlines, I just made a change to the repo to ensure that all files in the `src/resources` dir use `lf`: https://github.com/quarto-dev/quarto-cli/commit/37aa2f529d782f861ffb34ff22b9c37ea7ff8658. @dragonstyle These were all crlf on checkout due to default git settings. 

Unfortunately even after this change I am still seeing the CRLF -- perhaps something about the way we are copying the file(s)? @dragonstyle Let's investigate later this AM.

For `number-sections`, I am seeing section numbers correctly included. Could you send an MRE of a repo where you are seeing them not included?

**Comment by jjallaire** [comment]
Upon further testing it looks like my change to treatment of files in `src/resources` did indeed fix the CRLF issue. @eitsupi If you see CRLF after updating to v0.9.53 (https://github.com/quarto-dev/quarto-cli/releases/tag/v0.9.53) let us know.

**Comment by eitsupi** [comment]
It turns out that it is when the file is contained in a subdirectory that it is not rendered correctly.
You can reproduce this with the following example. (I just moved one of the qmd files included in the sample project to a subdirectory)

```powershell
quarto create-project mybook --type book
cd mybook
mkdir test
mv summary.qmd test
$txt = $(Get-Content _quarto.yml) -replace "summary.qmd", "test/summary.qmd"
$txt > _quarto.yml
quarto render
```

**Comment by jjallaire** [comment]
Thanks for the repro! It was a windows backslash/forwardslash issue. Fixed here: https://github.com/quarto-dev/quarto-cli/commit/1098ea0bff16c5c97e7d1714244d9b82f154bf7b

**Comment by eitsupi** [comment]
With the latest release (quarto cli v0.9.58), I have confirmed that Windows and Linux generate exactly the same HTML Book.
This is really great. Thank you very much.
