### ISSUE TITLE
multiple pdf targets clean up wrongly

### ISSUE THREAD

**Issue by cscheid** [quarto-dev/quarto-cli#3762]
repro:

```
# format-variants.qmd
---
format:
  pdf+simple:
    output-file: simple.pdf
  pdf+fancy:
    output-file: fancy.pdf
    pdf-engine: lualatex
---

This is a test.
```

This will fail with:

```
ERROR: NotFound: No such file or directory (os error 2), open 'format-variants.tex'

NotFound: No such file or directory (os error 2), open 'format-variants.tex'
    at async Object.open (deno:runtime/js/40_files.js:55:17)
    at async processLines (file:///Users/cscheid/repos/github/quarto-dev/quarto-cli/src/format/pdf/format-pdf.ts:366:16)
    at async file:///Users/cscheid/repos/github/quarto-dev/quarto-cli/src/format/pdf/format-pdf.ts:335:5
    at async Object.complete (file:///Users/cscheid/repos/github/quarto-dev/quarto-cli/src/command/render/render.ts:222:11)
```

**Comment by darthlite** [comment]
I found this issue while searching for a similar error. In my case, I have `beamer` and `pdf` instead of two pdfs under `format`. I get the same sort of error on quarto 1.3.427:
`ERROR: NotFound: No such file or directory (os error 2), open /path/to/file/filename.tex`.

Seems like some sort of .tex file is missing or gets erased too quickly? Not sure.

And I only get this when running `quarto render --to pdf,beamer` or `quarto render --to all`. If I run `quarto render --to pdf` or `quarto render --to beamer` separately, all works fine.

In which version was this fix introduced? And should it handle this case as well? Or maybe this is a different issue altogether?

**Comment by cscheid** [comment]
You're experiencing a related, but different problem. We are aware of it, and I believe we have an open issue somewhere in the repo. This is unfortunately not an easy fix. We know what to do, but we only plan to start work on in when we start 1.5, which is at least 3 months away.

**Comment by darthlite** [comment]
Thanks for the info! Also, good to know it's a known issue. I could not find the same exact error when searching, but it may be related to another issue.

 I'll just keep on doing `quarto render --to pdf && quarto render --to beamer` for now.

**Comment by cderv** [comment]
> but it may be related to another issue.

I believe this is related to this one, even if it is for HTML in the description
* https://github.com/quarto-dev/quarto-cli/issues/4583
