### ISSUE TITLE
[featrue request] Clickable listing category labels

### ISSUE THREAD

**Issue by juliantao** [quarto-dev/quarto-cli#398]
The labels for the categories look like buttons and I cannot help but want to click them 😀 

For a good reason: won't it be nice to make them clickable and link them to the list of documents with the same category?

**Comment by jjallaire** [comment]
Yes, in fact in Distill (after which much of this is modeled) they are indeed clickable links. @dragonstyle what do you think?

**Comment by dragonstyle** [comment]
They should already be clickable on the listing page itself in the grid and default views. If you aren't seeing this, let me know so I can investigate...

In the case of the article/page itself (after the user has clicked an article / document in a listing), I want to make them clickable, but since individual pages could appear in different listings, I need to find the right general solution (to be sure they should the correct listing & categories). Let me give that some thought- I have a couple ideas...

**Comment by juliantao** [comment]
Yes, I was referring to the second case, on the article/page itself. 

Thanks for considering this!

**Comment by dragonstyle** [comment]
Ok good news - will definitely see what I can get going!

**Comment by dragonstyle** [comment]
Ok, the latest release should support this - give it a try and let me know how things work for you. Great catch, thank you!

https://github.com/quarto-dev/quarto-cli/releases/tag/v0.9.82

**Comment by juliantao** [comment]
I just had a quick check. I got a warning when I click a page:
```markdown
❯ quarto preview diary/2022-03-09.qmd
[1/2] diary/2022-03-09.qmd
[2/2] index.qmd

Output created: ../docs/diary/2022-03-09.html

Watching files for changes
Browse at http://localhost:7322/diary/2022-03-09.html
Opening in existing browser session.
  /listings.json (404: Not Found)
```
So maybe it is not copied into the output directory?

**Comment by dragonstyle** [comment]
I am able to reproduce this, but there is something a bit more mysterious going on. I will update here when I have diagnosed!

**Comment by dragonstyle** [comment]
Quarto requires that listing pages be rendered at least one time in order for things like this category behavior to work properly (basically, Quarto has to know about the listings page's existence so it can use that knowledge to properly enable this type of behavior on the pages that appear in the listing). I'm guessing that perhaps no listing page has been rendered yet in your case? (At least that was how I was able to reproduce the issue).

This results in the 404 under the hood and the categories silently not being links:
```bash
> quarto create-project myblog --type website --template blog  
> cd myblog/posts/post-with-code/
> quarto preview index.qmd
```

This, however, will be fine:
```bash
> quarto create-project myblog --type website --template blog  
> cd myblog
> quarto preview 
```

as will
```bash
> quarto create-project myblog --type website --template blog  
> cd myblog
> quarto render index.qmd
> cd posts/post-with-code/
> quarto preview index.qmd 
```

Since in both cases the listing page has been rendered prior to rendering the 'leaf' pages.

Once Quarto becomes aware of a listing page, we will automatically inject it into the render list when leaf pages are rendered, so we really only need to come to know about it once and everything should be pretty automatic from that point forward.

Does this align with what you're seeing or is there another issue that I'm not yet seeing?

**Comment by dragonstyle** [comment]
Doh! I hadn't pushed the changes (there was an issue where we wouldn't generate the listings.json file when you don't have a feed configured). I did just push the changes and would appreciate you giving it another try if possible...

**Comment by juliantao** [comment]
Just tried it out, it works! Thank you~~
