### ISSUE TITLE
Side-by-side plots with fig-show: hold not working in Quarto

### ISSUE THREAD

**Issue by jtr13** [quarto-dev/quarto-cli#4007]
The following code works in Rmarkdown but not in Quarto to produce side-by-side plots:

`.Rmd` file:

````
---
title: "Side-by-side plot test"
output: html_document
---

```{r, fig.show='hold', out.width='50%'}
plot(1, 2)
plot(3, 4)
```
````

Correct output: plots appear in one *row* in `.html` output file.

`.qmd` file

````
---
title: "Side-by-side plot test"
format: html
---

```{r}
#| fig-show: hold
#| out-width: 50%
plot(1, 2)
plot(3, 4)
```
````

Incorrect output: plots appear in one *column* in `.html` output file.

I tested on the latest nightly release: 1.3.115
RStudio version: 2022.07.2 
OS: macOS Monterey 12.5.1

_No response_

### Checklist

- [x] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [x] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [x] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [x] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
Quarto uses a different syntax than RMarkdown for side-by-side figures, as described in our [figures](https://quarto.org/docs/authoring/figures.html#computations) section.

````
---
title: "Side-by-side plot test"
format: html
---

```{r}
#| layout-ncol: 2
plot(1, 2)
plot(3, 4)
```
````

That generates this output:

<img width="832" alt="image" src="https://user-images.githubusercontent.com/285675/213233437-ed3f22dd-f0e6-4ee3-ac06-d1717c49d9b7.png">

Note that if your window is not wide enough, quarto will responsively reflow the columns.

**Comment by jtr13** [comment]
Sorry I missed that and thanks so much for the explanation.

**Comment by cscheid** [comment]
No worries! It's a big program and often we do miss things in the docs or in the feature set itself. We're happy to take all incoming issues.

**Comment by jtr13** [comment]
Thanks, good to know! It might be helpful to flag items such as this in the docs, i.e. .Rmd users: this replaces `fig.show="hold"`. All of the knitr options pop up in auto-complete in the Quarto syntax so that adds a bit to the confusion.
<img width="305" alt="image" src="https://user-images.githubusercontent.com/14161912/213288700-d13ac596-e8ed-4532-ba70-6d9f748cf34a.png">

**Comment by cderv** [comment]
@jtr13 it is not exactly replacing `fig.show: hold`. This option only controls if code chunk should be before all figure or each figure (the default) 

<details>
<summary>See example </summary>

````markdown
---
title: "Side-by-side plot test"
format: html
---

# Code chunk between each plot

```{r}
plot(1, 2)
plot(3, 4)
```

# Code chunk before both plots

```{r}
#| fig-show: hold
plot(1, 2)
plot(3, 4)
```
````

![image](https://user-images.githubusercontent.com/6791940/213429527-be3e75ac-95d1-4331-8fd1-d0cb3a1b949e.png)


</details>

What Quarto is bringing is a `layout-ncol` options that is more advanced and working for all computation, which is replacing some **knitr** specific combination of `out-width: 50%` with `fig-show: hold` to achieve the same. 

FWIW the **knitr** tricks is not working because Quarto output HTML structure different than R Markdown, and applying `out.with` on image does not have effect (because of some more div around figures). 

Anyway, all knitr options pops up because they can be useful at some point. I believe it is just some **knitr** tricks that are not working anymore, and usually have an equivalent in Quarto not just for knitr

**Comment by jtr13** [comment]
This is so incredibly helpful... thanks so much!
