### ISSUE TITLE
Outdated L3 programming layer for expl3.sty because of --update-path option?

### ISSUE THREAD

**Issue by rddaz2013** [quarto-dev/quarto-cli#4043]
### Bug description

First of all, congratulations on the wonderful work you have done at Quarto. I use Quarto with tinytex under WIN11 and Linux under Docker/WSL. 

In a new Dockerfile, I tried the following:

- use of "quarto install tinytex" works fine (as user install)
- use of "quarto install tinytex --update-path " brings an error. (as root or user)

**Error -> "Outdated L3 programming layer for expl3.sty" if i try to make a pdf.**

_Source - https://github.com/rddaz2013/vscode-python_

### Checklist

- [x] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [x] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by dragonstyle** [comment]
I'm not sure why this issue is caused by the `--update-path` flag, but it does seem like it is somehow caused by an invalid state in the texlive installation. Perhaps somehow our updating of paths is pointing us at an unexpected installation of tex?

You could try `which tlmgr` after installation and that might provide a clue, especially if it points to different installations in the two install scenarios.

You could also try running the following after installing with the update-path option:

`sudo fmtutil-sys --all` (credit https://tex.stackexchange.com/questions/586467/outdated-l3-programming-layer-for-expl3-sty)

Sorry you've run into this!
