### ISSUE TITLE
display of qmd file on GitHub

### ISSUE THREAD

**Issue by jmbuhr** [quarto-dev/quarto-cli#406]
I have the weird problem where GitHub seems to think that everything in my quarto document is actually front matter, so it it displays it in a table and the content as one line. Does anyone have an idea why this would happen?

This is what it looks like: https://github.com/hits-mbm-dev/paper-talin-loop/blob/main/index.qmd
This is the raw file: https://raw.githubusercontent.com/hits-mbm-dev/paper-talin-loop/main/index.qmd
It renders just fine with quarto: https://hits-mbm-dev.github.io/paper-talin-loop/
This is how other quarto files e.g. of the quarto website are displayed: https://github.com/quarto-dev/quarto-web/blob/main/index.qmd

**Comment by dragonstyle** [comment]
I think you can add this to your `.gitattributes` file (in the root of your repo).

```
*.qmd linguist-language=markdown
```

which will let GH know to render `cmd` files as markdown rather than whatever it is they are doing. 

I believe we have a PR open to add this to GH more generally, but need to show sufficiently common use in order to get the PR merged, so we're waiting a bit to gain more usage...

**Comment by jmbuhr** [comment]
hm, it looks like I already had this (https://github.com/hits-mbm-dev/paper-talin-loop/blob/main/.gitattributes)

**Comment by dragonstyle** [comment]
I think perhaps this: 

`*.qmd linguist-language=RMarkdown`

**Comment by jmbuhr** [comment]
That did the trick, thank you! :)
