### ISSUE TITLE
HTML preview of `output: gfm` documents

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [quarto-dev/quarto-cli#4066]
In RStudio, when a Quarto document with `output: gfm` is rendered, it shows the raw markdown in the Viewer. I think it would be more useful to see the HTML preview, to match what it will look like on GitHub.

**Comment by cscheid** [comment]
I think @jjallaire did this on purpose, so we could see the output that will be in the repo.

I also don't know how useful the HTML preview would be, because we don't really try to match GitHub's CSS. But maybe _that_ is something we could do...

**Comment by mine-cetinkaya-rundel** [comment]
Even with different CSS, I think this would be helpful. The biggest reason why I would like this is that I have students write up their work in Quarto and push it to GitHub. If they render to HTML they can view locally but can't on GitHub as we don't want to turn on GitHub pages for these repos since we want the work to be private (it's graded coursework). If they render to PDF that comes with its own issues of learning about page breaks, figure positioning, etc. GitHub Markdown was the happy medium in between even with the different CSS between RStudio and GitHub.

@jennybc had also inquired about this for the use case of `README.qmd` -> `README.md` for package documentation. She might have more to add.

**Comment by cderv** [comment]
We also do that by default in `rmarkdown::github_document()` and it is really useful to see the HTML preview. 
In R Markdown, this is done by a special rendering with Pandoc using special template, and some custom CSS to try match Github preview. 

We probably could do the same with Quarto.

**Comment by eitsupi** [comment]
FYI, for VS Code, use the following extension(s) to change the Markdown preview to GitHub style.
https://github.com/mjbvz/vscode-github-markdown-preview

**Comment by jjallaire** [comment]
Yeah, we will do this for v1.3. We'll need an option to enable/disable the HTML preview)

**Comment by eitsupi** [comment]
If possible, I hope that HTML generation can be configured (opt-in) in a separate location from the YAML front matter of the document.......
In collaborative editing, one person may prefer that HTML be generated, while others may not want it to be generated, I think.

**Comment by dragonstyle** [comment]
This will be fixed in the next release (should be available shortly once the Apple notary service stabilizes). We ended up with a metadata setting `preview-mode: raw` as an option to disable the HTML preview for those who would prefer markdown. 

We don't create HTML artifacts as a result of this change, just provide an HTML based preview.

**Comment by dragonstyle** [comment]
This will be fixed in the next release (should be available shortly once the Apple notary service stabilizes). We ended up with a metadata setting `preview-mode: raw` as an option to disable the HTML preview for those who would prefer markdown. 

We don't create HTML artifacts as a result of this change, just provide an HTML based preview.
