### ISSUE TITLE
Strict YAML validation collides with existing lua filters for Pandoc

### ISSUE THREAD

**Issue by bcdavasconcelos** [quarto-dev/quarto-cli#4139]
### Bug description

The field bibliography now must be validated as a string, but existing filters for Pandoc sometimes use other types. Example:

```
bibliography:
  primary: test/primary.bib
  secondary: test/secondary.bib
```

This is the case of the [multi bib filter](https://github.com/pandoc-ext/multibib). Please see: https://github.com/pandoc-ext/multibib/issues/1 

Is there any way to bypass this validation?

Thank you.

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
You can add `validate-yaml: false` to your front matter.

This isn't a bug, though - YAML validation is too important for our users, and since Lua filters can access arbitrary metadata, there's no other alternative for us. Perhaps you could consider changing the way the filter works by accessing multibib from a separate field.

**Comment by bcdavasconcelos** [comment]
Thank you.
