### ISSUE TITLE
Using ojs_define() inside a Jupyter notebook

### ISSUE THREAD

**Issue by IliasAarab** [quarto-dev/quarto-cli#4344]
Quarto gives the option to make Python/R variables available to OJS via the `ojs_define()` function. However, when working inside a Jupyter notebook `ojs_define()` is obviously not defined. Current workaround requires converting to .qmd first then adding a Python/R snippet using `ojs_define()` and then rendering the .qmd file.

**Comment by cderv** [comment]
Hi, 

Thanks for the feedback. I believe your issue is a duplicate of https://github.com/quarto-dev/quarto-cli/issues/4344
We are aware of the limitation, and as said in the above issue @cscheid is currently working on solutions to help of
interoperability between language, and how to communicate information to Quarto. This should lead to `ojs_define()`-like function being available in native python.  However, this will still tied to quarto when you render a document. 

> Current workaround requires converting to .qmd first then adding a Python/R snippet using ojs_define() and then rendering the .qmd file.

If you want to render from a `.ipynb` file, you need to explicitly asked for execution `quarto render my.ipynb --execute` so that we inject the right tools for `ojs_define()` to work in quarto rendering.
This is explain in here https://quarto.org/docs/computations/python.html#rendering: 
> Note that when rendering an .ipynb Quarto will not execute the cells within the notebook by default (the presumption being that you already executed them while editing the notebook). If you want to execute the cells you can pass the --execute flag to render

**Comment by IliasAarab** [comment]
Thanks for the elaborate response. 

In case you are referring to #4314, then yes this could be considered a duplicate. I overlooked the issue as I was browsing a different Quarto repo. Looking forward to the proposed solution. 

Using `--execute` allows to render Jupyter notebooks which include (markdown) cells that use `ojs_define()` without any issues indeed!
