### ISSUE TITLE
PDF side-by-side figure with caption error with echo: false

### ISSUE THREAD

**Issue by AQLT** [quarto-dev/quarto-cli#4370]
### Bug description

The following file seems to return an error (LaTeX Error: Not in outer par mode) only with `echo:false`. Tested on MacOS and Windows.

````
---
format: pdf
---

::: {#fig-12 layout-ncol=2}

```{r}
#| fig-cap: "f1"
#| echo: false
plot(1)
```

```{r}
#| fig-cap: "f2"
plot(2)
```

Figure
:::
````

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
I've confirmed this hasn't worked with quarto going at least as far back as `1.0.38`.

The issue here is that we need a better system for detecting subfigures and avoiding nested `figure` environments. It's doable, but it's a big fix. Unfortunately, we're preparing a 1.3 release and I'm reluctant to introduce a regression risk with a big change of this sort.

**Comment by cscheid** [comment]
In 1.4, the problem is that the `\begin{Shaded}` environment (which we use for code listings) doesn't appear to work inside minipages, which we use for layout.
