### ISSUE TITLE
tibble width doesn't match display width in revealjs 

### ISSUE THREAD

**Issue by Aariq** [quarto-dev/quarto-cli#4392]
### Bug description

When wide tibbles are displayed in revealjs slides, they wrap onto a second line.
```` md
---
title: "Untitled"
format: revealjs
editor: visual
---

## A dataset

```{r}
library(dplyr)
bind_cols(mtcars, mtcars) |> as_tibble()
```
````

In the console, it looks like this: 
![Screenshot 2023-02-16 at 2 34 38 PM](https://user-images.githubusercontent.com/25404783/219468682-c415eeae-f783-435d-ac1b-0740159dfdf4.png)

In the rendered slide, it looks like this:
![Screenshot 2023-02-16 at 2 35 02 PM](https://user-images.githubusercontent.com/25404783/219468744-dc823b93-968c-4538-9060-b0bce1015b3f.png)

I'd expect the output to show one row per line.

**Software**:
RStudio: Version 2022.12.0+353 (2022.12.0+353)
macOS: 13.1 (22C65)
Quarto: 1.2.335

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
Unfortunately, this is more or less inevitable. There's no predictable way to figure out the width of the line in the resulting page (because of theme and device variations). We're choosing to wrap the line instead of adding a horizontal scroll, but simply because that's the least bad option. You'll need to change the font size manually for that slide. We explain this in https://quarto.org/docs/presentations/revealjs/index.html#content-overflow:

````

## A dataset {.smaller}

```{r}
library(dplyr)
bind_cols(mtcars, mtcars) |> as_tibble()
```

````

**Comment by Aariq** [comment]
Ah thanks.  I was able to fix it by setting `options(pillar.width = 70)` by trial and error.

**Comment by cscheid** [comment]
The difference is that RStudio knows, at the time of printing, how wide the terminal is.

Quarto can't know how wide the screen will be in characters (because of font sizes from themes, devices, etc)
