### ISSUE TITLE
Conda packages for Windows

### ISSUE THREAD

**Issue by jslorrma** [quarto-dev/quarto-cli#4638]
### Bug description

Hello quarto team,

I have found this pull request https://github.com/conda-forge/quarto-feedstock/pull/1 to enable the build of conda packages for windows. However this PR is open since a bit more than half a year.

What's the status of this PR? Will there be any windows conda packages available anytime soon?

## Context

We'd like to use quarto to generate some internal reports. Unfortunately, we have to use Windows to run our report generation pipeline and having an extra manual installation/ maintenance step instead of using a package manager handling this causes additional effort and some trouble from time to time.

## System
R Studio Version: -
OS: Windows 10 Pro, 19044.2604

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
@jslorrma AIUI, we're presently blocked because we're not able to successfully get a conda build of the dart runtime (necessary for sass) on windows.

**Comment by jslorrma** [comment]
Ok, thanks for your quick response.

@msarahan just commented and mentioned the current blocking build  issues with dart-sass in his open PR here: https://github.com/conda-forge/quarto-feedstock/pull/1

**Comment by cderv** [comment]
Duplicate of #61

**Comment by msarahan** [comment]
Windows conda packages should be available in the next few minutes.

**Comment by msarahan** [comment]
I submitted one patch from the conda recipe here #4691 

There are 2 other patches, but I think they might be too conda-specific for general consideration:
* https://github.com/conda-forge/quarto-feedstock/blob/main/recipe/0001-look-for-tinytex-in-conda-bin-paths-when-CONDA_PREFI.patch, which is a TinyTeX path lookup patch. It utilizes a variable that only the Conda recipe sets, QUARTO_CONDA_PREFIX. This happens in the conda package's activate.d script. It does this instead of using conda's usual CONDA_PREFIX because I thought people might use Quarto standard installs alongside conda environments for Python, and this would be confused with the conda quarto package, leading to incorrect search paths. 
* https://github.com/conda-forge/quarto-feedstock/blob/main/recipe/0001-win-conda-path-overrides.patch, which is mostly the lazy man's approach to getting the BAT scripts done properly.

**Comment by jslorrma** [comment]
> Windows conda packages should be available in the next few minutes.

Thanks so much @msarahan. Great support.👏 Really appreciate this 🙏

Don‘t know if I should leave this issue open for discussion on @msarahan [comment](https://github.com/quarto-dev/quarto-cli/issues/4638#issuecomment-1459159812). Can be closed as far as I’m concerned.
