### ISSUE TITLE
standalone confluence docs should disable editing and use index-based duplicates 

### ISSUE THREAD

**Issue by jjallaire** [quarto-dev/quarto-cli#4706]
### Bug description

Currently if I publish an individual docs it is still editable (this on Confluence Public Cloud). I also noted that duplicates receive a uuid-based suffix rather than an index (not sure if its straightforward to remedy this though).

![Screen Shot 2023-03-08 at 11 24 07 AM](https://user-images.githubusercontent.com/104391/223770872-79f48172-566a-49b5-b693-dc6a78f9a058.png)

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by allenmanning** [comment]
For the first issue, I think that for the free plan you can't change page preferences so it seems that we should give a warning about that as discussed here:  https://github.com/quarto-dev/quarto-cli/issues/4474

For the uniqification indexing issue, I tried out a full implementation of using numbered indexes rather than UUIDs for uniqification of pages.  I ended up reverting it as I found the 'fuzzy' CQL support for searching for existing index pages to be less reliable than I wanted.  To protect myself I then ended up needing to make extra calls per page to ensure it was unique and that slowed things down.  In the end, I just went back to the faster more reliable UUID approach.

**Comment by jjallaire** [comment]
Okay, makes sense on both counts!
