### ISSUE TITLE
Unable to use regular pandoc quarto crossref using short-caption pandoc filter

### ISSUE THREAD

**Issue by Minh-AnhHuynh** [quarto-dev/quarto-cli#4776]
### Bug description

Hello,

Per this [issue](https://github.com/pandoc/lua-filters/issues/265), I am reporting a bug when trying to crossreference a figure:

Using quarto, I am unable to crossref using regular citation syntax, with short-captions.lua pandoc filter. Figures without the short caption filter can be crossreferenced but not with that filter. I am forced to use the latex alternative which is less practical for another reason.

I am not sure if the problem comes from quarto or this filter.

`![**Bold caption** [@Armas.2004]](figure.jpeg){#fig-cap short-caption="**short-cap**"}`

`@fig-cap` returns **?@fig-cap**

Anything that is not `@fig- `breaks as quarto expects a bibliography citation instead.
`@fig:test` returns (fig:test<empty citation>).

`\ref{fig-cap}` works.

[Here is a minimal reproductible example.](https://github.com/pandoc/lua-filters/files/10949365/short-captions-test.zip)

Instead, I have to use \ref{fig-cap} to reference my figure. The issue is that going to visual mode would remove the bold modifications I make, which is why I would have liked to use the quarto syntax.

For example, `(**Figure \ref{fig-cap}**)` is returned as `(**Figure** \ref{fig-cap})` in visual mode which is not what I want.

I am using the latest version of quarto (1.2.335) and RStudio (4.2.2) on Windows 11, 22H2 lastest version.

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
There are a number of things going on.

1. 1.2.335 isn't the latest version of quarto; the 1.3 prerelease https://github.com/quarto-dev/quarto-cli/releases/tag/v1.3.258 is.
2. There are a number of changes from 1.2 to 1.3, including the fact that we moved to Pandoc 3. Unfortunately, Pandoc 3 changes the way that Figures are treated, and from my inspection of short-captions.lua, that filter simply won't work as it is 
 
From my understanding of short-captions.lua, it's looking for Pandoc's "implicit figures", but Pandoc now has a specific AST node Figure. In addition, text content in Pandoc 3 Figures can reside in Plain nodes instead of Para nodes.

So, the filter you have simply won't work.

The following one _should_ work, though:

```lua
if FORMAT ~= "latex" then
  return
end

function Figure(fig)
  local short_caption
  fig:walk({
    Image = function(image)
      if short_caption == nil then
        short_caption = image.attributes["short-caption"]
      end
    end
  })
  if short_caption == nil then
    return nil
  end
  fig.caption.short = pandoc.Inlines(pandoc.Str(short_caption))
  print(fig)
  return fig
end
```

quarto 1.3.258 uses pandoc 3.1.1:

```
$ quarto pandoc --version
pandoc 3.1.1
Features: +server +lua
Scripting engine: Lua 5.4
User data directory: /Users/cscheid/.local/share/pandoc
Copyright (C) 2006-2023 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

And [Pandoc 3.1 should have the ability to write list of figures correctly in the presence of short captions](https://pandoc.org/releases.html#pandoc-3.1-2023-02-09). Unfortunately, that doesn't seem to be happening, even though I can verify that the filter I wrote sets the short caption correctly. The print statement I snuck in there prints the following.

```
Figure ("fig-R-short-cap",[],[]) (Caption (Just [Str "R logo"]) [Plain [Str "This",Space,Str "is",Space,Str "the",Space,Str "long",Space,Str "R",Space,Str "logo",Space,Str "caption."]]) [Plain [Image ("",[],[("short-caption","R logo")]) [Str "This",Space,Str "is",Space,Str "the",Space,Str "long",Space,Str "R",Space,Str "logo",Space,Str "caption."] ("R_logo.png","")]]
```

Unfortunately, it seems that the output we're getting from Pandoc doesn't include the short caption setup.

@tarleb, do you know what might be going on?

**Comment by Minh-AnhHuynh** [comment]
> EDIT: This isn't a bug. Don't use that filter; use `fig-scap` instead:
> 
> ```
> ![This is the long R logo caption.](R_logo.png){#fig-R-short-cap fig-scap="R logo"}
> ```
> 
> It works out of the box.

Thank you so much for the answer. It makes writing my thesis so much easier.

I am encountering the same issue with in-built markdown pandoc tables. I have looked for any solutions regarding short captions for tables. Am I not wrong in assuming that it is not yet natively included ? So far I have found this [issue](https://github.com/rstudio/bookdown/issues/543) where it is possible using `knitr::kable(caption.short=...)`.
