### ISSUE TITLE
`fig-scap` is hard to find in our docs

### ISSUE THREAD

**Issue by cscheid** [quarto-dev/quarto-cli#4783]
Looking for "short caption" in quarto docs yields the code cell options, but nothing on LaTeX authoring.

See #4776 for the confusion this generates.

**Comment by cderv** [comment]
Possibly the same for other figure attributes that we handle in Lua
https://github.com/quarto-dev/quarto-cli/blob/be1f37e89c69886927f3c8d6463acb033b80d261/src/resources/filters/common/figures.lua#L4-L12

They are based possibly on **knitr** options, ported to Jupyter support and direct Markdown syntax support.

**Comment by cwickham** [comment]
Of those mentioned by @cderv, these are already described in the docs:
* [`fig-align`](https://quarto.org/docs/authoring/figures.html#figure-alignment)
* [`fig-env`](https://quarto.org/docs/authoring/figures.html#environments)
* [`fig-alt`](https://quarto.org/docs/authoring/figures.html#alt-text)
* [`fig-pos`](https://quarto.org/docs/authoring/figures.html#figure-position)

I propose `fig-scap` should be described in [LaTeX Figures](https://quarto.org/docs/authoring/figures.html#latex-figures) where `fig-env` and `fig-pos` are currently.

Questions:
* Is `fig-cap` an alternative to providing the caption like `![Caption]()`? Should we describe it in [Figure Basics](https://quarto.org/docs/authoring/figures.html#figure-basics)?
* When would someone use `resize.width` or `resize.height`? (*And why do they use `.` not `-`?*)
* Are there attributes that can be added in other contexts (like tables, headings etc.) that may suffer from this same lack of documentation? Because these don't exist in the "Reference" I know I only discover them by happening upon them in the "Guide".

**Comment by cscheid** [comment]
> * Is `fig-cap` an alternative to providing the caption like `![Caption]()`? Should we describe it in [Figure Basics](https://quarto.org/docs/authoring/figures.html#figure-basics)?

`fig-cap` is shown in https://quarto.org/docs/authoring/figures.html#cross-references, but it probably deserves a more prominent explanation. We use `fig-cap` in knitr and jupyter code cells that produce figures.

**Comment by cwickham** [comment]
But would you ever use `fig-cap` as an attribute outside of computation? E.g. like `![](some-image.png){fig-cap="Some caption"}`.

**Comment by cwickham** [comment]
`fig-cap` as a chunk option is also covered in https://quarto.org/docs/authoring/figures.html#computations, and https://quarto.org/docs/computations/r.html#chunk-options and on all the Code and Document Reference pages. So, I suggest if no one would ever use it outside of computation it probably needs no further coverage.
