### ISSUE TITLE
Plotly not correctly scaled based on width and height

### ISSUE THREAD

**Issue by dkmanl** [quarto-dev/quarto-cli#4836]
### Bug description

When rendering a plotly plot with quarto it is not correctly scaled according to given width & height arguments passed to the ggplotly scale.
This has also been tested for Rmarkdown and there the behavior is as expected. Scaling of the plot output happens on the basis of the width & height arguments.

Rstudio version: 
RStudio 2022.12.0+353.pro20 "Elsbeth Geranium" Release (02ace23e263335c78e1df5b0892e48913e5fcecf, 2022-12-15) for Ubuntu Bionic
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 Edg/111.0.1661.41

Quarto version: 1.2.280

Quarto example:

````markdown
---
title: "Quarto"
author: "dkmanl"
format: 
  html:
    embed-resources: true
---

```{r}
#| label: packages
#| results: hide
#| echo: true
#| message: false

library(tidyverse)
library(plotly)
```


```{r}
#| label: data 
#| echo: true

df <- mtcars |> 
  rownames_to_column("model")
```

```{r}
#| label: plot
#| echo: true

plot <- df |> 
  ggplot(aes(x = mpg, y = hp, color = model)) +
  geom_point()

plotly_width <- 1000
plotly_height <- 600

plot |> ggplotly(width = plotly_width, height = plotly_height)
```
````

Rmarkdown example:
````markdown
---
title: "Rmarkdown"
author: "dkmanl"
output: html_document
---

```{r, label=packages, results='hide', message=FALSE, echo=TRUE}

library(tidyverse)
library(plotly)
```


```{r, label=data, echo=TRUE}

df <- mtcars |> 
  rownames_to_column("model")
```

```{r, label=plot, echo=TRUE}

plot <- df |> 
  ggplot(aes(x = mpg, y = hp, color = model)) +
  geom_point()

plotly_width <- 1000
plotly_height <- 600

plot |> ggplotly(width = plotly_width, height = plotly_height)
```
````

Quarto check:

```
[✓] Checking Quarto installation......OK
      Version: 1.2.280
      Path: /opt/quarto/v1.2.280/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.7
      Path: /opt/python/3.10.7/bin/python3
      Jupyter: 5.1.3
      Kernels: python3, py3.7.7, py3.10.7

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.2.2
      Path: /opt/R/4.2.2/lib/R
      LibPaths:
      rmarkdown: 2.20

[✓] Checking Knitr engine render......OK
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by cscheid** [comment]
Thanks for the report. Can you try https://github.com/quarto-dev/quarto-cli/releases/tag/v1.3.271 to see if the problem persists?

**Comment by cscheid** [comment]
@cderv Do you know what could be causing our behavior to deviate from that of RMarkdown?

**Comment by cderv** [comment]
Yes - we specifically tweak sizing in Quarto HTML format for htmlwidgets figures (by using 100% to be responsive).  

Before it was unconditional but now it is when `fig-responsive` is active (which is the default in HTML format) - This conditional was done as part of #191 so a while back, so that revealjs format could set it to false. 

What we do for responsiveness: 

* we set the width to 100% and the height to proportionate value so that the display width will be ~650px
* So in `width:100%;height:390px` the 100% is set by Quarto and are user provided value rescaled `390= 600/1000 * 650` 

Setting `fig-responsive: false` in the YAML header for the document will give us the same as in R Markdown, but this will apply to all the htmlwidgets in the document. There is not per chunk configuration for this. 

````markdown
---
title: "Quarto"
author: "dkmanl"
format: 
  html:
    embed-resources: true
fig-responsive: false
---

```{r}
#| label: packages
#| results: hide
#| echo: true
#| message: false
library(tidyverse)
library(plotly)
```


```{r}
#| label: data 
#| echo: true

df <- mtcars |> 
  rownames_to_column("model")
```

```{r}
#| label: plot
#| echo: true
plot <- df |> 
  ggplot(aes(x = mpg, y = hp, color = model)) +
  geom_point()

plotly_width <- 1000
plotly_height <- 600

plot |> ggplotly(width = plotly_width, height = plotly_height)
```
````

I guess in this case `fig-responsive: false` is what is needed if specific size is required ? Options is just mentioned in reference page https://quarto.org/docs/reference/formats/html.html#figures

**Comment by cscheid** [comment]
Thanks! It's my understanding, then, that this isn't a bug, and rather an intentional change in behavior.

@dkmanl I'm going to go ahead and close this one. Please feel free to reopen if the solution from Christophe doesn't work for you.

**Comment by dkmanl** [comment]
Problem is solved! Thank you very much @cderv & @cderv.
Changing `fig-responsive: false` gives the the desired behavior.

Sorry for the bug-report, i should have opened a discussion thread instead.

But thank you for the help and the detailed explanation, i understand the change in behavior now.
Also a document wide change is totally fine, no need for a per chunk configuration.

**Comment by eteitelbaum** [comment]
Hi! I'm having the same problem and it doesn't seem to be solved by `fig-responsive: false`. I don't have github repo for this presentation, but [here it is]()https://eteitelbaum.quarto.pub/modernization-theory/) on Quarto Pub.  See slides 10, 11, 12 and 17.

What I am noticing is that it seems like `fig-responsive: false` solves the problem when you render locally but when you open the actual .html file the plotly chart is still not fitting on the screen and so something like an iframe opens up. 

Is this a new development? I don't remember encountering this before. 

I've tried adjusting the figure size at the level of each code chunk with `fig-width` and `fig-height` and that just stretches the image out. I have also tried turning off auto stretch (`autostretch: false`) and adjusting fig width and height. 

I like having the interactive plots in my slides so that I can hover over the points and show my students which countries are where. I also use them for in class exercises where the students explore different data points and discuss where they are on the plots. I mean, they still work. They just don't look that great.

**Comment by eteitelbaum** [comment]
P.S. I went to a different machine and tried to render the presentation there and it worked. [Here is the link](https://eteitelbaum.quarto.pub/modernization-theory-lecture/) to the updated presentation. 

Is it possible that it is a problem with newer versions of Quarto? The machine that rendered the presentation successfully is running 1.2.335 whereas the machine where I got the oversized plotly charts is running 1.3.310.

**Comment by cderv** [comment]
@eteitelbaum thanks for the report. Do not hesitate to open new issues in case like this, linking to another you think could be related. This is easier than discussing and reopening an old one. Anyhow, let me have a look at this. 

> Is it possible that it is a problem with newer versions of Quarto? The machine that rendered the presentation successfully is running 1.2.335 whereas the machine where I got the oversized plotly charts is running 1.3.310.

Do you have the same **plotly** version on both machine ? Just to check that also in case it changed. 

>  I don't have github repo for this presentation

Can you share the qmd content part for the plotly graph that caused the issue ?

**Comment by cderv** [comment]
@eteitelbaum I can reproduce this with latest Quarto using plotly graph from this issue. 

Please do open a new issue, and share a qmd code with the plotly graph and chunk options you are using. Thank you !

**Comment by ThierryO** [comment]
I ran into a similar issue. I've solved it by manually defining the dimension of the plotly figure.

```
ggplotly(p, height = 500, width = 800)
```
