### ISSUE TITLE
Move 1.3 feature documentation into website

### ISSUE THREAD

**Issue by cwickham** [quarto-dev/quarto-cli#4892]
Some thoughts on where 1.3 highlight will live in the "Release Candidate" website:

**Bold** indicates a new page/section:

* [Confluence](https://quarto.org/docs/prerelease/1.3/confluence.html) ->  Guide/Publishing/**Confluence** 

  Also add to list of options on https://quarto.org/docs/publishing/
  
  Do we also need an entry for `confluence-html` in  https://quarto.org/docs/output-formats/all-formats.html?
  
* [Multi-format](https://quarto.org/docs/prerelease/1.3/multi-format.html) -> 
    * [Guide/Documents/HTML/HTML Basics # **Multi-format Links**](https://quarto.org/docs/output-formats/html-basics.html) ? 
    * Or, Guide/Documents/HTML/**Multi Format Links**?
    
    
* [Embedding Notebook Output](https://quarto.org/docs/prerelease/1.3/embed.html) -> 

  * Guide/Advanced/**Embed Jupyter Cells** (like includes)
  * [Guide/Computations/Python](https://quarto.org/docs/computations/python.html)?  Not really right, since this mostly focuses on executable code.
  * Guide/Authoring/**Jupyter Cells** (like embedding videos)
  * Add to list of [native shortcodes](https://quarto.org/docs/extensions/shortcodes.html)
  
* [Article Grid Customization](https://quarto.org/docs/prerelease/1.3/grid.html) -> 
  * Guide/Documents/HTML/**HTML Layout**
  * Or, add to [Guide/Advanced/Page Layout](https://quarto.org/docs/output-formats/page-layout.html)

* [Code Annotation](https://quarto.org/docs/prerelease/1.3/code-annotation.html) -> New Annotating Code section in:
  * [Guide/Documents/HTML/HTML Code Blocks](https://quarto.org/docs/output-formats/html-code.html)
  * Guide/Documents/PDF/PDF Basics?
  * Guide/Documents/MS Word/Word Basics?
  * A link from [Guide/Authoring/Markdown Basics#Source Code](https://quarto.org/docs/authoring/markdown-basics.html#source-code)?
  
  
* [AsciiDoc Books](https://quarto.org/docs/prerelease/1.3/asciidoc-books.html) -> ?  No equivalent for other book formats

  * Add to [list of Books formats](https://quarto.org/docs/books/)
  * Add to [list of All formats](https://quarto.org/docs/output-formats/all-formats.html#documents)
  
* [Website Navigation Improvements](https://quarto.org/docs/prerelease/1.3/website-nav.html) 
    - Navbar Tools -> [Guide/Websites/Website Navigation#Top Navigation](https://quarto.org/docs/websites/website-navigation.html#top-navigation)
    - Responsive Navbar and Sidebar content: doesn't need to live anywhere else?

* [Mermaid Diagram Theming](https://quarto.org/docs/prerelease/1.3/mermaid.html) -> Guide/Authoring/Diagrams#**Mermaid Theming**

* [PDF: SVG and Remote Images](https://quarto.org/docs/prerelease/1.3/pdf.html#filenames-with-modifiers)
  * SVG Images 
  * Remote Images
  * Filename with modifiers 
  
  These don't really feel at home anywhere. More like, things you hope would work, now do.

* [kbd Shortcode](https://quarto.org/docs/prerelease/1.3/kbd.html) -> ? (Doesn't feel big enough for it's own page in Guide/Authoring)
  * Add to list of [native shortcodes](https://quarto.org/docs/extensions/shortcodes.html)
 
* [Extensions: Quarto AST]() -> Somewhere in Extensions/
  * [Extensions/Creating Extensions](https://quarto.org/docs/extensions/creating.html)
  * [Extensions/Creating Extensions/Filters](https://quarto.org/docs/extensions/filters.html) 

* [Extensions: HTML Tables](https://quarto.org/docs/prerelease/1.3/tables.html) ?
  Feels a bit different - more like guidelines for authors that want there tables to work with Quarto.

**Comment by dragonstyle** [comment]
> [Confluence](https://quarto.org/docs/prerelease/1.3/confluence.html) -> Guide/Publishing/Confluence

Agree on publishing.

Given that there are limitations of the confluence-html format, I think it does make sense to include in the list of formats.

> [Multi-format](https://quarto.org/docs/prerelease/1.3/multi-format.html)

Agree- title is challenging!

> [Embedding Notebook Output](https://quarto.org/docs/prerelease/1.3/embed.html)

For this one, I'm not 100% sure the best spot for it, but I wonder if we should be creating a `Jupyter Notebooks` section and including this https://quarto.org/docs/extensions/nbfilter.html as well.

I'm not totally convinced about the above (filters are definitely advanced). I think putting this in `authoring` might be the best place to start.

> [Article Grid Customization](https://quarto.org/docs/prerelease/1.3/grid.html) ->

For this, I think maybe we need to connect it to both Article Layout https://quarto.org/docs/authoring/article-layout.html and perhaps also under Websites somehow (since I think this will be the most common use of it).

> [Code Annotation](https://quarto.org/docs/prerelease/1.3/code-annotation.html) 

Could also consider a new section under 'authoring' for `Code Annotation` since this is well supported for HTML, PDF, and Asciidoc and has baseline support in other formats.

> [AsciiDoc Books](https://quarto.org/docs/prerelease/1.3/asciidoc-books.html) 

We have a page for customizing output https://quarto.org/docs/books/book-output.html - probably makes sense to just place the asciidoc stuff as a section in that doc. 

> [Website Navigation Improvements](https://quarto.org/docs/prerelease/1.3/website-nav.html)

Agree - we probably don't need to add the sections about 'responsive' - we never had them before and those are mainly there to let people know the changes.

> [Mermaid Diagram Theming](https://quarto.org/docs/prerelease/1.3/mermaid.html) -> Guide/Authoring/Diagrams#Mermaid Theming

Agree!

> [PDF: SVG and Remote Images](https://quarto.org/docs/prerelease/1.3/pdf.html#filenames-with-modifiers)

Agree!

> [kbd Shortcode](https://quarto.org/docs/prerelease/1.3/kbd.html) -> ? (Doesn't feel big enough for it's own page in Guide/Authoring)

This one is tough, but what about adding to markdown basics (near the bottom) https://quarto.org/docs/authoring/markdown-basics.html

> [Extensions: Quarto AST](https://github.com/quarto-dev/quarto-cli/issues/4892) -> Somewhere in Extensions/

I think this will need more extensive work to get right- I think we probably need a little more explanation on the base page and also need to probably set up a more structured reference style page for each of the node types. This content probably belongs with `filters ` under `extension`. Perhaps we want to break that into a couple of pages including the node reference pages. I'd suggest that we consider tackling this post RC as I think it will take some time to get right.

>[Extensions: HTML Tables](https://quarto.org/docs/prerelease/1.3/tables.html) ?

I'm stumped by this one - I can't find the right spot. Some brainstorms:

- Just put it in `advanced`
- Don't have it appear in navigation, but just have it appear in search results and link to it directly if/where appropriate
- Could create a new extensions section for package authors targeting QMD output

**Comment by allenmanning** [comment]
🙌
