### ISSUE TITLE
quarto release candidate breaks on an image url

### ISSUE THREAD

**Issue by apsteinmetz** [quarto-dev/quarto-cli#4964]
### Bug description

This code renders successfully with Quarto stable

```
---
title: "example of broken link"
---
![](http://r-statistics.co/screenshots/ggplot_masterlist_2.png){width="488"} [SOURCE](http://r-statistics.co/Top50-Ggplot2-Visualizations-MasterList-R-Code.html)
```
$ quarto check

[>] Checking Quarto installation......OK
      Version: 1.2.475
      Path: C:\Program Files\Quarto\bin
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....(None)

      Unable to locate an installed version of Python 3.
      Install Python 3 from https://www.python.org/downloads/

[>] Checking R installation...........OK
      Version: 4.2.1
      Path: C:/PROGRA~1/R/R-42~1.1
      LibPaths:
        - C:/Users/Apste/AppData/Local/R/win-library/4.2
        - C:/Program Files/R/R-4.2.1/library
      rmarkdown: 2.16

--------------------------------------------------
It does not with the Quarto release candidate. I think it has something to do with 'deno,' whatever that is.

pandoc 
  to: html
  output-file: temp.html
  standalone: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png
  
metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  title: example of broken link
  
ERROR: The filename, directory name, or volume label syntax is incorrect. (os error 123), stat 'C:\Users\Apste\Documents\R Projects\http:\r-statistics.co\screenshots\ggplot_masterlist_2.png'

Error: The filename, directory name, or volume label syntax is incorrect. (os error 123), stat 'C:\Users\Apste\Documents\R Projects\http:\r-statistics.co\screenshots\ggplot_masterlist_2.png'
    at Object.statSync (deno:runtime/js/30_fs.js:322:9)
    at createWalkEntrySync (file:///C:/PROGRA~1/Quarto/bin/quarto.js:2754:23)
    at expandGlobSync (file:///C:/PROGRA~1/Quarto/bin/quarto.js:2874:25)
    at expandGlobSync.next (<anonymous>)
    at expandGlobs (file:///C:/PROGRA~1/Quarto/bin/quarto.js:5786:24)
    at resolveGlobs (file:///C:/PROGRA~1/Quarto/bin/quarto.js:5862:26)
    at resolvePathGlobs (file:///C:/PROGRA~1/Quarto/bin/quarto.js:5798:12)
    at resolveFileResources (file:///C:/PROGRA~1/Quarto/bin/quarto.js:76176:23)
    at resourceFilesFromFile (file:///C:/PROGRA~1/Quarto/bin/quarto.js:76191:37)
    at resourceFilesFromRenderedFile (file:///C:/PROGRA~1/Quarto/bin/quarto.js:76185:12)

$ quarto check

[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.3.290
      Path: C:\Program Files\Quarto\bin
      CodePage: 1252

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....(None)

      Unable to locate an installed version of Python 3.
      Install Python 3 from https://www.python.org/downloads/

[>] Checking R installation...........OK
      Version: 4.2.1
      Path: C:/PROGRA~1/R/R-42~1.1
      LibPaths:
        - C:/Users/Apste/AppData/Local/R/win-library/4.2
        - C:/Program Files/R/R-4.2.1/library
      knitr: 1.42
      rmarkdown: 2.16

[>] Checking Knitr engine render......OK

RStudio 2023.03.0+386 "Cherry Blossom" Release (3c53477afb13ab959aeb5b34df1f10c237b256c3, 2023-03-09) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2023.03.0+386 Chrome/108.0.5359.179 Electron/22.0.3 Safari/537.36

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by cscheid** [comment]
Thanks for the report.

I can't reproduce this on macOS:

<img width="606" alt="image" src="https://user-images.githubusercontent.com/285675/227731961-fb9caa31-5a21-40ad-bd8f-f311d9743e3e.png">

The error message makes it look like it's a path resolution issue ultimately from `resolvePathGlobs` in `src/core/path.ts`. The failure itself seems to be coming from inside deno's expandGlobSync call. I think this is, ultimately, another problem when our filenames include colons on windows.

**Comment by allenmanning** [comment]
@cscheid @cderv Is this a regression?  If so, do we know what regressed it?

**Comment by cderv** [comment]
Sharing here my findings shared yesterday on slack based on investigation

Doing a git bisect, I found that this is the commit that have make this unhidden: https://github.com/quarto-dev/quarto-cli/commit/2f3507a1231e1e28cd0684259681938492f140ce

Before this commit the http resource was transformed to `http:\r-statistics.co\screenshots\ggplot_masterlist_2.png` (see backslash instead of `http://r-statistics.co/screenshots/ggplot_masterlist_2.png` and then it passed through `resolveGlobs()` as a `smartGlob` and got `**`  appended. What was going through `expandGlobSync()`  was `**/http:\\r-statistics.co\\screenshots\\ggplot_masterlist_2.png` which did not caused an issue.

Whereas now the resource url `http://r-statistics.co/screenshots/ggplot_masterlist_2.png` is passed unmodified to `expandGlobSync()` and, as it does not support remote https file I believe, the "path" is seen as non absolute, so it gets prepended by root. This leads to a complete unexisting path to be checked e.g. `C:\Users\chris\Documents\http:\r-statistics.co\screenshots\ggplot_masterlist_2.png`

So @dragonstyle commit did make this problem unhidden, but it was not found until now, because it seems we did not have a test with remote image (which i am surprised by that...)

My proposal is that we filter out `http(s)` from the resource to expand as glob. As discussed with @dragonstyle, it is probably easier to specifically target this for now, instead of covering all the possible remote protocol to filter out. 

However @dragonstyle I am seeing we remove the data URI filtering to deal with it in Lua - We filter out http there... 
Is that supposed to prevent the issue and is it not working ? 

I am referring to https://github.com/quarto-dev/quarto-cli/commit/009c833a5e2c26d7a42e20673daad169af60b5c4

So @allenmanning working on it :)

**Comment by cderv** [comment]
> However @dragonstyle I am seeing we remove the data URI filtering to deal with it in Lua - We filter out http there...
Is that supposed to prevent the issue and is it not working ? I am referring to https://github.com/quarto-dev/quarto-cli/commit/009c833a5e2c26d7a42e20673daad169af60b5c4

It seems related to preview only based on the comment. 

I wondering if the fix should be as you've done in Lua, and just be sure that http resource are not "discovered" and register as resource to handle 🤔

**Comment by cderv** [comment]
@dragonstyle I think I did not go deep enough yesterday to understand how resource discovery works. My comment above is not correct. We are discovering resources through Lua. 

I think we just have an issue in or Lua pattern matching as the regex only targets https and not http. Doing this solve the issue

````diff
diff --git a/src/resources/filters/quarto-pre/resourcefiles.lua b/src/resources/filters/quarto-pre/resourcefiles.lua
index 10144d357..d23059428 100644
--- a/src/resources/filters/quarto-pre/resourcefiles.lua
+++ b/src/resources/filters/quarto-pre/resourcefiles.lua
@@ -11,7 +11,7 @@ function resourceFiles()
     -- around this
     Image = function(el)
       local targetPath = el.src
-      if not targetPath:match('^http[s]:') and not targetPath:match('^data:') then
+      if not targetPath:match('^https?:') and not targetPath:match('^data:') then
         -- don't include this resource if it is a URL, data file or some not file path
         if pandoc.path.is_relative(targetPath) then
           local inputDir = pandoc.path.directory(quarto.doc.input_file)
````

I think that is probably the fix to do here.

**Comment by dragonstyle** [comment]
You are absolutely correct- this is what that pattern was supposed to be doing!
