### ISSUE TITLE
Error rendering code in callout (code listing in a callout)

### ISSUE THREAD

**Issue by dragonstyle** [quarto-dev/quarto-cli#5011]
Error:

- The error appears to be caused by placing attributed code inside a callout 
- Issue could be that we're incorrectly turning this into a code listing
- Issue could be that we don't properly support code listings in callouts

```
LaTeX Error: Not in outer par mode.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.221
```

repro:

````markdown

---
title: Hello
format: pdf
keep-tex: true
---

::: {.callout-note}
If the `www-frame-origin` option is set to `same` or `any` instead of a URI, you must add the following setting with the actual URI:

```{.ini filename="/etc/rstudio/rsession.conf"}
tutorial-api-client-origin=http://localhost:8080
```
:::

````

relevant tex diff:

**Good**
```latex
\begin{tcolorbox}[enhanced jigsaw, left=2mm, rightrule=.15mm, arc=.35mm, toprule=.15mm, coltitle=black, bottomtitle=1mm, titlerule=0mm, opacityback=0, breakable, opacitybacktitle=0.6, toptitle=1mm, colbacktitle=quarto-callout-note-color!10!white, colback=white, title=\textcolor{quarto-callout-note-color}{\faInfo}\hspace{0.5em}{Note}, bottomrule=.15mm, leftrule=.75mm]

If the \texttt{www-frame-origin} option is set to \texttt{same} or
\texttt{any} instead of a URI, you must add the following setting with
the actual URI:

\textbf{/etc/rstudio/rsession.conf}

\begin{Shaded}
\begin{Highlighting}[]
\DataTypeTok{tutorial{-}api{-}client{-}origin}\OtherTok{=}\StringTok{http://localhost:8080}
\end{Highlighting}
\end{Shaded}

\end{tcolorbox}
```

**Bad**
```latex
\begin{tcolorbox}[enhanced jigsaw, leftrule=.75mm, arc=.35mm, toptitle=1mm, left=2mm, colback=white, breakable, colbacktitle=quarto-callout-note-color!10!white, bottomtitle=1mm, title=\textcolor{quarto-callout-note-color}{\faInfo}\hspace{0.5em}{Note}, bottomrule=.15mm, titlerule=0mm, opacityback=0, colframe=quarto-callout-note-color-frame, toprule=.15mm, rightrule=.15mm, opacitybacktitle=0.6, coltitle=black]

If the \texttt{www-frame-origin} option is set to \texttt{same} or
\texttt{any} instead of a URI, you must add the following setting with
the actual URI:

\begin{codelisting}

\caption{\texttt{/etc/rstudio/rsession.conf}}

\begin{Shaded}
\begin{Highlighting}[]
\DataTypeTok{tutorial{-}api{-}client{-}origin}\OtherTok{=}\StringTok{http://localhost:8080}
\end{Highlighting}
\end{Shaded}

\end{codelisting}

\end{tcolorbox}
```

**Comment by dragonstyle** [comment]
I added us both as I suspect there are two issues here, and I think you may have insight into this becoming a code listing. I tried to bisect to a commit, but there were too many skips for it to be helpful.

**Comment by cscheid** [comment]
Let's talk about this live tomorrow.

The issue is the presence of `filename="/etc/rstudio/rsession.conf"`. That causes us to attempt to render the code block as a listing, so that we can do the caption treatment on it.

In 1.2, we'd render the code block by itself like this:

<img width="454" alt="image" src="https://user-images.githubusercontent.com/285675/228420357-5e60e34c-7222-42fc-8a3c-ce415c2b3d43.png">

In 1.3, we render the code block by itself like this:

<img width="612" alt="image" src="https://user-images.githubusercontent.com/285675/228420420-87b9002e-90b0-4f8e-bb3b-1b62cafafdbe.png">

I did this by design, but only because I didn't consider that people would want to put a listing inside a callout.

I think the new appearance is better, but I agree that we should have a way to disable this treatment since LaTeX callouts are necessarily relatively limited in functionality.

**Comment by cscheid** [comment]
Without the filename attribute, we render successfully in 1.3:

<img width="638" alt="image" src="https://user-images.githubusercontent.com/285675/228420925-894fbf1c-19d4-495d-ac8d-1c6f30336396.png">

This suggests a workaround: move `/etc/rstudio/rsession.conf` to outside the filename declaration.

**Comment by dragonstyle** [comment]
We can also fix this in post - the issue is the floating element within a tcolorbox, but I can mark that as `H` and it should be ok. I'll give it a try.
