### ISSUE TITLE
Using meta shortcodes with value defined in Lua filters is not possible anymore 

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#5031]
Try this filter called `custom.lua`

````
function Meta(meta)
    meta["new"] = "new meta"
    return meta
end
````

Then 

````markdown
---
title: "Untitled"
format: gfm
filters: ["custom.lua"]
---

What is defined in the lua filter: "{{< meta new >}}"

````

If I run this with quarto 1.2 , I get the meta

````
Untitled
================

What is defined in the lua filter: “new meta”
````

If I run this with latest 1.3, I get an issue
````markdown
# Untitled

What is defined in the lua filter: “**?meta:new**”
````

Warning is being thrown
````
WARNING: Unknown meta key new specified in a metadata Shortcode.
````

Possibly a regression to look into. Unless we think this was not desired behavior. Though it seems expected to me to be able to expose custom meta defined in a filter through the meta shortcode. I know one extension who does not work anymore https://github.com/mcanouil/quarto-lua-env

**Comment by cderv** [comment]
As suspected, this is a side effect of 56888bb94 for #3694 with the new AST custom node.  (confirm by a `git bisect` investigation)

@cscheid is this a regression on purpose ? Or something we can adapt ?

**Comment by cscheid** [comment]
The issue here is that the `meta` shortcode handler resolves through a call to `option()`, and `option()` gets its information from the output of `initOptions()`. `initOptions()` used to be called after user filters in 1.2, but that doesn't work anymore because some of the AST normalization needs `option()` calls.

As a stopgap measure, I'll make it so that we recompute the `option()` data after user filters. With that said, I'm pretty sure I'm going to change this for 1.4 (or later) so that we have an explicit quarto.set_option() call instead of revisiting the entire document and recomputing the entire options object. This is for performance reasons, which I'm (now) acutely aware of...

**Comment by cderv** [comment]
Thanks @cscheid !
