### ISSUE TITLE
Filenames of executable blocks should be treated the same as as non-executable

### ISSUE THREAD

**Issue by eitsupi** [quarto-dev/quarto-cli#5101]
### Bug description

This qmd file includes filename attribute

````qmd
---
title: foo
---

```{python filename="Python"}
print("Hello, world.")
```

```{.python filename="Python"}
print("Hello, world.")
```
````

is convert to this md file in Docusaurus project.

````md
---
title: foo
---

``` python
print("Hello, world.")
```

``` text
Hello, world.
```

```python title="Python"
print("Hello, world.")
```
````

Displayed as like this.

![image](https://user-images.githubusercontent.com/50911393/230096800-5c0b81a1-31b3-4957-b476-fd1f44e19b8f.png)

Using the edge version unreleased Quarto CLI on Debian Linux.

```sh
$ quarto check

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 99.9.9
      Path: /tmp/quarto-cli/package/dist/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.2
      Path: /usr/bin/python3
      Jupyter: 5.3.0
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by cscheid** [comment]
That syntax in executable blocks isn't supported by any format at the moment. (I agree that it should! But it's going to be part of the crossref work I do in 1.4) You can check the rendering in `html` in versions 1.2 and 1.3. At this point we're only fixing regressions for 1.3, but we'll make sure to fix in 1.4.

**Comment by eitsupi** [comment]
Thanks for your response.

> That syntax in executable blocks isn't supported by any format at the moment.

When I used this previously, I believe it was supported in HTML format.
That can be found here. (It seems built with Quarto 1.2.313)
https://eitsupi.quarto.pub/use-prql-executable-code-blocks-on-quarto/

In any case, I look forward to getting this working in 1.4.

**Comment by cderv** [comment]
Here is some context about the syntax and why it worked for your document @eitsupi . 

It works for document using **knitr** engine because of how **knitr** option are working. They are parsed as chunk option, and unknown chunk options are passed through. so it will produce the expected syntax in the markdown file for the feature to work 

````markdown
---
title: foo
---

```{r filename="test.R"}
print("Hello, world.")
```
````

Gives this intermediate markdown

````markdown
---
title: foo
keep-md: true
---

::: {.cell filename='test.R'}

```{.r .cell-code}
print("Hello, world.")
```

::: {.cell-output .cell-output-stdout}
```
[1] "Hello, world."
```
:::
:::
````

and 

it gives 
![image](https://user-images.githubusercontent.com/6791940/230382618-9bf0bc73-1450-40d5-a0b7-0891ea86c022.png)

This feature is from https://github.com/quarto-dev/quarto-cli/pull/1726  and the attributes on Cell div is supported 
https://github.com/quarto-dev/quarto-cli/blob/37ce04581238dc036985fcdab20534aaf78732de/src/resources/filters/quarto-pre/code-filename.lua#L48-L52

For python chunk, the options need to be set inline to get the same behavior (unknown option passed through). So this works 
````markdown
---
title: foo
keep-md: true
---

```{python}
#| filename: test.py
print("Hello, world.")
```
````

![image](https://user-images.githubusercontent.com/6791940/230383717-fb83168d-c2cc-4552-b04b-b37ba0bb4a8a.png)

This is probably the proper syntax for executable code chunks, as options are expected to be passed inside chunk. 

This is with HTML format, due to the Codefilename Lua feature.  Not sure how docusaurus works but I think the syntax you see it is not handle by the same feature, but directly by the writer 
https://github.com/quarto-dev/quarto-cli/blob/37ce04581238dc036985fcdab20534aaf78732de/src/resources/extensions/quarto/docusaurus/docusaurus.lua#L65-L75

> That syntax in executable blocks isn't supported by any format at the moment. (I agree that it should! But it's going to be part of the crossref work I do in 1.4)

@cscheid I understand we want to make the syntax evolved - I just wanted here to give current situation and point the difference with docusaurus format. It seems when CodeFilename happens in Lua the cell Div with the attributes are not there anymore, hence the processing not happening.

**Comment by eitsupi** [comment]
@cderv Thanks for the detailed explanation!

I had forgotten the difference in behavior between knitr and Jupyter because I use the knitr engine more often.

Also, the following page doesn't seem to describe how to specify when to use Jupyter.
https://quarto.org/docs/output-formats/html-code.html#code-filename

Also, it does not seem to work on Docusaurus anyway.

````qmd
---
title: foo
keep-md: true
---

```{python}
#| filename: test.py
print("Hello, world.")
```
````

To

````md
---
title: foo
keep-md: true
---

``` python
print("Hello, world.")
```

``` text
Hello, world.
```
````

![image](https://user-images.githubusercontent.com/50911393/230393424-902d08d7-ee08-4c0b-bd67-5aed4f5e5b9e.png)

**Comment by cderv** [comment]
> I just wanted here to give current situation and point the difference with docusaurus format. It seems when CodeFilename happens in Lua the cell Div with the attributes are not there anymore, hence the processing not happening.

@eitsupi yes - I meant by the above that it is not working with the `::: {.cell filename=...}` is not there anymore when the processing happens to retrieve the attributes. I think this is a current limitation of docusaurus, as it is a md based format, and Codefilename does not work by default with markdown format. This is why there is a specific handling with the two lua code mentioned above. 

As it was an oppportunity to learn more about all Lua AST handling in Quarto, here is why it does not work with docusaurus format.

`docusaurus-md` is markdown based, and we deactivate support for output div for some format by unwrapping the Div content 
https://github.com/quarto-dev/quarto-cli/blob/56888bb94984fd93f16edb42dbe5564c6dc65eaa/src/resources/filters/main.lua#L172

This happens when internal param `output-divs` is false, which it is by default for markdown based format. 
https://github.com/quarto-dev/quarto-cli/blob/657a8a32a3109f5b6280aa33d7e8d22228554c47/src/format/markdown/format-markdown.ts#L63-L68

This is not reactivated for docusaurus so the Divs are removed as part of the `outputs()` filter. Which means when reaching `CodeFilename()` filter , there is not `Div` or class `.cell` to look into
https://github.com/quarto-dev/quarto-cli/blob/56888bb94984fd93f16edb42dbe5564c6dc65eaa/src/resources/filters/main.lua#L183

And as I described above, this is what usually handle the `filename` attributes sets on computation code chunk source, so it is not for Docusaurus. 

> Also, the following page doesn't seem to describe how to specify filename when using Jupyter.

Maybe it is a side effect of how things work for certain format, and it is not documented because not officially supported by format. 

Anyhow, it was an instructive code reading - hopefully it will help decide if this feature could be supported.

**Comment by eitsupi** [comment]
> Codefilename does not work by default with markdown format.

I did not know this.
The predecessor extension (from @quarto-ext) did support it, right? (I just searched the repository and couldn't find it. Is it now private?)

**Comment by cderv** [comment]
Sorry @eitsupi I wasn't enough clear. I meant that point in the context of `filename` within a computation chunk. The side effect of creating `::: {.cell filename=...}` to be handled by the filter does not happen for md format. I did mean the all feature using `` ```{.python filename=...}``` ``

> The predecessor extension (from https://github.com/quarto-ext?type=source) did support it, right? (I just searched the repository and couldn't find it. Is it now private?)

but now that you mention this (and yes it has been put in private and not just archive it seems), it seems a regression from 1.2. I'll open an issue for that
