### ISSUE TITLE
Copy and paste text including em-dash in visual mode crashes RStudio 

### ISSUE THREAD

**Issue by cermak-consulting** [quarto-dev/quarto-cli#5148]
### Bug description

I have had a couple of instances now when copying-and-pasting text containing em-dashes in Quarto's visual mode causes RStudio to freeze. When this occurs, I cannot save changes and cannot restart the R session. The only option is to end the program using the Windows Task Manager. I can go into source mode (if I remember to do so) and move copy-and-paste without a problem. I only seems to occur when in visual mode. I may occasionally work without a problem, but eventually moving it will cause the problem.

RStudio 2023.03.0+386 "Cherry Blossom" Release (3c53477afb13ab959aeb5b34df1f10c237b256c3, 2023-03-09) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2023.03.0+386 Chrome/108.0.5359.179 Electron/22.0.3 Safari/537.36

OS Name	Microsoft Windows 11 Pro
Version	10.0.22621 Build 22621
12th Gen Intel(R) Core(TM) i5-1240P, 1700 Mhz, 12 Core(s), 16 Logical Processor(s)

quarto check - no idea how to find this from the description below

Also interestingly, you are requesting I attach a single .qmd file for this issue, but when I tried to do this, I get a message stating that .qmd files are not supported. Hence, I have put it into a zip file and attached it that way.

[em-dash bug.zip](https://github.com/quarto-dev/quarto-cli/files/11194184/em-dash.bug.zip)

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [X] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by cscheid** [comment]
I think this probably belongs in either the rstudio repo (https://github.com/rstudio/rstudio/) or the repo where we host the visual editor code (https://github.com/quarto/quarto).

@jjallaire what do you think?

**Comment by jjallaire** [comment]
If it repros within the Visual Editor running within the VS Code extension on Windows then it belongs in quarto/quarto, if not it belongs in rstudio/rstudio.

**Comment by ivanlambert1975** [comment]
I have exactly the same issue, with exactly the same version of R Studio, but slightly different OS which implies that R Studio is likely not handling exception on copy and paste in Visual when editing a .qmd .

Situation:
A simple copy and paste randomly crashes the entire session when in "Visual". It's hard to "reproduce" a random crash by it's very nature. Sometimes copy and paste works - 1 time in ~50 it locks up entire R session. Menus are clickable - Visual window however is entirely unresponsive. I've had it happen 3 times in last 2 days - losing changes on the way. 
Sometimes, it's just copy and pasting YML, sometimes it's the body. I'm stretching Quarto a bit here, I've got many leaflet maps for geographic areas over different metrics. There doesn't seem to be a solid pattern to crashing in "Visual", other than it randomly crashes on copy and paste. The only other clue is that the copy of clipboard could be the source of crash not the paste. It's only as users we notice when the paste fails, that we suspect the "Visual" has locked-up again.

Do you have a completely reliable copy and paste in "Visual" on your system? What differences do you think might be the cause? 

Workaround: Don't use "Visual" - it cannot be depended upon and crashes. Render to doc output using own caches. Use "Source" instead, and make your own caches because the Quarto caches don't work reliably for many leaflet maps.

I think Quarto is a fantastic idea. However, at the moment it's just got a few rather rough-edges and this is one of them. 

Env:
RStudio 2023.03.0+386 "Cherry Blossom" Release (3c53477afb13ab959aeb5b34df1f10c237b256c3, 2023-03-09) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2023.03.0+386 Chrome/108.0.5359.179 Electron/22.0.3 Safari/537.36

Many thanks

**Comment by cscheid** [comment]
@ivanlambert1975 This isn't a quarto-cli bug; it is either a bug in RStudio itself (in which case you have to file it at https://github.com/rstudio/rstudio) or a bug in quarto's editor support (in which case you have to file it at https://github.com/quarto/quarto).

Any chance you can test this in VS Code with the quarto extension? That would let us know where to go next.

**Comment by sda030** [comment]
I tested now in VS Code with the Quarto extension and it rendered an em-dash (copied from a website) correctly, no warnings or errors. I also tested with RStudio, both in source and in visual editor modes, copying in an em-dash. It renders correctly in any case. I used almost newest daily builds of RStudio and Quarto (1.4.435). I suggest the issue be closed.
