### ISSUE TITLE
autocompletion: render-on-save does not appear in yaml

### ISSUE THREAD

**Issue by jooyoungseo** [quarto-dev/quarto-cli#5238]
`render-on-save` does not seem to be included in the autocompletion list under `editor:` in yaml.

**Comment by cscheid** [comment]
I'm not sure why this was triaged to me :) I don't see `render-on-save` anywhere on `quarto-cli`. 

I'm assuming this is an option that needs to be added to `src/resources/schema/document-editor.yml`. @jjallaire ?

**Comment by cderv** [comment]
> I'm not sure why this was triaged to me :) 

because I saw that as related to YAML completion and validation and you seemed to be the better fit to know what to do on this. :-) ... or who should be best to know what to do ;-)

AFAIU [from our doc ](https://quarto.org/docs/tools/vscode.html#render-on-save) `render-on-save` should be in `editor` schema

**Comment by allenmanning** [comment]
Thanks @cderv for attempting to find a good first owner.

**Comment by jjallaire** [comment]
This will be added in v1.4: https://github.com/quarto-dev/quarto-cli/commit/38be8140922b6d076d92ec3c45d0e3795034dc02
