### ISSUE TITLE
Inconsistent coding style in R examples

### ISSUE THREAD

**Issue by richelbilderbeek** [quarto-dev/quarto-cli#5324]
Dear maintainers, 

I was just recommended about Quarto in a course and it looks great! 

However, in that course we got distracted by a minor issue: the inconsistent coding style in the R examples at [https://quarto.org/docs/get-started/hello/rstudio.html](https://quarto.org/docs/get-started/hello/rstudio.html). It is a minor Issue, but hey, let's make the website even more awesome :-)

In the text, within the `.qmd` document, it reads:

```
library(tidyverse)
```

Note that the library is loaded without double-quotes. In the text later, however, a library is loaded with double-quotes:

```
install.packages("quarto")
```

This caused a discussion in class about which way is better and what are the differences, which was a needless distraction.

I suggest to use a consistent loading of libraries.

**Comment by cscheid** [comment]
> I suggest to use a consistent loading of libraries.

Thanks for the suggestion. Unfortunately, these are different commands. `install.packages()` _installs packages_, and requires a character vector because the packages might not be installed yet; `library()` _loads packages_, and doesn't use character vectors. This is a quirk, but it's completely standard in R documentation.

Here's eg https://www.tidyverse.org/packages/#installation-and-use with the same difference:

<img width="801" alt="image" src="https://user-images.githubusercontent.com/285675/234892342-da095dc3-d40e-4d11-b7da-986643b1a245.png">

**Comment by richelbilderbeek** [comment]
:facepalm: silly me, I completely agree; some neuron must have misfired. Thanks!
