### ISSUE TITLE
RevealJS Pause marker (. . .) is rendered as text in HTML format

### ISSUE THREAD

**Issue by awe-hnu** [quarto-dev/quarto-cli#5340]
### Bug description

I render documents in multiple formats, particularly as Website and RevealJS presentation. That worked well until the update, with v.1.3x the RevealJS Pause marker `. . .` is also rendered in HTML ouput. Would be great if that could be filtered out again. Thanks in advance!

### Checklist

- [ ] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [ ] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [ ] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by cderv** [comment]
This is not a regression IMO but a change in Pandoc - and new 1.3 comes with newer Pandoc. 

I was reported in https://github.com/jgm/pandoc/issues/8281 following an issue here in https://github.com/quarto-dev/quarto-cli/issues/2302

Previously, `. . .` was also parsed as a pause in non-slide HTML when below a header only, which wrongly created a incremental div

````markdown
# Hello

content

. . .

content
````

Converted to HTML with `pandoc` 2.19.2 latest before Pandoc 3 gives 
````html
<h1 id="hello">Hello</h1>
<p>content</p>
<div class="incremental">
<p>content</p>
</div>
````

and with Pandoc 3 and later will give 
```html
<h1 id="hello">Hello</h1>
<p>content</p>
<p>. . .</p>
<p>content</p>
```

When no header, then it would be only `. . .`

```markdown
content

. . .

content
```

```html
<p>content</p>
<p>. . .</p>
<p>content</p>
````

The fix https://github.com/jgm/pandoc/commit/86a3467ece8f6b9355f267d7cb1816e3465a56f8 in Pandoc seems to leave the `. . .` alone in non slide output. [Maybe it was not the right fix in Pandoc](https://github.com/jgm/pandoc/issues/8281#issuecomment-1237258364) - this should be discussed there probably.

In this comment, I am sharing a lua filter useful to remove the `. . .` in non slide output https://github.com/quarto-dev/quarto-cli/issues/2302#issuecomment-1237212189

Hope it helps clarify - this is not a change in Quarto directly but in Pandoc due to how they fix the initial issue.

**Comment by awe-hnu** [comment]
Thanks for the quick reply including a fix.
And sorry that I have not noticed https://github.com/jgm/pandoc/issues/8281 and https://github.com/quarto-dev/quarto-cli/issues/2302.

Great support!

**Comment by cderv** [comment]
Don't worry, I wouldn't expect you to see those pandoc issues as a quarto user, you were completely right to ask !
