### ISSUE TITLE
Publishing requires deleting the freezed post 

### ISSUE THREAD

**Issue by msh855** [quarto-dev/quarto-cli#5360]
I have noticed that when I have made changes to a post that has to run Python or R code, the changes do not get published (`quarto publish`) or previewed (`quarto preview`) unless I delete first the folder in the `freeze` directory and repeat the process.

I have set `freeze: true` in my `metadata` file

Any help understanding and fixing this unexpected behaviour?

**Comment by dragonstyle** [comment]
I hope this helps explain things:

https://quarto.org/docs/projects/code-execution.html#freeze

`freeze: true` instructs Quarto never to re-execute the document's code during a global rendering (such as happens during a publish action). You could want to try `freeze: auto`?

Deleting the freeze directory is causing re-execution since there is no 'frozen' version of the document available.

Please feel free to use our discussions if you have questions that you aren't certain are bugs - it will help us keep the bug list a bit shorter and get the community more involved in answering questions as well!

**Comment by msh855** [comment]
Indeed, this worked. I found confusing the documentation. As my post included computationally intensive tasks, I thought setting `feeze:true` is the right option. Hence, I reported this as a bug. 

I now got it. And thank you once again for the help. Still learning quarto.
