### ISSUE TITLE
Chunk option `attr-output` in R chunks does not add attribute to html 

### ISSUE THREAD

**Issue by ateucher** [quarto-dev/quarto-cli#5456]
### Bug description

Adding the `attr-output` option in an R chunk has no effect on the rendered html (i.e., the attribute does not get added).

Reprex:

````
```{r}
#| error: true
#| warning: true
#| message: true
#| attr-output: "style='color: blue;'"
#| attr-error: "style='color: yellow;'"
#| attr-warning: "style='color: orange;'"
#| attr-message: "style='color: green;'"
#| results: asis
cat("something")
stop("something")
warning("something")
message("something")
```
````

![image](https://user-images.githubusercontent.com/2816635/236914113-378feae1-a756-4f41-bb20-a7adafea8fb7.png)

### Quarto check:
```
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.340
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.6
      Path: /Library/Developer/CommandLineTools/usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.0
      Path: /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources
      LibPaths:
        - /Users/andyteucher/Library/R/arm64/4.3/library
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.42
      rmarkdown: 2.21

[✓] Checking Knitr engine render......OK
```

### Checklist

- [x] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [x] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [ ] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.
- [x] Please provide the output of `quarto check` so we know which version of quarto and its dependencies you're running.

**Comment by mcanouil** [comment]
FYI, I opened an issue upstream since the behaviour is the same using `rmarkdown`, see <https://github.com/yihui/knitr/issues/2256>.

**Comment by cderv** [comment]
@ateucher let me put also here the answer I give upstream at https://github.com/yihui/knitr/issues/2256#issuecomment-1539657320

This is just happening in your example because you are using `results: asis` 

This means no code chunk output will be created by **knitr** to put the attributes on. It will be output asis in the resulting document. So that is expected for this specific usage. 

See this example showing the difference 

````markdown
---
title: "Demo"
output:
  html_document:
    keep_md: true
---

```{r}
# Set global option
knitr::opts_chunk$set(attr.output = "style='color: blue;'")
```

```{r}
#| results: asis
cat("something")
```

```{r}
cat("something")
```

````

![image](https://user-images.githubusercontent.com/6791940/237035387-776f8e90-1d4c-4a94-bc63-9e0139a57fe8.png)

<details>
<summary>And intermediate source code </summary>

````markdown
---
title: "Demo"
output:
  html_document:
    keep_md: true
---


```r
# Set global option
knitr::opts_chunk$set(attr.output = "style='color: blue;'")
```


```r
cat("something")
```

something


```r
cat("something")
```

```{style='color: blue;'}
## something
```
````

</details>

There is no issue here - just an unexpected usage of `attr.output`. For message, error and warning, `asis` does not apply so that is why you get the correct wrapping in `.md` file with correct class. 

I'll look closer at your original slack message for the original issue with `out-extra`

**Comment by mcanouil** [comment]
> In Quarto, being able to add attributes other than class allows to use many things, such as tooltip, hover effect, aria-, etc. to a code cell.
I am not sure it would be really complex to add such things, unless you want to notify the user he/she is doing nonsense html thing, and even if that's the case Pandoc will basically prepend data- to the whole value of attributes which in the end should be harmless.

Source: <https://github.com/yihui/knitr/issues/2256#issuecomment-1540909948>

To continue on discussing the possible addition of `attributes` alongside `classes` as a more general approach (not tied up to `knitr`) to add any kind of attributes (including classes) on code cells.

**Comment by cderv** [comment]
@mcanouil Le'ts create a specific feature request for this with some example on expected results and why it would be useful. This issue is initially about a related problem but not directly to this idea of yours. I think that would be easier to track.

**Comment by mcanouil** [comment]
True, I hesitated.
Although this issue itself seems "resolved", isn't it?

**Comment by cderv** [comment]
Yes exactly, if you open a new one , I'll close this one.

**Comment by mcanouil** [comment]
I am closing this as resolved.

For discussion about the global code cell `attributes` option, see #5587
