### ISSUE TITLE
Error or warning when a listing path doesn't match any files

### ISSUE THREAD

**Issue by dragonstyle** [quarto-dev/quarto-cli#5463]
Consider providing a warning or error when a listing points at a path that doesn't resolve to any files or inputs (e.g. it is producing an empty listing or pointing at a path that doesn't exist at all).

**Comment by dragonstyle** [comment]
(Make a listing that points to a non-existent folder and note that we just silently don't populate the listing)

**Comment by schneiderpy** [comment]
Hi, I have seen that this issue is closed, but I could not find a solution since I encounter the same problem
 `ERROR: The listing in 'posts\index.qmd' using the following contents:
- index.qmd
doesn't match any files or folders.`

However, the folder exists (top-level), but (almost) empty (no posts yet) but with an index.qmd (if necessary?) and an optional _metadata.yml.

**Comment by cderv** [comment]
@schneiderpy please open a new issue with an example and some details so we can have a look. 
be sure to update to latest stable version 1.4 and if possible try the pre-release 1.5. 

We prefer new thread, especially for issue that are 6 months old. Thank you !
