### ISSUE TITLE
[feature] capability to access repl

### ISSUE THREAD

**Issue by majidaldo** [quarto-dev/quarto-cli#5682]
### Bug description

ref discussion https://github.com/quarto-dev/quarto-cli/discussions/5664

As of ver 1.4.80, Quarto does not allow the capability to 'get into' the kernel in a repl session. Quarto could implement something like a `--debug` that would allow the user to debug errors by intercepting stack traces. Or, in the case of jupyter, it could use or give kernel connection information.

**Comment by cscheid** [comment]
This is technically quite hard to do in the context of the many different things quarto-cli does, and it's unlikely we'll do that anytime in the future. In the meantime, we really do recommend users that want interactivity to either use jupyter directly (since we support .ipynb as input formats) or one of the many available IDEs, including RStudio and VS Code.

**Comment by majidaldo** [comment]
i can wrap quarto with something like
```


def eval_qmd(qmd, globals={}):
    from re import findall, DOTALL
    re = "```{python}(.*?)```"
    for code in findall(re, qmd, DOTALL):
        try:
            exec(code, globals)
        except Exception as e:
            import pdb
            print(code)
            print(e)
            pdb.post_mortem(e.__traceback__)


if __name__ == '__main__':
    import sys
    from pathlib import Path

    def read_qmd():
        f = (sys.argv[1])
        f = Path(f)
        f = open(f)
        f = f.read()
        return f

    
    qmd1 = ''
    from time import sleep
    while True:
        qmd2 = read_qmd()
        if qmd1 != qmd2:
            eval_qmd(qmd2)
            qmd1 = qmd2
        sleep(1)
        
```
