### ISSUE TITLE
Observable rendering suppresses comments outside function definition

### ISSUE THREAD

**Issue by ijlyttle** [quarto-dev/quarto-cli#569]
For example, in an {ojs} block:

```js
// comments disappear here
f = function (x) {
  // but they appear here
  return x + 1;
}
```

**Comment by jjallaire** [comment]
@cscheid Could that be because the comment at the top is getting removed by our cell option logic?

**Comment by cscheid** [comment]
I believe this is happening because the OJS block in general doesn't know how to associate comments to functions. We use acorn-js to walk the JS ast and collect declarations and statements, but we ignore comments. What should we do about:

```js
function f1(x) { return x * x; }
// is this a comment about f1 or f2?
function f2(x) { return x + x; }
```

**Comment by ijlyttle** [comment]
If it helps, I think you get no more than one definition per cell.

**Comment by cscheid** [comment]
You don't get more than a definition per cell on observablehq, but you do on quarto ;) It helps when you want to do things like fancy layouts, etc.

**Comment by ijlyttle** [comment]
Yikes - 🤯

<homer-recedes-into-the-bush.gif>

**Comment by cscheid** [comment]
As of commit 2036735f8, I improved the handling of this case somewhat. Whenever there's a single definition in an OJS cell, we use the entirety of the source, which means that in your particular case, all comments now show up.

With that said, if your OJS cell includes more than one definition, then in general we are unable to figure out how to associate the comment nodes with the definitions. This happens because the parser used by observable doesn't return top-level comments in their AST, and so we don't even see it (and we need to parse the source in order to split the different definitions).

**Comment by ijlyttle** [comment]
Thanks!
