### ISSUE TITLE
Random hash inserted in title when publishing to Confluence

### ISSUE THREAD

**Issue by nwisn** [quarto-dev/quarto-cli#5797]
### Bug description

I followed the example at https://quarto.org/docs/publishing/confluence.html to publish the default Quarto file confluence-demo.qmd, with title specified in the yaml as "Confluence Demo". The preview resulting from `quarto preview confluence-demo.qmd` looks correct. The page that makes it to Confluence using `quarto publish confluence confluence-demo.qmd` ends up with a random hash added to the title, for example "Confluence Demo 58b33578". This hash changes to a different random value when republished.

### Steps to reproduce

````qmd
---
title: "Confluence Demo"
format: confluence-html
---

## Quarto

Quarto enables you to weave together content and executable code into a finished document. To learn more about Quarto see <https://quarto.org>.

## Running Code

When you click the **Render** button a document will be generated that includes both content and the output of embedded code. You can embed code like this:

```{r}
1 + 1
```

You can add options to executable code like this

```{r}
#| echo: false
2 * 2
```
````

### Expected behavior

<img width="654" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/11002770/5607661f-8a44-4712-b351-08d62f9f3337">

### Actual behavior

<img width="734" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/11002770/5fbf5e0b-2882-4f81-9007-c1027f201540">

### Your environment

- IDE: RStudio 2023.03.1+446
- OS: macOS Monterey 12.3
- R: 4.1.2

### Quarto check output

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.326
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.8.9
      Path: /Applications/Xcode.app/Contents/Developer/usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.1.2
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Users/Nick/Code/bulkRNAseq/renv/library/R-4.1/x86_64-apple-darwin17.0
        - /Library/Frameworks/R.framework/Versions/4.1/Resources/library
      knitr: 1.37
      rmarkdown: 2.11

[✓] Checking Knitr engine render......OK

**Comment by mcanouil** [comment]
Thank you for the report!

You probably did not close properly the code block of your example leading to everything being treated as code, could you fix it please?

**Comment by allenmanning** [comment]
Thanks for posting this @nwisn.  

Is there already a page with the Title "Confluence Demo" in the space you are publishing to?  This also includes pages that have been archived and not yet deleted?

**Comment by nwisn** [comment]
You are correct. After removing an old page, the problem is resolved. Thank you!

**Comment by allenmanning** [comment]
@nwisn I find it confusing as well, and I wish that limitation wasn't there.  We tried version numbers rather than UUIDs but the Confluence search API wasn't stable enough to support that at least with my first couple of attempts.

"Quarto may add some additional characters to meet the Confluences requirement that every page in a space has a unique name." [Quarto Docs](https://quarto.org/docs/publishing/confluence.html#project-structure)

Confluence has a limitation that all Page Titles within a space must be unique.  The way that we work-around this limitation is by first checking if the title is already in use, and if so, we then make it unique.  

@cwickham I'm keeping an eye on reports around this.  If folks continue to be confused by this (which really is confusing) we can chat about adding additional doc or potentially some form of CLI logging to help inform folks.
