### ISSUE TITLE
Figures are always cropped in PDF output

### ISSUE THREAD

**Issue by salim-b** [quarto-dev/quarto-cli#5981]
If both the `pdfcrop` binary and Ghostscript are available on the system, Quarto crops figures in PDF output regardless of the relevant chunk option. Tested on Ubuntu 22.04 with Quarto 1.3.361.

I've tried to disable cropping without success by

- setting the chunk option (in YAML format) `crop: false`
- setting the chunk option (in YAML format) `fig-crop: false`
- setting `knitr.opts_chunk.crop: false` in `_quarto.yml`.
- setting `knitr.opts_chunk.fig_crop: false` in `_quarto.yml`. 
- setting `format.pdf.crop: false` in `_quarto.yml`.
- setting `format.pdf.fig_crop: false` in `_quarto.yml`.
- running `knitr::opts_chunk$set(crop = FALSE)` in a chunk before the figure chunks.
- running `knitr::opts_chunk$set(fig_crop = FALSE)` in a chunk before the figure chunks.

The only way that actually disabled PDF figure cropping was running `knitr::knit_hooks$set(crop = function(...){})` in a chunk before the figure chunks.

Note that I'm a bit confused about the correct name of the cropping chunk option on the knitr side of things: While the *R Markdown Cookbook* [mentions a `crop` chunk option](https://bookdown.org/yihui/rmarkdown-cookbook/crop-plot.html) (same what the [Quarto sources seem to refer to](https://github.com/quarto-dev/quarto-cli/blob/c8fb73c433215926d1b8b18f39e29bc1a215e33d/src/resources/rmd/execute.R#L277-L281)), the *R Markdown: The Definitive Guide* [mentions a `fig_crop` chunk option](https://bookdown.org/yihui/rmarkdown/pdf-document.html#figure-options-1). Quarto seems to ignore both of them.

_Originally posted by @salim-b in https://github.com/quarto-dev/quarto-cli/discussions/2917#discussioncomment-6224496_

**Comment by baptiste** [comment]
For reference, I believe the problem occurs [here](https://github.com/quarto-dev/quarto-cli/blob/574396e68882c41336e9f539f4aee7ace6485f03/src/resources/rmd/execute.R#L272)

**Comment by salim-b** [comment]
Note that also PNG (and possibly other image formats) get cropped in PDF output.

To reproduce:

1. Install the `pdfcrop` LaTeX package (e.g. via `tinytex::tlmgr_install("pdfcrop")`) and Ghostscript (on Ubuntu/Debian via `sudo apt install ghostscript`).
2. Render the following file via `quarto t.qmd --to=pdf --no-cache --metadata=keep-md:true`:

    <details><summary><code>t.qmd</code></summary>
    
    ````qmd
    ---
    format:
      pdf:
        fig-pos: H
    ---
    
    ```{r}
    #| label: init
    #| include: false
    
    library(ggplot2)
    
    sample_df <- data.frame(
      group = factor(rep(letters[1:3], each = 10)),
      value = rnorm(30)
    )
    
    group_means_df <- setNames(
      aggregate(value ~ group, sample_df, mean),
      c("group", "group_mean")
    )
    
    plot <-
      ggplot(data = sample_df, mapping = aes(x = group, y = value)) +
      geom_point() +
      geom_point(
        mapping = aes(y = group_mean), data = group_means_df,
        colour = 'red', size = 3
      ) +
      theme(plot.margin = margin(t = 50, r = 50, b = 50, l = 50))
    ```
    
    # Test
    
    A paragraph.
    
    ## Using the `pdf` graphics device
    
    ```{r}
    #| label: fig-pdf-2
    #| fig-cap: "PDF"
    #| echo: false
    #| dev: pdf
    
    plot
    ```
    
    ```{r, 'fig-pdf-1', echo=F, dev='pdf', fig.cap='PDF (inline chunk opts)'}
    plot
    ```
    
    ## Using the `png` graphics device
    
    ```{r}
    #| label: fig-png-2
    #| fig-cap: "PNG"
    #| echo: false
    #| dev: png
    
    plot
    ```
    
    ```{r, 'fig-png-1', echo=F, dev='png', fig.cap='PNG (inline chunk opts)'}
    plot
    ```
    
    Another paragraph.
    ````
    
    </details>

---

I think the best solution for Quarto would be to introduce (and properly document) an additional chunk option `fig-crop` that corresponds to the [knitr chunk option `fig_crop`](https://bookdown.org/yihui/rmarkdown/pdf-document.html#figure-options-1).

**Comment by cderv** [comment]
Possibly related also to 
https://github.com/quarto-dev/quarto-cli/issues/5734

**Comment by cderv** [comment]
Quarto choose to not have a `fig-crop` option and act by default as `pdf_document(fig_crop = "auto")` in R Markdown. 

Opting out this behavior needs to be done at the **knitr** engine level only without any Quarto format flag. (i.e `crop = NULL` chunk options)

The reason is I believe in Quarto we tend to avoid format option specific to an engine. `fig-crop` would only apply to `engine: knitr` and has no effect to other engine. 

More details below with examples

----

Just want to share here that the correct way to deactivate an option hook in **knitr** for a chunk is to use `NULL` and not `FALSE` as value. 

If an option is `NULL` value, then **knitr** will not run any associated option hooks. If `FALSE`, it will run it and then the option hook will act accordingly to the value. 

The knitr hook `knitr::hook_pdfcrop()` does not react to `crop = FALSE`. So to deactivate it, it needs to be `crop = NULL`

So either using a chunk 

````markdown
````{r}
#| include: false 
knitr::opts_chunk$set(crop = NULL)
```
````

Or using YAML  in Quarto 
````yaml
knitr:
  opts_chunk: 
    crop: null
````

So in current Quarto situation, this works 

````markdown
---
title: "test"
format: pdf
execute: 
  echo: false
knitr:
  opts_chunk: 
    crop: null
---


Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

```{r}
library(ggplot2)
ggplot() + theme(plot.margin = margin(t=2,b=2,unit='cm')) # wide margins to see the effect (or lack thereof)
```

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.


````

![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/d574464c-0645-435f-9ae8-d447570f09be)


Without `crop: null`, indeed Quarto act like default `fig_crop = "auto"` in R Markdown and cropping will be done as long as tools are detected. 

![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/93e1b315-7c35-47f7-bbb5-abdb97cb89ea)


 > I think the best solution for Quarto would be to introduce (and properly document) an additional chunk option fig-crop that corresponds to the [knitr chunk option fig_crop](https://bookdown.org/yihui/rmarkdown/pdf-document.html#figure-options-1).
 
 This would be a solution to add a format option like in **rmarkdown**, however in Quarto we tend to avoid format option specific to an engine. `fig-crop` would only apply to `engine: knitr` and has no effect to other engine. 

So we could either consider that this is the way to opt out

````yaml
knitr:
  opts_chunk: 
    crop: null
````

or make it more clear by having **knitr** support `crop = FALSE` as a way to not crop when set on a chunk.
````yaml
knitr:
  opts_chunk: 
    crop: false
````

**Comment by cderv** [comment]
> make it more clear by having knitr support crop = FALSE as a way to not crop when set on a chunk.

We can do that at the Quarto level in fact, so I went with that and setting `crop: false` as a chunk will allow to opt out

**Comment by salim-b** [comment]
> Just want to share here that the correct way to deactivate an option hook in knitr for a chunk is to use NULL and not FALSE as value.
> 
> If an option is NULL value, then knitr will not run any associated option hooks. If FALSE, it will run it and then the option hook will act accordingly to the value.
> 
> The knitr hook knitr::hook_pdfcrop() does not react to crop = FALSE. So to deactivate it, it needs to be crop = NULL

Thanks for sharing that info! `crop = NULL` is indeed an unintuitive API to disable cropping, so I totally appreciate that

> We can do that at the Quarto level in fact, so I went with that and setting `crop: false` as a chunk will allow to opt out

---

What still remains is that

> I'm a bit confused about the correct name of the cropping chunk option on the knitr side of things: While the *R Markdown Cookbook* [mentions a `crop` chunk option](https://bookdown.org/yihui/rmarkdown-cookbook/crop-plot.html) (same what the [Quarto sources seem to refer to](https://github.com/quarto-dev/quarto-cli/blob/c8fb73c433215926d1b8b18f39e29bc1a215e33d/src/resources/rmd/execute.R#L277-L281)), the *R Markdown: The Definitive Guide* [mentions a `fig_crop` chunk option](https://bookdown.org/yihui/rmarkdown/pdf-document.html#figure-options-1).

Why the different chunk option names? [`rmarkdown::pdf_document()`](https://rmarkdown.rstudio.com/docs/reference/pdf_document.html) has a `fig_crop` parameter (which can apparently be `TRUE`, `FALSE` or `auto`)...

IMHO, `fig_crop` / `fig-crop` are less ambiguous than just `crop` since the cropping only applies to figures/images.

**Comment by cderv** [comment]
> Why the different option names? [rmarkdown::pdf_document()](https://pkgs.rstudio.com/rmarkdown/reference/pdf_document.html) has a fig_crop parameter (which can apparently be TRUE, FALSE or auto)...

`rmarkdown::pdf_document()` is a R Markdown format, which happens to have an option to control the automatic cropping detection. It defaults to `"auto"` (meaning auto detection based on tools), `TRUE` which means to opt-in, but still conditionally on tools, and `FALSE` opt out. 

But `crop` chunk option is also working in **rmarkdown**. As I shared in https://github.com/quarto-dev/quarto-cli/issues/5981#issuecomment-1850349351, `crop = NULL` as chunk option is the way to opt out cropping. Even if `fig_crop` is set in `pdf_document`, `crop = NULL` would opt out of cropping. 


Quarto does behave by default like `"auto"` in R Markdown. We did had a `fig-crop` option because as I explained in my previous, Quarto format configuration are for most of them engine independent. There are some exception (like `code-link` which uses **downlit** so only for **knitr** engine) but I tend to avoid adding too many of them. 

If feels like 
````yaml
knitr:
  opts_chunk: 
    crop: false
````

is ok, especially as `crop: false` is easier to understand (or guess) than `crop: null`. 

If we do a 
````r
format: 
  pdf: 
     fig-crop: 'auto'
````

this would be specific to `engine: knitr` with no effect on `engine: jupyter` and format options are not made to engine specific. 

That is why I kept it as `knitr` chunk option for same purpose.  I could reconsider though at some point if really this is not user-friendly. 

> fig_crop / fig-crop are less ambiguous than just crop since the cropping only applies to figures/images.

`fig-crop` could be an alias chunk option for `crop` if this is really what is confusing. 🤔
