### ISSUE TITLE
Error running filter `main.lua`: attempt to index a boolean value

### ISSUE THREAD

**Issue by rgaiacs** [quarto-dev/quarto-cli#6013]
Consider the minimal working example (`mwe.qmd`) below:

```
---
title: MWE
author: Raniere Silva
---

Awesome.
```

`quarto render mwe.qmd --to markdown` works as expected and produces

```
---
author:
- Raniere Silva
title: MWE
toc-title: Table of contents
---

Awesome.
```

Pandoc's `--metadata` argument can be used to change the YAML file. For example, `quarto render mwe.qmd --to markdown --metadata="toc-title:Foo Bar"` produces

```
---
author:
- Raniere Silva
title: MWE
toc-title: Foo Bar
---

Awesome.
```

I expect that I could use Pandoc's `--metadata` to enable [citable articles](https://quarto.org/docs/authoring/create-citeable-articles.html) but `quarto render mwe.qmd --to markdown --metadata="citation:true"` produces

```
pandoc --metadata citation:true
  to: markdown
  output-file: mwe.md
  standalone: true
  default-image-extension: png
  
metadata
  title: MWE
  author: Raniere Silva
  
Error running filter /opt/quarto/share/filters/main.lua:
/opt/quarto/share/filters/main.lua:1177: attempt to index a boolean value (local 'citationMeta')
stack traceback:
        /opt/quarto/share/filters/main.lua:5261: in field 'Meta'
        /opt/quarto/share/filters/main.lua:79: in function 'run_emulated_filter'
        (...tail calls...)
        /opt/quarto/share/filters/main.lua:74: in function 'run_emulated_filter'
        /opt/quarto/share/filters/main.lua:566: in local 'callback'
        /opt/quarto/share/filters/main.lua:577: in upvalue 'run_emulated_filter_chain'
        /opt/quarto/share/filters/main.lua:610: in function </opt/quarto/share/filters/main.lua:607>
```

I believe this is because

> [--metadata](https://pandoc.org/MANUAL.html#option--metadata) affects the metadata of the underlying document (which is accessible from filters and may be printed in some output formats) and metadata values will be escaped when inserted into the template.

Is possible to extend `appendix-cite-as` to enable both formats and allow it to be enable by `--metadata`?

**Comment by cderv** [comment]
> In this case, the issue is that "true" is read as a scalar/string for the citation key which failed the yaml validation.

I don't think that is what is happening here. It is not a YAML validation issue. 

First, I don't think we validate metadata passed to `--metadata` Pandoc flag. Usually validation error happens before any processing, and is not an error thrown by Lua. 
Second, I believe the syntax `--metadata citation:true` will correctly be parsed as a boolean. 

The issue here is that our Lua filters expect `citation` to be a list, as described in example at https://quarto.org/docs/authoring/create-citeable-articles.html#citation-fields. 
However, `citation: true` in YAML is a special syntax that does get process specifically in our internal Quarto processing. 
It is transformed to an empty list. 
https://github.com/quarto-dev/quarto-cli/blob/bdf8a7a2a1b373b872b00334ab66d2f11148be22/src/command/render/pandoc.ts#L909-L916

But this processing does not apply on `--metadata` pass at command line it seems. Hence the error because `citation: true` is not transformed to a subsetable element for our Lua processing 
https://github.com/quarto-dev/quarto-cli/blob/bdf8a7a2a1b373b872b00334ab66d2f11148be22/src/resources/filters/common/citations.lua#L37-L42

It seems to work with `--metadata-file` so I got puzzled. It seems we are no processing both flag the same. 

https://github.com/quarto-dev/quarto-cli/blob/019ec0b1e6926eeea03c5e72c091da57c2a1c058/src/command/render/flags.ts#L211-L219

https://github.com/quarto-dev/quarto-cli/blob/019ec0b1e6926eeea03c5e72c091da57c2a1c058/src/command/render/flags.ts#L197-L209

We are considering any `--metadata-file` as a Quarto metadata. Whereas for `--metadata` we are separating Quarto metadata and Pandoc metadata. It seems `citation` is not found as Quarto meta and skip the processing.

https://github.com/quarto-dev/quarto-cli/blob/bdf8a7a2a1b373b872b00334ab66d2f11148be22/src/config/metadata.ts#L150-L156

@dragonstyle maybe all this will help. I wonder if : 

* We need to adapt our Lua filter to maybe do the `citation: true` to empty list in the Lua side maybe ? 
* Or consider the `citation` key as part of Quarto metadata to be processed. It seems an oversight that it is not in there. 
* Or both...

**Comment by mcanouil** [comment]
Thanks @cderv for your usual in depth investigation 😉

**Comment by dragonstyle** [comment]
Agreed! I think the correct short term fix is simply to make the filter ensure that the type is expected (fix incoming). There are quite a few metadata values that bypass the `isQuartoMetadata` check (including `citation`) - I think it would be a larger thing to try to dig into all of them and ensure that they are processed appropriately and is likely to cause regressions...

**Comment by mcanouil** [comment]
> There are quite a few metadata values that bypass the isQuartoMetadata check (including citation) - I think it would be a larger thing to try to dig into all of them and ensure that they are processed appropriately and is likely to cause regressions...

Maybe worth to open a dedicated issue? 🤔
