### ISSUE TITLE
quarto-required argument is ignored

### ISSUE THREAD

**Issue by EmilHvitfeldt** [quarto-dev/quarto-cli#6071]
### Bug description

Using the `quarto-required` argument as described here: https://quarto.org/docs/reference/formats/html.html#format-options doesn't appear to work.

### Steps to reproduce

````qmd
---
format:
  html:
    quarto-required: ">= 1000.4.375"
---

## Quarto

````

### Expected behavior

I would expect an error to be thrown is the version wasn't satisfied. 

### Actual behavior

Argument is ignored.

### Your environment

- IDE: Version 2023.05.0-daily+206 (2023.05.0-daily+206)
- OS: MacOS Ventura 13.4

### Quarto check output

```bash
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.2: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.176
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.7 (Conda)
      Path: /Users/emilhvitfeldt/miniforge3/bin/python
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with conda install jupyter

[✓] Checking R installation...........OK
      Version: 4.2.1
      Path: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources
      LibPaths:
        - /Users/emilhvitfeldt/Library/R/arm64/4.2/library
        - /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library
      knitr: 1.43
      rmarkdown: 2.22

[✓] Checking Knitr engine render......OK-
```

**Comment by mcanouil** [comment]
Indeed it has no effect ...
To note, this seems independent of the format.

**Comment by cderv** [comment]
`quarto-required` has been added in https://github.com/quarto-dev/quarto-cli/pull/2322 
FWIW it was supposed to replace `quarto-version` field, but for now `quarto-required` it is only used in extensions. 

`quarto-version` is still valid though because is was used in #2322 (wrongly?), even if it has replaced by  `quarto-required` in the documentation

So this is what is working currently
````markdown
---
format:
  html:
    quarto-version: ">= 1000.4.375"
---

## Quarto

````

@cscheid was the aim of #2322 to replace `quarto-version` by `quarto-required` entirely ? Like breaking change for anyone using `quarto-version` already ?
