### ISSUE TITLE
`QUARTO_R` does not work in `_environment` file

### ISSUE THREAD

**Issue by mcanouil** [quarto-dev/quarto-cli#6162]
### Bug description

From <https://quarto.org/docs/projects/environment.html>, it's possible to set environment variable in a `_environment` file.
Unfortunately, it seems `_environment` is read too late thus has no effect.

### Steps to reproduce

```sh
quarto create project website mywebsite
quarto check

# Does not work
echo QUARTO_PYTHON=/opt/homebrew/bin/python3.10 > _environment
quarto check

# Does work
export QUARTO_PYTHON=/opt/homebrew/bin/python3.10
quarto check
```

### Expected behavior

```sh
echo QUARTO_PYTHON=/opt/homebrew/bin/python3.10 > _environment
quarto check
#> 
#> [✓] Checking versions of quarto binary dependencies...
#>       Pandoc version 3.1.2: OK
#>       Dart Sass version 1.55.0: OK
#>       Deno version 1.33.2: OK
#> [✓] Checking versions of quarto dependencies......OK
#> [✓] Checking Quarto installation......OK
#>       Version: 99.9.9
#>       Path: /Users/mcanouil/Projects/quarto/quarto-cli/package/dist/bin
#> 
#> [✓] Checking basic markdown render....OK
#> 
#> [✓] Checking Python 3 installation....OK
#>       Version: 3.10.12
#>       Path: /opt/homebrew/opt/python@3.10/bin/python3.10
#>       Jupyter: (None)
#> 
#>       Jupyter is not available in this Python installation.
#>       Install with python3 -m pip install jupyter
#> 
#> (/) Checking R installation...........ℹ R version 4.3.1 (2023-06-16)
#> ! Config '~/.Rprofile' was loaded!
#> [✓] Checking R installation...........OK
#>       Version: 4.3.1
#>       Path: /Library/Frameworks/R.framework/Resources
#>       LibPaths:
#>         - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
#>       knitr: 1.43
#>       rmarkdown: 2.23
#> 
#> [✓] Checking Knitr engine render......OK
#> 
#> 
```

### Actual behavior

```sh
echo QUARTO_PYTHON=/opt/homebrew/bin/python3.10 > _environment
quarto check
#> 
#> [✓] Checking versions of quarto binary dependencies...
#>       Pandoc version 3.1.2: OK
#>       Dart Sass version 1.55.0: OK
#>       Deno version 1.33.2: OK
#> [✓] Checking versions of quarto dependencies......OK
#> [✓] Checking Quarto installation......OK
#>       Version: 99.9.9
#>       Path: /Users/mcanouil/Projects/quarto/quarto-cli/package/dist/bin
#> 
#> [✓] Checking basic markdown render....OK
#> 
#> [✓] Checking Python 3 installation....OK
#>       Version: 3.11.4
#>       Path: /opt/homebrew/opt/python@3.11/bin/python3.11
#>       Jupyter: 5.3.1
#>       Kernels: julia-1.9
#> 
#>       NOTE: No Jupyter kernel for Python found
#> 
#> (/) Checking R installation...........ℹ R version 4.3.1 (2023-06-16)
#> ! Config '~/.Rprofile' was loaded!
#> [✓] Checking R installation...........OK
#>       Version: 4.3.1
#>       Path: /Library/Frameworks/R.framework/Resources
#>       LibPaths:
#>         - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
#>       knitr: 1.43
#>       rmarkdown: 2.23
#> 
#> [✓] Checking Knitr engine render......OK
#> 
#>
```

### Your environment

- IDE: VSCode latest
- OS: macOS venture (arm64)

**Comment by cderv** [comment]
@mcanouil It is possible that when running `quarto check`, the code path for `_environment` file is not run. (project context settings)

Do you see the issue with `quarto render` ? If you set `_environment` is your project, is the right Python version used ? 

Juts curious if you tried that already and the issue is with both `quarto render` and `quarto check`

**Comment by mcanouil** [comment]
````sh
echo -e '---\nformat: html\n---\n\n```{python}\nimport sys\nprint(sys.version)\n```\n\n' > index.qmd
quarto check # Python 3.11.4 -> default
quarto render index.qmd # Python 3.11.4 -> default

echo "QUARTO_PYTHON=/opt/homebrew/bin/python3.10" > _environment
quarto check # Python 3.11.4 -> unexpected
quarto render index.qmd # Python 3.11.4 -> unexpected

export QUARTO_PYTHON=/opt/homebrew/bin/python3.10
quarto check # Python 3.10.12 -> expected
quarto render index.qmd # status unknown "Invalid jupyter YAML metadata found in file (must be string or object)"
```

<img width="1624" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/48f52f83-64ba-4a6b-b65c-a202930adb55">

**Comment by cderv** [comment]
FWIW I cannot reproduce this 
````
echo "QUARTO_PYTHON=/opt/homebrew/bin/python3.9" > _environment
quarto check jupyter # Python 3.11.4 -> unexpected
quarto render index.qmd # Python 3.11.4 -> unexpected
````

For me 
* `quarto check` doesn't pick the right python from `_environment` (but because currently `quarto check` does not load the env vars from that file - From what I can see from our code as no project context is loaded for a `quarto check`

* `quarto render` does pick the python version I have set in the `_environment` file. From our code, `quarto render` does load the project context, and so the env vars are read and set by `Deno.env.set()`. This works for me. 


From all the issue I have seen, the Python configuration is not that easy because it involves two things: 

* A python version which has a Jupyter available
* How Jupyter kernels are configured - meaning which python version they use. 
 
It happens that you can configure a single Jupyter to use different python environment.(https://ipython.readthedocs.io/en/stable/install/kernel_install.html#kernels-for-different-environments). This means that a 3.9.4 Python installation could have a Jupyter available but its kernel would call an environment with another python environment defined (like 3.11.4). 

One thing I have checked in the path is how you kernel spec are currently configured. 

* Be sure to use the jupyter from the version you want 
* Call `jupyter kernelspec list` 
* Check the default kernel to see its configuration. 

I remember some issues were some jupyter kernal were configured to use a conda env... Really unexpected by the user and us 😅

**Comment by cderv** [comment]
I still can't reproduce this on my side (Windows for now) 

`quarto check knitr` gives my default R version (4.2.2 here) because as we said `quarto check` is not project aware so no _environment. 

However doing 
```` 
> bat .\_environment
───────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: .\_environment
───────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ QUARTO_R="C:\Program Files\R\R-4.3.0\bin\"
───────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
````

If I `quarto render` a document with this chunk 
```` markdown
```{r}
normalizePath(R.home())
```
````

I get in output `C:\\Program Files\\R\\R-4.3.0` which is the `_environment`  version. If I remove this file, then re-render, I get `C:\\Program Files\\R\\R-4.2.2` as value for `R.home()`

So working ok on my side, per the code (as `quarto render` is project aware and set `QUARTO_R` with `Deno.env.set()` 

What I don't understand is your 3rd example above:

3. you set `QUARTO_R=/opt/R/4.2.3/bin` in `_environment` and you get `R 4.2.3` => it seems expected ?  Some typos ? 

I am sorry I do not manage to reproduce your setup. I'll try also on Linux in case there is a OS difference. 

But from the code base, I can confirm that `quarto render` will do a project context loading which will set the env vars according to `_environment` and this is done before running R where `QUARTO_R` is checked. 


> Contrary to QUARTO_PYTHON, setting things like export QUARTO_R=/something/obviously/wrong raise absolutely no warnings or errors which in my opinion is bad, as QUARTO_R is set by user, he/she should be informed he/she did something wrong.

As explained in Slack discussion, with Python if we have a wrong Python set in `QUARTO_PYTHON`, then there still some fallback, one of them being the Julia Conda version if available. (https://github.com/quarto-dev/quarto-cli/pull/1931)

With R it is the same, there are fallback - `QUARTO_R` is the first things checked and it needs to be a valid path on disk (it needs to exist)
https://github.com/quarto-dev/quarto-cli/blob/a5a81f5d2afa2664f8748ac9ae5e70b4a0a2baf7/src/core/resources.ts#L78-L80

Otherwise it is skipped and the rest is search (`R_HOME` env var, `PATH` env var and then on windows only Registry, then `PROGRAMFILES` env var). 


> Finally, in my opinion, quarto check should report what's used by quarto render, meaning _environment and project context should be read by it.

Yes I think we agree on this. It would be good for `quarto check` run in a project to return values as it will be run by the project.

**Comment by mcanouil** [comment]
I'll make a Docker container/file to figure this out as I don't have multiple R on my Mac and there are possibly some setup issue in my work virtual machine.
(It's really hard to pinpoint what's wrong with Quarto being completely silent on what it is doing to find the tools)

**Comment by cderv** [comment]
> (It's really hard to pinpoint what's wrong with Quarto being completely silent on what it is doing to find the tools)

Usually I enter debug mode in VSCODE to understand step by step what this is doing. I don't think we have `debug()` code in this part of the code but we could add some. This is usually how you add more verbosity to what Quarto is doing internally 
https://quarto.org/docs/troubleshooting/#verbose-mode

**Comment by cderv** [comment]
> I don't think we have debug() code in this part of the code but we could add some. This is usually how you add more verbosity to what Quarto is doing internally
[quarto.org/docs/troubleshooting/#verbose-mode](https://quarto.org/docs/troubleshooting/#verbose-mode)

You can try #6178 branch to have some DEBUG call that will print what is happening.

**Comment by mcanouil** [comment]
Perfect, that will definitely help.

**Comment by mcanouil** [comment]
Here is a repository with a devcontainer setup which exhibits the issue.

- https://github.com/mcanouil/quarto-cli-issue6162

I did no try yet the PR.

**Comment by cderv** [comment]
> It appears I can't compile Quarto from source inside the container due to possibly some issue in Typst install/download script.

About that the issue is 
```
tar (child): xz: Cannot exec: No such file or directory
```

This just means you are missing the `xz` program required to uncompress `tar.xz` file. 
https://linuxhint.com/extract-tar-xz-files-linux/

If you install it, then it should solve it.

**Comment by mcanouil** [comment]
> This just means you are missing the `xz` program required to uncompress `tar.xz` file. 
> 
> https://linuxhint.com/extract-tar-xz-files-linux/
> 
> 
> 
> If you install it, then it should solve it. 

Oh, so it must not be something usual in dev if it is not part of the base image I used. 🤷‍♂️
I'll add this in my Quarto install script.

**Comment by cderv** [comment]
@mcanouil even with you devcontainer environment I cannot reproduce. 

If I set `QUARTO_R` in `_environment`, set it is correctly used by `quarto render` 

Document you have 
````markdown
---
title: 4.3.1
format: html
---

```{r}
R.version.string
```
````

Then
```bash
rig default 4.3.1
```
after a `quarto render index.qmd` I have
```
[1] "R version 4.3.1 (2023-06-16)"
```

and after this 
```
echo "QUARTO_R=/opt/R/4.2.3/bin" > _environment
```
I get 
````
[1] "R version 4.2.3 (2023-03-15)"
````

So I stay by my comment above 

> But from the code base, I can confirm that quarto render will do a project context loading which will set the env vars according to _environment and this is done before running R where QUARTO_R is checked.

**Comment by mcanouil** [comment]
The only remaining difference I see is the arch which was arm64 when built the repo.

**Comment by mcanouil** [comment]
I finally figured out (thanks to @cderv who helped narrowing it down) the issue which was mostly about structure (kind of nested quarto projects).
