### ISSUE TITLE
Bibliography field in YAML is no longer able to evaluate inline `r expression`

### ISSUE THREAD

**Issue by dmi3kno** [quarto-dev/quarto-cli#6189]
### Bug description

Quarto no longer evaluates inline expressions in the `bibliography` field in YAML (unlike the same behavior in RMD).  I am pretty sure it used to work in the previous version of Quarto

I was relying on evaluating the bibliography field using `rbbt` package (which parses the source file and writes back the .bib file before reading it again). I would love to keep this field evaluating the inline code, please. I understand that you may want to make YAML platform independent. What is the reason that led you to disable code evaluation in this field?

### Steps to reproduce

Content of file `untitled.qmd`

```qmd
---
title: "Untitled"
bibliography: "`r paste0('untitled-', 1, '.bib')`"
format: html
---

## Quarto
To learn more about Expert Knowledge Elicitation see [@ohagan2019ExpertKnowledgeElicitation]
```

### Expected behavior

![Screenshot from 2023-07-12 15-13-41](https://github.com/quarto-dev/quarto-cli/assets/13419011/2b276f0c-164a-4ca8-ac5f-e20d4e4dab7f)

### Actual behavior

Produces an error:
```r
># File r paste0('untitled-', 1, '.bib') not found in resource path
```

When the same file is renamed to `untitled.rmd` the document is rendering just fine. 

### Your environment

- IDE: Rstudio 2021.06.1 Build 524
- OS: Ubuntu 22.04 LTS

<details>

<summary>sessionInfo()</summary>

```r
R version 4.3.0 (2023-04-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 22.04.2 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3 
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.20.so;  LAPACK version 3.10.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=sv_SE.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=sv_SE.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=sv_SE.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=sv_SE.UTF-8 LC_IDENTIFICATION=C       

time zone: Europe/Stockholm
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

loaded via a namespace (and not attached):
 [1] vctrs_0.6.3     httr_1.4.6      cli_3.6.1       knitr_1.43     
 [5] rlang_1.1.1     xfun_0.39       stringi_1.7.12  png_0.1-8      
 [9] jsonlite_1.8.7  glue_1.6.2      clipr_0.8.0     rprojroot_2.0.3
[13] htmltools_0.5.5 hms_1.1.3       fansi_1.0.4     rmarkdown_2.23 
[17] grid_4.3.0      evaluate_0.21   tibble_3.2.1    tzdb_0.3.0     
[21] fastmap_1.1.1   yaml_2.3.7      lifecycle_1.0.3 stringr_1.5.0  
[25] compiler_4.3.0  fs_1.6.2        pkgconfig_2.0.3 rstudioapi_0.14
[29] digest_0.6.32   rbbt_0.0.0.9000 R6_2.5.1        readr_2.1.4    
[33] utf8_1.2.3      curl_5.0.1      pillar_1.9.0    magrittr_2.0.3 
[37] withr_2.5.0     tools_4.3.0     details_0.3.0   xml2_1.3.4     
[41] desc_1.4.2     

```
</details>

### Quarto check output

```bash
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.433
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.6
      Path: /usr/bin/python3
      Jupyter: 5.3.1
      Kernels: conda-env-r-reticulate-py, julia-1.8, python3

[✓] Checking Jupyter engine render....OK
```

**Comment by cscheid** [comment]
> I would love to keep this field evaluating the inline code, please. I understand that you may want to make YAML platform independent. What is the reason that led you to disable code evaluation in this field?

Thanks for the report. To be clear, inline eval expressions has never been officially supported in `quarto`, and we don't consider it a bug.

We try to support some of it in a best-effort way from RMarkdown, but this is not syntax that we want to support in the long run for a number of reasons. It makes yaml validation impossible, like you mentioned, but it also makes it generally impossible to do any static analysis of the code, which means we have no way to implement features in the future like parallelization and linting.

If you must use this kind of feature, I instead recommend you take advantage of project pre-render scripts, and use arbitrary R or Python scripts to write your .qmd file.

**Comment by cderv** [comment]
Edit: I saw @cscheid while posting this. I figured I'll post anyway 

With last 1.4 pre-release and with latest 1.3 version  I can't reproduce ....

I don't have any issue with it with this reproducible example 
````markdown
---
title: "Untitled"
bibliography: "`r paste0('ref-', 1, '.bib')`"
format: html
---

```{r, echo = FALSE}
knitr::write_bib("knitr", paste0('ref-', 1, '.bib'))
```


## Quarto

To learn more about knitr see [@R-knitr]
````

Your example is lacking the bib file. But it is also lacking the knitr engine. The **knitr** engine is not run by default unless there is a  R code. Try add in your YAML 
````
engine: knitr
````

I believe this will still work as in previous version. The change that happen in 1.3 is that `engine: knitr` is used by default only in document with a R chunk. 

Though this still work in the context of previous @cscheid answer. And by working I mean there is no error thrown and document seems to be rendered ok. 

However in the console logging I can see 
````
bibliography:
    - '`r paste0(''ref-'', 1, ''.bib'')`'
````
which illustrate that something is not really expected. 

Using inline R knitr code inside YAML header options is not something really supported in Quarto because the fields will be processed by Quarto before any rendering by **knitr** happens. So the field is not evaluated. For example, `bibliography` will be probably retrieved to know which resources are used by the document. 

I don't know how **rbbt** is working, but with Quarto you could use pre-render script for your project to generate the bib file before rendering. Those file would have fixed name. 

Or you could try probably use [variables](https://quarto.org/docs/authoring/variables.html#var) by creating a `_variables.yml` dynamically. But probably same issue with static analysis and YAML validation in the long run...

**Comment by dmi3kno** [comment]
> The change that happened in 1.3 is that engine: knitr is used by default only in document with a R chunk. And no more if only an inline R code.

This explains it. Thank you! You are a wizard, @cderv ! I will try and find a more long-term solution. For now, I needed this feature to test improvements in `rbbt`. Thanks so much for the tips!

**Comment by cderv** [comment]
You're welcome ! 

> I was relying on evaluating the bibliography field using rbbt package (which parses the source file and writes back the .bib file before reading it again)

I am curious on how you are using this. Please do not hesitate to ping me on **rbbt** side. I understand there is connection to Zotero and this writes a bib file. So for broader context in case you don't know about it, know that there are new feature in visual mode for VSCODE and RStudio IDE that would be relevant feature-wise 

* https://quarto.org/docs/visual-editor/vscode/#zotero-citations
* https://quarto.org/docs/visual-editor/technical.html#citations-from-zotero

This allows to read from Zotero and add to bib file, all from within the IDE you use. Kind of similar to an addin. But again, don't know **rbbt** so it may be completely out of scope.

**Comment by dmi3kno** [comment]
Pinged you on `rbbt` closed issue to illustrate the usecase.

**Comment by bwiernik** [comment]
@dmi3kno can you give a link to the rbbt issue you mention? I can't seem to find it

**Comment by cderv** [comment]
@bwiernik this one : https://github.com/paleolimbot/rbbt/issues/12
