### ISSUE TITLE
Quarto should warn that `QUARTO_R`/`QUARTO_PYTHON` are wrong then use a fallback method

### ISSUE THREAD

**Issue by mcanouil** [quarto-dev/quarto-cli#6207]
Currently, if a user set a bad value to `QUARTO_PYTHON`, a warning is displayed then it continues if it can by looking at alternatives.
But for `QUARTO_R`, there is no warnings and no messages that Quarto is going to do something else.

As an enhancement, when `QUARTO_R`/`QUARTO_PYTHON` are set, I believe Quarto should tell the user that the values (set by the user) are wrong and that it is going to try something else[^1].
Otherwise, say nothing, as Quarto is using what the user set or the default.

[^1]: related to #6206 and #6162

**Comment by cderv** [comment]
For context, we are just talking about this specific function which check `QUARTO_PYTHON` existence
https://github.com/quarto-dev/quarto-cli/blob/4ef2843f5fc14722edabe9db4903ce0a9b02780e/src/core/jupyter/capabilities.ts#L118-L152

and warn otherwise. 

This function is then use in other place like `jupyterCapabilities()`

On the contratry, R does not warn when there is no existence of the path sets in `QUARTO_R`
https://github.com/quarto-dev/quarto-cli/blob/4ef2843f5fc14722edabe9db4903ce0a9b02780e/src/core/resources.ts#L84-L92
