### ISSUE TITLE
 having books under a blog website

### ISSUE THREAD

**Issue by candemircan** [quarto-dev/quarto-cli#638]
Hello hello,

I am trying to use the blog template as a dashboard for a collection of Quarto books. However, if I type `posts/*/index.qmd` under contents, each blog post only displays the index page for the given book. If I render the books and type `posts/*/_book/index.html`, the blog does not display any of the books. I tried to pass the yaml files of the books under contents as well, which did not work.  Am I missing a feature to make this possible, or is this not a possibility yet?

Thanks :)

**Comment by jjallaire** [comment]
It might be tricky to get all of the listing patterns right here. For "subprojects" you also need to arrange to not have the parent project render the child project documents. You might consider doing something like this:

1) Put all of your books in a `books/` directory, then provide this render directive:

```yaml
project:
  type: website
  render:
    - "**/*.qmd"
    - "!books/"
```

For the index, you might want to just create a YAML file that you hand edit rather than trying to glob up all the books. @dragonstyle I didn't see the YAML feature of listings documented anywhere on the site -- is there a pointer for docs on that? Also, if you do have an idea how this would work w/o YAML let us know (I'm worried that its too tricky to write the glob expression to collect the books, esp. because their most important metadata will be `_quarto.yml` rather than `index.qmd`)

**Comment by dragonstyle** [comment]
I can't think of a way that this would work using the raw files themselves, currently, since currently listings don't differentiate between the current project and subprojects (which means that each of the chapter `qmd` files would likely appear in the listing independently rather than as one merged book.

I think the metadata idea is a good approach for what we have now. It is documented here:

https://quarto.org/docs/websites/website-listings-custom.html#metadata-listings

This won't be as dynamic since you need to define the list of books in yaml, but it will give you complete control of the metadata and presentation and should work exactly with what we have now (keeping the project / render directive that @jjallaire  noted above).

The examples in the documentation show using a custom template to also control the appearance of the listing, but you can just use the metadata with the built in layouts - just be sure that the metadata has fields like (title, subtitle, description, path, and so on):

```
listing:
  contents:
     - title: My First Book
       description: |
        This is my first book. I hope that you enjoy it!
       date: 1/1/2022
       path: books/book.pdf
```

HTH!

**Comment by cderv** [comment]
FWIW the r-manuals website we have put in the gallery is a website which includes book: https://rstudio.github.io/r-manuals/
Source is here: https://github.com/rstudio/r-manuals

We went a bit meta on this to make this works but everything is automated
* Each book is rendered using Quarto on its own
* The output folder for each book is put in the main website (only the resulting HTML and resources)
* Quarto website project configuration is updated accordingly so that we can share a common layout between books and website
* Quarto website is rendered. 

Not exactly the same use case, but I believe it is one example of how something like this could be done. 

Hope it helps too :)
