### ISSUE TITLE
Applying Templates in Custom Lua Writers

### ISSUE THREAD

**Issue by mculbert** [quarto-dev/quarto-cli#6462]
### Bug description

As far as I can tell, Pandoc expects custom writers to apply the template indicated in the options supplied to the Writer() function. From the Quarto side, the Lua writer provided for a custom format extension is treated as a filter, called from the hook created by [wrapped_writer()](https://github.com/quarto-dev/quarto-cli/blob/96ff7001080c915bf89186ea237d35da74672415/src/resources/filters/ast/wrappedwriter.lua#L6). The writer actually supplied to Pandoc is [customwriter.lua](https://github.com/quarto-dev/quarto-cli/blob/96ff7001080c915bf89186ea237d35da74672415/src/resources/filters/customwriter/customwriter.lua#L6), which simply dumps the string constructed by all the filters (including the extension's Lua writer), ignoring the template option. But, wrapped_writer() doesn't pass along any options to the extension's Writer() call. So, any template is completely ignored.

How should format extensions using a custom Lua writer apply templates to the rendered documents?

### Steps to reproduce

[Minimal example](https://gist.github.com/mculbert/b07a0411001449dd01798f27768fb354)

After moving the extension files to `_extensions/tstluawriter`,
```
quarto render test.qmd --verbose
```
Shows that pandoc is aware of the template file, but produces `test.txt` without the template.

```
quarto pandoc test.qmd --from markdown --to _extensions/tstluawriter/tstluawriter.lua --template _extensions/tstluawriter/template.txt -o pandoc-test.txt
```
Produces `pandoc-test.txt` with the template.

### Your environment

Quarto version 1.3.450

**Comment by cscheid** [comment]
I believe this isn't a bug - custom writers need to use the Lua API to produce the entirety of the output, and that includes using Pandoc's Lua functions for compiling and applying templates. https://pandoc.org/lua-filters.html#module-pandoc.template.

**Comment by mculbert** [comment]
How is the Quarto-wrapped custom writer supposed to obtain the configuration information that indicates which template should be applied? Quarto does not pass template information to the wrapped custom writer (as Pandoc does). Is it intended that the Lua writer should be hard coded with the template (and that a separate Lua writer is required for each templated)?

**Comment by cscheid** [comment]
> 
How is the Quarto-wrapped custom writer supposed to obtain the configuration information that indicates which template should be applied?

> Quarto does not pass template information to the wrapped custom writer (as Pandoc does).

I'm not sure I understand. You can still access input document metadata, so you should still be able to pass necessary information. By "template information", do you mean the specific `template` metadata key? I haven't checked, but I believe your claim. It doesn't stop you from using a _different_ metadata key, though, and that might be advised anyway since a custom format is very much on "deep waters" territory; there's not a lot of overlap between that and the rest of pandoc anyway.

> Is it intended that the Lua writer should be hard coded with the template (and that a separate Lua writer is required for each templated)?

I'm totally confused by "should be hard coded with the template", and I'm now wondering if we mean different things by the word "template". I meant "Pandoc templates". Since a Lua writer is just Lua code that completely controls output generation, your Lua code would have to include logic to use different Pandoc templates.
