### ISSUE TITLE
Chinese Characters Missing in PDF Export

### ISSUE THREAD

**Issue by krishaamer** [quarto-dev/quarto-cli#6507]
### Bug description

Chinese Characters as well as some other characters are missing in the rendered pdf. For example 漢字 would leave a blank space.

### Your environment

Quarto 1.3.296

**Comment by cscheid** [comment]
In PDF you need to make sure that your font has the right Unicode code points. There's unfortunately not much we can do on our side, as checking every font usage against every code point is not practical. I'm pretty sure that's what's happening here, since it's very similar to the reports of PDF rendering and greek letters. I'm going to go ahead and close this one, but feel free to reopen if you think I made a mistake.

**Comment by NoahWanax** [comment]
I encountered the same issue.
But the output in HTML and Docs formats is normal.

**Comment by mcanouil** [comment]
@NoahWanax There is nothing we can do with the information you gave us.
Please open a GitHub Discussion and provide sufficient information for anyone to help. Thank you!
See <https://quarto.org/bug-reports.html>.
