### ISSUE TITLE
titlesec render error: compilation failed- error Argument of \paragraph has an extra }.

### ISSUE THREAD

**Issue by csgroen** [quarto-dev/quarto-cli#6598]
### Bug description

Knitting a qmd document in RStudio including the `titlesec` package yields an error:

Notably: this worked perfectly as of two months ago when I last updated this document in June.

### Steps to reproduce

```
---
title: ""
format: 
    pdf:
        papersize: A4
        fontsize: 11pt
        include-in-header:
            - text: |
                \pagenumbering{roman}
                \defaultfontfeatures{Scale=MatchLowercase}
                \newcommand*\NewPage{\newpage\null\thispagestyle{empty}\newpage}
                \usepackage{titlesec}
                \titleformat*{\section}{\fontsize{14}{17}\selectfont}
                \titleformat*{\subsection}{\fontsize{13}{15}\selectfont}
                \titleformat*{\subsubsection}{\fontsize{12}{14}\selectfont}
---
# Minimal example

This is a minimal example

\newpage

Paragraph #2
```

### Expected behavior

Render the PDF

### Actual behavior

Yields error:

```
compilation failed- error
Argument of \paragraph has an extra }.
<inserted text> 
                \par 
l.1641 \ttl@extract\paragraph
```
                    

### Your environment

- IDE: RStudio 2023.06.0 (421)
- Ubuntu 22.04

### Quarto check output

```
[✓] Checking Quarto installation......OK
      Version: 0.9.327
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.8.10 (Conda)
      Path: /home/clarice/miniconda3/bin/python
      Jupyter: 5.3.0
      Kernels: spatial, python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /usr/lib64/R
      LibPaths:
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      rmarkdown: 2.23

[✓] Checking Knitr engine render......OK
```

**Comment by mcanouil** [comment]
There is a missing ending `}` in your example.

**Comment by csgroen** [comment]
I edited the example, same error

**Comment by cscheid** [comment]
>       Version: 0.9.327

This is a very old version of quarto, we unfortunately cannot support them this far back. Can you try with [quarto 1.3](https://quarto.org/docs/get-started/) and report back?

**Comment by csgroen** [comment]
Updated quarto. I still get the same error.

**Comment by mcanouil** [comment]
This issue is from Pandoc template, see <https://duckduckgo.com/?q=titlesec+pandoc>

**Comment by cderv** [comment]
To add to existing information, the part of the template shown above is feature in Pandoc that we activate in Quarto by default and it could conflict when using its own process for sections (like `titlesec`). 

When `block-headings` feature is activated, Pandoc is doing a specific processing for paragraph as show above. With quarto, it can be opt-out using `block-headings: false` in YAML. This variable is listed in https://quarto.org/docs/reference/formats/pdf.html#layout with same documentation as in Pandoc https://pandoc.org/MANUAL.html#layout
We just activate it by default for PDF
https://github.com/quarto-dev/quarto-cli/blob/0147b505091ffafeb752fe95a06a829236252488/src/format/pdf/format-pdf.ts#L136-L138

So instead of twealing partials I would set opt-out

```yaml
format:
  pdf: 
    block-headings: false
```

Then `titlesec` should works (if the header-includes is correct titlesec comment).

From doc, it seems that we could have used [Koma Script](https://ctan.org/pkg/koma-script) to tweak titles. Koma script is used by default in quarto pdf, so you could also use that instead of `titlesec` and maybe there will be no conflict with `block-headings` feature. 

Hope it helps

**Comment by mcanouil** [comment]
Additionally, `titlesec` is known to NOT be compatible with KOMA-script.

**Comment by cderv** [comment]
Then it means `documentclass` needs to be adapted with a Quarto PDF document when one is using trying to use `titlesec`. 
Probably using Koma Script feature to tweaks headings is the better way it seems. 

Thanks for sharing this @mcanouil ! For reference, links to titlesec repo with this info: https://github.com/jbezos/titlesec/issues/22

**Comment by csgroen** [comment]
Thanks. Indeed, switching from titlesec to KOMA-script completely fixed the issue.
