### ISSUE TITLE
The categories tab under the title is unclickable in the lates release.

### ISSUE THREAD

**Issue by shalom-lab** [quarto-dev/quarto-cli#671]

**Comment by dragonstyle** [comment]
I just double check against our latest build and I'm having trouble reproducing this. Would you mind sharing an example or website I could take a look at to see the behavior? If you have a deployed or publicly viewable website that you're seeing this, it would be particularly helpful as my guess is that we've introduced some javascript error that is preventing the links from being activated on the categories...

**Comment by shalom-lab** [comment]
I may have found the answer. I forget to include the "categories" in the fields of listing page.The categories below the title in the article page is unclickable,right?

**Comment by shalom-lab** [comment]
Yeah,the categories below the title in the article page is unclickable in my local browser. But it work well in server. [Here ](https://blog-7gi7tsfg85e1922f-1257749604.ap-shanghai.app.tcloudbase.com)is my blog. Thanks for careating so powerful tool.

**Comment by dragonstyle** [comment]
Since it seems to be working when deployed but not locally, could you see if there are javascript errors in your console when you see that the categories aren't working? 

Like so: https://developer.chrome.com/docs/devtools/open/#console

Any help appreciated!

**Comment by shalom-lab** [comment]
I thought it's a problem associated with file path. The thumbnail image(banner.png) in listing page also fail to load in my local browser.
![image](https://user-images.githubusercontent.com/49271035/163998261-a6a5e730-232c-44fb-b20e-41c2c202b72e.png)
![image](https://user-images.githubusercontent.com/49271035/163999012-cb4693d5-15c5-450a-b351-4df22d954d19.png)
![image](https://user-images.githubusercontent.com/49271035/163998760-43d84826-f6b2-43bf-91cd-500a234b6482.png)
![image](https://user-images.githubusercontent.com/49271035/163999128-d1c86869-fd32-48e9-95d6-a449faada03e.png)

**Comment by dragonstyle** [comment]
Ah, interesting. Are you using `quarto preview` to view your files? This actually will run a http server that can fulfill requests for additional files (and will use file watching to automatically reload the page whenever you re-render it). In this case, it looks like we're using `fetch` to try to read some additional JSON to configure the category links, but since the file is being view using the local file system, the fetch fails (there is no http server to return the file). Could you try using `quarto preview` and see if this resolves it for you?
