### ISSUE TITLE
Problematic execution of inline expressions when using Jupyter kernels

### ISSUE THREAD

**Issue by psads-git** [quarto-dev/quarto-cli#6710]
### Bug description

Consider the following `quarto` document and the fact that I am using `quarto pre-release — v1.4.346`:

<pre>
---
title: "My title"
execute:
  cache: true
author: Author
abstract: |
  Some text
jupyter: python3
date: last-modified
date-format: "YYYY"
format: 
  pdf:
   template-partials:
    - before-body.tex
    - _titlepage.tex
   toc: true
   number-sections: true
   fontsize: 12 pt
   papersize: A4
   fig-pos: 'H'
   geometry: "left=2.54cm,right=2.54cm,top=2.54cm,bottom=2.54cm"
   classoption: table
   include-in-header:
     text: |
       \usepackage{changepage} 

---

```{python}
# |echo: false

import pandas as pd
import numpy as np
```

{{< pagebreak >}}

```{python}
#|echo: false
x = 2
```

The answer is `{python} x`.
</pre>

The `_titlepage.tex` file is:

```
\vspace*{4.5cm}

\begin{center}
\LARGE{\itshape MY TITLE}

\vspace{1.5cm}
\large{BY}

\vspace{1.5cm}
\large{\bfseries \uppercase{$author$}}
\end{center}

\vspace{1.5cm}

\begin{adjustwidth}{1.5cm}{1.5cm}
\noindent {\itshape $abstract$}
\end{adjustwidth}

\vspace{7cm}

\noindent \makebox[\linewidth]{$date$}
```

The `before-body.tex` file is:

```
$if(has-frontmatter)$
\begin{frontmatter}
\begin{titlepage}
$_titlepage.tex()$
\end{titlepage}
\end{frontmatter}
$else$
\begin{titlepage}
$_titlepage.tex()$
\end{titlepage}
$endif$

```

### Expected behavior

It should output

`The answer is 2.
`

### Actual behavior

But the actual output is

`The answer is {python} x.`

**Comment by cderv** [comment]
I can't reproduce with latest Quarto. 

Is this happening also if you render to 
```
format: 
   html: default
```

this would make the example simpler, if PDF and LaTeX are not involved.  

Also I see you are using `cache: true` and I don't have your cache when running the example. 

Could you try setting `cache: false` and re-render ? I think this would work in that case.

**Comment by psads-git** [comment]
Thanks, Christophe, for your answer.

In fact, but setting

`cache: false
`
fixes the problem.

**Comment by cderv** [comment]
Following the last idea, the reproducible example is 

* Run this document with `cache: true` enable
````markdown
---
title: "My title"
execute:
  cache: true
author: Author
jupyter: python3
format: 
  html: default
---

```{python}
#|echo: false
x = 2
```

````
* Then add this line at the end of the document and re-render. 
```
The answer is `{python} x`.
```

The document indeed includes the unevaluated inline code.

* Setting `cache: false` and re-rendering will evaluate the inline
* Setting back `cache: true` will reshow the unevaluated string 


@jjallaire is this a known limitation for our implementation (I don't see anything in our doc regarding cache) or is this an issue we should fix right now ?

**Comment by psads-git** [comment]
The example, Christophe, you suggested with `HTML` as output format also exhibits the reported issue, after the second rendering.

With

`cache: false 
`

everything goes fine.

**Comment by jjallaire** [comment]
In order to get access to the `x` variable for caching we need to be in an uncached run (i.e. the "cache" is really just of outputs not of the global execution state). So AFAICU this behavior is expected.

**Comment by psads-git** [comment]
That is right, Carlos and Christophe.

Does it make sense to have, by design, `cache: true` incompatible with inline python expressions?

**Comment by jjallaire** [comment]
The only way inline expressions can be evaluated is to send them to a live Jupyter kernel (which we don't have when running from cache). 

Let's imagine that we wanted a cache that could actually service this type of request: you'd need the cache to store a serialized version of the entire Python environment after every cell (so that it could accurately recall the value of `x` at that given time). That's not even remotely like what Jupyter cache does (it just caches cell outputs). 

So I think there is no way to get the current implementation of Jupyter Cache to work with inline expressions. It could possibly be extended to also cache user expressions (but not this gets tricky b/c markdown cell changes don't currently invalidate the cache).

As @psads-git said we probably need to throw an error if an inline expression is used when `cache: true`

**Comment by cscheid** [comment]
> Let's imagine that we wanted a cache that could actually service this type of request: you'd need the cache to store a serialized version of the entire Python environment after every cell (so that it could accurately recall the value of x at that given time). That's not even remotely like what Jupyter cache does (it just caches cell outputs).

Does the ipynb format allow us to stash extra metadata in the file? Since we're wrapping those inline expression calls anyway, we could do extra work there that would allow us to keep the results of the inline expressions as they were evaluated.

(In the meantime, I agree with throwing an error.)

**Comment by jjallaire** [comment]
Jupyter Cache is a 3rd party package we call. It handles all of the caching and currently it only caches code cells (markdown cells can be freely modified and don't invalidate the cache -- the use case is authoring/preview turnaround where you don't want to recompute for merely a content update). So it would need to be modified to (a) Also cache execution result metadata; and (b) Somehow implement cache invalidation for content cells (e.g. invalidate if an expression not previously seen is encountered). It definitely could be done, but it needs to be done in Jupyter Cache rather than in Quarto.

**Comment by jjallaire** [comment]
Made it an error w/ this commit: https://github.com/quarto-dev/quarto-cli/commit/fd5b2190f24854d947525b74da564d3b80f3e452

**Comment by jjallaire** [comment]
A final note of clarification: we don't actually write or otherwise maintain the cache (this is all done by Jupyter Cache). What we do is realize the ipynb from our qmd then submit that to Jupyter Cache, which then does an opaque (to us) calculation as to whether it can restore the code cell outputs from cache. As I understand it, this calculation is basically checking whether any of the source code has changed, in which case the entire cache is invalidated. At the point at which we commit to the cache we have the inline evaluation values in hand (and in fact they are attached to the markdown cells as metadata). These markdown cells are however thrown out by Jupyter Cache.

Note that we use the exact same serialization format as MystJS does for inline expression metadata. So if Jupyter Cache were enhanced to cache these expressions (and have a more sophisticated invalidation criteria that includes them) it would work equally well for Quarto and MystJS.

**Comment by psads-git** [comment]
I do not know whether the following can be useful:

[`ipycache`](https://github.com/rossant/ipycache).

**Comment by cscheid** [comment]
@psads-git cell magics are specific to the IPython kernel, so we can't use them.
