### ISSUE TITLE
PDF Render fails if tinytex is installed through CRAN

### ISSUE THREAD

**Issue by guslipkin** [quarto-dev/quarto-cli#679]
If `tinytex` is installed through CRAN, render to PDF won't work due to `scrreprt.cls` not being found.

Error:
```
updating tlmgr

updating existing packages
finding package for scrreprt.cls

compilation failed- no matching packages
LaTeX Error: File `scrreprt.cls' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: cls)

Enter file name: 
! Emergency stop.
<read *> 
         
l.10 \usepackage
                {amsmath,amssymb}^^M 

see Report.log for more information.
```

To resolve, uninstall `tinytex` and remove it. If you try to remove tinytex through the quarto CLI, it will refuse because tinytex was not installed by quarto.
```
tinytex::uninstall_tinytex()
remove.packages("tinytex")
```

Then install using quarto's recommended method.
```
quarto tools install tinytex
```

Systems tested:
- M1 Max MacOS 12.4 Beta (21F5048e)
- Intel MacOS Hackintosh 12.3

I'm not sure what the best solution for this would be. Either quarto could suggest overwriting other installs or warn that `tinytex` should be installed through the quarto CLI so that all components are available.

**Comment by dragonstyle** [comment]
Hi- thanks for reporting this. 

Quarto should work just fine with an existing installation of TinyTex,but I have a feeling that TeX Live and the recent switch from 2021 to 2022 may have caused problems (right now when we attempt to install packages, we don't detect that the error is coming from mismatching versions and provide a helpful message to update your tinytex, instead we just give up).  If your existing installation was a 2021 version, that can long install packages as the 2022 distribution is now live. When you uninstalled and reinstalled using Quarto, you also likely got the correct version, fixing the error.

I'm a little uncomfortable biting off overwriting existing installations since we may not always succeed given how little me may know about how the TexLive installation was configured. That said, I definitely think that if the issue is a version issue, we should 100% provide a clear and helpful message that indicates this is the issue and how you can resolve it. I will keep this open so I can add that!

**Comment by guslipkin** [comment]
CRAN didn't show any tinytex updates when I tried checking. I'll admit I'm not too familiar with TeX itself, but shouldn't the march 29 update been enough to correct this?

I'm not sure I know enough to create an issue with `tinytex` or how I would even check.

**Comment by dragonstyle** [comment]
TeX Live release updates at the start of April each year which rolls over to the new year so march 29 would be just before that happened this year. 

The issue is very much ours- we should be creating the better error message so i will fix this soon!
