### ISSUE TITLE
`fig-asp` defined at top level is ignored

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [quarto-dev/quarto-cli#6792]
### Bug description

If you define `fig-asp` at the top level of a project, e.g. in `_quarto.yml` of a book:

```yaml
execute:
  fig-width: 4
  fig-asp: 0.5
```

it's ignored.

### Steps to reproduce

Cloning and rendering https://github.com/mine-cetinkaya-rundel/test-book should reproduce the problem.

### Expected behavior

Based on https://quarto.org/docs/reference/formats/html.html#figures and https://quarto.org/docs/books/book-crossrefs.html#creating-references I would have expected the top-level option to be applied to figures throughout the book.

Current solution that works is:

```yaml
knitr:
  opts_chunk:
    fig.asp: 0.5
```

Either `fig-asp` should be removed from top-level options on the docs and only included in knitr related pages, or (in an ideal work) this functionality should work (but I believe that's non-trivial since it doesn't work in Jupyter).

### Actual behavior

It's ignored in figure sizing.

### Your environment

- RStudio: 2023.09.0 Build 380
- OS: 13.5 (22G74)

### Quarto check output

```bash
Quarto 1.4.346
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.6: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.346
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2023.08
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/mine/Library/TinyTeX/bin/universal-darwin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.6
      Path: /Library/Developer/CommandLineTools/usr/bin/python3
      Jupyter: 5.3.0
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.43
      rmarkdown: 2.24

[✓] Checking Knitr engine render......OK
```

**Comment by cderv** [comment]
From what I know and understand, here is the status on how to set options and where. 

`execute` options are defined in https://quarto.org/docs/computations/execution-options.html. The one going below `execute` key and really the [output options](https://quarto.org/docs/computations/execution-options.html#output-options) as they are the ones with auto completion
![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/1f87c11b-e3d8-4ceb-85ba-4de2701f7d25)

For figure options, only  `fig-width` and `fig-height` are [mentioned there](https://quarto.org/docs/computations/execution-options.html#figure-options) and example show to use them rather below `format` sub key. They are documented indeed in the `html` format  doc: https://quarto.org/docs/reference/formats/html.html#figures. 

So I guess the expected way should be 
````yaml
format:
  html:
    fig-asp: 0.5
````
as YAML auto completion suggest. 
![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/6e44dd6a-8de8-42c9-87c1-021524907e04)

`fig-asp` has effect only for **knitr** - so as this way could be used for any engine, there is a note about it in the doc. `fig-asp` is also mentioned at https://quarto.org/docs/reference/cells/cells-knitr.html#figures without a note on being knitr specific, because this is the knitr engine chunk option page. Anything in this page is for knitr only. 

Following this situation, `fig-asp` is not yet process like other option internally, and not passed to **knitr** from `execute` or from `format` so only the `knitr` YAML key works for now. 

Even if this is for **knitr** only, I think we can make it work as expected. I'll push a PR.
