### ISSUE TITLE
in revealjs output, if the last slide is hidden the footer is suppressed

### ISSUE THREAD

**Issue by anielsen001** [quarto-dev/quarto-cli#6800]
### Bug description

I create a reveal.js presentation with a footer and when the last slide is hidden, the footer is suppressed. 

I created a github repo which demos this https://github.com/anielsen001/quarto-last-hidden-no-footer

### Steps to reproduce

The project in this github repo demonstrates this problem:
https://github.com/anielsen001/quarto-last-hidden-no-footer

### Expected behavior

I would like to hide slides at the end and keep the footer.

### Actual behavior

The footer is suppressed when the last slide is hidden.

### Your environment

Ubuntu 20.04, with text editor.

### Quarto check output

13:16 $ quarto check

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.450
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.8.3
      Path: /home/apn/sw/bin/python3
      Jupyter: 4.10.0
      Kernels: julia-1.8, python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /usr/lib/R
      LibPaths:
        - /home/apn/R/x86_64-pc-linux-gnu-library/4.3
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      knitr: 1.43
      rmarkdown: 2.24

[✓] Checking Knitr engine render......OK

**Comment by cscheid** [comment]
Thanks for the clear description and git repo! I can definitely repro the bug.

**Comment by cscheid** [comment]
The bug is (unsurprisingly, perhaps) that the footer is inserted in the last slide, and we remove "hidden" slides from the resulting HTML, [here](https://github.com/quarto-dev/quarto-cli/blob/main/src/format/reveal/format-reveal.ts#L461-L480).

I wonder which other elements we are inadvertently removing...

**Comment by anielsen001** [comment]
Thank you for looking at this. I'm glad it was easy to reproduce. It was very vexing to identify. Lesson to self: render frequently.

**Comment by cscheid** [comment]
It seems that our fix for this breaks `decktape`. What we do [is](https://github.com/quarto-dev/quarto-cli/pull/6801#issuecomment-1738113490):

> The best solution is to make sure that div is never a part of a slide, and then to remove the div in the postprocessor if it's empty.

I think that's causing the bad behavior from `decktape`. Although `revealjs` doesn't have a spec for its acceptable content (so that we could say whether the bug is on `decktape` or `quarto`), `revealjs`'s docs [say](https://revealjs.com/markup/):

> The presentation markup hierarchy needs to be `.reveal > .slides > section` where the section element represents one slide and can be repeated indefinitely.

I think this means our generated DOM is not "valid revealjs DOM", and I think the solution needs to be the hack we had considered earlier: to move the auto-generated content to a non-`hidden` slide.

**Comment by cscheid** [comment]
Fixed on `main`, verified that it still passes the regression test `tests/docs/smoke-all/2023/09/11/6800.qmd`
