### ISSUE TITLE
Single images in long scrollable sildes in reveal.js output have height:0

### ISSUE THREAD

**Issue by AndreiBiziuk** [quarto-dev/quarto-cli#6967]
### Bug description

By default revealjs format has `auto-stretch: true`. According to documentation this means: "For slides with a single top-level image, automatically stretch it to fill the slide", but if slide is `scrollable` and has long text, picture or figure is 'stretched' to 0 height.

If I set `auto-stretch: false`, pictures are visible. Also pictures are visible if there is more than 1 on the same slide.

### Steps to reproduce

1. create file `test.qmd`:

````
---
format:
  revealjs:
    scrollable: true
---

## This figure is visible

``` {r}
cars <- c(1, 3, 6, 4, 9)
plot(cars)

```
## This figures are also visible


V

e

r

y

l

o

n

g

t

e

x

t

``` {r}
cars <- c(1, 3, 6, 4, 9)
plot(cars)

```

``` {r}
cars <- c(1, 3, 6, 4, 9)
plot(cars)

```

## This figure is not visible

V

e

r

y

l

o

n

g

t

e

x

t

``` {r}
cars <- c(1, 3, 6, 4, 9)
plot(cars)

```


````

2. render this file: `quarto render ./test.qmd`

3. view `test.html`

### Expected behavior

Figures and images are visible on long scrollable slides.

### Actual behavior

Single figure or image on long scrollable slide has `height:0` and is not visible

### Your environment

Arch Linux, Quarto 1.4.376

### Quarto check output

``` bash
quarto check            
Quarto 1.4.376
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.8: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.376
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      Chromium: 869685
      TinyTeX: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /usr/bin
      Version: undefined

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.5
      Path: /usr/bin/python3
      Jupyter: 5.3.1
      Kernels: haskell, python3

(\) Checking Jupyter engine render....0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
(-) Checking Jupyter engine render....0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /usr/lib64/R
      LibPaths:
        - /home/andrei/R/x86_64-pc-linux-gnu-library/4.3
        - /usr/lib/R/library
      knitr: 1.43
      rmarkdown: 2.24

[✓] Checking Knitr engine render......OK

```

**Comment by cderv** [comment]
Thanks for the report. 

This is indeed related to stretch feature of RevealJS, and why `auto-stretch: false` solves it; This stretch feature is from Revealjs itself (https://revealjs.com/layout/#stretch) and try to calculate remaining size on the slide to auto size the image. 

`auto-stretch: true` means that Quarto slides will apply stretching to images when there is only one on a slide. This is why "pictures are visible if there is more than 1 on the same slide." because they do have have the stretching computation applied to them. 

I believe than on slides with `.scrollable`, when long text as you did, their is no more size on slides for the revealjs computation. Or something else is making the calculation wrong. 

This is a pretty edge case to have images on slides with scrollable. Slides aren't usually scrollable. 

I wonder if we shouldn't just don't apply auto-stretch on slides with `.scrollable`, because I think this will always make the calculation wrong. Problem is `.scrollable` could be applied on the all presentation. 

We don't control the way the stretching feature works... So for now, solution is to manually to not-stretch on very long slides. 

* Either setting `auto-stretch: false` and apply `.stretch` on Slides where we want to auto size the image
* Either applying `.nostretch` class on slides with very long text, where stretching the image does not make sense. e.g. in your example `## This figure is not visible {.nostretch}`

I'll think of something if we can apply `.nostretch` automatically... `.scrollable` is mainly a CSS rule added when class is there (for `overflow-y: auto`. Doing something more clever would probably mean detecting an overflow, and applying no stretching in that case.

Could also be something upstream to fix in the calculation 🤔

**Comment by cderv** [comment]
### Current workaround

* Set `auto-stretch: false` and manually add `.stretch` on slides where you need autosizing of image
* Set `.nostretch` on slides where stretching feature causes issue (like slides with overflow)

### Idea of what we could do automatically

* opt-in / opt-out based on config context 
	* Set `auto-stretch: false` when `scrollable: true`, meaning setting `scrollable` globally suppose manual stretching using `.stretch` on slides.
	* Set `.nostretch` on slides with `.scollable` manualy applied 
* Dynamically detect overflow and opt-out
	* Detecting slides with overflow (using [`getBoundingClientRect`](https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect)) - if possible considering how revealjs does sizing.
	* add `.nostretch` in that case

**Comment by cderv** [comment]
Solution would be to document the conflict with stretching when scrollable is set.

**Comment by ute** [comment]
Thank you for the workaround @cderv 😄 👍 I had the same problem also with a non scrollable slide that had too much text on it. (1.4.552)
