### ISSUE TITLE
Endless waiting when there is a Python error in inline code

### ISSUE THREAD

**Issue by psads-git** [quarto-dev/quarto-cli#7005]
Consider the following `quarto` document:

````
---
title: "Untitled"
format: pdf
---


```{python}
import pandas as pd

df = pd.DataFrame(
    {
        'a': [2, 3],
        'b': [1, 4]
    }
)
```

Some value: `{python} df['c'].sum()`.
````

Quarto 1.4.383 _never_ ends rendering. Notice that `df` has no column `c`, which causes a key value error. The issue is that `quarto` appears to know nothing about how to deal with that error but waiting endlessly.

I am using Fedora Linux 38.

**Comment by mcanouil** [comment]
FYI, same on MacOS, so it is not platform/operating system dependent.

**Comment by psads-git** [comment]
> FYI, same on macOS, so it is not platform/operating system dependent.

I have just edited my initial report, to add that I am running Fedora Linux 38. It appears to be, as you say, cross-plataform.

**Comment by jjallaire** [comment]
I don't know if this would work or not. These expressions use a specific protocol (e.g. they might not be able to be multi-line or include blocks or functions within them, we'd have to try). Note that Python records the expression and plays that back in the results (so we've have then reverse out our injected envelope). I would say that if this is confined to Pandas or otherwise narrow in occurrence it's not worth doing all of that (not in general, just w/r/t all of our other work in flight). If it happens commonly then we should definitely try something like what you've suggested. Note that most of the time people prime the values in cells (easier to incrementally develop/debug) and then just reference the variable in their inline expression. We could also add something to the docs saying that people shouldn't attempt non-trivial computations in inline expressions.

**Comment by psads-git** [comment]
I have just discovered that inline python code that uses threads may also be problematic. For instance, consider the following quarto document:

```` 
---
title: "Untitled"
format: pdf
---


```{python}
from threading import Thread
import time

def callback():
    time.sleep(1)
    print(1 / 2) 
```

Some value: `{python} Thread(target=callback).start()`.
```
```` 

The output is:

`Some value:  None.  “‘`

**Comment by mcanouil** [comment]
I would argue that for readability, inline code should mostly call variables rather than function calls.

**Comment by psads-git** [comment]
> I would argue that for readability, inline code should mostly call variables rather than function calls.

The point is that if in the main code chunk one uses

`x = Thread(target=callback).start()`

and then in the inline code one has 

`Some value: `{python} x`.`

the problem also occurs!

**Comment by mcanouil** [comment]
Thanks for explaining this.
I believe this to be even trickier to fix.

**Comment by cscheid** [comment]
@psads-git that's because the value returned by the `start()` method is in fact `None`. This isn't a bug; this is a Python feature that, to put it plainly, you need to learn to program around.

**Comment by jjallaire** [comment]
I've update the docs on inline expressions to note that you shouldn't do non-trivial things within them: https://github.com/quarto-dev/quarto-web/commit/a2527181210318b08d63cf04822cd4272beda28d

**Comment by psads-git** [comment]
> @psads-git that's because the value returned by the `start()` method is in fact `None`. This isn't a bug; this is a Python feature that, to put it plainly, you need to learn to program around.

Thanks, Carlos, but the following code returns `0.5`:

```
from threading import Thread
import time

def callback():
    time.sleep(1)
    print(1 / 2)  # Division by zero

x = Thread(target=callback).start()
x
```

**Comment by cderv** [comment]
> the following code returns 0.5:

The following code returns 0.5 through the callback function. But `x` has no value. If you execute in Python console you'll see that running only this
````python
x = Thread(target=callback).start()
````
will print the 0.5 in console. 

If you then ask for `x` value. There will be nothing. 

So you need indeed to program around if you want to capture the callback in a value to reuse.
