### ISSUE TITLE
revealjs: annotations with code-line-numbers cause off-by-one highlighting

### ISSUE THREAD

**Issue by aronatkins** [quarto-dev/quarto-cli#7042]
### Bug description

Using line highlighting with revealjs together with code annotations causes the final indicated line to not be highlighted. Reproduced with Quarto 1.3 and a recent Quarto 1.4.

https://quarto.org/docs/presentations/revealjs/#line-highlighting
https://quarto.org/docs/authoring/code-annotation.html

### Steps to reproduce

````markdown
---
title: code highlighting
format: revealjs
---

```{.r code-line-numbers=2-3}
1
2 # <1>
3 # <2>
4
5
```
1. first two primes
````

### Expected behavior

Lines two and three should be highlighted.

<img width="432" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/362187/ca530fe9-bf96-47ed-be98-c6cdbdd9bcc3">

### Actual behavior

Only line 2 is highlighted.

<img width="418" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/362187/929c24a6-9e11-4219-bc85-9a2c1221dd12">

Workaround is to artificially change the `code-line-numbers` value to highlight the missed line.

### Your environment

macos ventura 13.5.2
quarto 1.3.433 and quarto 1.4.376

### Quarto check output

```

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.433
      Path: /Applications/RStudio.app/Contents/Resources/app/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.6
      Path: /Library/Developer/CommandLineTools/usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library
      knitr: 1.43
      rmarkdown: 2.24

[✓] Checking Knitr engine render......OK
```

**Comment by mcanouil** [comment]
I can reproduce and same behaviour with computational code cell:

````qmd
---
title: code highlighting
format: revealjs
---

```{r}
#| code-line-numbers: 2-3
#| echo: true
#| eval: false
1
2 # <1>
3 # <2>
4
5
```
1. first two primes
````

**Comment by cderv** [comment]
The issue is because code annotation adds a `<a>` element for the annotation on the left, in the middle of the line `<span>` which makes the `line-highlight` plugin not working. The line highlighting happens in browser with JS plugin for revealjs, and because we are selecting with `span:nth-child()` it does not manage to highlight after the `<a>`. 

We need to adapt the rule or make an exception for when cells are annotated. 

Thanks for the report!

**Comment by mine-cetinkaya-rundel** [comment]
I usually write my code chunks with a blank line between the chunk options and the code. The issue I'm running into with `code-line-numbers` and code annotation is slightly different, potentially because of this. I'm seeing the annotations move to the other side of the chunk.

````
---
format: revealjs
execute:
  echo: true
---

```{r}
#| code-line-numbers: "|1|2|3"

1 + 1 #<1>
2 + 2 #<2>
3 + 3 #<3>
```
1.  hello
2.  mello
3.  jello
````

https://github.com/quarto-dev/quarto-cli/assets/5965649/6718d8b5-b944-4239-8199-b7157cc561cc
