### ISSUE TITLE
Code annotation on hover always introduces a slider

### ISSUE THREAD

**Issue by snhansen** [quarto-dev/quarto-cli#7056]
### Bug description

When using the `code-annotations: hover` option, the annotation box has an unusable slider in the bottom of the text box. I suspect this isn't intended as it has been introduced in newer versions (wasn't the case in e.g. 1.4.309).

![ss1](https://github.com/quarto-dev/quarto-cli/assets/45770265/66df6490-ded9-419e-b3a3-202647b06ba5)

### Steps to reproduce

	---
	format: 
	  html:
	    code-annotations: hover
	---

	```{r}
	x <- 1 # <1>
	```
	1. Annotation.

### Your environment

Windows 11.

### Quarto check output

```
Quarto 1.4.388
[>] Checking Quarto installation......OK
      Version: 1.4.388
      Path: C:\Users\au234616\AppData\Local\Programs\Quarto\bin
      CodePage: 1252
```

**Comment by mcanouil** [comment]
Thanks for the report!

Which version are you currently using?

**Comment by snhansen** [comment]
Just updated to the latest version (1.4.388) and the issue persists. I'm on Windows, by the way. Are you on macOS? I've seen such a behavior only being present on Windows before (https://github.com/quarto-dev/quarto-cli/issues/5700).

**Comment by mcanouil** [comment]
> I'm on Windows, by the way.

This is why we asked those information in the issue form.

**Comment by cderv** [comment]
@dragonstyle you added the scroll at https://github.com/quarto-dev/quarto-cli/commit/8301889bd8f11cb444276e07753e806fee0e9464

````css
.tippy-content {
  overflow-x: scroll;
}
````

Would that be ok to use `auto` instead of `scroll` to show the slider only when this is needed ? 

Or maybe it was not possible because of some other box sizing reason. 🤔 

Also I am not sure why this is a windows only issue... 🤷‍♂️ 

Thanks ! 

BTW, it seems that content has break-words because even a very long string does not get overflow

````markdown
---
format: 
  html:
    code-annotations: hover
---

```{r}
x <- 1 # <1>
1 + x # <2>
```
1. Annotation.
2. VERY VERY VERY VERY VERY VERY VERY VERY LONG ANNOTATION

````

![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/1cb4f9d2-d1f8-4100-9d65-e3f7b29a06b2)

**Comment by snhansen** [comment]
Just wanted to add this is not only for code annotations but more generally for any cross-ref hover (equations, figures, sections, etc.).
