### ISSUE TITLE
Quarto with wide DT datatable objects in widened container: DT page controls do not work properly

### ISSUE THREAD

**Issue by donboyd5** [quarto-dev/quarto-cli#720]
I am an absolute beginner with html so I am not 100% sure this is a bug, but I think it is.

I have a wide data frame that I would like to display in an html report with the R function `DT::datatable`. The table is too wide for the quarto html default page so `datatable` gives it a horizontal scrollbar. The table is longer than the default number of rows to display so `datatable` gives it clickable page controls below the table (1, 2, 3, ...), so that depending on what you click, you can see 10 records, then the next 10, and so on.

With the default settings, with my particular table, the container (I think that's the right word) for the table is too narrow to be visually attractive (I have some very wide text columns that need more space to be readable). Thus, I want to widen the container for this table, but not for the whole html document. (I also reduce the font size, but that does not affect the behavior and so I do not do that in my example.) This is where I run into trouble. 

When displaying a wide DT::datatable in Rstudio with quarto, and the table is **too wide** for the page:

-   IF an html div widens the container,
-   THEN the clickable page controls below the table, i.e.,

> Previous, 1, 2, 3, 4, 5, ..., 10 Next

-   do NOT work properly. For example, 1 and 10 may respond to clicks, but 2-5 may not. Or, if you click 10, making 6-9 visible, 9 will respond to a click, but 6-8 will not.
-   This behavior occurs if the html is rendered and viewed in a web browser (Chrome).
-   However, if the html is rendered and viewed in the viewer pane, the page controls work properly.
-   If this qmd file is converted to an rmd markdown file and knit as rmd (without quarto), this behavior does not occur - page controls work properly. In addition, the page automatically is much wider than the page rendered in quarto.

[This qmd file](https://github.com/donboyd5/mres/blob/main/quarto_DT/quarto_DT.qmd) has a minimal reproducible example  that shows the problem.

[This rmd file](https://github.com/donboyd5/mres/blob/main/rmd_DT/rmd_DT.Rmd) has a minimal reproducible example that shows that the problem does NOT occur with Rmarkdown.

If I am using the wrong approach to widen the container, and there is a way to do so without causing page controls to break I would much appreciate it if someone could let me know a better way to accomplish my goal.

**Comment by cderv** [comment]
Hi, 

Thanks for the shared document example. 

Unfortunately, I cannot reproduce the page control not working properly - all the example have page control working properly on Google Chrome 100.0.4896.127. 
Do you have some error in browser console  (developer pane you should be able to open using  F12) ?

> (Note that quarto converted `<div style = "width: 1200px;">` to `::: {style="width: 1200px;"}`)

About this, the `<div>` is written in Qmd document using its markdown equivalent powered by Pandoc Divs. 
This is equivalent to a `<div class="class-of-div" attr="val">content</div>`
````markdown
::: {.class-of-div attr="val"}
content
:::
````

**Comment by cderv** [comment]
> From Googling around, these files seem to be related to error debugging and not essential for rendering, but I am not sure.

Yes there are not essential for rendering, and helpful for debugging. I don't know if we could prevent this error message 🤔 

> However, it still exists with my full use case and with a [new tiny example](https://github.com/donboyd5/DT_test) - more info on that in a minute.

This time I can reproduce the side effect you are seeing by rendering the qmd in your repo. I don't know where this comes from, and if this is related to Quarto or not. 

Possibly this could be a conflict between some CSS / JS. If you can retry with Rmd and update your repo that would help

**Comment by cderv** [comment]
I think the issue comes from how element are layered in the document. Specifically, Quarto website have a sidebar for margin content, and this sidebard has a `z-index` set to 1 so higher up than other content. The DT table falls below the sidebar meaning that when you try to click on the number below the sidebar place, you can't reach the navigation button of the table as it will click on the sidebar element instead. 

@dragonstyle I believe the `z-index` for the sidebar set to higher the document content is on purpose for some feature ? I don't know if we could improve this somehow or if this is expected. 

@donboyd5 you could try this CSS in your project to make the DT table with higher index. 
````css
div.dataTables_wrapper {
  z-index: 10;
}
````

Adding this in your qmd document
````yaml
format:
  html:
    css: style.css
````

**Comment by donboyd5** [comment]
1. The css solves the problem. This is like wizardry to me!
2. The rmd approach does not have the problem

I have updated the repo -- it has 3 folders: qmd_test (same as before, page controls not working properly), rmd_test (page controls work properly), and qmdcss_test (with the css fix, page controls now work properly).

Thanks!

Don

**Comment by cderv** [comment]
> The rmd approach does not have the problem

The Rmd indeed does not have the issue because this comes from Quarto layout and own CSS. This is a conflict between widgets and the layout. So that is expected to work in Rmd, thanks for the update though. 

> This is like wizardry to me!

If I try to simplifly: 

* Quarto has a layout for HTML with sidebars, main content and navbars. right sidebar is used for some margin feature for example (https://quarto.org/docs/authoring/article-layout.html#margin-content) 
* By extending your table width, you are extending into the margin / sidebar space. 
* In HTML, component can be layered, which is the case with sidebar component where within Quarto CSS we are asking for it to be on top of every other element. 
* The last point means that when you are clicking on the table **where the sidebar is**, the table is in fact below the sidebar, and you are cliking on the sidebar element, which does not react to your click. 
* By setting a custom z-index on the DT table, we are asking for it to be on top of the sidebar, which means that you are this time clicking on the table itself. 

Hope it helps clarify. 

I did not try yet, but in fact maybe you can set up some overflow in margin for your table. 🤔 See 
https://quarto.org/docs/authoring/article-layout.html#overflowing-content

**Comment by cderv** [comment]
This should work fine and get you what you look for, isn't it ? 

````markdown
---
title: "title"
author: "Don Boyd"
date: today
date-format: long
format: html
---

## Introduction

```{r libraries}
library(DT)
```

## Appendix

```{r}
#| column: screen-inset-right
tabdata <- readRDS(here::here("testdata.rds"))
tab <- datatable(tabdata,
                 rownames = FALSE,
                 filter = "top")
tab
```

````

be sure to remove `include: FALSE` though in your `_quarto.yml` here 
https://github.com/donboyd5/DT_test/blob/aa9de70253005aa0a661d254ef08df3743c0283a/qmd_test/_quarto.yml#L13

**Comment by donboyd5** [comment]
Thank you for the explanation of what the wizardry is doing. That's very helpful.

Thanks also for the chunk option `#| column: screen-inset-right`. I had previously tried `#| column: screen-right` but that had not solved the problem. 

I just tried `#| column: screen-inset-right` and you are right that it does indeed solve the page controls problem, without requiring `styles.css`. 

However, it seems to override (or perhaps mask) the page width setting, so that the page is not wider. However, `styles.css` works well by itself and also works with `#| column: screen-inset-right` , in either case widening the page, so I think you have fully solved my problem.

I really appreciate this.

**Comment by donboyd5** [comment]
@cderv should I therefore close the issue? (I am not well versed in GitHub etiquette.)

**Comment by cderv** [comment]
Yes I'll close. Thanks !
