### ISSUE TITLE
Table numbering incorrect with multi-part tables and export to PDF

### ISSUE THREAD

**Issue by dmkaplan2000** [quarto-dev/quarto-cli#7267]
### Bug description

When I include sub-tables in a qmd document to be exported to PDF, the numbering gets all out of whack, generally treating each multi-part table as if it was 2 or more individual tables.

### Steps to reproduce

Render the document below:

````qmd
---
title: "Test table numbering"
format: pdf
---

```{r}
df = data.frame(a=1:3,b=letters[1:3])
```


# Table 1

```{r}
#| label: tbl-table1
#| tbl-cap: A first caption
knitr::kable(df)
knitr::kable(df)
```


# Table 2

```{r}
#| label: tbl-table2
#| tbl-cap: A second caption
knitr::kable(df)
knitr::kable(df)
```
````

The table in Section "Table 2" is given number Table 4.

### Expected behavior

The first table should be numbered 1 and the second should be numbered 2.

### Actual behavior

Second table is given the number 4.

### Your environment

- IDE: RStudio 2023.09.0 Build 463
- R:  version 4.3.1 (2023-06-16)
- OS: Ubuntu 20.04.6 LTS
- Quarto: 1.3.433
- xelatex:
    - XeTeX 3.14159265-2.6-0.999991 (TeX Live 2019/Debian)
    - kpathsea version 6.3.1
    - Copyright 2019 SIL International, Jonathan Kew and Khaled Hosny.
    - There is NO warranty.  Redistribution of this software is
    - covered by the terms of both the XeTeX copyright and
    - the Lesser GNU General Public License.
    - For more information about these matters, see the file
    - named COPYING and the XeTeX source.
    - Primary author of XeTeX: Jonathan Kew.
    - Compiled with ICU version 66.1; using 66.1
    - Compiled with zlib version 1.2.11; using 1.2.11
    - Compiled with FreeType2 version 2.10.1; using 2.10.1
    - Compiled with Graphite2 version 1.3.13; using 1.3.13
    - Compiled with HarfBuzz version 2.6.4; using 2.6.4
    - Compiled with libpng version 1.6.37; using 1.6.37
    - Compiled with poppler version 0.68.0
    - Compiled with fontconfig version 2.13.1; using 2.13.1

### Quarto check output

````bash
$ quarto check

[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.433
      Path: /usr/lib/rstudio/resources/app/bin/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.8.10
      Path: /tmp/RtmpnA8kJL/rstudio/terminal/python3
      Jupyter: 4.6.3
      Kernels: python3

(\) Checking Jupyter engine render....Traceback (most recent call last):
  File "/usr/lib/rstudio/resources/app/bin/quarto/share/jupyter/jupyter.py", line 21, in <module>
    from notebook import notebook_execute, RestartKernel
  File "/usr/lib/rstudio/resources/app/bin/quarto/share/jupyter/notebook.py", line 18, in <module>
    from nbclient import NotebookClient
ModuleNotFoundError: No module named 'nbclient'
[✓] Checking Jupyter engine render....OK
````

**Comment by cscheid** [comment]
Thanks for the report! I can repro locally in 1.3 and 1.4 prereleases as well.

I have a fix incoming but I want to document this for posterity, because it's kind of wild.

The issue is that Pandoc emits longtable environments for its Markdown Tables. That is a sensible thing to do.

The `longtable` environment, on the other hand, conflates the generation of table output with crossreferencing. Bafflingly (IMO), it increases the counter of the `table` environment (!!), cf page 13 of https://mirrors.ibiblio.org/CTAN/macros/latex/required/tools/longtable.pdf under the definition of `\LT@array`. That is (again IMO) _not_ a sensible thing to do.

Because there's no other good latex table output library in the ecosystem, we have to support `longtable`. But we can't have this clear crossrefencing bug. So we'll from now on manually decrement the counter of `table` every time we render a Pandoc Table in LaTeX output. This is a pretty blatant hack that causes warnings on the PDF compilation, but ultimately does the right thing.

In Quarto 1.4, the new crossreferencing system takes over the caption and labels from tables, which mean we should never actually see a `\caption` inside a longtable in our output. That means we're probably safe, and I've verified that `\listoftables` works with this new hack as well:

<img width="789" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/94e40d94-f21d-4b12-b749-e5146a13d534">

**Comment by dmkaplan2000** [comment]
Not sure I got all of that, but glad to be of help and happy to see there is a solution coming out...

**Comment by dmkaplan2000** [comment]
A couple of things:

1) Is there anyway that I can get quarto with this fix right away? It is for a paper I am trying to submit...

2) Have you tried your solution with more than 2 subtables? I have noticed that the numbering jumps by irregular intervals that do not seem to be clearly linked to the number of subtables...

**Comment by mcanouil** [comment]
use the development version (see repository readme) or use the [v1.4.429](https://github.com/quarto-dev/quarto-cli/releases/tag/v1.4.429) which contains the fix.

**Comment by dmkaplan2000** [comment]
And I verified that the table numbering works perfectly with this new version of Quarto...

**Comment by cderv** [comment]
> Thank you, mission accomplished, but I think I found another error with either v1.4.429 or the `titlepages-pdf` quarto extension. I begin my document, which uses the `titlepages-pdf` format, with the following:
> 
> ```
> ::: {.center data-latex=""}
> **ABSTRACT**
> :::
> ```
> 
> However, when this is rendered the `\begin{center}` is placed on the same line as a comment in the LaTeX document (`%%%%% end titlepage extension code`). This causes an error on compilation. I have found a workaround by adding a false nearly empty paragraph, but this worked before, so something has changed in the interim.

@dmkaplan2000 Could you open a new issue with how to run an example that reproduce so that we can have a look ? thank you !

**Comment by dmkaplan2000** [comment]
OK
