### ISSUE TITLE
Custom layout for figures does not work anymore for LaTeX 

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#7309]
This is what we document at https://quarto.org/docs/authoring/figures.html#complex-layouts

````markdown
---
title: "test"
format: 
  pdf: default
  html: default
keep-tex: true
---

```{r}
#| include: false
xfun::download_file("https://raw.githubusercontent.com/quarto-dev/quarto-web/main/docs/authoring/_figure-examples/surus.png", mode = "wb")
```

::: {layout="[[40,-20,40], [100]]"}
![Surus](surus.png)

![Hanno](surus.png)

![Lin Wang](surus.png)
:::

````

This does not work anymore for PDF with 1.4 but it works for 1.3 . 

We may be adding to many `figure` environment, as there is one more inside each `minipage` environment compared to 1.3 latex generated version
![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/26802302-add9-4b52-bb67-523c09651bdf)

Probably related to 
* https://github.com/quarto-dev/quarto-cli/issues/7269

as this is using layout too

**Comment by cscheid** [comment]
Thanks, that's a good catch.

**Comment by mcanouil** [comment]
Might be related to:
- #7262

**Comment by cderv** [comment]
Definitely related ! Thanks for helping cross reference issue @mcanouil !

**Comment by cscheid** [comment]
We have to decide what to do a little bit here. The problem is that this syntax is still kind of broken in 1.3. Look at what happens in LaTeX vs HTML in 1.3 for the following input:

````
---
title: "test"
---

::: {layout="[[40,-20,40], [100]]"}
![Surus](surus.png)

![Hanno](surus.png)

![Lin Wang](surus.png)
:::

![another](surus.png){#fig-1}

See @fig-1.
````

<table>
<tr><td>LaTeX</td><td>HTML</td></tr>
<tr><td>
<img width="830" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/f8f31c06-ac15-47f8-98f8-716f5642e0e7">
</td><td>
<img width="851" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/6c77daf2-9d3e-4b4c-a6a1-f935f957a553">

</td></tr></table>

Figure 4 is visible in LaTeX, it's just floating to the bottom. The difference is in the figure counters.

The fundamental question here is how do we want to treat captioned images that are _not_ crossreferenceable elements. Emitting a \caption{} command outside of a float environment feels quite wrong to me, but that's what we did in 1.3.

In 1.4, the following works:

````
::: {layout="[[40,-20,40], [100]]"}
![](surus.png)

![](surus.png)

![](surus.png)
:::
````

(To be clear: we should never emit bad latex in pure quarto, so I'm not disputing it's a bug. I'm just not sure we want the 1.3 behavior either)

**Comment by cscheid** [comment]
On `main` in PDF, we now reproduce the --- not ideal --- behavior of 1.3. We should do better, but it's not a regression anymore.

**Comment by cscheid** [comment]
> We should do better, but it's not a regression anymore.

I no longer think this is something we should try to solve. Images with captions in LaTeX will always have the counters associated with them, and there's nothing we can do about it; it's a limitation of the template.

**Comment by cderv** [comment]
> On main in PDF, we now reproduce the --- not ideal --- behavior of 1.3

I just note that in Quarto 1.4 we do not number the figure the same. This is what I got in 1.4 and main
![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/39b22042-0dc9-424e-b61d-2019678efb18)

It seems we now use `\subcaption` outside of a figure environment. Which increment the counter. 

> The fundamental question here is how do we want to treat captioned images that are not crossreferenceable elements. Emitting a \caption{} command outside of a float environment feels quite wrong to me, but that's what we did in 1.3.

Why don't we use `\caption*` in this case ? This would create the caption, without adding numbering, like in HTML

![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/451cfa21-7baf-4d49-b77c-25c88e58d179)


> Figure 4 is visible in LaTeX, it's just floating to the bottom. 

Just in case anyone wonders, this is not a bug. this is default floating behavior for LaTeX figures.
Setting `fig-pos="H"` makes the figure not float and `Figure 4` now stays below the image, like I did in above example. 
````markdown
::: {layout="[[40,-20,40], [100]]"}
![Surus](surus.png)

![Hanno](surus.png)

![Lin Wang](surus.png)
:::

![another](surus.png){#fig-1 fig-pos="H"}

See @fig-1.
````

**Comment by cscheid** [comment]
> > The fundamental question here is how do we want to treat captioned images that are not crossreferenceable elements. Emitting a \caption{} command outside of a float environment feels quite wrong to me, but that's what we did in 1.3.
> 
> Why don't we use `\caption*` in this case ? This would create the caption, without adding numbering, like in HTML

Because I don't think that's what users will expect. `\begin{figure}\caption{...}\end{figure}` without a `\label{}` _does_ increment a counter, so I think we should match the standard LaTeX behavior.
