### ISSUE TITLE
Quarto qmd file hangs when rendering with Microsoft365R

### ISSUE THREAD

**Issue by plukethep** [quarto-dev/quarto-cli#7337]
### Bug description

I'm writing a qmd report that pulls data from MS OneDrive using `library(Microsoft365R)`. The code within the qmd works fine if run manually, i.e.:

`drive <- get_business_onedrive()`

putting the following into the console: 
```
Loading Microsoft Graph login for default tenant
Using authorization_code flow
Creating Microsoft Graph login for default tenant
Using authorization_code flow
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
```

Loading a new browser window:

```
Authenticated with Azure Active Directory. Please close this page and return to R.
```

And running the script correctly. But when I try and run the script by pressing `render`, It hangs on the code chunk `setup` that runs `drive <- get_business_onedrive()`

```
processing file: timetables.qmd
1/17                  
2/17 [setup]   
```

no browser window is opened and it just sits there. Whilst this is hanging, if I try and run: `drive <- get_business_onedrive()`, it gives

```
> drive <- get_business_onedrive()
Loading Microsoft Graph login for default tenant
Using authorization_code flow
Creating Microsoft Graph login for default tenant
Using authorization_code flow
Error in initialize(...) : Failed to create server
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file 'C:\Users\User\AppData\Local//AzureR/IDString', probable reason 'No such file or directory'
createTcpServer: address already in use
```

**Comment by mcanouil** [comment]
I don't think this has to do with Quarto.
What if you put all the code into a regular R script, and run `Rscript my-script.R` does it work?

Also note that you did not provide any of the information requested in the template such as:
- Steps to reproduce
- Expected behavior
- Actual behavior
- Your environment
- Quarto check output

Currently, there is nothing we can really do without the requested information.
If you could please provide those and share a complete reproducible example it would help.
Thank you for the bug report and consideration regarding the above issues.

You can share a Quarto document using the following syntax, _i.e._, using more backticks than you have in your document (usually four ` ```` `).

`````md
````qmd
---
title: "Reproducible Quarto Document"
format: html
---

This is a reproducible Quarto document using `format: html`.
It is written in Markdown and contains embedded R code.
When you run the code, it will produce a plot.

```{r}
plot(cars)
```

The end.
````
`````

**Comment by plukethep** [comment]
Thanks, "Rmarkdown or Quarto won't open browser for authentication as any non interactive script" explains it, I'll have to cache the data first. I take it there is no way to enable browser authentication in quarto render

**Comment by mcanouil** [comment]
> I take it there is no way to enable browser authentication in quarto render

I am pretty sure, if you put your code in an R script and run `Rscript my-script.R` you'll get the exact same results.

Browser authentication is for interactive use only otherwise there are SSH key, tokens, etc. for non interactive use.
