### ISSUE TITLE
Possible bug introduced when trying to improve overall support for multiple architecture tools

### ISSUE THREAD

**Issue by b-rodrigues** [quarto-dev/quarto-cli#7344]
### Bug description

We are trying to package Quarto 1.4.444 pre-release for the NixOS operating system (to prepare for the upcoming release), and may have found a bug introduced here: https://github.com/quarto-dev/quarto-cli/commit/541287c75070d6e001f6bb5249ee71dc317b53f0#diff-477dc21184191b85ed1c39d9726c6943f3d3203e96484ed34d22511a3026c963  

Trying to run `quarto check` results in the following error message: 
 
```
Quarto 1.4.444

[✓] Checking versions of quarto binary dependencies...
ERROR: Error executing '/nix/store/fhja5l5knmha9wqh7ssc5hm1cqsrwcf1-quarto-1.4.444/bin/tools/x86_64/pandoc': No such file or directory (os error 2)
```

We have a draft PR where we are discussing this update, and here is what @minijackson thinks might be the problem: 

> On x86_64-linux, the `toolsPath("pandoc")` call was replaced with `toolsPath("x86_64/pandoc")` in order to allow vendoring architecture-dependent tools.
> 
> But this moved the override variable from `QUARTO_PANDOC` to `QUARTO_x86_64/PANDOC`, which cannot exist.
> 

Link: https://github.com/NixOS/nixpkgs/pull/263108#issuecomment-1777664009

### Quarto check output

```
Quarto 1.4.444

[✓] Checking versions of quarto binary dependencies...
ERROR: Error executing '/nix/store/4idy5jfy33as6sjyin8d48ynafsn0fyh-quarto-1.4.444/bin/tools/x86_64/pandoc': No such file or directory (os error 2)
```

**Comment by cscheid** [comment]
Thanks for the message. I'm not sure I understand how we're involved in this, though. I believe our Linux installers work fine, and we are not involved in NixOS packaging at all.

**Comment by minijackson** [comment]
@cscheid I don't think this is about NixOS packaging. This is an issue we encountered in our package about, but this is about the `QUARTO_PANDOC`, `QUARTO_ESBUILD`, `QUARTO_DART_SASS`, etc. variables, which you also use in your [Conda recipes](https://github.com/quarto-dev/quarto-cli/blob/b71ffa08acc2241938440d348d07c831f3bfa9f0/package/conda-recipe/build.sh). Those variables don't seem to work anymore, so you might also have an issue in your Linux Conda package.

**Comment by cscheid** [comment]
@minijackson Thank you, that actually helps. We'll get back to you.

**Comment by cderv** [comment]
> this is about the QUARTO_PANDOC, QUARTO_ESBUILD, QUARTO_DART_SASS, etc. variables, which you also use in your [Conda recipes](https://github.com/quarto-dev/quarto-cli/blob/b71ffa08acc2241938440d348d07c831f3bfa9f0/package/conda-recipe/build.sh). Those variables don't seem to work anymore, so you might also have an issue in your Linux Conda package.

@mfisher87 did you notice any issue with the conda recipe ? Is this part of something we discussed already ? 
If you have time to confim if this is working for conda recipe, that will help ! If not, no worries. Thanks !

**Comment by mfisher87** [comment]
Thanks for looping me in, @cderv ! I'm glad to see work packaging 1.4 for Nix. I have not yet tried packaging 1.4 for Conda, so thank you for smoothing the road for those behind you ;)

>>Those variables don't seem to work anymore
>
>did you notice any issue with the conda recipe ?

We have received reports of issues with envvars not being correctly set with Bourne-incompatible shells, e.g. Fish: https://github.com/conda-forge/quarto-feedstock/issues/30 . This is specific to Conda "activation scripts" though, which `export` environment variables.

```
$ cat ~/.local/share/miniconda3/envs/quarto/etc/conda/activate.d/quarto.sh 
  #!/bin/sh
  export QUARTO_DENO=/home/robatt/.local/share/miniconda3/envs/quarto/bin/deno
  export QUARTO_DENO_DOM=/home/robatt/.local/share/miniconda3/envs/quarto/lib/deno_dom.so
  export QUARTO_PANDOC=/home/robatt/.local/share/miniconda3/envs/quarto/bin/pandoc
  export QUARTO_ESBUILD=/home/robatt/.local/share/miniconda3/envs/quarto/bin/esbuild
  export QUARTO_DART_SASS=/home/robatt/.local/share/miniconda3/envs/quarto/bin/sass
  export QUARTO_SHARE_PATH=/home/robatt/.local/share/miniconda3/envs/quarto/share/quarto
  export QUARTO_CONDA_PREFIX=/home/robatt/.local/share/miniconda3/envs/quarto
```

My experience with Nix extends to using `nix-shell` a handful of times. I _think_ this is related to the problem faced by Nix maintainers. The symptoms are very similar to those seen by Conda users with incompatible shells. I'm also relatively new to maintaining the Quarto Conda Forge feedstock, so I'm operating on assumptions for sure, so don't treat me as a source of truth :) Our package sets these envvars to help the main Quarto script find dependencies it otherwise would detect in the incorrect location. Alternately, we could patch that script, but I think that's less desirable than what we do: define envvars that make it behave as desired. Should the script be updated to more robustly find its dependencies, or should (can?) Nix maintainers do something similar to the Conda activate scripts?

_OT: To resolve the Conda envvar issue above, there is a more shell-agnostic way of handling this in Conda, but it's undocumented and I have searched and not found any other conda-forge feedstocks using it. I'm going to want to do some thorough testing to make sure this works before going forward. Ideally, I'd like official confirmation that this interface is supported by Conda, but I haven't heard back on that yet. More details in the linked issue. Of course, I'd welcome and support anyone that wants to jump in on this issue. My pace working on this alongside `$DAY_JOB` may not be the fastest :)_

**Comment by b-rodrigues** [comment]
I can say that with https://github.com/quarto-dev/quarto-cli/pull/7398 , Quarto 1.4.455 now works as expected (well, at least `quarto check` now passes)

**Comment by cderv** [comment]
Thanks for confirming @b-rodrigues . 

I believe we can close here, and @mfisher87 we can follow up conda stuff in other places. 

Thanks everyone !
