### ISSUE TITLE
A way to create a publishable article from multiple qmd files

### ISSUE THREAD

**Issue by amichuda** [quarto-dev/quarto-cli#742]
I know that books can take many qmd files and merge them into one, but is there a format for something like a journal article? Moreover, for that particular use-case what is the purpose of an index file, which seems to be required for rendering a book?

**Comment by cderv** [comment]
Yes there have been some discussion around template for journal articles in https://github.com/quarto-dev/quarto-cli/discussions/414 and https://github.com/quarto-dev/quarto-cli/discussions/374 
and also other issue you can follow like https://github.com/quarto-dev/quarto-cli/issues/170
This is ongoing work and there should be some solution soon. 

Which journal are you targeting ? 

On the form, for journal's article, it will be using a single `.qmd` document rather than a book project. However, with book project, you should definitely be able to write a book to paper publish. 

Hope it helps

**Comment by dragonstyle** [comment]
Quarto now supports a lot of infrastructure to make this possible, documented here:

https://quarto.org/docs/journals/

**Comment by bblais** [comment]
I don't see why this was closed as completed, as there is no documentation for how to take multiple qmd files and combine them into a single journal article, which is what the OP asked.  I see how it is done with books, but not for articles or websites.  Is this actually possible?

**Comment by bblais** [comment]
I didn't see anything in the docs linked that said something like, to make an article from multiple files you need to 1) make it a book project and 2) add something in the _quarto.yml like 
```
pandoc:
    top-level-division: section
```

so that the article template won't give an error on \chapter.  I think this works (I figured it out by a bit of trials and error last night), but perhaps I'm missing something?  Thanks for the pointer on the includes!

**Comment by dragonstyle** [comment]
This is pretty interesting and not something I think we had contemplated too closely. Is the goal with multiple documents to help manage the amount of content (e.g. it's a long complex article) or perhaps is there a benefit to using a book project since it will produce multipage output for HTML formats (this may actually be a negative if you truly want to create a single page article in all formats)? Just curious why this appeals to you so we can better support it in the future!

**Comment by bblais** [comment]
It's primarily for breaking content up into manageable pieces.  I do this currently with separate markdown files.  It's also for the fact that in an article, an Introduction may be primarily text but a Methods or Results section would have figures generated by code.  I use Jupyter, so it would make sense to use standard markdown perhaps for the Introduction but Jupyter for the code-specific parts.  Hadn't thought about the multi-page html and I agree that it would probably be a negative for an article, although perhaps some would like it.  Does that help?
