### ISSUE TITLE
Problems ssing !expr in label: 

### ISSUE THREAD

**Issue by ldecicco-USGS** [quarto-dev/quarto-cli#7453]
### Bug description

I can't dynamically create labels for figures to allow me to cross referencing. 

I see the note, so I realize it's probably user error:
```
the !expr syntax is an example of a YAML “tag” literal, and it can be unintuitive. !expr needs to be 
followed by a single YAML “flow scalar”: see the [YAML spec](https://yaml.org/spec/1.2.2/#73-
flow-scalar-styles) for details on how double-quoted, single-quoted, and unquoted strings work.
```
But, I'm not sure why I can get it to work with fig-cap and not label

### Steps to reproduce

````qmd
---
title: "Untitled"
format: html
---

## Quarto


```{r}
#| echo: false
my_label <- "fig-hi"
```

I would like to cross reference @`r my_label`

```{r}
#| label: !expr 'my_label'
plot(1:10)
```


````

### Expected behavior

I would expect that I could dynamically create labels so I know how to reference them later in the text. If I change it to `#| fig-cap: !expr 'my_label'`, the caption is generated as expected. I tried wrapping the "my_label" in double quotes, single quotes, and no quotes. 

### Actual behavior

When I render it in RStudio, I get:

```r

Error in match(x, table, nomatch = 0L) : 
  'match' requires vector arguments
Calls: .main ... process_file -> split_file -> lapply -> FUN -> parse_block -> %in%
Execution halted
```

### Your environment

- IDE: RStudio: 2023.09.1 Build 494
- OS: Windows 10 Enterprise

### Quarto check output

```bash
$ quarto check
Quarto 1.4.398
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.8: OK
      Dart Sass version 1.55.0: OK
      Deno version 1.33.4: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.398
      Path: C:\Program Files\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Tex:  (not detected)

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.11.1
      Path: C:/Program Files/Python311/python.exe
      Jupyter: 5.3.0
      Kernels: julia-1.8, python3

(-) Checking Jupyter engine render....0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
(\) Checking Jupyter engine render....0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[>] Checking Jupyter engine render....OK

[>] Checking R installation...........OK
      Version: 4.3.1
      Path: C:/PROGRA~1/R/R-43~1.1
      LibPaths:
        - C:/Users/ldecicco/AppData/Local/R/win-library/4.3
        - C:/Program Files/R/R-4.3.1/library
      knitr: 1.45
      rmarkdown: 2.25

[>] Checking Knitr engine render......OK
```

**Comment by cscheid** [comment]
Because `!expr` is not supported in general (it's a quite-specific knitr feature), and `label` is one of the fields where we can't really support it. What are you trying to do more generally?

**Comment by mcanouil** [comment]
The proper way (even in knitr/rmarkdown) would be:

````qmd
---
title: "Untitled"
format: html
---

## Quarto

```{r}
#| echo: false
my_label <- "fig-hi"
```

I would like to cross reference @`r my_label`

```{r}
#| output: asis
#| echo: false
cat(
  knitr::knit_child(
    text = c(
      "```{r}",
      sprintf("#| label: %s", my_label), 
      "plot(1:10)",
      "```"
    )
  )
)
```
````

**Comment by ldecicco-USGS** [comment]
I'm using the `whisker` package to create some large Quarto docs like this. If this file is test.qmd:

````qmd
---
title: "Untitled"
format: html
---

## Quarto


{{#sets}}

```{r}
#| echo: false
#| results: asis

set <- "{{.}}"
my_label <- paste0("fig-", set)
cat("##", set)
cat("\n\n")
```

I would like to cross reference @`r my_label`

```{r}
#| label: !expr my_label
plot(1:10)
title(set)
```

{{/sets}}

````

Then I run:

```r
md_contents <- strsplit(whisker::whisker.render(xfun::read_utf8("vignettes/test.qmd"),
                        data = list(sets = letters[1:5])), "\n")[[1]]

usethis::write_over("my_report.qmd", md_contents)
```

which generates my_report.qmd:

````qmd
---
title: "Untitled"
format: html
---

## Quarto



```{r}
#| echo: false
#| results: asis

set <- "a"
my_label <- paste0("fig-", set)
cat("##", set)
cat("\n\n")
```


I would like to cross reference @`r my_label`

```{r}
#| label: !expr my_label
plot(1:10)
title(set)
```



```{r}
#| echo: false
#| results: asis

set <- "b"
my_label <- paste0("fig-", set)
cat("##", set)
cat("\n\n")
```


I would like to cross reference @`r my_label`

```{r}
#| label: !expr my_label
plot(1:10)
title(set)
```



```{r}
#| echo: false
#| results: asis

set <- "c"
my_label <- paste0("fig-", set)
cat("##", set)
cat("\n\n")
```


I would like to cross reference @`r my_label`

```{r}
#| label: !expr my_label
plot(1:10)
title(set)
```



```{r}
#| echo: false
#| results: asis

set <- "d"
my_label <- paste0("fig-", set)
cat("##", set)
cat("\n\n")
```


I would like to cross reference @`r my_label`

```{r}
#| label: !expr my_label
plot(1:10)
title(set)
```



```{r}
#| echo: false
#| results: asis

set <- "e"
my_label <- paste0("fig-", set)
cat("##", set)
cat("\n\n")
```


I would like to cross reference @`r my_label`

```{r}
#| label: !expr my_label
plot(1:10)
title(set)
```

````

In general I've had many reasons to dynamically calculate chunk options in the past in Rmd. Captions might need inline R values, figure height depends on the data, stuff like that.  I'm loving the cross-referencing support in Quarto.

If there are better ways to do this, I'll happily learn it! Thanks for all your work

**Comment by mcanouil** [comment]
Why then not using the same approach to replace labels directly instead of wanting to evaluate them a second time within Quarto?
You are already replacing content.

**Comment by cscheid** [comment]
> In general I've had many reasons to dynamically calculate chunk options in the past in Rmd.

The context is helpful, and we hear you. `label` is unfortunately special (it needs to be known statically for a variety of reasons we can't control; this is true as well in .Rmd and knitr, not just in quarto). `!expr` makes it essentially impossible for our IDE tooling to work well. We can't tell whether you made a mistake in that expression, we can't tell the type, and we have to assume "everything is going to work out". When it doesn't work out, then we get really terrible error messages (like the one you just saw!).

We hope to reduce the need for `!expr` progressively as quarto matures, precisely because it's not a feature that works well.

> Captions might need inline R values

In quarto 1.4 you can do this:

````
::: {#fig-1}

```{r}
plot(1,2,3,4)
```

My fancy stats has p = `r analysis$p_value`.
:::

See @fig-1.
````

> Figure height depends on the data

You should be able to call the device directly in R code to control that, but I agree that the `!expr` syntax is somewhat convenient.

**Comment by cderv** [comment]
> But, I'm not sure why I can get it to work with fig-cap and not label

This is not related to `!expr`. **knitr** does not allow R expression to be used for `label`, because it is a specific options that needs to be a name and not evaluated, however any other options are evaluated. 

See 
````markdown
```{r label = "setup"}
custom <- "my_chunk"
```

```{r label = custom}
1 + 1
```

```{r}
knitr::all_labels()
```
````

If you knitr that, you'll see that the second chunk has label `custom` and not `my_chunk`
````
> knitr::all_labels()
## [1] "setup"           "custom"          "unnamed-chunk-1"
````

This is exactly what you observed. 

`!expr` is just a way to pass R object to evaluate in a YAML field. But it changes nothing here. 


> In general I've had many reasons to dynamically calculate chunk options in the past in Rmd. (...)
> If there are better ways to do this, I'll happily learn it! Thanks for all your work

If you need to derive some chunk labels from some parameters or other variables, the recommended way to use templating and child document feature of **knitr**. 

The R Markdown Cookbook shows an example with own templating function `knitr::knit_expand()` (https://bookdown.org/yihui/rmarkdown-cookbook/knit-expand.html), and then `knitr::knit_child()` to render. You could though use any tool as templating software - **whisker** is fine ! Idea is that you will create the .qmd content, including the chunk label using the template and values. 

As @mcanouil said, you don't need a chunk to dynamically generate content as you are using a template tool already 

It seems in your usage, you don't even need `knit_child()` but just use the templating feature of **whisker**. I think your example can be simplified to this 

````markdown
---
title: "Untitled"
format: html
---

## Quarto


{{#sets}}

## {{.}}

I would like to cross reference @fig-{{.}}

```{r}
#| label: fig-{{.}}
plot(1:10)
title("{{.}}")
```

{{/sets}}
````

<details>
<summary>which gives this document</summary>

````markdown
---
title: "Untitled"
format: html
---

## Quarto



## a

I would like to cross reference @fig-a

```{r}
#| label: fig-a
plot(1:10)
title("a")
```


## b

I would like to cross reference @fig-b

```{r}
#| label: fig-b
plot(1:10)
title("b")
```


## c

I would like to cross reference @fig-c

```{r}
#| label: fig-c
plot(1:10)
title("c")
```


## d

I would like to cross reference @fig-d

```{r}
#| label: fig-d
plot(1:10)
title("d")
```


## e

I would like to cross reference @fig-e

```{r}
#| label: fig-e
plot(1:10)
title("e")
```
````


</details>

So overall, I don't think this is anything to do with `!expr` feature, or anything else. Just about correct and simple way to create .qmd content using a template. 

Hope it helps

**Comment by ldecicco-USGS** [comment]
Thanks all, I learned a lot from these responses! The reason I can't use the `{{.}}` directly on the label as-written - the sets contain spaces and non-characters that won't work in the cross referencing (so in my real world example, I was doing some gsub on the `{{.}}` before using it in the label). 

I can probably re-define the "sets" so that they are label-friendly and point to the correctly formatted text. I've been using `whisker` for years, but have been meaning for nearly as long to get just as proficient at child docs, this might be a good place to try too.

**Comment by mcanouil** [comment]
You could work the other way around, use syntactic names and then replace the separator character with spaces, this way you get valid labels (avoid using underscores in labels if you intend to use LaTeX/PDF at some point).

**Comment by ldecicco-USGS** [comment]
I think that circles back to my original issue, which is how would I modify some text to make a chunk label. My original thought was to use !evalr in the `label:` line itself. I wouldn't be surprised *at all* if I was missing an obvious solution.


If my "sets" are:
```r
sets <- c("pH [std units]",
          "Dissolved Oxygen [mg/L]")

```

Then I can't do this and get the cross-referencing to work:

````qmd
{{#sets}}

```{r}
#| echo: false
#| results: asis
set <- "{{.}}"
cat("##", set)
cat("\n\n")
```
I would like to cross reference @fig-{{.}}
```{r}
#| label: fig-{{.}}
plot(1:10)
title(set)
```
{{/sets}}
````


I was trying to do this:
````qmd
{{#sets}}
```{r}
#| echo: false
#| results: asis

set <- "{{.}}"
my_label <- paste0("fig-", set)
cat("##", set)
cat("\n\n")
label_set <- stringr::str_replace_all(sets, "[[:punct:]]", "")
label_set <- gsub(" ", "", label_set)
label_set <- paste0("fig-", label_set)
```
I would like to cross reference @`r label_set`

```{r}
#| label: `r label_set` #### <- not sure what to do here! that's why I tried !evalr #### 
plot(1:10)
title(set)
```
{{/sets}}
````

**Comment by cderv** [comment]
> which is how would I modify some text to make a chunk label ? 

Why not use several variables from your `sets` value, correctly processed to file the template the right way ? 

I don't know well whisker, so not sure how you would do that, but `knitr::knit_expand()` or **glue** + `knitr::knit_child()` can definitely help.  Logic is a bit different though: 
* Use a template tool to create a sub part of your report 
* Do a loop to redo that as many times as needed (your number of `sets`) 
* Use `knit_child()` to knit it and include results in main file

This would look that way using only **knitr** feature. It works the same in Quarto and R Markdown. 

````markdown
---
title: "Test"
format: html
---

```{r}
#| echo: false
#| include: false
sets <- c("pH [std units]", "Dissolved Oxygen [mg/L]")

# We fill the template with the value
src <- lapply(sets, function(set) {
  label_set <- stringr::str_replace_all(set, "[[:punct:]]", "")
  label_set <- gsub(" ", "", label_set)
  label_set <- paste0("fig-", label_set)
  knitr::knit_expand("_child.qmd")
})

# We need to knit so that the chunks inside are rendered 
rendered_content <- knitr::knit_child(text = unlist(src), quiet = TRUE)
# The results will be output inline in the doc
```

`r rendered_content`
````

You could do more complex things with `knitr::knit_child()` that requires some more consideration - Example at https://bookdown.org/yihui/rmarkdown-cookbook/child-document.html shows more

One solution with Quarto only would be a two step process: You could get the same type of results by using a [pre project script ](https://quarto.org/docs/projects/scripts.html#pre-and-post-render)that would create some `.qmd` files to be included based on values (using a templating tool), then you would have chunks in your main document project loading those with[ `{{< include ... >}}` ](https://quarto.org/docs/authoring/includes.html)

There is not yet pre-render per file that could happen, but maybe at some point (can't find the opened issue I am thinking of... 🤔 )


Hope it helps understand that this is a design problem IMO in the first place. You need to clearly see what you want to do, and leverage simple solution in the tools. Using `!expr` is mainly last resort and quite advanced usually.

**Comment by ldecicco-USGS** [comment]
In case future me (or anyone else) comes back to see how it worked out, I did end up taking the @mcanouil 's initial suggestion:

````qmd
---
title: "Untitled"
format: html
---

{{#sets}}

```{r}
#| echo: false
#| output: asis

set <- "{{.}}"
my_label <- paste0("fig-", set)
cat("##", set)
cat("\n\n")
label_set <- stringr::str_replace_all(set, "[[:punct:]]", "")
label_set <- gsub(" ", "", label_set)
label_set <- paste0("fig-", label_set)
```
I would like to cross reference @`r label_set`

```{r}
#| echo: false
#| output: asis

cat(
  knitr::knit_child(
    text = c(
      "```{r}",
      sprintf("#| label: %s", label_set),
      "#| fig-cap: Median sample result of {{.}}",
      "#| echo: false",
      "plot(1:10)",
      "title(set)",
      "```"
    ),
    envir = environment(), quiet = TRUE
  )
)
```
{{/sets}}
````

Then using `whisker`:

```r
sets <- c("pH [std units]",
          "Dissolved Oxygen [mg/L]")
md_contents <- strsplit(whisker::whisker.render(xfun::read_utf8("test.qmd"),
                                                data = list(sets = sets)), "\n")[[1]]

usethis::write_over("my_report.qmd", md_contents)
```
If I didn't have a ton of stuff already done using this set of `sets` with `whisker` I'd probably try to figure out how to do it with actual child.qmd files. Next project!

Anyway, it did indeed produce the type of behavior I was looking for:

![image](https://github.com/quarto-dev/quarto-cli/assets/1105215/9d939980-ceac-474e-973a-3c9e767d2456)

Thanks again all.

**Comment by cderv** [comment]
Awesome ! It indeed works very well like that! 

Thanks for the discussion. This thread has nice examples will be able to reference too if needed.
