### ISSUE TITLE
LaTeX in figure captions with lightbox

### ISSUE THREAD

**Issue by dragonstyle** [quarto-dev/quarto-cli#7592]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/7591

<div type='discussions-op-text'>

<sup>Originally posted by **snhansen** November 15, 2023</sup>
### Description

I noticed that LaTeX syntax isn't rendered properly in the lightbox view of figures. Is that a bug or should I use some other syntax?

	---
	format: 
	  html:
	    lightbox: true
	---

	```{r}
	#| fig-cap: "$\\beta_0$"
	#| label: fig-label
	library(ggplot2)
	ggplot(data = mtcars, aes(y = mpg, x = wt)) + geom_point()
	```</div>

**Comment by cderv** [comment]
The issue is that we do set in the attributes the content as text, and math is lost... 
````html
<a href="index_files/figure-html/fig-label-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1" data-description="Figure&nbsp;1: \beta_0"><img src="index_files/figure-html/fig-label-1.png" class="img-fluid figure-img" width="672"></a>
</div>
````

we do transforme the content to string - so we loose the information 
https://github.com/quarto-dev/quarto-cli/blob/b8aa561c8380a54fffa0db177b60d7de1aa1eb3c/src/resources/filters/layout/lightbox.lua#L72-L75

This will happen with any Markdown syntax. A minimal reproducible example is 

````markdown
---
format: 
  html:
    lightbox: true
keep-md: true
---

![**This is bold caption**](https://placehold.co/400){#fig-ph}

````

![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/9e628008-8b7b-4968-8613-d388ff1255a4)

I don't know if there is a simple way to keep those markup, without relying on the advanced description syntax 
Source: https://github.com/biati-digital/glightbox/blob/master/README.md#examples
```
<!-- Advanced Description -->
<a href="large.jpg" class="glightbox5" data-glightbox="title: My title; description: .custom-desc1">
  <img src="small.jpg" alt="image" />
</a>

<div class="glightbox-desc custom-desc1">
  <p>The content of this div will be used as the slide description</p>
  <p>You can add links and any HTML you want</p>
</div>
````

We may need to rely on this when we detect some markup content maybe ? 🤔 

Hope it helps
