### ISSUE TITLE
Citations in callouts not processed for AsciiDoc

### ISSUE THREAD

**Issue by jeroenjanssens** [quarto-dev/quarto-cli#7632]
### Bug description

Citations inside a callout block are not processed when the target is `asciidoc`. The original qmd code (i.e., `[@knuth1984]`) is passed as-is and no entry in the References Div is added.

There's no problem when the div class is not `.callout-*` or when the citation is placed in a footnote.

This problem does not happen for targets `md` and `html`. I have not tried other targets.

### Steps to reproduce

1. Download *references.bib* from https://raw.githubusercontent.com/quarto-dev/quarto-web/dea2b8283307f06a5706693163364bbaf4ef2895/references.bib.
1. Save the code below as *cite-in-callout.qmd*
1. Run `quarto render cite-in-callout.qmd --quiet --to asciidoc --output -`

````qmd
---
title: AsciiDoc Citation Test
bibliography: references.bib
---

## Introduction

Foo [@knuth1984].

::: {.callout-important}
Bar [@wickham2015].
:::

## References {.unnumbered}

::: {#refs}
:::
````

### Expected behavior

```
= AsciiDoc Citation Test

== Introduction

Foo (Knuth 1984).

[IMPORTANT]
====
Bar (Wickham 2015).
====

== References

[[refs]]
[[ref-knuth1984]]
Knuth, Donald E. 1984. “Literate Programming.” _The Computer Journal_ 27 (2): 97–111.

[[ref-wickham2015]]
Wickham, Hadley. 2015. _R Packages_. 1st ed. O’Reilly Media, Inc.
```

### Actual behavior

```
= AsciiDoc Citation Test

== Introduction

Foo (Knuth 1984).

[IMPORTANT]
====
Bar [@wickham2015].
====

== References

[[refs]]
[[ref-knuth1984]]
Knuth, Donald E. 1984. “Literate Programming.” _The Computer Journal_ 27 (2): 97–111.
```

### Your environment

- IDE: vim
- OS: macOS 12.5

### Quarto check output

````
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.450
      Path: /Applications/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.1
      Path: /Users/jeroen/.pyenv/versions/3.11.1/bin/python3
      Jupyter: 5.3.1
      Kernels: python3

(-) Checking Jupyter engine render....0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /opt/homebrew/Cellar/r/4.3.1/lib/R
      LibPaths:
        - /opt/homebrew/lib/R/4.3/site-library
        - /opt/homebrew/Cellar/r/4.3.1/lib/R/library
      knitr: 1.43
      rmarkdown: 2.24

[✓] Checking Knitr engine render......OK
````

**Comment by cderv** [comment]
Thanks for the report. 

@cscheid I believe we need to convert https://github.com/quarto-dev/quarto-cli/blob/59ff6aadb6c15ef052b07cd08ecc350e24c15a81/src/resources/filters/quarto-post/render-asciidoc.lua to use the new Lua API so that custom nodes like `Callout` can be rendered correctly. Currently it stills uses the Writer logic
 https://github.com/quarto-dev/quarto-cli/blob/59ff6aadb6c15ef052b07cd08ecc350e24c15a81/src/resources/filters/quarto-post/render-asciidoc.lua#L56-L61 

so we don't handle content inside the callouts correctly. 

Let me know if you want me to give it a try with a PR.

**Comment by cscheid** [comment]
> I believe we need to convert https://github.com/quarto-dev/quarto-cli/blob/59ff6aadb6c15ef052b07cd08ecc350e24c15a81/src/resources/filters/quarto-post/render-asciidoc.lua to use the new Lua API

We could and it would clean up the code, but it wouldn't really fix the bug.

> so we don't handle content inside the callouts correctly.

This is weird. We're just telling Pandoc to render that citation to asciidoc in a call to pandoc.write() (because that's what the contents are: `Para [Str "Bar",Space,Cite [Citation {citationId = "wickham2015", citationPrefix = [], citationSuffix = [], citationMode = NormalCitation, citationNoteNum = 2, citationHash = 0}] [Str "[@wickham2015]"],Str "."]`). And it's clearly doing the wrong thing. But if we let the citation through to the end of our AST processing, and then let Pandoc render the document to asciidoc, then it uses the right style. So I think what's happening is that there's some asciidoc options we're not forwarding through on that call to `pandoc.write()` or something like that.

Nevertheless, the fix is to let Pandoc itself render the contents itself, so I'll do that.

**Comment by cderv** [comment]
> So I think what's happening is that there's some asciidoc options we're not forwarding through on that call to pandoc.write() or something like that.

We are not passing any Writer options to `pandoc.write()`, and we are also no calling `pandoc.utils.citeproc()` on the `Pandoc` AST node.  So if this expected to get conversion the same as we get at the end of the document, we probably need to do that. 

I did not mention it but that would have been my other fix - I thought new style with ast renderer was needed. 

See this dummy example 

````markdown
---
title: "Quarto Playground"
format: html
bibliography: references.bib
filters: 
  - filter.lua
---

::: {.custom}

**Bar** [@wickham2015].

:::
````

Let's say I want to replace the content of Custom div by generating the HTML directly instead of letting Pandoc do it at the end. 

This Lua is what we do with ascii doc I believe. 
````lua
processDiv = function(d)
  if d.classes:includes('custom') then
    local htmlContent = pandoc.write(pandoc.Pandoc(d.content), "html")
    return pandoc.RawBlock('html', htmlContent)
  end
end


return {
  Div = processDiv
}
````

No Citeproc processing at all. 
![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/22236bf8-1b00-42b3-a8c4-c8a5b608f6c4)


No lets add citeproc processing because we know we could have some citation in there. 

````lua
processDiv = function(d)
  if d.classes:includes('custom') then
    local htmlContent = pandoc.write(pandoc.utils.citeproc(pandoc.Pandoc(d.content)), "html")
    return pandoc.RawBlock('html', htmlContent)
  end
end


return {
  Div = processDiv
}
````
![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/caac7e37-a395-4f22-ac19-49913f182d2b)


We now do get Citeproc processing, but the reference is not found. This is because our conversion do not get any information about the bibliography used. Meta is not passed. Let's change that 

````lua
local meta

processDiv = function(d)
  if d.classes:includes('custom') then
    local htmlContent = pandoc.write(pandoc.utils.citeproc(pandoc.Pandoc(d.content, { bibliography = meta['bibliography'] })), "html")
    return pandoc.RawBlock('html', htmlContent)
  end
end


return {
  {Meta = function(m) meta = m end},
  {Div = processDiv}
}
````

![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/db1626bd-ec3a-4be7-8fa2-304e8ce6a6d4)


Now this is revolved as expected. Though it does not get our default behavior because link-citation is not active. Let's pass all the meta

````lua
local meta

processDiv = function(d)
  if d.classes:includes('custom') then
    local htmlContent = pandoc.write(pandoc.utils.citeproc(pandoc.Pandoc(d.content, meta)), "html")
    return pandoc.RawBlock('html', htmlContent)
  end
end


return {
  {Meta = function(m) meta = m end},
  {Div = processDiv}
}

**Comment by cscheid** [comment]
This is very helpful, thank you!

We have `string_to_quarto_ast_inlines` and `string_to_quarto_ast_blocks`, which go through qmd-reader, shortcode resolution, AST parsing, etc. What we should also have is `quarto.write` or something like that, which does all the work that you've described.
