### ISSUE TITLE
RevealJS: Unexpected behavior from blockquoted unordered lists

### ISSUE THREAD

**Issue by mfisher87** [quarto-dev/quarto-cli#7715]
### Bug description

In RevealJS format, blockquoting an unordered list (and nothing else; putting other things in the blockquote may prevent this from reproducing) causes the unordered list to be rendered as an incremental list without blockquote styling.

I think this is an issue with Pandoc possibly, but I'm not sure. I felt having an issue on this repo would be helpful for other Quarto users searching for info about this behavior. I feel somewhat surprised that I've had difficulty finding previous reports of this behavior. It doesn't seem that uncommon to want to blockquote a list. I apologize if I've missed something obvious before submitting this report!

### Steps to reproduce

See repro repo: https://github.com/mfisher87/sscce-quarto-revealjs-blockquoted-list-weirdness

Deployed repro: https://mfisher87.github.io/sscce-quarto-revealjs-blockquoted-list-weirdness

Render a blockquoted list as revealjs format (`revealjs: default`):

``````markdown
## Repro

```markdown
> * Foo
> * Bar
```

> * Foo
> * Bar

Can you see "Foo" or "Bar"? Try advancing the slide.
``````

### Expected behavior

I expected the list would render normally, but styled like a blockquote.

### Actual behavior

List renders without blockquote style, but renders incrementally (starts hidden, shows each list item as you advance the slide).

The list also renders in unexpected ways relative to other elements in the slide, for example, when rendered next to an un-blockquoted list, the two lists render side-by-side instead of one beneath the other.

Reproduced with Quarto versions:

* 1.3.450
* 1.3.433
* 1.4.510

### Your environment

OS: Pop!_OS 22

### Quarto check output

```bash
$ quarto check
Quarto 1.4.510
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.9: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.510
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: v2023.11
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /home/robatt/.TinyTeX/bin/x86_64-linux
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.9 (Conda)
      Path: /home/robatt/.local/share/miniconda3/bin/python
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with conda install jupyter

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

**Comment by cderv** [comment]
> I think this is an issue with Pandoc possibly, but I'm not sure.

Yes this is Pandoc's bahevior which adds a `fragment` class on each item. You could have tested this way: 

````powershell
> quarto pandoc --to revealjs
> * Foo
> * Bar
^Z
<section class="slide level6">

<ul>
<li class="fragment">Foo</li>
<li class="fragment">Bar</li>
</ul>
</section>
````

I believe this is expected behavior by Pandoc's documentation at https://pandoc.org/MANUAL.html#incremental-lists
See last past part of the doc saying: " an older method is also supported: putting lists inside a blockquote will depart from the document default"

<details>
<summary>Extract from Doc</summary>

````
While using incremental and nonincremental divs is the recommended method of setting incremental lists on a per-case basis, an older method is also supported: putting lists inside a blockquote will depart from the document default (that is, it will display incrementally without the [-i](https://pandoc.org/MANUAL.html#option--incremental[) option and all at once with the [-i](https://pandoc.org/MANUAL.html#option--incremental[) option):

> - Eat spaghetti
> - Drink wine
Both methods allow incremental and nonincremental lists to be mixed in a single document.

If you want to include a block-quoted list, you can work around this behavior by putting the list inside a fenced div, so that it is not the direct child of the block quote:

> ::: wrapper
> - a
> - list in a quote
> :::

````

</details>

Unfortunately, it seems this was the old syntax used by Pandoc from incremental before `--incremental` flag was added. 


So you need the trick to wrap in nonincremental, or add content in the blockquote. 

Note sure Quarto should change this default (even if I am not sure we want it). @cscheid what do you think ? Would it worth patching so that `BulletList` is not first Item of `BlockQuote` when inside revealjs ? If we did then it would not trigger the fragment. 

````
> quarto pandoc --to native
> * Foo
> * Bar
^Z
[ BlockQuote
    [ BulletList
        [ [ Plain [ Str "Foo" ] ] , [ Plain [ Str "Bar" ] ] ]
    ]
]
````

Revealjs post processing is also possible - we do already some and removing fragment class in there could be possible. 

I am inclined to make this behavior not work for Quarto, but we would be touching a Pandoc ones. Interested by your thoughts.
