### ISSUE TITLE
Title and date can be duplicated in hugo output

### ISSUE THREAD

**Issue by linogaliana** [quarto-dev/quarto-cli#795]
When using [hugo format](https://quarto.org/docs/output-formats/hugo.html), I experienced that title and date will be duplicated in output. They will be present two times: once in the YAML but also in the document.

For instance, the example in the document

~~~markdown
---
title: Hello, Quarto
date: "2012-04-06"
categories: 
  - Matplotlib
  - Coordinates
format: hugo
jupyter: python3
---

## Polar Axis

For a demonstration of a line plot on a polar axis, see @fig-polar.

```{python}
#| label: fig-polar
#| fig-cap: "A line plot on a polar axis"

import numpy as np
import matplotlib.pyplot as plt

r = np.arange(0, 2, 0.01)
theta = 2 * np.pi * r
fig, ax = plt.subplots(subplot_kw={'projection': 'polar'})
ax.plot(theta, r)
ax.set_rticks([0.5, 1, 1.5, 2])
ax.grid(True)
plt.show()
```
~~~

will lead to the following `.md` when using `quarto render --to hugo`:

```markdown
---
title: Hello, Quarto
date: "2012-04-06"
categories: 
  - Matplotlib
  - Coordinates
format: hugo
jupyter: python3
---

Hello, Quarto
================
2012-04-06

## Polar Axis
...
```

which does not mix well with `wowchemy/academic` themes (see my personal project https://62726a7214f35700b4efbea7--linogaliana-teaching.netlify.app/rappelsclasses/ : title and date are duplicated) 

If possible, the best option would be to avoid creating the 

```
title
================
date
```

section. 

# quarto version

I used version `0.9.345`

**Comment by cderv** [comment]
We have this because for Hugo format, we are using a special template 
https://github.com/quarto-dev/quarto-cli/blob/2b4efc1c83ebe7affa1b0acbd21bdc1cf0447c96/src/resources/pandoc/templates/default.markdown?plain=1#L1-L10
which will output title, date and author.

@jjallaire when you added this template in f9ee6765fe22394819bf95c58863496dcecfa3b7, what it suppose to cover `format: hugo` ? I am not sure title, date and author are desired in a Hugo markdown format.

**Comment by cderv** [comment]
Oh I see ! I did not spotted this part with `keep-yaml`. Thanks!

**Comment by linogaliana** [comment]
Yes this solved the _issue_, thanks (tested locally)
