### ISSUE TITLE
Missing Custom `revealjs`  Plugins instructions documentation

### ISSUE THREAD

**Issue by rleyvasal** [quarto-dev/quarto-cli#806]
I want to get the [fullscreen plugin](https://github.com/rajgoel/reveal.js-plugins) to work with quarto but not enough information is given in the [quarto documentation](https://quarto.org/docs/presentations/revealjs/advanced.html#reveal-plugins)  to install the plugin.

I copied the `plugin.js` file from https://github.com/rajgoel/reveal.js-plugins/tree/master/fullscreen
into my local `fullscreen` directory C:\Users\R\Downloads\quarto_test_files\libs\revealjs\plugin\fullscreen\plugin.js

 The [vscode-reveal example](https://raw.githubusercontent.com/evilz/vscode-reveal/master/samples/fullscreen.md) shows how to make HTML in slides fullscreen mode with the following code.

```html
<!-- .slide: data-fullscreen-->


<iframe class="stretch" data-src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d61206.89156051744!2d-151.77366863890407!3d-16.50433878928727!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2sde!4v1467468929561"></iframe>
```

I have added plugin: - fullscreen to the yaml header and tried the same code above in quarto but the iframe does not show in fullscreen

```rmarkdown
---
title: "Quarto Presentations"
subtitle: "Create beautiful interactive slide decks with Reveal.js"
format:
  revealjs:
    plugins:
      - fullscreen
---    

<!-- .slide: data-fullscreen-->


<iframe class="stretch" data-src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d61206.89156051744!2d-151.77366863890407!3d-16.50433878928727!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2sde!4v1467468929561"></iframe>

```

How can this plugin be implemented in Quarto?
Is there an easier way to add custom plugins without navigating into the local files to create the correct folder, etc?

**Comment by jjallaire** [comment]
You need to package plugins with a `plugin.yml` file as described here: https://quarto.org/docs/presentations/revealjs/advanced.html#reveal-plugins

**Comment by rleyvasal** [comment]
Thanks for the response @jjallaire, I did check the documentation for plugins but I am not very familiar with how yaml and the plugin interact - therefore I did not get very far. Feel free to close this issue. 

The following were the steps I took:
1. I created a folder `fullscreen` in my local plugin folder with plugin.js and plugin.yml files inside
2. created the plugin.yml file with the following code inside
```rmarkdown
name: fullscreen
script: [fullscreen.js]
```

**Comment by cderv** [comment]
Here are the step to create a bundle plugin: 

* Create a folder with the name you want for the plugin, here `fullscreen`
* Download plugin file https://raw.githubusercontent.com/rajgoel/reveal.js-plugins/master/fullscreen/plugin.js and rename it `fullscreen.js` (or leave the name)
* In that folder add a `plugin.yml`, with this content as the plugin as only one script and not other resource
  ```
  name: RevealFullscreen
  script: [fullscreen.js]
  ````
  * `name` must the name of the JS function that the JS script defines
  * `script` must be the name to the JS file inside the folder created

* Add this to your YAML
    ````yaml
	format: 
	  revealjs:
	    revealjs-plugins:
	      - fullscreen
    ```` 
    the value in the list under `revealjs-plugins` must be the path to the folder with the bundled plugin

* For this specific plugin, considering its documentation, the attributes `data-fullscreen` should be added in the section. So using the Markdown syntax, it would be that way in a document, 
    ````markdown
    ## {fullscreen=true}

	  <iframe class="stretch" data-src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d61206.89156051744!2d-151.77366863890407!3d-16.50433878928727!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2sde!4v1467468929561"></iframe>
    ````

This is not really documented at this level, and I believe the documentation is not correct. `revealjs-plugins` is working and not `plugins`

@jjallaire should I just update the documentation with the correct option name 
https://github.com/quarto-dev/quarto-cli/blob/abaad235d7734c3a872c70881a7cac71643da28c/src/format/reveal/format-reveal-plugin.ts#L35

Or do we want to change it so that what is in the documentation should work ? 
````yaml
---
title: "Presentation"
format:
  revealjs:
    plugins:
      - myplugin
---
````

I found other metatada using `revealjs-` prefix : `revealjs-url` and `revealjs-config`. The former is documented as `reveal-js-url` in YAML schema (and thus reference page), `revealjs-config` is not in schema and not documented, neither is the plugin YAML variable. 

I can do PR, I just wanted to confirm what we are aiming for YAML metadata specific to some formats.

**Comment by cderv** [comment]
@rleyvasal we have added a more detailed documentation and fix the metadata name. This should be working ok now. I'll close this.
