### ISSUE TITLE
Category counts are incorrect with multiple listings: total number is wrong when About page is included and counts do not respect `categories: false` when including multiple listings on a page

### ISSUE THREAD

**Issue by tylermorganwall** [quarto-dev/quarto-cli#8120]
### Bug description

Two issues:

1) The total number of categories is incorrect when multiple listings are included. This arises from the inclusion of the About page, even though the about page has no categories listed.
2) Category counts do not respect the field `categories: false` for that listing: the categories are included in the count(s) even when it's turned off for that listing.

### Steps to reproduce

I have included a repository here that reproduces the issues:

https://github.com/tylermorganwall/quarto-category-bug

### Expected behavior

1) The About page should not add to the total number of categories when multiple listings are included if it does not include any categories.
2) When a listing has `categories: false`, the categories in that listing should not add to the category count.

### Actual behavior

Attached below is an image, one with `categories: false`. Note the total number is 5, instead of 4 (with the uncorrected multiple categories problem) or 2 (respecting the one listing with `categories: false`)

<img width="1026" src="https://github.com/quarto-dev/quarto-cli/assets/297609/21661314-48c4-429b-8f07-79a42688e51c">

Here is an image with three listings, two with `categories: false`. Note the total number is 8, instead of 6 (with the uncorrected multiple categories problem) or 2 (respecting the two listings with `categories: false`).

<img width="1028"  src="https://github.com/quarto-dev/quarto-cli/assets/297609/7acdaa59-f734-4966-9008-bd6ff57b8f05">

Finally, below is a screenshot of the page rendered when the About page has been removed. Note the total number is now 6: the first problem has gone away.

<img width="1344" src="https://github.com/quarto-dev/quarto-cli/assets/297609/b44efff4-8819-452e-8053-5794fcbded1b">

### Your environment

IDE: RStudio (2023.12.0 Build 369)
OS: Ventura 13.4.1

### Quarto check output

Quarto 99.9.9
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 99.9.9
      Path: /Users/tyler/Desktop/quarto-cli/package/dist/bin

[✓] Checking tools....................OK
      TinyTeX: v2022.07
      Chromium: 869685

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/tyler/Library/TinyTeX/bin/universal-darwin
      Version: 2022

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.8
      Path: /opt/homebrew/opt/python@3.10/bin/python3.10
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.1
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.43
      rmarkdown: 2.24

[✓] Checking Knitr engine render......OK

**Comment by mcanouil** [comment]
Thanks for the great report!

**Comment by dragonstyle** [comment]
I don't believe that either of these is a bug- I think that both are by design and sensible.

1) Categories are a page level setting- they are currently determined for an entire page of listings since the categories themselves make up a single list on the page (rather than multiple sets of categories appearing with each listing). Because of this, as the documentation says, we use the setting of the first listing to control whether categories are enabled for the page:

> When multiple listings appear on the page, categories will be enabled based upon the option set in the first listing. If categories are enabled for the first listing, all listings on the page will contribute their item categories to the list of categories and all will be filtered when the user clicks a category. (https://quarto.org/docs/websites/website-listings.html#category-appearance)

2) The number next to the category is the number of items that match that filter. When you select `All` you are showing _all_ items in the listings without regard to whether they have a category (rather than all items which have at least one category, but ignoring the actual category values). As a result, the number `5` is actually correct. 

I think this makes sense when you consider that the number of items that appears next to the category is identical to the number of items that will be displayed on the page if that value is selected.

Thx for the nice bug report I hope this clears it up and makes sense.
