### ISSUE TITLE
Empty _authors.tex file required for last versions of quarto to render with user-defined template

### ISSUE THREAD

**Issue by jchiquet** [quarto-dev/quarto-cli#8158]
### Bug description

We have a quarto-based template for our journal which defines HTML and PDF output.
https://github.com/computorg/computo-quarto-extension

We regularly check that rendering works when updating to different versions of quarto on a sample document located here
https://github.com/computorg/published-paper-tsne

Recently, the following error occurred in the CI:
https://github.com/computorg/published-paper-tsne/actions/runs/7434984888/job/20229814715

Locally, adding an empty `partials/pdf/_authors.tex` file solves the problem.

Is this what is now expected for template design, or is it a bug on the quarto side?

thanks in advance

**Comment by cderv** [comment]
In Quarto 1.4, as part of 
https://github.com/quarto-dev/quarto-cli/pull/8007
we are now throwing an error when a partials is not found. 
https://github.com/quarto-dev/quarto-cli/blob/4fd435bbba3db10eced275dffd2684ed66a529d0/src/command/render/template.ts#L61-L65

Before, it was silently passing. This means that your extension probably requires this partials. 

I can see at https://github.com/computorg/computo-quarto-extension/blame/488a7ea0f5f5505a5dbfb9d2ce3df284e15ec61a/_extensions/computo/_extension.yml#L77
```yaml
      template-partials:
        - "partials/pdf/_authors.tex"
        - "partials/pdf/before-body.tex"
```
so your extension is asking for this template. 

Introduced last year in https://github.com/computorg/computo-quarto-extension/commit/176765472e39b66f0a829dc14811504109f31f91 but not template added at the time it seems. 

If you removed this line instead of adding an empty template, I believe it should render without error.

**Comment by jchiquet** [comment]
Thanks @cderv, sorry for wasting your time, probably a problem on our side then.

**Comment by cderv** [comment]
No problem - do not hesitate to reach out ! When sharing all the relevant information it is quick enough for me to check everything seems fine. I don't mind having some false positive - especially if this could be a bug before we make a new release ! 

Always good to have another pair of 👀 on a problem !
