### ISSUE TITLE
Make figures as large as possible in reveal.js presentations

### ISSUE THREAD

**Issue by maxpel** [quarto-dev/quarto-cli#829]
For some reason, setting width or height for figures in reveal.js presentations gets ignored. I have a centered figure:

`![](extended_analysis_both.svg){fig-align="center"}`

And I would like to make it larger, but that has no effect:

`![](extended_analysis_both.svg){fig-align="center" width="150%"}`

I also tried knitr::include_graphics with setting out.width but that doesn't work either. Is there a way to accomplish this task of stretching a figure as large as possible to fill the available space?

**Comment by jjallaire** [comment]
There is an auto-stretch feature (documented here: https://quarto.org/docs/presentations/revealjs/advanced.html#stretch)

Although I'm not sure whether it works for svg? @cderv do you know?

**Comment by cderv** [comment]
Yes it works on svg. 

@maxpel, by default the stretch class will be applied so that it fits the slide space - we call this the auto-stretch feature.  It will apply  stretch class if there is a single image on slide without any `height` provided. When stretch is active, it will recompute the size based on available space. So adding `width` on image is currently ignored, unless you deactivate auto-stretch.

If you want to completely deactivate this feature, you can set `auto-stretch: false` in YAML
````yaml
format: 
  revealjs:
    auto-stretch: false
````

You can deactivate per slide by adding `.nostretch` class on the slide header. 

See doc here https://quarto.org/docs/presentations/revealjs/advanced.html#stretch

And see this example as illustration 

````markdown
---
title: "Untitled"
format: revealjs
---

## Image stretched

![](https://revealjs.com/images/logo/reveal-black-text.svg){fig-align="center"}

## Image no stretch {.nostretch}

![](https://revealjs.com/images/logo/reveal-black-text.svg){fig-align="center"}

## Image no stretch controlled width {.nostretch}

![](https://revealjs.com/images/logo/reveal-black-text.svg){fig-align="center" width="75%"}
````

**Comment by maxpel** [comment]
@jjallaire @cderv Thank you very much for fast and informative answers! That explains it to me, now I understand.
