### ISSUE TITLE
[Docusaurus] Can't build website from mdx files with "error: quartoRawHtml is not defined" error (Quarto 1.4)

### ISSUE THREAD

**Issue by eitsupi** [quarto-dev/quarto-cli#8331]
### Bug description

docusaurus-md format including html output seems broken.

### Steps to reproduce

````qmd
---
title: foo
format: docusaurus-md
---

```{python}
#| filename: Python
import polars

polars.DataFrame({"foo": [1, 2,]})
```
````

### Expected behavior

````md
---
title: foo
format: docusaurus-md
---

export const quartoRawHtml =
[`<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (2, 1)</small>`,`</div>`];


```python title="Python"
import polars

polars.DataFrame({"foo": [1, 2,]})
```

<div dangerouslySetInnerHTML={{ __html: quartoRawHtml[0] }} />

| foo |
|-----|
| i64 |
| 1   |
| 2   |

<div dangerouslySetInnerHTML={{ __html: quartoRawHtml[1] }} />

````

Generated by Quarto CLI 1.4.432

### Actual behavior

````mdx
---
title: foo
format: docusaurus-md
---





```python title="Python"
import polars

polars.DataFrame({"foo": [1, 2,]})
```

<div dangerouslySetInnerHTML={{ __html: quartoRawHtml[0] }} />

| foo |
|-----|
| i64 |
| 1   |
| 2   |

<div dangerouslySetInnerHTML={{ __html: quartoRawHtml[1] }} />
````

### Your environment

- Ubuntu 22.04

### Quarto check output

```sh
$ quarto check   
Quarto 1.4.545
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.545
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Tex:  (not detected)

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.12
      Path: /usr/local/python/current/bin/python3
      Jupyter: 5.7.1
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.2
      Path: /usr/local/lib/R
      LibPaths:
        - /workspaces/querying-with-prql/renv/library/R-4.3/x86_64-pc-linux-gnu
        - /usr/local/lib/R/library
      knitr: 1.45
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK
```

**Comment by cderv** [comment]
Simpler reprex: 

````markdown
---
title: foo
format: docusaurus-md
keep-md: true
---

```{=html}
<span class="dummy">Content</span>
```
````

Gives now 

````markdown
---
title: foo
format: docusaurus-md
keep-md: true
---




<div dangerouslySetInnerHTML={{ __html: quartoRawHtml[0] }} />

````


This is broken since 8e15dde0dd7d3f56149e226a9bd6235b76818b65  (#7996) 

Thanks for the report - and sorry for all the breakage. 😓

**Comment by cderv** [comment]
The `export` is supposed to be written in the Pandoc filter 
https://github.com/quarto-dev/quarto-cli/blob/9e35ab3f1bf38338c10e8b5b625bee60184165b8/src/resources/extensions/quarto/docusaurus/docusaurus.lua#L17-L27

but since #7996 no `rawHtmlVars` is found because the filters are now applied in a `topdown` approach. 
https://github.com/quarto-dev/quarto-cli/blob/9e35ab3f1bf38338c10e8b5b625bee60184165b8/src/resources/extensions/quarto/docusaurus/docusaurus.lua#L152-L160

I wasn't expecting this, but possibly using `Pandoc` in a `topdown` approach will execute first before all the other function. 

So it does not get first into `rawBlock` that was supposed to fill the `rawHtmlVars` list 

https://github.com/quarto-dev/quarto-cli/blob/9e35ab3f1bf38338c10e8b5b625bee60184165b8/src/resources/extensions/quarto/docusaurus/docusaurus.lua#L53-L69

We need to move this part

**Comment by krishaamer** [comment]
Thanks for this report, I was just about to complain about this too. I'm experiencing the same errors on Quarto 1.4.545 and Docusaurus 3.1.0 on MacOS Ventura.

**Comment by cscheid** [comment]
There's a couple of things going on here.

1. Dumb bug, fix incoming. Our regression test coverage in docusaurus is improving, but we're hurting here. Thanks for the patience.
2. Quarto's table processing is catching the table and converting it to Pandoc AST in order to allow filters to process it. I'm not sure if docusaurus will like seeing Markdown tables in general. The "fixed" output looks like this now:

````
---
title: foo
format: docusaurus-md
---




export const quartoRawHtml =
[`<div><style>
.dataframe > thead > tr > th,
.dataframe > tbody > tr > td {
  text-align: right;
}
</style>
<small>shape: (2, 1)</small>`,`</div>`];


```python title="Python"
import polars

polars.DataFrame({"foo": [1, 2,]})
```

<div dangerouslySetInnerHTML={{ __html: quartoRawHtml[0] }} />

| foo |
|-----|
| i64 |
| 1   |
| 2   |

<div dangerouslySetInnerHTML={{ __html: quartoRawHtml[1] }} />
````

In case Docusaurus turns out to not like some Markdown table features, Quarto's html table processing can be disabled with `html-table-processing: none` in the metadata.

**Comment by eitsupi** [comment]
Thanks for quick update!
