### ISSUE TITLE
Rendering rich jupyter outputs

### ISSUE THREAD

**Issue by betolink** [quarto-dev/quarto-cli#84]
We just ran into a notebook that uses some libraries that generate some widget-based visualizations, they render OK in nbviewer but Quarto seems to have some issues with it. We wonder if the underlying issue here is related to javascript or styling files used by these libraries. i.e. Holoviews.

The notebook in question: https://git.earthdata.nasa.gov/projects/LPDUR/repos/hls-tutorial/raw/HLS_Tutorial.ipynb

With nbviewer:

https://nbviewer.jupyter.org/urls/git.earthdata.nasa.gov/projects/LPDUR/repos/hls-tutorial/raw/HLS_Tutorial.ipynb/%3Fat%3Drefs%252Fheads%252Fmain

And this is how part of the notebook renders with Quarto.

![quarto-hls](https://user-images.githubusercontent.com/717735/128393258-9e755321-59e6-49ee-a3e9-4d78e4cd9426.png)

**Comment by jjallaire** [comment]
We tested with a few of the rich jupyter output sources (e.g. plotly, leaflet, etc.) but not all of them. I'm sure this is something we can sort out -- will take a closer look and report back.

**Comment by jjallaire** [comment]
It turns out that the rich jupyter outputs were not the problem. The issue was that we had horizontal rules (`---`) right on top of headers (which isn't valid in pandoc markdown, so pandoc was interpreting the region between the `---` lines as a table!). Here's the fix I applied to the notebook to get things to render properly:

https://github.com/jjallaire/ipynb-widget-openscapes/commit/aef366da5252b39e309755818d834d966078a59e

I also noticed when debugging this that we were outputting text/plain content with a normal proportional font (vs. monospaced font). I fixed that here (https://github.com/quarto-dev/quarto-cli/commit/e2ba7d5041d3bdddce54f825e40a1cb10b7dbf11), which makes the textual output in the notebook look much better. That is available in the latest release binary (v0.2.60).

Finally, I noticed that many of the code cells had source code or output that was wider than the default main article column Quarto uses. We generally try to encourage users to fit their code into ~ 90 characters wide, this is both for readable output when there are other navigational elements present (sidebar, toc, etc.) but also so that the output is visible in print form (which will just cut off code that is too wide). That said, we do have some options you can use for wider display if that's absolutely what you need. Here's another commit that turns off the table of contents (which is likely on by default in the openscapes site) and sets `page-layout: custom` (which means occupy the full width of the page modulo the sidebar):

https://github.com/jjallaire/ipynb-widget-openscapes/commit/12ca31aba21ba4b6ff40df1b73be3c39858f33de

You lose the toc here (which is quite useful for longer documents like this one) but you do get wider code output which might be more important.

**Comment by betolink** [comment]
Thanks for looking into this @jjallaire! I wonder, those `---` end with a newline so technically they are not in the same line if we were to interpret markdown in Jupyter. Maybe Pandoc is not parsing those newline chars correctly? (correct as in how Jupyter sees them) in any case, those edits are minor and I think they can be done by the DAAC. 

Regarding the Quarto column and wide content, can the main column be collapsible? in case you want to look at just the document.

**Comment by jjallaire** [comment]
For pandoc. you need a full blank line after the horizontal rule (it can't be right on top of the next line). That's not the case for Jupyter markdown though.

The main column currently derives it's width from whether you have a sidebar and/or toc. You can set `toc: false`, `sidebar: false` and/or `page-layout: custom` to statically affect this but it can't currently be toggled dynamically (although that's on our todo list).
