### ISSUE TITLE
Unexpected usage of ejs templating in viewer.ts

### ISSUE THREAD

**Issue by kevinushey** [quarto-dev/quarto-cli#8459]
Derived from https://github.com/rstudio/rstudio/issues/14174.

https://github.com/quarto-dev/quarto-cli/blob/7b1e6d1cda0ae363de3ae602e3839562765b0dee/src/webui/quarto-preview/src/frame/viewer.ts#L39-L44

**Comment by mcanouil** [comment]
Originally:
- #8445

**Comment by cscheid** [comment]
Thanks, @ronblum - What happened here is that this is fixed in v1.5 but we didn't consider it for backporting. (In hindsight, we should have). I've backported it now.

@dragonstyle One thing I don't understand here is the relation between the fix and the commit message. How does this connect to OJS? I ask because I wonder if there are things in the quarto/quarto codebase we should be doing with OJS to help here.

**Comment by dragonstyle** [comment]
It actually has nothing to do with OJS- that should read EJS! This code was previously in an ejs template and this variable got missed when making it standalone js 🤓
