### ISSUE TITLE
Activating ITables in Quarto causes a warning

### ISSUE THREAD

**Issue by mwouts** [quarto-dev/quarto-cli#8670]
### Bug description

Hey, thanks for the wonderful tool!

I have just documented how to use [ITables in Quarto](https://mwouts.github.io/itables/quarto.html), and it works very well.

I have taken care of setting `data-quarto-disable-processing="true"` on the tables that can't be parsed by Quarto.

Yet I still get a warning when I call `init_notebook_mode`, which does not display any table:
```
WARNING (/opt/quarto/share/filters/main.lua:7892) Unable to parse table from raw html block: skipping.
```

The warning goes away if I add `html-table-processing: none` in the document header, but I guess I should not need that, since I have followed the [library authors](https://quarto.org/docs/authoring/tables.html#library-authors) instructions.

### Steps to reproduce

~~~
---
title: ITables in Quarto
subtitle: "`init_notebook_mode` causes a warning"
standalone: true
format:
  html:
    code-line-numbers: false
jupyter:
  jupytext:
    text_representation:
      extension: .qmd
      format_name: quarto
      format_version: '1.0'
      jupytext_version: 1.16.1
  kernelspec:
    display_name: itables
    language: python
    name: itables
---

## How to reproduce

Include this in the Quarto document:

```{python}
#| echo: true

from itables import init_notebook_mode

init_notebook_mode(all_interactive=True)
```

And then render it with `quarto render`, and you'll get 

```
WARNING (/opt/quarto/share/filters/main.lua:7892) Unable to parse table from raw html block: skipping.
```
~~~

### Expected behavior

No warning

### Actual behavior

```
WARNING (/opt/quarto/share/filters/main.lua:7892) Unable to parse table from raw html block: skipping.
```

### Your environment

Latest Ubuntu, Quarto 1.4.549 installed from the `.deb` package, and `itables==1.7.0`.

### Quarto check output

```
Quarto 1.4.549
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.549
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /usr/bin
      Version: 2021

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.4 (Conda)
      Path: /home/marc/miniconda3/envs/itables/bin/python
      Jupyter: 5.3.0
      Kernels: python3, itables, base, javascript, bash, jupytext

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/
```

**Comment by cscheid** [comment]
Thanks for the report, and thanks for making itables work well with Quarto!

This is Interesting. You can see that your code isn't even emitting any actual tables; However, your HTML raw block for library initialization _does_ have the `<table>` string in it, and so we are attempting to parse it, failing, and letting you know.

It's [admittedly gross](https://stackoverflow.com/a/1732454), but we have to use regular expressions to try and find the delimiting table elements since it's not practical for Quarto to include a full-fledged javascript + HTML parser to detect HTML elements.

When you have document-wide metadata requesting tables to not be processed, then we don't attempt to do that, and you see no warnings.

I think that we need to add a new feature to help you further emit clean documents (which we absolutely want to support!)

If we were to detect a special comment in the HTML rawblock, something like `<!-- quarto-disable-table-processing -->`, would that be acceptable in the way your library is written? I think that should be the case and I'm going to go ahead and implement this, but please let me know if that wouldn't work for you.

Thanks again for the report; we really want library authors to have an easy time targeting Quarto documents!

**Comment by mwouts** [comment]
Awesome! Thank you @cscheid !

Yes the proposed solution sounds great. I will just need to add `<!--| quarto: disable-table-processing -->` to [itables/html/initialize_offline_datatable.html](https://github.com/mwouts/itables/blob/main/itables/html/initialize_offline_datatable.html), which is very easy. I'll do this shortly. When do you think the change will be available in `quarto` for testing?

**Comment by cscheid** [comment]
It's already merged on `main` now.

**Comment by cscheid** [comment]
Just FYI, we're going to use a slightly different comment syntax:

```
<!--| quarto-html-table-processing: none -->
```

(If this is starting to look like the syntax we use in code cells, that's not an accident.)
