### ISSUE TITLE
Add warnings when `QUARTO_R`, `QUARTO_PYTHON`, etc. are invalid

### ISSUE THREAD

**Issue by mcanouil** [quarto-dev/quarto-cli#8794]
Related to https://github.com/quarto-dev/quarto-cli/issues/8793

Another related issue is that a user can set `QUARTO_PYTHON=/very/bad/path` and still get Quarto to work without any warnings.

```txt
> QUARTO_PYTHON="/bad/path" && quarto render index.qmd 

Executing 'index.quarto_ipynb'
  Cell 1/1: ''...Done

pandoc 
  to: html
  output-file: index.html
  standalone: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png
  
metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  title: Quarto Playground
  
Output created: index.html
```

```txt
QUARTO_R="/bad/path" && quarto render index.qmd

processing file: index.qmd
output file: index.knit.md

pandoc 
  to: html
  output-file: index.html
  standalone: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png
  
metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  title: Quarto Playground
  
Output created: index.html
```

**Comment by cderv** [comment]
We already warn whe the **environment variable** `QUARTO_PYTHON` is set but no python found there.

here you are using a bash variable not an environment variable. 

Try 

````bash
$ QUARTO_PYTHON=/bad/path quarto render test.qmd
WARNING: Specified QUARTO_PYTHON '/bad/path' does not exist.
WARNING: Specified QUARTO_PYTHON '/bad/path' does not exist.

Executing 'test.ipynb'
  Cell 1/1: ''...Done

pandoc
  to: html
  output-file: test.html
  standalone: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png

metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  title: test

Output created: test.html
````

See the code base to confirm maybe 

https://github.com/quarto-dev/quarto-cli/blob/11c10f3f5c9fec4cf9c813cba5311c4fe54fa153/src/core/jupyter/capabilities.ts#L157-L159

This will be the same for R 

https://github.com/quarto-dev/quarto-cli/blob/11c10f3f5c9fec4cf9c813cba5311c4fe54fa153/src/core/resources.ts#L96-L98

**Comment by mcanouil** [comment]
Indeed, it was missing the "export" command.

Am I missing something as I don't get warnings when using `_environment` file with `QUARTO_PYTHON=/bad/path` in it and the Preview button on VSCode.
Using `quarto render` and `quarto preview` in the terminal properly display the warnings.

PS: why the warning is displayed twice?

**Comment by cderv** [comment]
> PS: why the warning is displayed twice?

It is displayed twice just because we happened to do the detection twice. Not perfect and it will probably be fixed when we'll tackle improvement on the jupyter engine detection workflow. 

If you think this is really disturbing, I can see if we can warn only once (I think we have a function for that). 
TBH this is among the little thing we could improve but that still take time to do. PR welcome. 

> Am I missing something as I don't get warnings when using _environment file with QUARTO_PYTHON=/bad/path in it and the Preview button on VSCode.

This is probably related to another discussion we had (https://github.com/quarto-dev/quarto-cli/issues/6162) and there is also 
https://github.com/quarto-dev/quarto-cli/issues/6206

If this is only in VSCODE with extension, then this is probably related. My understand is that the preview button will use the Python interpreter set in VSCODE. It is possible that the `_environment` setting is overwritten ignore. 

Look at [quarto-dev/quarto](https://github.com/quarto-dev/quarto) existing discussion, look at the code base to see when `QUARTO_PYTHON` is set, and if it seems off then open an issue there. I'll close this here. 

Thanks.

**Comment by mcanouil** [comment]
> Look at [quarto-dev/quarto](https://github.com/quarto-dev/quarto) existing discussion

Nothing reported so far

> look at the code base to see when QUARTO_PYTHON is set, and if it seems off then open an issue there. I'll close this here.

I'll take a deeper look at the codebase, especially for the extension as it could be simply a matter of path resolution (Preview button uses absolute path for some reason).

**Comment by cderv** [comment]
> I can see if we can warn only once (I think we have a function for that).

Change made.
