### ISSUE TITLE
Github pages deployment error from {{ in latex math

### ISSUE THREAD

**Issue by bonStats** [quarto-dev/quarto-cli#8915]
### Bug description

Including`{{` in math expression renders fine locally, but fails upon GitHub pages deployment.

### Steps to reproduce

Including `$$\underset{{\color{green}f}$$` in quarto document leads to GitHub pages deployment failure.

e.g. https://github.com/bonStats/score-cal-24s/actions/runs/8079546122

Can be avoided by including space: `$$\underset{ {\color{green}f}$$`

**Comment by cderv** [comment]
How is configured your repo for Github pages deployment ? 

Have you seen our doc https://quarto.org/docs/publishing/github-pages.html ? 

Your build is currently configured to use Jekyll to build your website. So it will process .qmd files using Jekyll as the error linked shows
![image](https://github.com/quarto-dev/quarto-cli/assets/6791940/eef54d8c-3664-41bf-a633-9c224225c48f)

You don't want to build Jekyll with Quarto, so you need to configure correctly so that it does not try to build .qmd file. And you also should opt-out Jekyll.  We mention this in our doc at
https://quarto.org/docs/publishing/github-pages.html#render-to-docs 

and Github documents it at https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#troubleshooting-publishing-from-a-branch

> Your GitHub Pages site will always be deployed with a GitHub Actions workflow run, even if you've configured your GitHub Pages site to be built using a different CI tool. Most external CI workflows "deploy" to GitHub Pages by committing the build output to the gh-pages branch of the repository, and **typically include a .nojekyll file. When this happens, the GitHub Actions workflow will detect the state that the branch does not need a build step**, and will execute only the steps necessary to deploy the site to GitHub Pages servers.

and at https://github.blog/2009-12-29-bypassing-jekyll-on-github-pages/

BTW if you use `quarto publish gh-pages`, we do most of the setup including the `.nojekyll` addition. 
* https://quarto.org/docs/publishing/github-pages.html#publish-command

Hope it helps
