### ISSUE TITLE
Unwanted spacing with revealjs, `echo: true` and `output-location: column`

### ISSUE THREAD

**Issue by tvatter** [quarto-dev/quarto-cli#9017]
I think that something weird is happening when using revealjs, `echo: true` and `output-location: column`.

Basically, when the first code chunk appears before the first line of text, one has the "standard" spacing for the chunk of code following the line of text. But when there is no code chunk BEFORE the first line of text, some additional spacing is added between the text and the echoed code. Note that this only happens when using `output-location: column`.

Any idea what might be going on and/or how to solve this?

See below for an MWE with screenshots:
````markdown
---
title: "Test"
format:
  revealjs:
    echo: true
jupyter: python3
---


## Before/after with `output-location: column`

```{python}
#| output-location: column
l = ["a", "b", "c"]; print(l)
```

Code chunks before and after the text

```{python}
#| output-location: column
l = ["a", "b", "c"]; print(l)
```

## After with `output-location: column`

Code chunk only after the text

```{python}
#| output-location: column
l = ["a", "b", "c"]; print(l)
```

## After without `output-location: column`

Code chunk only after the text

```{python}
l = ["a", "b", "c"]; print(l)
```
````

![before_after_with](https://github.com/quarto-dev/quarto/assets/5273142/bb0b4eba-7fc9-4fc4-bf6a-72aa42bf4dc9)
![after_with](https://github.com/quarto-dev/quarto/assets/5273142/41f88cf0-4c8e-4c91-82bc-69ad22bc98ff)
![after_without](https://github.com/quarto-dev/quarto/assets/5273142/e513d2ca-f9c2-48bd-bbb3-da8a3c1c9e71)

**Comment by cderv** [comment]
(_Note: I edited your code for correct formatting - see [our guide](https://quarto.org/bug-reports.html#small-is-beautiful-aim-for-a-single-document-with-10-lines)_)

It seems to be a CSS rules that applies it: 
https://github.com/quarto-dev/quarto-cli/blob/0b11aa23efdba15cb534a74a872b91fd527e7637/src/resources/formats/revealjs/styles.html#L72-L74

We explicitly adds extra spacing for .columns below some text (e8b0d5174672d854b5a8f7b66523edc2e98e6ea2) 

However, the rule is quite specific so it misses some case and applies only in the example you share (Header > text > columns) 

So this is expected by our default CSS rule, and one way would be to add more spacing also in your first example. The others would be to remove this spacing entirely... 🤔 

Styling choice are hard because always no best choice - just opinions... 😅

**Comment by mcanouil** [comment]
First `echo: true` should be under `execute` as documented.

```yaml
---
title: "Test"
format: revealjs
execute:
  echo: true
jupyter: python3
---
```

Because Reveal.js is HTML based, you can use your browser ands its developer/inspect mode to look at the CSS rules and the HTML codes.

| No extra rule | Extra rule |
|--------|--------|
| <img width="1624" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/c0c6b3b0-f898-43d2-8f31-231a181f7d18"> | <img width="1624" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/8896044/4c735156-0365-4731-b83e-08d376beb418"> | 

This rule is defined at:

- https://github.com/quarto-dev/quarto-cli/blob/b222df50198848437ebcaa2b6489b4b29ddfc907/src/resources/formats/revealjs/styles.html#L72-L74

**Comment by cderv** [comment]
> First echo: true should be under execute as documented.

Unless you need to apply a different value depending on the format. For example 
````yaml
format:
  html:
    echo: true
  pdf:
    echo: false
````

Quarto maps the right option to the right place - this works for execute key and it useful for multi format from same .qmd where some difference would need to be set. 

Globally, placing under `execute` is the right place indeed!

**Comment by tvatter** [comment]
First of all, thanks to both @cderv and @mcanouil. I agree that styling is hard, and I apologize for what claim that spacing was "unwanted". What bothered me is rather that it was not consistently applied.

Now, I've tried bypassing the rule but my CSS is terrible. I use the following YAML

````markdown
````markdown
title: "Test"
format:
  revealjs:
    css: styles.css
execute:
  echo: true
  code-fold: false
jupyter: python3
---
````

As well as a `styles.css` file containing only:

````css
.reveal .slide .columns:nth-child(3) {
  margin-block-start: 0;
}
````

However, it doesn't seem to be overriding the rule :/ I've verified that my CSS file is correctly taken into account by using `display: none;` and checking that the column code block indeed disappear. When inspecting the HTML as suggested, it seems that the override doesn't work for this parameter (see screenshot below). Any idea why ?

![style_cant_override](https://github.com/quarto-dev/quarto-cli/assets/5273142/5eb02fa1-7f59-4cbc-84d5-16f9cd783c34)

**Comment by cderv** [comment]
This is because your rule applies before the default in CSS ordering. 

You need either makes a more specific rule (https://specifishity.com/) or put your rule inside a theme (https://quarto.org/docs/presentations/revealjs/themes.html#customizing-themes) as it will be merged with default one, and could end up after.

**Comment by tvatter** [comment]
Oh, that's unfortunate, but understood, thanks a lot.
