### ISSUE TITLE
Code cell example should show the backticks part not only content.

### ISSUE THREAD

**Issue by mcanouil** [quarto-dev/quarto-cli#9113]
### What would you like to do?

Give feedback or suggest an improvement

### Description

Take for instance: https://quarto.org/docs/get-started/computations/rstudio.html#multiple-figures

The code you can copy is only the content which is not really useful as the users needs to write the enclosing code cells for real reason.

```r
#| label: fig-mpg
#| fig-cap: "City and highway mileage for 38 popular models of cars."
#| fig-subcap:
#|   - "Color by number of cylinders"
#|   - "Color by engine displacement, in liters"
#| layout-ncol: 2
#| column: page

ggplot(mpg, aes(x = hwy, y = cty, color = cyl)) +
  geom_point(alpha = 0.5, size = 2) +
  scale_color_viridis_c() +
  theme_minimal()

ggplot(mpg, aes(x = hwy, y = cty, color = displ)) +
  geom_point(alpha = 0.5, size = 2) +
  scale_color_viridis_c(option = "E") +
  theme_minimal()
```

The code cell example should show:

````qmd
```{r}
#| label: fig-mpg
#| fig-cap: "City and highway mileage for 38 popular models of cars."
#| fig-subcap:
#|   - "Color by number of cylinders"
#|   - "Color by engine displacement, in liters"
#| layout-ncol: 2
#| column: page

ggplot(mpg, aes(x = hwy, y = cty, color = cyl)) +
  geom_point(alpha = 0.5, size = 2) +
  scale_color_viridis_c() +
  theme_minimal()

ggplot(mpg, aes(x = hwy, y = cty, color = displ)) +
  geom_point(alpha = 0.5, size = 2) +
  scale_color_viridis_c(option = "E") +
  theme_minimal()
```
````

**Comment by cscheid** [comment]
> The code you can copy is only the content which is not really useful as the users needs to write the enclosing code cells for real reason.

It depends on the use case, and no single answer will be right.

If you're in RStudio, often people copy the code to paste into the R terminal.

So there's two options that fail in different ways:

- we include the enclosing backticks and it fails on a terminal
- we don't include the backticks and it requires extra work on the editor

I'm fairly confident that your suggestion makes the overall situation worse, because editing the pasted code on a terminal is much harder than editing the pasted code on a text editor.
