### ISSUE TITLE
Figure references not considered link but sub figure references are

### ISSUE THREAD

**Issue by dylanrussellmd** [quarto-dev/quarto-cli#9436]
### Bug description

This is in a `.qmd` document being rendered to PDF by `typst`.

    ```{=typst} 
    #show link: set text(blue)
    #show link: underline
    ```
    ::: {#fig-pictures layout-nrow=2}
    ![Picture 1](bird.jpeg){#fig-pic1 width="100%"}
    
    ![Picture 2](bird2.jpg){#fig-pic2 width="100%"}
    :::
    
    @fig-pictures is not considered a link, but @fig-pic1 and @fig-pic2 are.

[repro.pdf](https://github.com/typst/typst/files/15050598/repro.pdf)

### Steps to reproduce

Render this `.qmd` to `typst`:

   ```{=typst} 
    #show link: set text(blue)
    #show link: underline
    ```
    ::: {#fig-pictures layout-nrow=2}
    ![Picture 1](bird.jpeg){#fig-pic1 width="100%"}
    
    ![Picture 2](bird2.jpg){#fig-pic2 width="100%"}
    :::
    
    @fig-pictures is not considered a link, but @fig-pic1 and @fig-pic2 are.

### Expected behavior

All figure references should be cross-reference links.

### Actual behavior

Only subfigure links are cross-reference links.

### Your environment

Version: 1.88.1 (user setup)
Commit: e170252f762678dec6ca2cc69aba1570769a5d39
Date: 2024-04-10T17:41:02.734Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22621
Remote: WSL2 Debian

### Quarto check output

Quarto 1.4.553
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.553
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /usr/bin
      Version: 2022

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.2
      Path: /usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/

**Comment by cscheid** [comment]
This is not a bug.

## The quick fix

Use this instead:

````
```{=typst} 
#show ref: set text(blue)
#show ref: underline
```
````

## A warning

You're emitting raw typst code. You should be aware that this puts you in "I know what I'm doing" mode, and that in this case, you should be willing to inspect the emitted .typ file, which you can do with `keep-typ: true`. You'll need to do it anyway in order to climb out of holes you might have dug! You'll 

Here's what's going on:

## An explanation

Typst itself doesn't use links in their default implementation for the show rule of a `ref` element. ([see the `ref` documentation](https://typst.app/docs/reference/model/ref/)) . You can observe that with a pure Typst document:

````
#show link: set text(blue)
#show link: underline

In this report, we will explore the
various factors that influence fluid
dynamics in glaciers and how they
contribute to the formation and
behaviour of these natural structures.

Glaciers as the one shown in
@glaciers will cease to exist if
we don't take action soon!

#figure(
  image("glacier.jpg", width: 70%),
  caption: [
    _Glaciers_ form an important part
    of the earth's climate system.
  ],
) <glaciers>
````

(This is taken from https://typst.app/docs/tutorial/writing-in-typst/, and uses your show rule)

When you compile this document, you'll see that your show rule doesn't do what you want there:

<img width="782" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/d63458bd-19ef-4e91-a972-4f140e1df35b">

Quarto needs to override the rendering of the `ref` element for the case of subreferences, and _we_ emit a(n unstyled) link element. But for regular `ref` elements, we use Typst's implementation, which doesn't.

However, what you _really_ wanted to do was not to style links, but to _style `ref` elements_. You do that with the show rule I showed above.
