### ISSUE TITLE
Changes not refreshing on Quarto website (cache?)

### ISSUE THREAD

**Issue by michalkohuttn** [quarto-dev/quarto-cli#9493]
### Bug description

Hi all,
I am really glad and thankfull for Quarto! I am novice and can't help myself.

I made a Quarto website that I need to update infrequently. I have paid webhosting service and own domain, and I do the updates by deleting all files and then uploading them all again after update (I know it is not ideal).. However, when I open the page on my browser (Chrome), I do not see the changes (I tried refreshing, closing and opening, restarting pc..). When I open in incognito mode, it works just fine. I found that the reason is probably cache of browser. Is there a way to not chache the files? Thanks.

### Expected behavior

Show the actual website.

### Actual behavior

Changes are not visible.

### Your environment

Rstudio

**Comment by mcanouil** [comment]
Unfortunately, if you don't provide the information requested, we can't help.

**Comment by michalkohuttn** [comment]
> Unfortunately, if you don't provide the information requested, we can't help.

I am using Quarto Website in Rstudio. I rendered the website and uploaded the files from "_site" folder on my webhosting. Everything worked fine. After that, I added some new pages with content and added them as content to "_quatro.yml" I rendered again, deleted all the files on webhosting and uploaded the files from "_site" again. However, the new pages could not be found using search function, or even visible in the sidebar. When I open the website in the Incognito mode (Chrome), everything works just fine - the new page can be found in search results, and is shown in sidebar. 

I have not changed any files in "site_libs".

Is there any more information you need?

**Comment by mcanouil** [comment]
All the information from the template issue you did not fill.
Here, you did not share your setup, the Quarto version being used, code, etc.
The only thing we know is that you have an issue and nothing to work with.

Does the `_site` contains the up to date changes? If so, then the issue is not on Quarto side.

> When I open in incognito mode, it works just fine. I found that the reason is probably cache of browser. Is there a way to not cache the files?

Browser cache is not controlled by Quarto.
Quarto is a command line tool that generate static HTML files (in your case). Nothing more. Hosting issue, caching issue are not Quarto's doing.
