### ISSUE TITLE
Cross-reference figures/tables not working in margin for LaTeX format without "pos"

### ISSUE THREAD

**Issue by mcanouil** [quarto-dev/quarto-cli#9582]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/9581

Cross-reference figures and tables do not work for LaTeX in margin

````qmd
---
title: Minimal Example
format: pdf
---

Text

::: {.column-margin}
![Example of an Image](https://placehold.co/600x400.png){#fig-example-image}
:::
````

Produces: `LaTeX Error: Not in outer par mode.`.

Adding the position argument allows the PDF to compile.

````qmd
---
title: Minimal Example
format: pdf
---

Text

::: {.column-margin}
![Example of an Image](https://placehold.co/600x400.png){#fig-example-image fig-pos="H"}
:::
````

**Comment by pastorn** [comment]
I learned that you just have to do it the particular way that quarto wants it, if you want it to work:

```qmd

Text referencing @fig-example-image.

::: {.column-margin #fig-example-image cap-location=bottom}

![](https://placehold.co/600x400.png)

Example of an Image

:::

```

I may have asked about it (don't remember) but my solution was to a bunch of trial-and-error until i stumbled upon a way that happened to work...

**Comment by mcanouil** [comment]
Thanks for linking the other issue.
I did not find it as the title was really focused on the caption location.

**Comment by franzeder** [comment]
Thank you so much for answering this question so quickly. Putting the cross-reference into the ```.column-margin``` environment works perfectly!

**Comment by cscheid** [comment]
Note that these two styles don't produce the same output.

## Source

````md
---
format: pdf
---

::: {.column-margin #fig-example-image}
![](https://placehold.co/600x400.png)

Example of an Image 1
:::

Making space for the second margin figure...

Making space for the second margin figure...

Making space for the second margin figure...

Making space for the second margin figure...

Making space for the second margin figure...

Making space for the second margin figure...

::: {.column-margin}
![Example of an Image 2](https://placehold.co/600x400.png){#fig-example-image fig-pos="H"}
:::
````

## Output

<img width="1004" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/285675/cac2dc80-5abf-4435-9085-c28fd2b9fd97">

**Comment by pastorn** [comment]
Related to this thing?

https://github.com/quarto-dev/quarto-cli/issues/8806

**Comment by cscheid** [comment]
Ok, I found a narrow-enough fix.

Now both syntaxes work. A number of caveats, though. The following syntax **will not work**:

### WILL NOT WORK!

````
::: {.column-margin}
![Example of an Image 2](https://placehold.co/600x400.png){#fig-example-image-2}

![Example of an Image 3](https://placehold.co/600x400.png){#fig-example-image-3}
:::
````

will _not_ work, and this is not a bug that we can fix. It won't crash, but it will generate an ugly document. We now issue a warning in this case. AFAICT this isn't something we can solve ourselves, because it involves an interaction between the packages we use for captions and the ones we use for margin figures. Similarly, you can't mix floats and text in a margin div:

### WILL NOT WORK!

````
::: {.column-margin}
![Example of an Image 2](https://placehold.co/600x400.png){#fig-example-image-2}

Margin notes here.

![Example of an Image 3](https://placehold.co/600x400.png){#fig-example-image-3}
:::
````

This will also issue a warning. Effectively, each div with `.column-margin` can either contain exactly one figure, exactly one table, or content that has no floats.

This also means that custom crossrefs will not work in margin figures. Unfortunately, that's another thing that I don't think we can fix.
