### ISSUE TITLE
Using `polyglossia` with LaTeX engines other than xelatex

### ISSUE THREAD

**Issue by tpellard** [quarto-dev/quarto-cli#959]
The documentation in [pandoc-user-guide.qmd](https://raw.githubusercontent.com/quarto-dev/quarto-gallery/main/articles/pdf/pandoc-user-guide.qmd) states that

> `xelatex` uses `polyglossia` (with `lang`)

but when using `pdf-engine: lualatex`, `babel` seems to be used by default.

I need to use  `polyglossia` with `lualatex` but there seems to be no option for that.

**Comment by cderv** [comment]
The documentation you pointed out is an old version. Last version for Pandoc manual is here https://pandoc.org/MANUAL.html

I believe **polyglossia** is no more used by default in Pandoc's latex template since Pandoc 2.15 (https://pandoc.org/releases.html#pandoc-2.15-2021-10-23):
> Use babel, not polyglossia, with xelatex. Previously polyglossia worked better with xelatex, but that is no longer the case, so we simplify the code so that babel is used with all latex engines. This involves a change to the default LaTeX template.

I am not sure that Pandocs offer a switch to not use `babel` package without providing a custom template. Using `lang` will activate `babel` The default template used by Pandoc is here: https://github.com/jgm/pandoc/blob/master/data/templates/default.latex 
We are using a copy of this version with slight adjustment: https://github.com/quarto-dev/quarto-cli/blob/main/src/resources/formats/pdf/pandoc/template.tex

You could probably include the missing part to use polyglossia using included file (https://quarto.org/docs/output-formats/pdf-basics.html#latex-includes) but `babel` would still be activated I think from the default template

**Comment by tpellard** [comment]
Thanks for the information. It seems `babel` has improved to the point that it can indeed replace `polyglossia`. I'll give it a try.
