### ISSUE TITLE
htmlwidgets don't render in a loop

### ISSUE THREAD

**Issue by ArthurAndrews** [quarto-dev/quarto-cli#9598]
### Bug description

With RMarkdown, I could print a list of tables or figures in a loop through a chunk option `results: asis` and a `print()` inside the loop.

This doesn't seem in to work in Quarto with htmlwidgets like those from `{reactable}` or `{plotly}`.  

I included a reprex below for both of these.

I sense this is related to this issue about `gt`, but I'm not sure the extent of the similarity.
https://github.com/quarto-dev/quarto-cli/issues/2370

### Steps to reproduce

````qmd
---
title: "Untitled"
format: html
editor: visual
---

```{r}
#| warning: false
#| message: false
library(reactable)
library(purrr)
library(htmltools)
library(plotly)
```

```{r}
tabs <- reactable(mtcars[1:4, 1:5]) |> 
  list() |> 
  rep(3)
```

```{r}
#| results: asis
tabs |> 
  purrr::walk(print)
```

```{r}
#| results: asis
tabs |> 
  map(tagList) |> 
  walk(print)
```

```{r}
plots <- list(
  plot_ly(mtcars, x = ~wt, y = ~mpg, type = "scatter", mode = "markers")
) |> 
  rep(3) 
```

```{r}
#| results: asis
plots |> 
  walk(print)
```


````

### Expected behavior

Tables and plots render in the html document.

### Actual behavior

Tables and plots don't render.

### Your environment

RStudio
2024.04.0 Build 263

### Quarto check output

Quarto 1.4.547
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.547
      Path: C:\Users\arthu\AppData\Local\Programs\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Tex:  (not detected)

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....OK
      Version: 3.11.2
      Path: C:/Users/arthu/AppData/Local/Programs/Python/Python311/python.exe
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with py -m pip install jupyter

[>] Checking R installation...........OK
      Version: 4.3.2
      Path: C:/PROGRA~1/R/R-43~1.2
      LibPaths:
        - C:/Users/arthu/AppData/Local/R/win-library/4.3
        - C:/Program Files/R/R-4.3.2/library
      knitr: 1.45
      rmarkdown: 2.25

[>] Checking Knitr engine render......OK

**Comment by mcanouil** [comment]
I don't believe the loop has anything to do with the issue here.

Below is the complete picture and what is the syntax to use.

````qmd
---
title: "Untitled"
format: html
keep-md: true
---

```{r}
#| warning: false
#| message: false
library(reactable)
library(htmltools)
```

## Single

### Does not work

```{r}
print(reactable(mtcars[1:4, 1:5]))
```

### Does work-ish

```{r}
print(tagList(reactable(mtcars[1:4, 1:5])))
```

### Does work

```{r}
tagList(reactable(mtcars[1:4, 1:5]))
```

### Does work

```{r}
#| output: asis
print(tagList(reactable(mtcars[1:4, 1:5])))
```

## Loop

### Does not work

```{r}
for (i in 1) {
  print(reactable(mtcars[1:4, 1:5]))
}
```

### Does work-ish

```{r}
for (i in 1) {
  print(tagList(reactable(mtcars[1:4, 1:5])))
}
```

### Does not work

```{r}
for (i in 1) {
  tagList(reactable(mtcars[1:4, 1:5]))
}
```

### Does work

```{r}
#| output: asis
for (i in 1) {
  print(tagList(reactable(mtcars[1:4, 1:5])))
}
```
````

**Comment by mcanouil** [comment]
Oh, "funny" and usual issues here actually.
The dependency is not loaded when used only in loops ...

<table>
<tr><th>Works</th><th>Does not</th></tr>
<tr><td>

````qmd
---
title: "Untitled"
format: html
---

```{r}
#| warning: false
#| message: false
library(reactable)
library(htmltools)
```

```{r}
#| eval: true
reactable(mtcars[1:4, 1:5])
```

```{r}
#| output: asis
reactable(mtcars[1:4, 1:5]) |> 
  list() |> 
  rep(3) |> 
  purrr::map(tagList) |>
  purrr::walk(print)
```

````

</td><td>

````qmd
---
title: "Untitled"
format: html
---

```{r}
#| warning: false
#| message: false
library(reactable)
library(htmltools)
```

```{r}
#| eval: false
reactable(mtcars[1:4, 1:5])
```

```{r}
#| output: asis
reactable(mtcars[1:4, 1:5]) |> 
  list() |> 
  rep(3) |> 
  purrr::map(tagList) |>
  purrr::walk(print)
```

````

</td></tr>
</table>

**Comment by cderv** [comment]
> are the left and right sides identical?

They differ by the second chunk setting `eval: true` on the left, and `eval: false` on the right. Because the former case does evaluate  a reactable call at top level, the correct knitr processing is done, and dependencies are caught up to be inserted. Later calls use the same dependencies so it works; 

Though this is quite a side effect and workaround - effective but can't say if it is generic solution. I'll explain the behavior below. 

> With RMarkdown, I could print a list of tables or figures in a loop through a chunk option results: asis and a print() inside the loop.

But first, @ArthurAndrews is the example you shared working in R Markdown ? It surprises me that objets like **reactable** or **plotly** would work in iteration with print. 

Let me explain more on this.  

This type of issue is not related to Quarto. This is about how **knitr** is supposed to work especially when using complex output like HTML dependencies. This would be the same behavior in R Markdown. 

Basically, tools like **reactable** are producing htmldependencies object as a results. By using regular print and asis output, any meta information about dependencies is removed. So it is expected that nothing is attached or loaded in this case. 

**knitr** uses a special printing function called `knit_print()` that knows how to handle such objects in knitting context. It needs to be used during rendering, and can't be used in list object like `walk()` - it needs to be called on the results. `knit_print` methods that handles all this needs to be evaluated on top level expression and not inside loops. There is some discussion about this in **knitr** repo

This is related to all the existing issues in this repo, rmarkdown repo or forum.posit.co about how to loop on complex object (like ggplot, htmldependency, or mixing markdown + code ) to programmatically create some content. 

Usually my advice is to considered iterating through generated .qmd code itself, leveraging `knitr::knit_expand()` and `knit_child()` (or the latter directly)

One existing example is here: https://examples.quarto.pub/create-tabsets-panel-from-r-code/
It shows how to create tabsets with **gt** table inside using iteration. 

For your example here, this is how I would do it
````markdown
---
title: "Untitled"
format: html
keep-md: true
---

```{r}
#| warning: false
#| message: false
library(reactable)
library(purrr)
library(htmltools)
library(plotly)
```

```{r}
tabs <- reactable(mtcars[1:4, 1:5]) |> 
  list() |> 
  rep(3)
```

```{r}
#| output: asis
tabs |> 
  map(\(x) knitr::knit_child(text = "`r x`", envir = environment(), quiet = TRUE)) |> 
  unlist() |>
  cat(sep = "\n")
```

It works with plots, and even allow to customize each output with options

```{r}
plots <- list(
  plot_ly(mtcars, x = ~wt, y = ~mpg, type = "scatter", mode = "markers")
) |> 
  rep(3) 
```

Using block syntax allows to pass options for the evaluation

```{r}
#| results: asis
plots |> 
  map(\(x) knitr::knit_child(text = c("```{r}", "#| echo: false", "x", "```"), envir = environment(), quiet = TRUE)) |> 
  unlist() |>
  cat(sep = "\n")
```
````

**Comment by cderv** [comment]
@ArthurAndrews I hope it makes sense. I'll close this as this is not Quarto directly anyhow. 

Thanks for the question.

**Comment by ArthurAndrews** [comment]
Thank you for the solutions.  I've been experimenting with them since.  

The downside of the `knitr::knit_child` solution seems to be that it doesn't run in the RStudio editor?  It will render for me to the document, but not interactively in the editor.

The solution that I've been using is to print the first element of the list in its own chunk `tabs[[1]]`, then print the rest like this `tabs[2:length(tabs)] |> map(tagList) |> walk(print)` with chunk setting `#| output: asis`.
