### ISSUE TITLE
Silent clash of freeze: true and --execute

### ISSUE THREAD

**Issue by rgaiacs** [quarto-dev/quarto-cli#9792]
### Bug description

`--execute` argument in the command line is silent ignored if YAML has

```
execute:
  freeze: true
```

### Steps to reproduce

Create `mwe.qmd` as

``````
---
title: MWE
execute:
  freeze: true
---

```{python}
import random

random.randint(0, 1000)
```
``````

and execute `quarto render mwe.qmd --execute` **twice**.

### Expected behavior

On second execution, warning message saying

```
WARNING: --execute being overwrite by freeze: true in YAML configuration
```

### Actual behavior

No warning message on second execution.

```
pandoc 
  to: html
  output-file: mwe.html
  standalone: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png
  
metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  title: MWE
  
Output created: mwe.html
```

### Your environment

- OS: Ubuntu running on WLS2

### Quarto check output

```
Quarto 1.5.39
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.39
      Path: /opt/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /usr/bin
      Version: 2021

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.3 (Conda)
      Path: /home/raniere/micromamba/envs/nlp/bin/python
      Jupyter: 5.7.2
      Kernels: python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.3
      Path: /usr/lib/R
      LibPaths:
        - /home/raniere/R/x86_64-pc-linux-gnu-library/4.3
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      knitr: 1.45
      rmarkdown: 2.25

[✓] Checking Knitr engine render......OK
```

**Comment by cderv** [comment]
Just a note that `--execute` flags is really only relevant for ipynb source and not .qmd has executing is the default. 

I think this is more generic though, as I don't think `freeze: true` will ever log that a file is rendered through freezer. 
but this is also mainly because it is intended to be used in a project. 

- Set `freeze: true` at project level
	- Then `quarto render` project will use freezer silently 
	- `quarto render index.qmd` will use the freezer (because incremental rendering)
	- `quarto render index.qmd --use-freezer`

- I don't think `freeze: true` is expected to be set at document level, but it is seems it is working. 
	- In that case, all call to `quarto render`, including incremental render will cause to use freezer, and we don't have a `--no-use-freezer` available. 
	- So calling `quarto render mwe.ipynb --execute` multiple time will always execute the notebook and not using the freezer.

So I don't know in which case you were really in 
* https://github.com/quarto-dev/quarto-cli/discussions/9790

which I suspect was the original use case, 

but when using `freeze: true` in a project, calling `quarto render` on the file should always not use the freezer (which is what is called incremental render) . Code is here to confirm this (only using `--use-freezer` on incremental render would be the exception)
https://github.com/quarto-dev/quarto-cli/blob/bc3fc8a4f514a1db353e20f2a914afb0bc9971ce/src/command/render/project.ts#L134-L137

So I believe the problem here is the bad experience when setting `freeze: true` at the file level. 

Did you set it at the ipynb /qmd level like in your example above, or at project level ? 

Regarding logging, currently we never log or show a message that the freezer will be used for rendering, nor with `--execute` key or any other usage.

**Comment by rgaiacs** [comment]
Thanks @cderv for the great explanation.

> So I believe the problem here is the bad experience when setting `freeze: true` at the file level.

You are correct.

> Did you set it at the ipynb /qmd level like in your example above, or at project level ?

At the file level **without** a `_quarto.yml` file.

> but when using `freeze: true` in a project, calling `quarto render` on the file should always not use the freezer (which is what is called incremental render).

I understand this part and I think that a line in the logs as a reminder might be helpful for people running from the command line.

**Comment by cderv** [comment]
@cscheid Is this expected for you that `freeze` is allowed at the document level ?  I wonder if this could be a side effect of the new single file project context adaptation. 

`freeze` is documented as a project feature, and I think we should probably not allow it in the document level. 

* Document execute options are at : https://quarto.org/docs/computations/execution-options.html
* Project level freeze is also under `execute` key (https://quarto.org/docs/projects/code-execution.html#freeze) but meant to be set in project.

**Comment by cscheid** [comment]
> I wonder if this could be a side effect of the new single file project context adaptation.

I think that's what's happening, yes.

**Comment by cscheid** [comment]
Partial fix incoming - Quarto will render and not complain about `freeze`, because it will no longer honor that option in single-file renders.

We should also issue warnings in this case, but that's harder to do cleanly, so we will defer that to a future fix.

**Comment by cscheid** [comment]
Let's close this one and open a new issue for the remaining problem of warning the user about using the ignored option on a single-file render.
