### ISSUE TITLE
Different syntax highlighting theme for light/dark modes

### ISSUE THREAD

**Issue by pat-s** [quarto-dev/quarto-cli#990]
AFAICS one can currently only set one highlighting theme.

It would be great if one could select one for each, light and dark mode. Light highlighting themes are not easy on the eyes in dark website themes 🙂 

I am aware that some styles exists which provide light and dark themes - however selecting different ones for light and dark would be great!

**Comment by dragonstyle** [comment]
Right now, you can't pass dark and light under the `highlight-style` key, though that would make sense and be nice. I will get this working soon.

**Comment by EllaKaye** [comment]
Agreed, that would be very nice! Thanks for adding this to the to-do list.

**Comment by EllaKaye** [comment]
Hello. I've had another look at the documentation for custom syntax highlighting, https://quarto.org/docs/output-formats/html-code.html#custom-highlighting, and it says that 

> to provide adaptive themes, you may also pass both a light and dark theme file

However, the example directly below that just provides one theme, and also looks wrong (just one line of `---`):

```
---
highlight-style: pygments
```

I've tried all feasible yaml ways I can think of to pass two files, but none work. The fact that this issue is still open also suggests that this is not yet implemented, despite what the documentation says.

@dragonstyle, would you mind providing an update on whether this is possible or not. If so, how? If not, would you be able to give a sense of when this might be implemented (above it says 'Future', which could be anything!) In either case, it would be good to update the documentation.

Thank you very much.

**Comment by dragonstyle** [comment]
I was completely wrong and @jjallaire was correct. You can do the following:

```
highlight-style:
  light: custom-light.theme
  dark: custom-dark.theme
```

And that works just fine. I update the documentation to provide an example of this approach (waiting on the deployment to  complete), correcting the error that you noted.

Note that adaptive themes (dark/light) will use the foreground coloring from the theme, but will used the code background color from the overall site/web page theme.

Thanks for the followup on this and apologies for adding confusion!

**Comment by EllaKaye** [comment]
Thanks for following up @dragonstyle, and clarifying the confusion. Yes, that's working for me 😄 

(I was sure I'd tried this before posting my comment, but I guess not).
