### ISSUE TITLE
gt table disappears in dashboard with quarto 1.4.555

### ISSUE THREAD

**Issue by olivroy** [quarto-dev/quarto-cli#9939]
### Bug description

With dev gt 0.10.9000, a simple dashboard with a gt table disappears. Follow-up to https://github.com/quarto-dev/quarto-cli/issues/9696#issuecomment-2148097751. Note that this works in Quarto 1.4.554

### Steps to reproduce

````qmd
---
title: title
format: dashboard
---

```{r}
library(gt)
```

# Title

## Row

```{r}
#| title: gt

gt::gt(gt::exibble)
```


````

### Expected behavior

The table should show in the dashboard

### Actual behavior

The dashboard is empty
![image](https://github.com/quarto-dev/quarto-cli/assets/52606734/12cef8a3-b024-47a7-a16b-b2e5527f2fdc)

### Your environment

RStudio 2024.07+215
Windows
gt 0.10.9000

### Quarto check output

```bash
Quarto 1.4.555
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.4.555
      Path: C:\Users\username\AppData\Local\Programs\RStudio\resources\app\bin\quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Using: TinyTex
      Path: C:\Users\username\AppData\Roaming\TinyTeX\bin\windows\
      Version: 2024

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....(None)

      Unable to locate an installed version of Python 3.
      Install Python 3 from https://www.python.org/downloads/

[>] Checking R installation...........OK
      Version: 4.3.2
      Path: C:/PROGRA~1/R/R-43~1.2
      LibPaths:
        - C:/Users/username/AppData/Local/R/win-library/4.3
        - C:/Program Files/R/R-4.3.2/library
      knitr: 1.47
      rmarkdown: 2.27

[>] Checking Knitr engine render......OK
```

**Comment by cderv** [comment]
Hi, 

Please can you try 1.5 pre release version of Quarto ? I believe this has been fixed already.

**Comment by olivroy** [comment]
Yes. It works in 1.5.

However, it doesn't work with gt 0.10.1 and 0.10.1.9000 and Quarto 1.4.555, so it is a regression from 1.4.554

**Comment by mcanouil** [comment]
Sorry, it's unclear.
Which combination work and which don't?

**Comment by olivroy** [comment]
After all, gt version has no importance (both 0.10.1 and 0.10.1.9000 behave the same).

Works with Quarto 1.4.554, or Quarto > 1.5.41 

Doesn't work with stable 1.4.555

**Comment by cderv** [comment]
Thanks for the additional information. 

This is exactly what was discussed in https://github.com/quarto-dev/quarto-cli/issues/9696#issuecomment-2149301624

Following https://github.com/quarto-dev/quarto-cli/pull/9602, the patch https://github.com/quarto-dev/quarto-cli/commit/87a2fe8d39b67bce70a47e756e117688a882100b is using the scaffolding which has the hidden class, and trigger this exact bug

1.5 don't have the issue because we use the other scaffold function that do not add the hidden class

https://github.com/quarto-dev/quarto-cli/blob/305bea0c55fac2ca2e3fd218df6f03014ef04e84/src/resources/filters/normalize/parsehtml.lua#L211

This is a bug in Dashboard that we fixed in 1.5, but did not yet backported to 1.4. 

1.5 will be release soon as we are currently in release candidate more. 

I would suggest using latest 1.5 for this specific fix.

**Comment by cscheid** [comment]
(cf our discussion of where this issue fits, I'm going to remove it from 1.5 just to make our tracking cleaner)

**Comment by olivroy** [comment]
Since Quarto 1.5 is released and doesn't seem to introduce major regressions, I think this can be left as won't fix
