### ISSUE TITLE
revealjs: indentation with h3 in columns

### ISSUE THREAD

**Issue by aronatkins** [quarto-dev/quarto-cli#9999]
### Bug description

h3 elements within columns end up indented differently than lists and other text within the same column.

### Steps to reproduce

````markdown
---
title: columnar
format: revealjs
---

## Column lists

::: {.columns}

::: {.column}

### Odd

* one
* three
* five
* seven
* nine

:::

::: {.column}

### Even

* two
* four
* six
* eight
* ten

:::

:::

## Column text

::: {.columns}

::: {.column}

### Odd

this text is odd.

> this blockquote is also odd.

:::

::: {.column}

### Even

this text is even.

> this blockquote is also even.

:::

:::
````

### Expected behavior

sub-headings and other column text should have consistent alignment within columns

### Actual behavior

![image](https://github.com/quarto-dev/quarto-cli/assets/362187/4e3b538f-d0eb-485e-a2eb-882be13dc5ed)

![image](https://github.com/quarto-dev/quarto-cli/assets/362187/38ff4158-43c5-424c-aa7e-2dd6a042ff96)

### Quarto check output

````
Quarto 1.4.551
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.11: OK
      Dart Sass version 1.69.5: OK
      Deno version 1.37.2: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.4.551
      Path: /Users/aron/quarto/quarto-1.4.551-macos/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: Installation From Path
      Path: /Library/TeX/texbin
      Version: 2024

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.12.2
      Path: /opt/homebrew/opt/python@3.12/bin/python3.12
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.3.3
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
      knitr: 1.45
      rmarkdown: 2.27

[✓] Checking Knitr engine render......OK
````

**Comment by gordonwoodhull** [comment]
I was surprised by @cderv's analysis that this is because a margin specified in `em` will be a different size for `<p>` and `<h3>`, but yes indeed, `em` is relative not to the base font but to the font of the element.

````html
<html>
<head>
<style>
  .indent {
    margin-left: 4em
  }
</style>
</head>

<body>
  <h1 class="indent">H1 with indent</h1>
  <h2 class="indent">H2 with indent</h1>
  <h3 class="indent">H3 with indent</h1>
  <p class="indent">p with indent</h1>
</body>
</html>
````
<img width="318" alt="image" src="https://github.com/quarto-dev/quarto-cli/assets/1366709/bd961fb1-9bce-4d98-995f-8d5a7cd344f1">

**Comment by cderv** [comment]
Putting back here my analysis. This is due to some CSS settings we set which uses em units. 
https://github.com/quarto-dev/quarto-cli/blob/50b4cf15a0be98a439773ffe923e1e284301879b/src/resources/formats/revealjs/quarto.scss#L401-L413

It has been added at the time in https://github.com/quarto-dev/quarto-cli/commit/805f7ad84e17a2297657247f34b07e7e2f9b5bac to add spacing between columns

> (These margins would be the same size with rem units.)

We probably need to use `rem` then here, right @gordonwoodhull ?

**Comment by gordonwoodhull** [comment]
Absolute units like `px` could also work. I guess `rem` has the advantage of being the minimal change, but you’ll still have to test to make sure it looks good!
